// Auto-generated by `npx tsx scripts/generate-legal-dates.ts` — DO NOT EDIT BY HAND.
// Regenerated on every build (gen:parallel). Source of truth: git history
// of each legal page. Guard: src/__tests__/legal-dates.test.ts.

export const LEGAL_DATES: Record<string, string> = {
  "/privacy-policy/": "2026-09-19",
  "/terms/": "2026-09-19",
  "/cookies/": "2026-09-16",
  "/disclaimer/": "2026-09-16",
};

export function legalDate(route: string): string {
  return LEGAL_DATES[route] ?? new Date().toISOString().slice(0, 10);
}

export function formatLegalDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y!, m! - 1, d)).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}
