name = "toolzum"
compatibility_date = "2026-07-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[vars]
NEXT_PUBLIC_APP_URL = "https://toolzum.com"
NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAEe0A5L_32vG3O7z"

[[d1_databases]]
binding = "DB"
database_name = "toolhub-db"
database_id = "be7bd039-a6e8-45fd-a6fd-df56e6a20469"
migrations_dir = "src/db/migrations"

