name = "toolzum"
compatibility_date = "2026-07-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "toolhub-db"
database_id = "be7bd039-a6e8-45fd-a6fd-df56e6a20469"

