"use client";

import React, { useState, useRef, useMemo } from 'react';
import { Download, Award, Upload, Users, FileText } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { downloadOrShare } from '@/utils/nativeShare';

interface CertificateData {
  name: string;
  course: string;
  date: string;
  id: string;
}

export default function CertificateGenerator() {
  const [mode, setMode] = useState<'single' | 'bulk'>('single');
  const [name, setName] = useState('');
  const [course, setCourse] = useState('');
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [certId, setCertId] = useState('');
  const [bulkCsv, setBulkCsv] = useState('');
  const [generatedCount, setGeneratedCount] = useState(0);
  const previewRef = useRef<HTMLDivElement>(null);

  const certificateNumber = useMemo(() => {
    return certId || `TOOLHUB-${Date.now().toString(36).toUpperCase()}`;
  }, [certId]);

  const generateCertHtml = (data: CertificateData): string => `
    <div style="width:800px;height:600px;position:relative;font-family:'Times New Roman',Times,serif;background:#fff;overflow:hidden;border:12px solid #d4a843;box-sizing:border-box;">
      <div style="position:absolute;inset:8px;border:2px solid #d4a843;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:30px;text-align:center;">
        <div style="font-size:14px;color:#d4a843;letter-spacing:4px;text-transform:uppercase;margin-bottom:10px;">Certificate of Completion</div>
        <div style="width:60px;height:2px;background:#d4a843;margin:8px auto;"></div>
        <div style="font-size:13px;color:#666;margin-top:8px;">This is to certify that</div>
        <div style="font-size:28px;font-weight:bold;color:#1a1a1a;margin:10px 0;font-family:'Georgia',serif;">${data.name}</div>
        <div style="font-size:13px;color:#666;margin-bottom:8px;">has successfully completed the</div>
        <div style="font-size:18px;font-weight:bold;color:#333;margin:6px 0;">${data.course}</div>
        <div style="font-size:12px;color:#888;margin-top:10px;">Date: ${data.date}</div>
        <div style="margin-top:25px;display:flex;justify-content:space-between;width:70%;font-size:11px;color:#666;">
          <div style="text-align:center;"><div style="border-top:1px solid #333;width:140px;padding-top:4px;">Authorized Signature</div></div>
          <div style="text-align:center;"><div style="border-top:1px solid #333;width:140px;padding-top:4px;">Certificate ID</div></div>
        </div>
        <div style="margin-top:4px;display:flex;justify-content:space-between;width:70%;font-size:10px;color:#999;">
          <div style="text-align:center;width:140px;"></div>
          <div style="text-align:center;width:140px;">${data.id}</div>
        </div>
        <div style="position:absolute;bottom:8px;font-size:9px;color:#ccc;">Generated by ToolHub</div>
      </div>
    </div>
  `;

  const handlePrint = () => {
    if (!name.trim() && mode === 'single') return toast.error('Enter the recipient name');
    if (!course.trim()) return toast.error('Enter the course/title');

    const data: CertificateData = { name, course, date, id: certificateNumber };
    const html = generateCertHtml(data);
    const win = window.open('', '_blank');
    if (!win) return toast.error('Allow pop-ups to generate certificate');
    win.document.write(`<html><head><title>Certificate - ${name}</title><style>@page{margin:0}body{margin:0;display:flex;justify-content:center;align-items:center;min-height:100vh;}@media print{@page{margin:0}}<\/style></head><body>${html}</body></html>`);
    win.document.close();
    win.focus();
    setGeneratedCount(prev => prev + 1);
    setTimeout(() => win.print(), 500);
  };

  const handleBulkGenerate = () => {
    const lines = bulkCsv.split('\n').map(l => l.trim()).filter(Boolean);
    if (lines.length === 0) return toast.error('Paste at least one entry');
    const entries: CertificateData[] = lines.map((line, i) => {
      const parts = line.split(',').map(s => s.replace(/^"|"$/g, '').trim());
      return {
        name: parts[0] || `Recipient ${i + 1}`,
        course: parts[1] || course || 'Course Completion',
        date: parts[2] || date,
        id: parts[3] || `TOOLHUB-BULK-${(i + 1).toString().padStart(4, '0')}`,
      };
    });

    const win = window.open('', '_blank');
    if (!win) return toast.error('Allow pop-ups to generate certificates');
    win.document.write(`<html><head><title>Bulk Certificates</title><style>@page{margin:0}body{margin:0}@media print{@page{margin:0}}.page-break{page-break-after:always}<\/style></head><body>`);
    entries.forEach((entry, i) => {
      win.document.write(generateCertHtml(entry));
      if (i < entries.length - 1) win.document.write('<div class="page-break"></div>');
    });
    win.document.write('</body></html>');
    win.document.close();
    win.focus();
    setGeneratedCount(prev => prev + entries.length);
    setTimeout(() => win.print(), 500);
    toast.success(`${entries.length} certificates ready to print`);
  };

  return (
    <div className="max-w-5xl mx-auto animate-in fade-in duration-500 space-y-5">
      <div className="flex items-center gap-2">
        <Award className="w-5 h-5 text-amber-500" />
        <h3 className="text-lg font-bold text-zinc-900 dark:text-white">Certificate Generator</h3>
      </div>

      <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-white/10 rounded-2xl p-5 shadow-xl space-y-4">
        <div className="flex items-center gap-2 border-b border-zinc-200 dark:border-zinc-800 pb-3">
          <button onClick={() => setMode('single')}
            className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-semibold transition-colors ${mode === 'single' ? 'bg-amber-500 text-white' : 'text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800'}`}>
            <FileText className="w-3.5 h-3.5" /> Single Certificate
          </button>
          <button onClick={() => setMode('bulk')}
            className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-semibold transition-colors ${mode === 'bulk' ? 'bg-amber-500 text-white' : 'text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800'}`}>
            <Users className="w-3.5 h-3.5" /> Bulk Generate
          </button>
          {generatedCount > 0 && (
            <span className="text-[10px] text-zinc-500 ml-auto">{generatedCount} generated this session</span>
          )}
        </div>

        {mode === 'single' ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-3">
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-zinc-400 uppercase">Recipient Name *</label>
                <input value={name} onChange={e => setName(e.target.value)} placeholder="e.g. Arjun Mehta"
                  className="w-full bg-zinc-50 dark:bg-black/50 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-zinc-900 dark:text-white outline-none focus:ring-2 focus:ring-amber-500/30" />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-zinc-400 uppercase">Course / Title *</label>
                <input value={course} onChange={e => setCourse(e.target.value)} placeholder="e.g. Web Development Bootcamp"
                  className="w-full bg-zinc-50 dark:bg-black/50 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-zinc-900 dark:text-white outline-none focus:ring-2 focus:ring-amber-500/30" />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-zinc-400 uppercase">Date</label>
                  <input type="date" value={date} onChange={e => setDate(e.target.value)}
                    className="w-full bg-zinc-50 dark:bg-black/50 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-zinc-900 dark:text-white outline-none focus:ring-2 focus:ring-amber-500/30" />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-zinc-400 uppercase">Certificate ID</label>
                  <input value={certId} onChange={e => setCertId(e.target.value)} placeholder="Auto-generated"
                    className="w-full bg-zinc-50 dark:bg-black/50 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-zinc-900 dark:text-white outline-none focus:ring-2 focus:ring-amber-500/30" />
                </div>
              </div>
              <button onClick={handlePrint}
                className="w-full py-3.5 bg-amber-500 hover:bg-amber-600 text-white font-bold rounded-xl text-xs flex items-center justify-center gap-1.5 transition-colors">
                <Download className="w-4 h-4" /> Generate & Download Certificate
              </button>
            </div>
            <div className="bg-zinc-50 dark:bg-black/20 rounded-xl p-3 border border-zinc-200 dark:border-zinc-800 flex items-center justify-center min-h-[250px]">
              <div className="text-center text-zinc-400 text-xs max-w-xs">
                <Award className="w-8 h-8 mx-auto mb-2 text-zinc-300 dark:text-zinc-700" />
                <p className="font-medium">Certificate Preview</p>
                <p className="text-[10px] text-zinc-500 mt-1">Click generate to open a print-ready certificate</p>
                <p className="text-[9px] text-zinc-400 mt-2">Gold border with elegant serif typography</p>
              </div>
            </div>
          </div>
        ) : (
          <div className="space-y-3">
            <p className="text-xs text-zinc-500">Paste CSV data: <code className="text-amber-500">Name, Course, Date, CertificateID</code></p>
            <textarea value={bulkCsv} onChange={e => setBulkCsv(e.target.value)}
              placeholder={"Arjun Mehta,Web Development Bootcamp,2025-12-01,CERT-001\nPriya Sharma,Data Science Course,2025-12-01,CERT-002\nRahul Verma,UI/UX Design Masterclass,2025-12-05,CERT-003"}
              className="w-full bg-zinc-50 dark:bg-black/50 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-3 text-sm text-zinc-900 dark:text-white font-mono outline-none focus:ring-2 focus:ring-amber-500/30 resize-none h-32" />
            <div className="grid grid-cols-2 gap-2">
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-zinc-400 uppercase">Default Course (if missing)</label>
                <input value={course} onChange={e => setCourse(e.target.value)} placeholder="e.g. Course Completion"
                  className="w-full bg-zinc-50 dark:bg-black/50 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-zinc-900 dark:text-white outline-none" />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-zinc-400 uppercase">Default Date</label>
                <input type="date" value={date} onChange={e => setDate(e.target.value)}
                  className="w-full bg-zinc-50 dark:bg-black/50 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-2.5 text-sm text-zinc-900 dark:text-white outline-none" />
              </div>
            </div>
            <button onClick={handleBulkGenerate}
              className="w-full py-3.5 bg-amber-500 hover:bg-amber-600 text-white font-bold rounded-xl text-xs flex items-center justify-center gap-1.5 transition-colors">
              <Users className="w-4 h-4" /> Generate All Certificates ({bulkCsv.split('\n').filter(Boolean).length || 0})
            </button>
            <div className="bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-200 dark:border-indigo-800/30 rounded-xl p-3">
              <p className="text-[10px] text-indigo-600 dark:text-indigo-400">
                <strong>Pro:</strong> Upload Excel/CSV file directly, custom templates with logo/branding, auto-email certificates to recipients, and team management with role-based access.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
