"use client";

import React, { useState, useMemo } from 'react';
import { Calculator, Download, IndianRupee, Home, Car, Heart, Shield, PiggyBank, Briefcase, TrendingUp, FileText } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { downloadOrShare } from '@/utils/nativeShare';

interface TaxSlab { min: number; max: number; rate: number; }
interface TaxInputs {
  salary: number; otherIncome: number; 
  investment80C: number; nps80CCD: number; healthInsurance80D: number;
  rentPerMonth: number; homeLoanInterest: number; homeLoanPrincipal: number;
  ltaClaim: number; foodCoupons: number;
}

const NEW_REGIME_SLABS: TaxSlab[] = [
  { min: 0, max: 300000, rate: 0 }, { min: 300000, max: 600000, rate: 5 },
  { min: 600000, max: 900000, rate: 10 }, { min: 900000, max: 1200000, rate: 15 },
  { min: 1200000, max: 1500000, rate: 20 }, { min: 1500000, max: Infinity, rate: 30 },
];

const OLD_REGIME_SLABS: TaxSlab[] = [
  { min: 0, max: 250000, rate: 0 }, { min: 250000, max: 500000, rate: 5 },
  { min: 500000, max: 1000000, rate: 20 }, { min: 1000000, max: Infinity, rate: 30 },
];

const CESS_RATE = 0.04;

function calcTax(grossIncome: number, deductions: number, slabs: TaxSlab[]): { tax: number; cess: number; total: number } {
  const taxable = Math.max(0, grossIncome - deductions);
  let tax = 0;
  for (const slab of slabs) {
    if (taxable > slab.min) {
      const slabIncome = Math.min(taxable, slab.max) - slab.min;
      if (slabIncome > 0) tax += slabIncome * slab.rate / 100;
    }
  }
  const cess = tax * CESS_RATE;
  return { tax, cess, total: tax + cess };
}

function formatINR(n: number): string {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
}

export default function TaxSavingCalculator() {
  const [inputs, setInputs] = useState<TaxInputs>({
    salary: 1200000, otherIncome: 0, investment80C: 0, nps80CCD: 0, healthInsurance80D: 0,
    rentPerMonth: 0, homeLoanInterest: 0, homeLoanPrincipal: 0,
    ltaClaim: 0, foodCoupons: 0,
  });
  const [showAdvanced, setShowAdvanced] = useState(false);

  const update = (key: keyof TaxInputs, val: string) => {
    setInputs(prev => ({ ...prev, [key]: Math.max(0, parseFloat(val) || 0) }));
  };

  const { grossIncome, oldDeductions, newDeductions, oldResult, newResult, hraExemption, recommendation } = useMemo(() => {
    const gross = inputs.salary + inputs.otherIncome;

    const hra = Math.min(
      inputs.rentPerMonth * 12,
      inputs.salary * 0.5,
      (inputs.rentPerMonth * 12) - (inputs.salary * 0.1)
    );
    const hraExemption = Math.max(0, hra);

    const stdDeduction = 50000;
    const old80C = Math.min(inputs.investment80C, 150000);
    const old80CCD = Math.min(inputs.nps80CCD, 50000);
    const old80D = Math.min(inputs.healthInsurance80D, 25000);
    const homeInterest = Math.min(inputs.homeLoanInterest, 200000);

    const oldDeductions = stdDeduction + old80C + old80CCD + old80D + hraExemption + homeInterest + inputs.ltaClaim + inputs.foodCoupons;
    const newDeductions = stdDeduction;

    const oldResult = calcTax(gross, oldDeductions, OLD_REGIME_SLABS);
    const newResult = calcTax(gross, newDeductions, NEW_REGIME_SLABS);

    let recommendation = '';
    if (oldResult.total < newResult.total) {
      const save = newResult.total - oldResult.total;
      recommendation = `Old regime saves you ${formatINR(save)}. Invest in 80C/80D/NPS/HRA to maximize deductions.`;
    } else if (newResult.total < oldResult.total) {
      const save = oldResult.total - newResult.total;
      recommendation = `New regime saves you ${formatINR(save)}. No need to track investments for deductions.`;
    } else {
      recommendation = 'Both regimes give similar tax. New regime is simpler with less paperwork.';
    }

    return { grossIncome: gross, oldDeductions, newDeductions, oldResult, newResult, hraExemption, recommendation };
  }, [inputs]);

  const handleExportPDF = () => {
    const lines = [
      '=== Tax Saving Report ===',
      `Gross Income: ${formatINR(grossIncome)}`,
      '',
      '--- Old Regime ---',
      `Deductions: ${formatINR(oldDeductions)}`,
      `Taxable Income: ${formatINR(Math.max(0, grossIncome - oldDeductions))}`,
      `Income Tax: ${formatINR(oldResult.tax)}`,
      `Health & Education Cess: ${formatINR(oldResult.cess)}`,
      `Total Tax Liability: ${formatINR(oldResult.total)}`,
      '',
      '--- New Regime ---',
      `Standard Deduction: ${formatINR(newDeductions)}`,
      `Taxable Income: ${formatINR(Math.max(0, grossIncome - newDeductions))}`,
      `Income Tax: ${formatINR(newResult.tax)}`,
      `Health & Education Cess: ${formatINR(newResult.cess)}`,
      `Total Tax Liability: ${formatINR(newResult.total)}`,
      '',
      `Recommendation: ${recommendation}`,
      '',
      'Generated by Toolzum Tax Calculator. Consult a CA for filing.',
    ].join('\n');
    const blob = new Blob([lines], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    downloadOrShare(url, `tax_report_${Date.now()}.txt`);
    toast.success('Tax report downloaded!');
  };

  const inputField = (label: string, key: keyof TaxInputs, icon: React.ReactNode, placeholder = '0') => (
    <div className="space-y-1">
      <label className="flex items-center gap-1.5 text-[11px] font-semibold text-[var(--text-secondary)] uppercase tracking-wide">
        {icon} {label}
      </label>
      <input type="number" min="0" step="10000" value={inputs[key] || ''} onChange={e => update(key, e.target.value)}
        placeholder={placeholder} inputMode="numeric" aria-label={label}
        className="w-full bg-[var(--bg-overlay)] border border-[var(--border-subtle)] rounded-xl px-4 py-2.5 text-sm text-[var(--text-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] focus-visible:ring-offset-2 focus:ring-2 focus:ring-emerald-500/30" />
    </div>
  );

  return (
    <div className="max-w-5xl mx-auto animate-in fade-in duration-500 space-y-5">
      <div className="flex items-center gap-2 mb-1">
        <IndianRupee className="w-5 h-5 text-emerald-500" />
        <h3 className="text-lg font-bold text-[var(--text-primary)]">Tax Saving Calculator (Old vs New Regime)</h3>
      </div>

      <div className="bg-[var(--bg-elevated)] border border-[var(--border-subtle)] rounded-2xl shadow-xl overflow-hidden">
        <div className="p-5 space-y-5">
          <p className="text-xs text-[var(--text-secondary)]">Compare your tax liability under Old and New tax regimes. Enter your income and investments below.</p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {inputField('Annual Salary (CTC)', 'salary', <Briefcase className="w-3.5 h-3.5" />, '1200000')}
            {inputField('Other Income', 'otherIncome', <TrendingUp className="w-3.5 h-3.5" />, '0')}
          </div>

          <div className="border-t border-[var(--border-subtle)] pt-4">
            <button onClick={() => setShowAdvanced(!showAdvanced)}
              className="flex items-center gap-1.5 text-xs font-semibold text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors">
              <PiggyBank className="w-3.5 h-3.5" /> {showAdvanced ? 'Hide' : 'Show'} Investments & Deductions
            </button>

            {showAdvanced && (
              <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3 animate-in fade-in slide-in-from-top-2 duration-200">
                {inputField('80C Investments (PPF/ELSS/FD)', 'investment80C', <Shield className="w-3.5 h-3.5" />)}
                {inputField('NPS 80CCD(1B)', 'nps80CCD', <PiggyBank className="w-3.5 h-3.5" />)}
                {inputField('Health Insurance 80D', 'healthInsurance80D', <Heart className="w-3.5 h-3.5" />)}
                {inputField('Monthly Rent (HRA)', 'rentPerMonth', <Home className="w-3.5 h-3.5" />)}
                {inputField('Home Loan Interest', 'homeLoanInterest', <Car className="w-3.5 h-3.5" />)}
                {inputField('Home Loan Principal', 'homeLoanPrincipal', <Car className="w-3.5 h-3.5" />)}
                {inputField('LTA Claim', 'ltaClaim', <Briefcase className="w-3.5 h-3.5" />)}
                {inputField('Food/Meal Coupons', 'foodCoupons', <FileText className="w-3.5 h-3.5" />)}
              </div>
            )}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-t border-[var(--border-subtle)] pt-4">
            <div className="bg-[var(--bg-overlay)] rounded-xl p-4 border border-[var(--border-subtle)]">
              <h4 className="text-[11px] font-bold text-[var(--text-muted)] uppercase mb-3 flex items-center gap-1.5"><FileText className="w-3 h-3" /> Old Regime</h4>
              <div className="space-y-2 text-xs">
                <div className="flex justify-between"><span className="text-[var(--text-secondary)]">Gross Income</span><span className="font-semibold text-[var(--text-primary)]">{formatINR(grossIncome)}</span></div>
                <div className="flex justify-between"><span className="text-[var(--text-secondary)]">Total Deductions</span><span className="font-semibold text-emerald-500">{formatINR(oldDeductions)}</span></div>
                <div className="border-t border-[var(--border-subtle)] pt-2 flex justify-between"><span className="text-[var(--text-secondary)]">Taxable Income</span><span className="font-semibold">{formatINR(Math.max(0, grossIncome - oldDeductions))}</span></div>
                <div className="flex justify-between"><span className="text-[var(--text-secondary)]">Income Tax</span><span className="font-semibold">{formatINR(oldResult.tax)}</span></div>
                <div className="flex justify-between"><span className="text-[var(--text-secondary)]">Cess (4%)</span><span className="font-semibold">{formatINR(oldResult.cess)}</span></div>
                <div className="border-t border-[var(--border-subtle)] pt-2 flex justify-between text-sm"><span className="font-bold text-[var(--text-secondary)] dark:text-[var(--text-muted)]">Total Tax</span><span className="font-bold text-[var(--text-primary)] text-base">{formatINR(oldResult.total)}</span></div>
              </div>
            </div>

            <div className="bg-[var(--bg-overlay)] rounded-xl p-4 border border-[var(--border-subtle)]">
              <h4 className="text-[11px] font-bold text-[var(--text-muted)] uppercase mb-3 flex items-center gap-1.5"><TrendingUp className="w-3 h-3" /> New Regime</h4>
              <div className="space-y-2 text-xs">
                <div className="flex justify-between"><span className="text-[var(--text-secondary)]">Gross Income</span><span className="font-semibold text-[var(--text-primary)]">{formatINR(grossIncome)}</span></div>
                <div className="flex justify-between"><span className="text-[var(--text-secondary)]">Standard Deduction</span><span className="font-semibold text-emerald-500">{formatINR(newDeductions)}</span></div>
                <div className="border-t border-[var(--border-subtle)] pt-2 flex justify-between"><span className="text-[var(--text-secondary)]">Taxable Income</span><span className="font-semibold">{formatINR(Math.max(0, grossIncome - newDeductions))}</span></div>
                <div className="flex justify-between"><span className="text-[var(--text-secondary)]">Income Tax</span><span className="font-semibold">{formatINR(newResult.tax)}</span></div>
                <div className="flex justify-between"><span className="text-[var(--text-secondary)]">Cess (4%)</span><span className="font-semibold">{formatINR(newResult.cess)}</span></div>
                <div className="border-t border-[var(--border-subtle)] pt-2 flex justify-between text-sm"><span className="font-bold text-[var(--text-secondary)] dark:text-[var(--text-muted)]">Total Tax</span><span className="font-bold text-[var(--text-primary)] text-base">{formatINR(newResult.total)}</span></div>
              </div>
            </div>
          </div>

          <div className="bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800/40 rounded-xl p-4">
            <div className="flex items-start gap-2">
              <Calculator className="w-4 h-4 text-emerald-500 mt-0.5 shrink-0" />
              <div>
                <p className="text-xs font-bold text-emerald-700 dark:text-emerald-300 mb-0.5">Recommendation</p>
                <p className="text-[11px] text-emerald-600 dark:text-emerald-400">{recommendation}</p>
              </div>
            </div>
          </div>

          <button onClick={handleExportPDF}
            className="w-full py-3 bg-[var(--accent-ink)] hover:opacity-90 text-white font-bold rounded-xl text-sm flex items-center justify-center gap-1.5 transition-colors">
            <Download className="w-4 h-4" /> Download Tax Report
          </button>

          <div className="bg-[var(--accent)]/10/20 border border-[var(--accent)]/20 rounded-xl p-3">
            <p className="text-[10px] text-[var(--accent)] dark:text-[var(--accent)]">
              <strong>Pro:</strong> Personalized investment plan PDF with exact 80C/80D/NPS allocation, HRA optimization calculator, multiple income sources (freelance + salary), share with CA report, and side-by-side budget comparison.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
