// Auto-generated by `npm run gen:site-data` — DO NOT EDIT BY HAND.
// Regenerate whenever the registry or megamenu definition changes:
//   npm run gen:site-data   (wired into `npm run build`)
// Parity guard: src/__tests__/site-data.test.ts

export interface MegamenuTool {
  name: string;
  href: string;
}

export interface MegamenuColumn {
  title: string;
  icon: string;
  tools: MegamenuTool[];
  allCount: number;
  allHref: string;
  isIndia: boolean;
}

export const TOOL_COUNT = 1149;

export const SITE_STATS = {
  totalImplemented: 1065,
  freeTierTotal: 1002,
  localTools: 1026,
  cloudTools: 32,
  hybridTools: 4,
} as const;

export const MEGAMENU_COLUMNS: MegamenuColumn[] = [
  {
    "title": "Image",
    "icon": "image",
    "tools": [
      {
        "name": "Image Compressor",
        "href": "/image/image-compressor"
      },
      {
        "name": "Image Resizer",
        "href": "/image/image-resizer"
      },
      {
        "name": "Background Remover",
        "href": "/image/background-remover"
      },
      {
        "name": "Crop Image",
        "href": "/image/crop-image"
      },
      {
        "name": "Image Enhancer",
        "href": "/image/image-enhancer"
      },
      {
        "name": "Batch Image Editor",
        "href": "/image/batch-image-editor"
      },
      {
        "name": "PNG to JPG",
        "href": "/image/png-to-jpg"
      }
    ],
    "allCount": 42,
    "allHref": "/image",
    "isIndia": false
  },
  {
    "title": "PDF",
    "icon": "pdf",
    "tools": [
      {
        "name": "PDF Compressor",
        "href": "/pdf/pdf-compressor"
      },
      {
        "name": "PDF Merger",
        "href": "/pdf/pdf-merger"
      },
      {
        "name": "PDF Splitter",
        "href": "/pdf/pdf-splitter"
      },
      {
        "name": "PDF to Word",
        "href": "/pdf/pdf-to-word"
      },
      {
        "name": "PDF to Excel",
        "href": "/pdf/pdf-to-excel"
      },
      {
        "name": "Word to PDF",
        "href": "/pdf/word-to-pdf"
      },
      {
        "name": "JPG to PDF",
        "href": "/pdf/jpg-to-pdf"
      }
    ],
    "allCount": 62,
    "allHref": "/pdf",
    "isIndia": false
  },
  {
    "title": "Video",
    "icon": "video",
    "tools": [
      {
        "name": "Video Compressor",
        "href": "/video/video-compressor"
      },
      {
        "name": "Video to GIF",
        "href": "/video/video-to-gif"
      },
      {
        "name": "Video to MP3 Converter",
        "href": "/video/video-to-mp3"
      },
      {
        "name": "Crop Video",
        "href": "/video/crop-video"
      },
      {
        "name": "Subtitle Translator",
        "href": "/video/subtitle-translator"
      },
      {
        "name": "Video Trimmer",
        "href": "/video/video-trimmer"
      },
      {
        "name": "Video Watermark Adder",
        "href": "/video/video-watermark-adder"
      }
    ],
    "allCount": 19,
    "allHref": "/video",
    "isIndia": false
  },
  {
    "title": "Audio",
    "icon": "audio",
    "tools": [
      {
        "name": "Text to Speech (TTS)",
        "href": "/audio/text-to-speech-tts"
      },
      {
        "name": "Audio Cutter",
        "href": "/audio/audio-cutter"
      },
      {
        "name": "Speech to Text",
        "href": "/audio/speech-to-text"
      },
      {
        "name": "Audio Format Converter",
        "href": "/audio/audio-converter"
      },
      {
        "name": "Apple Music Preview Extractor",
        "href": "/audio/apple-music-preview-extractor"
      },
      {
        "name": "Bulk Audio Converter",
        "href": "/audio/bulk-audio-converter"
      },
      {
        "name": "MP3 Compressor",
        "href": "/audio/mp3-compressor"
      }
    ],
    "allCount": 16,
    "allHref": "/audio",
    "isIndia": false
  },
  {
    "title": "AI",
    "icon": "ai",
    "tools": [
      {
        "name": "AI Image Generator",
        "href": "/ai/ai-image-generator"
      },
      {
        "name": "AI Paraphrasing Tool",
        "href": "/ai/ai-paraphrasing-tool"
      },
      {
        "name": "AI Translator",
        "href": "/ai/ai-translator"
      },
      {
        "name": "AI Image Upscaler",
        "href": "/ai/ai-image-upscaler"
      },
      {
        "name": "AI Face Swap",
        "href": "/ai/ai-face-swap"
      },
      {
        "name": "AI Cover Letter Generator",
        "href": "/ai/ai-cover-letter-generator"
      },
      {
        "name": "AI Thumbnail Maker",
        "href": "/ai/ai-thumbnail-maker"
      }
    ],
    "allCount": 16,
    "allHref": "/ai",
    "isIndia": false
  },
  {
    "title": "Developer",
    "icon": "developer",
    "tools": [
      {
        "name": "JSON Formatter",
        "href": "/developer/json-formatter"
      },
      {
        "name": "SQL Formatter",
        "href": "/developer/sql-formatter"
      },
      {
        "name": "CSS Minifier",
        "href": "/developer/css-minifier"
      },
      {
        "name": "Diff Checker",
        "href": "/developer/diff-checker"
      },
      {
        "name": "Base64 Encode/Decode",
        "href": "/developer/base64-encode-decode"
      },
      {
        "name": "Regex Tester",
        "href": "/developer/regex-tester"
      },
      {
        "name": "JS Minifier",
        "href": "/developer/js-minifier"
      }
    ],
    "allCount": 243,
    "allHref": "/developer",
    "isIndia": false
  },
  {
    "title": "Text",
    "icon": "text",
    "tools": [
      {
        "name": "Character Counter",
        "href": "/text/character-counter"
      },
      {
        "name": "Word Counter",
        "href": "/text/word-counter"
      },
      {
        "name": "Fancy Text Generator",
        "href": "/text/fancy-text-generator"
      },
      {
        "name": "Font Generator",
        "href": "/text/font-generator"
      },
      {
        "name": "Cursive Text Generator",
        "href": "/text/cursive-text-generator"
      },
      {
        "name": "Text to Handwriting",
        "href": "/text/text-to-handwriting"
      },
      {
        "name": "Case Converter",
        "href": "/text/case-converter"
      }
    ],
    "allCount": 27,
    "allHref": "/text",
    "isIndia": false
  },
  {
    "title": "Finance",
    "icon": "finance",
    "tools": [
      {
        "name": "Currency Converter",
        "href": "/finance/currency-converter"
      },
      {
        "name": "EMI Calculator",
        "href": "/finance/emi-calculator"
      },
      {
        "name": "SIP Calculator",
        "href": "/finance/sip-calculator"
      },
      {
        "name": "Compound Interest Calculator",
        "href": "/finance/compound-interest-calculator"
      },
      {
        "name": "Invoice Generator",
        "href": "/finance/invoice-generator"
      },
      {
        "name": "Profit Margin Calculator",
        "href": "/finance/profit-margin-calculator"
      },
      {
        "name": "Salary Calculator",
        "href": "/finance/salary-calculator"
      }
    ],
    "allCount": 33,
    "allHref": "/finance",
    "isIndia": false
  },
  {
    "title": "Utility",
    "icon": "utility",
    "tools": [
      {
        "name": "QR Code Generator",
        "href": "/utility/qr-code-generator"
      },
      {
        "name": "Password Generator",
        "href": "/utility/password-generator"
      },
      {
        "name": "Wheel of Names",
        "href": "/utility/wheel-of-names"
      },
      {
        "name": "Random Number Generator",
        "href": "/utility/random-number-generator"
      },
      {
        "name": "Resume Builder",
        "href": "/utility/resume-builder"
      },
      {
        "name": "Dice Roller",
        "href": "/utility/dice-roller"
      },
      {
        "name": "Unit Converter",
        "href": "/utility/unit-converter"
      }
    ],
    "allCount": 83,
    "allHref": "/utility",
    "isIndia": false
  },
  {
    "title": "Converter",
    "icon": "converter",
    "tools": [
      {
        "name": "MKV to MP4",
        "href": "/converter/mkv-to-mp4"
      },
      {
        "name": "MP3 to WAV",
        "href": "/audio/mp3-to-wav"
      },
      {
        "name": "PNG to JPG",
        "href": "/image/png-to-jpg"
      },
      {
        "name": "JSON to CSV",
        "href": "/converter/json-to-csv"
      },
      {
        "name": "Markdown Tools",
        "href": "/converter/markdown-tools"
      },
      {
        "name": "JSON to XML",
        "href": "/converter/json-to-xml"
      },
      {
        "name": "Archive Converter",
        "href": "/converter/archive-converter"
      }
    ],
    "allCount": 38,
    "allHref": "/converter",
    "isIndia": false
  },
  {
    "title": "Privacy",
    "icon": "privacy",
    "tools": [
      {
        "name": "Temporary Email Generator",
        "href": "/privacy/temporary-email-generator"
      },
      {
        "name": "Password Strength Checker",
        "href": "/privacy/password-strength-checker"
      },
      {
        "name": "EXIF Data Remover",
        "href": "/privacy/exif-data-remover"
      },
      {
        "name": "Secure Note Sharer",
        "href": "/privacy/secure-note-sharer"
      },
      {
        "name": "PGP Key Generator",
        "href": "/privacy/pgp-key-generator"
      },
      {
        "name": "IP Anonymizer",
        "href": "/privacy/ip-anonymizer"
      },
      {
        "name": "Privacy Cleaner",
        "href": "/privacy/privacy-cleaner"
      }
    ],
    "allCount": 8,
    "allHref": "/tools",
    "isIndia": false
  },
  {
    "title": "SEO",
    "icon": "seo",
    "tools": [
      {
        "name": "Keyword Density Checker",
        "href": "/seo/keyword-density-checker"
      },
      {
        "name": "XML Sitemap Generator",
        "href": "/seo/xml-sitemap-generator"
      },
      {
        "name": "Robots.txt Generator",
        "href": "/seo/robots-txt-generator"
      },
      {
        "name": "Bulk URL Status Checker",
        "href": "/seo/bulk-url-status-checker"
      },
      {
        "name": "Word Frequency Counter",
        "href": "/seo/word-frequency-counter"
      },
      {
        "name": "Keyword Planner Tool",
        "href": "/seo/keyword-planner-tool"
      },
      {
        "name": "SEO Meta Tag Generator",
        "href": "/seo/seo-meta-tag-generator"
      }
    ],
    "allCount": 14,
    "allHref": "/seo",
    "isIndia": false
  },
  {
    "title": "Branding",
    "icon": "branding",
    "tools": [
      {
        "name": "Logo Maker",
        "href": "/branding/logo-maker"
      },
      {
        "name": "Social Media Post Maker",
        "href": "/branding/social-media-post-maker"
      },
      {
        "name": "Business Card Maker",
        "href": "/branding/business-card-maker"
      },
      {
        "name": "Email Signature Generator",
        "href": "/branding/email-signature-generator"
      },
      {
        "name": "URL Shortener",
        "href": "/utility/url-shortener"
      },
      {
        "name": "Social Media Calendar",
        "href": "/branding/social-media-calendar"
      },
      {
        "name": "Link in Bio Builder",
        "href": "/branding/link-in-bio-builder"
      }
    ],
    "allCount": 8,
    "allHref": "/branding",
    "isIndia": false
  },
  {
    "title": "India",
    "icon": "indian-utilities",
    "tools": [
      {
        "name": "Passport Photo Maker (India)",
        "href": "/indian-utilities/passport-photo-india"
      },
      {
        "name": "Aadhaar Wallet Cropper",
        "href": "/indian-utilities/aadhaar-wallet-cropper"
      },
      {
        "name": "GST Calculator",
        "href": "/indian-utilities/gst-calculator"
      },
      {
        "name": "GST Invoice Generator",
        "href": "/indian-utilities/gst-invoice-generator"
      },
      {
        "name": "GSTIN Lookup",
        "href": "/indian-utilities/gstin-lookup"
      },
      {
        "name": "PAN Card Resizer",
        "href": "/indian-utilities/pan-card-resizer"
      },
      {
        "name": "Aadhaar Card Masker",
        "href": "/indian-utilities/aadhaar-card-masker"
      }
    ],
    "allCount": 26,
    "allHref": "/indian-utilities",
    "isIndia": true
  }
];
