import type { ToolCategory } from './tools-types';

export const proSlugs = [
  "ai-image-generator", "ai-document-chat",
  "ai-paraphrasing-tool",
  "bulk-bg-changer", "bulk-qr-code-generator", "bulk-image-watermark",
  "bulk-pdf-data-extractor", "bulk-image-to-pdf", "bulk-audio-converter",
  "bulk-svg-to-png", "bulk-image-compressor", "bulk-pdf-size-reducer",
  "bulk-image-resizer", "bulk-video-compressor", "bulk-pdf-merger",
  "bulk-face-anonymizer", "bulk-pdf-form-extractor", "bulk-video-size-reducer",
  "bulk-audio-normalizer", "bulk-video-subtitle-burner",
  "bulk-invoice-receipt-parser", "bulk-csv-excel-to-json", "bulk-url-status-checker",
  "bulk-image-converter", "bulk-exif-stripper-injector", "bulk-app-icon-generator",
  "bulk-markdown-to-pdf-html", "bulk-font-subsetter", "bulk-subtitle-time-shifter",
  "bulk-regex-extractor-replacer", "bulk-image-to-text-ocr", "bulk-ebook-converter",
  "bulk-heic-to-jpg",
  "bulk-pdf-suite",
  "bulk-url-shortener",
  "batch-image-editor", "image-bulk-converter",
  "bulk-avif-optimizer", "bulk-heic-converter", "bulk-image-upscaler",
  // AI tools
  "ai-translator", "ai-image-upscaler", "ai-face-swap",
  "ai-bg-changer", "ai-thumbnail-maker", "ai-cover-letter-generator",
  "ai-chat-pdf", "grammar-checker", "ai-humanizer", "ai-detector",
  // Transcription / cloud tools
  "youtube-transcript-generator", "podcast-transcription", "meeting-minutes-generator",
  "indian-voice-transcriber", "subtitle-translator",
  "audio-to-text-transcription", "video-to-text-transcription",
  // AI tools that use /api/ai/generate
  "brand-color-palette-generator", "complaint-letter-generator",
  "pdf-ai-summariser", "resume-ats-score-checker",
  // Premium SaaS / batch
  "saas-metrics-dashboard",
  "bank-statement-analyser", "api-builder",
  // Restored: ungated for testing in 0217c642 (Jul 22), never re-gated.
  "pdf-workflow-builder",
];


export interface SeoPermutation {
  slug: string;
  name: string;
  category: ToolCategory;
  description: string;
  seoDescription?: string;
  parentSlug: string;
}

export const SEO_PERMUTATIONS: SeoPermutation[] = [
  // Tier 1 — Built as real tools (each has a wrapper component in DynamicModuleWrapper)
  { slug: "bulk-png-to-webp", name: "Bulk PNG to WebP", category: "Image", description: "Convert all your PNG images to modern WebP format in one batch. Shrinks file sizes by 30% without losing quality — essential for Pagespeed scores. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PNG to WebP — Convert all your PNG images to modern WebP format in one batch. Shrinks file sizes by 30% without losing quality — essential for Pagespeed scores. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-jpg-to-webp", name: "Bulk JPG to WebP", category: "Image", description: "Batch convert JPEG images to WebP format for faster websites. Keeps directory structure intact and generates fallback PNGs automatically. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk JPG to WebP — Batch convert JPEG images to WebP format for faster websites. Keeps directory structure intact and generates fallback PNGs automatically. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-webp-to-png", name: "Bulk WebP to PNG", category: "Image", description: "Need WebP files back to PNG? Convert entire folders of WebP images to universal PNG format in one click — zero quality loss. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk WebP to PNG — Need WebP files back to PNG? Convert entire folders of WebP images to universal PNG format in one click — zero quality loss. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-png-to-jpg", name: "Bulk PNG to JPG", category: "Image", description: "Batch convert PNG images to JPEG format. Perfect when you need smaller file sizes for email or web upload at the cost of transparency. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PNG to JPG — Batch convert PNG images to JPEG format. Perfect when you need smaller file sizes for email or web upload at the cost of transparency. ', parentSlug: "bulk-image-compressor" },
  { slug: "bulk-jpg-to-png", name: "Bulk JPG to PNG", category: "Image", description: "Convert JPEG photos to lossless PNG format in bulk. Essential for graphics needing transparency or when preserving every pixel matters. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk JPG to PNG — Convert JPEG photos to lossless PNG format in bulk. Essential for graphics needing transparency or when preserving every pixel matters. ', parentSlug: "bulk-image-compressor" },
  { slug: "bulk-resize-images", name: "Bulk Resize Images", category: "Image", description: "Resize hundreds of photos to exact pixel dimensions in one pass. Photographers standardize client galleries before delivery with this tool. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk Resize Images — Resize hundreds of photos to exact pixel dimensions in one pass. Photographers standardize client galleries before delivery with this tool. ', parentSlug: "bulk-image-resizer" },
  { slug: "bulk-compress-png", name: "Bulk PNG Compressor", category: "Image", description: "Compress dozens of PNG files at once with smart lossy compression. E-commerce sellers optimize product images while keeping transparency. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PNG Compressor — Compress dozens of PNG files at once with smart lossy compression. E-commerce sellers optimize product images while keeping transparency. ', parentSlug: "bulk-image-compressor" },
  { slug: "bulk-compress-jpg", name: "Bulk JPG Compressor", category: "Image", description: "Batch compress JPEG photos to smaller file sizes with consistent quality. Bloggers and web devs optimize entire image libraries before deployment. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk JPG Compressor — Batch compress JPEG photos to smaller file sizes with consistent quality. Bloggers and web devs optimize entire image libraries before deployment. ', parentSlug: "bulk-image-compressor" },
  { slug: "bulk-compress-pdf", name: "Bulk PDF Compressor", category: "PDF", description: "Reduce file size of multiple PDFs at once by compressing images and removing metadata. Law firms preparing document batches for email. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Compressor — Reduce file size of multiple PDFs at once by compressing images and removing metadata. Law firms preparing document batches for email. ', parentSlug: "bulk-pdf-size-reducer" },
  { slug: "bulk-pdf-to-jpg", name: "Bulk PDF to JPG", category: "PDF", description: "Convert each page of multiple PDFs to high-res JPG images. Presenters extracting slides from decks for social media or thumbnails. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF to JPG — Convert each page of multiple PDFs to high-res JPG images. Presenters extracting slides from decks for social media or thumbnails. ', parentSlug: "bulk-pdf-data-extractor" },
  { slug: "bulk-mp3-to-wav", name: "Bulk MP3 to WAV", category: "Audio", description: "Convert your MP3 music library to lossless WAV format in one batch. Audio editors and podcasters need WAV for professional production workflows. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk MP3 to WAV — Convert your MP3 music library to lossless WAV format in one batch. Audio editors and podcasters need WAV for professional production workflows. ', parentSlug: "bulk-audio-converter" },
  { slug: "bulk-wav-to-mp3", name: "Bulk WAV to MP3", category: "Audio", description: "Batch compress WAV recordings to space-saving MP3 files. Podcasters shrinking raw studio recordings for distribution on Spotify and Apple Podcasts. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk WAV to MP3 — Batch compress WAV recordings to space-saving MP3 files. Podcasters shrinking raw studio recordings for distribution on Spotify and Apple Podcasts. ', parentSlug: "bulk-audio-converter" },
  { slug: "bulk-mkv-to-mp4", name: "Bulk MKV to MP4", category: "Video", description: "Batch remux MKV video files to universally compatible MP4 without re-encoding. Smart TV and iPhone users solving format compatibility issues. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk MKV to MP4 — Batch remux MKV video files to universally compatible MP4 without re-encoding. Smart TV and iPhone users solving format compatibility issues. ', parentSlug: "bulk-video-compressor" },
  { slug: "bulk-compress-mp4", name: "Bulk MP4 Compressor", category: "Video", description: "Compress multiple MP4 videos at once for email, web, or messaging. YouTube studios batch-optimize daily uploads with consistent CRF settings. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk MP4 Compressor — Compress multiple MP4 videos at once for email, web, or messaging. YouTube studios batch-optimize daily uploads with consistent CRF settings. ', parentSlug: "bulk-video-compressor" },
  { slug: "bulk-strip-exif", name: "Bulk Photo Metadata Remover", category: "Privacy", description: "Strip GPS coordinates, camera data, and hidden metadata from batches of photos. Real estate agents protect client privacy before upload. No signup or account required.", seoDescription: 'Free online Bulk Photo Metadata Remover — Strip GPS coordinates, camera data, and hidden metadata from batches of photos. Real estate agents protect client privacy before upload. ', parentSlug: "bulk-exif-stripper-injector" },
  { slug: "bulk-url-checker", name: "Bulk URL Checker", category: "SEO", description: "Check the status of hundreds of URLs at once — find broken links, redirects, and dead pages across your entire website. Essential for SEO audits before Google crawls your site. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk URL Checker — Check the status of hundreds of URLs at once — find broken links, redirects, and dead pages across your entire website. Essential for SEO audits before Google crawls your site. ', parentSlug: "bulk-url-status-checker" },
  { slug: "bulk-link-checker", name: "Bulk Link Checker", category: "SEO", description: "Scan and validate every link on your site in one batch. Catch 404s, broken backlinks, and redirect chains before they hurt your search rankings. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk Link Checker — Scan and validate every link on your site in one batch. Catch 404s, broken backlinks, and redirect chains before they hurt your search rankings. ', parentSlug: "bulk-url-status-checker" },
  // Bulk Image Converter — all format pair permutations
  { slug: "bulk-jpg-to-avif", name: "Bulk JPG to AVIF", category: "Image", description: "Convert all your JPEG photos to next-gen AVIF format in one batch. Saves 50% more bandwidth than WebP while preserving visual quality. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk JPG to AVIF — Convert all your JPEG photos to next-gen AVIF format in one batch. Saves 50% more bandwidth than WebP while preserving visual quality. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-jpg-to-gif", name: "Bulk JPG to GIF", category: "Image", description: "Batch convert JPEG images to animated GIF format. Great for creating simple animations from photo sequences or compatibility with legacy systems. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk JPG to GIF — Batch convert JPEG images to animated GIF format. Great for creating simple animations from photo sequences or compatibility with legacy systems. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-jpg-to-bmp", name: "Bulk JPG to BMP", category: "Image", description: "Convert JPEG photos to uncompressed BMP format in bulk. Useful for image processing pipelines that require raw bitmap data or legacy software compatibility. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk JPG to BMP — Convert JPEG photos to uncompressed BMP format in bulk. Useful for image processing pipelines that require raw bitmap data or legacy software compatibility. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-jpg-to-ico", name: "Bulk JPG to ICO", category: "Image", description: "Turn your JPEG photos into Windows icon files in batch. Web developers and designers create favicon sets from existing images with zero quality loss. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk JPG to ICO — Turn your JPEG photos into Windows icon files in batch. Web developers and designers create favicon sets from existing images with zero quality loss. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-png-to-avif", name: "Bulk PNG to AVIF", category: "Image", description: "Batch convert PNG images to ultra-efficient AVIF format. Keeps transparency intact while crushing file sizes by up to 50% compared to PNG. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PNG to AVIF — Batch convert PNG images to ultra-efficient AVIF format. Keeps transparency intact while crushing file sizes by up to 50% compared to PNG. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-png-to-gif", name: "Bulk PNG to GIF", category: "Image", description: "Convert PNG images to GIF format in one batch. Perfect for adding transparency-backed frames to simple animations or older website compatibility. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PNG to GIF — Convert PNG images to GIF format in one batch. Perfect for adding transparency-backed frames to simple animations or older website compatibility. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-png-to-bmp", name: "Bulk PNG to BMP", category: "Image", description: "Convert transparent PNG graphics to BMP format in bulk. Designers preparing assets for legacy applications or custom image processing scripts. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PNG to BMP — Convert transparent PNG graphics to BMP format in bulk. Designers preparing assets for legacy applications or custom image processing scripts. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-png-to-ico", name: "Bulk PNG to ICO", category: "Image", description: "Generate Windows icon files from your PNG graphics in batch. Web developers create multi-resolution favicon packages from transparent source images. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PNG to ICO — Generate Windows icon files from your PNG graphics in batch. Web developers create multi-resolution favicon packages from transparent source images. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-webp-to-jpg", name: "Bulk WebP to JPG", category: "Image", description: "Need WebP images back to universal JPEG format? Convert entire folders of WebP files to JPEG in one click for maximum compatibility. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk WebP to JPG — Need WebP images back to universal JPEG format? Convert entire folders of WebP files to JPEG in one click for maximum compatibility. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-webp-to-avif", name: "Bulk WebP to AVIF", category: "Image", description: "Upgrade your WebP image library to next-gen AVIF format for even smaller file sizes. Save an additional 20-30% bandwidth without visible quality loss. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk WebP to AVIF — Upgrade your WebP image library to next-gen AVIF format for even smaller file sizes. Save an additional 20-30% bandwidth without visible quality loss. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-webp-to-gif", name: "Bulk WebP to GIF", category: "Image", description: "Convert WebP images to GIF format in batch. Useful when you need animated WebP files converted to universally compatible GIFs. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk WebP to GIF — Convert WebP images to GIF format in batch. Useful when you need animated WebP files converted to universally compatible GIFs. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-webp-to-bmp", name: "Bulk WebP to BMP", category: "Image", description: "Convert WebP images to uncompressed BMP format in bulk. Image analysts and legacy software users needing raw pixel data from modern WebP sources. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk WebP to BMP — Convert WebP images to uncompressed BMP format in bulk. Image analysts and legacy software users needing raw pixel data from modern WebP sources. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-webp-to-ico", name: "Bulk WebP to ICO", category: "Image", description: "Generate Windows icon files from WebP images in batch. Create favicon sets from your next-gen image library without intermediate conversions. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk WebP to ICO — Generate Windows icon files from WebP images in batch. Create favicon sets from your next-gen image library without intermediate conversions. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-avif-to-jpg", name: "Bulk AVIF to JPG", category: "Image", description: "Convert AVIF images back to universal JPEG format in one batch. Needed when sharing AVIF photos with recipients whose devices lack AVIF support. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk AVIF to JPG — Convert AVIF images back to universal JPEG format in one batch. Needed when sharing AVIF photos with recipients whose devices lack AVIF support. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-avif-to-png", name: "Bulk AVIF to PNG", category: "Image", description: "Batch convert AVIF images to lossless PNG format. Essential when you need transparency support or lossless editing from AVIF source files. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk AVIF to PNG — Batch convert AVIF images to lossless PNG format. Essential when you need transparency support or lossless editing from AVIF source files. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-avif-to-webp", name: "Bulk AVIF to WebP", category: "Image", description: "Convert AVIF images to WebP format for broader browser compatibility. Web developers ensure their next-gen images work across all modern browsers. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk AVIF to WebP — Convert AVIF images to WebP format for broader browser compatibility. Web developers ensure their next-gen images work across all modern browsers. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-avif-to-gif", name: "Bulk AVIF to GIF", category: "Image", description: "Convert AVIF images to GIF format in bulk. Create universally compatible animations from your high-efficiency AVIF source images. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk AVIF to GIF — Convert AVIF images to GIF format in bulk. Create universally compatible animations from your high-efficiency AVIF source images. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-avif-to-bmp", name: "Bulk AVIF to BMP", category: "Image", description: "Convert AVIF images to uncompressed BMP format. Image processing pipelines and legacy tools that require raw bitmap input from modern AVIF files. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk AVIF to BMP — Convert AVIF images to uncompressed BMP format. Image processing pipelines and legacy tools that require raw bitmap input from modern AVIF files. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-avif-to-ico", name: "Bulk AVIF to ICO", category: "Image", description: "Generate Windows icon files from AVIF images in batch. Build favicon sets from your most space-efficient image format without quality loss. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk AVIF to ICO — Generate Windows icon files from AVIF images in batch. Build favicon sets from your most space-efficient image format without quality loss. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heic-to-png", name: "Bulk HEIC to PNG", category: "Image", description: "Convert iPhone HEIC photos to universal PNG format in one batch. Preserves transparency and lossless quality from Apple's modern image format. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIC to PNG — Convert iPhone HEIC photos to universal PNG format in one batch. Preserves transparency and lossless quality from Apple modern image format. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heic-to-webp", name: "Bulk HEIC to WebP", category: "Image", description: "Convert Apple HEIC photos to WebP format for web use. Optimize iPhone images for websites with modern compression that preserves visual quality. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIC to WebP — Convert Apple HEIC photos to WebP format for web use. Optimize iPhone images for websites with modern compression that preserves visual quality. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heic-to-avif", name: "Bulk HEIC to AVIF", category: "Image", description: "Convert HEIC photos to AVIF format for even better compression. Perfect for migrating Apple device photos to the most bandwidth-efficient format. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIC to AVIF — Convert HEIC photos to AVIF format for even better compression. Perfect for migrating Apple device photos to the most bandwidth-efficient format. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heic-to-gif", name: "Bulk HEIC to GIF", category: "Image", description: "Convert iPhone HEIC photos to GIF format in batch. Useful for creating simple animations from Live Photos or compatibility with GIF-only platforms. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIC to GIF — Convert iPhone HEIC photos to GIF format in batch. Useful for creating simple animations from Live Photos or compatibility with GIF-only platforms. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heic-to-bmp", name: "Bulk HEIC to BMP", category: "Image", description: "Convert HEIC photos to uncompressed BMP format. Image editors and legacy software that need raw bitmap data from modern Apple photos. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIC to BMP — Convert HEIC photos to uncompressed BMP format. Image editors and legacy software that need raw bitmap data from modern Apple photos. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heic-to-ico", name: "Bulk HEIC to ICO", category: "Image", description: "Generate Windows icon files from your HEIC photos in batch. Create favicon packages from iPhone images without intermediate format conversions. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIC to ICO — Generate Windows icon files from your HEIC photos in batch. Create favicon packages from iPhone images without intermediate format conversions. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heif-to-jpg", name: "Bulk HEIF to JPG", category: "Image", description: "Convert HEIF images from modern cameras to universal JPEG format. Photographers working with HEIF files ensure compatibility with all editing software. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIF to JPG — Convert HEIF images from modern cameras to universal JPEG format. Photographers working with HEIF files ensure compatibility with all editing software. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heif-to-png", name: "Bulk HEIF to PNG", category: "Image", description: "Batch convert HEIF images to lossless PNG format. Preserves high dynamic range data from modern camera HEIF files in a universally supported format. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIF to PNG — Batch convert HEIF images to lossless PNG format. Preserves high dynamic range data from modern camera HEIF files in a universally supported format. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heif-to-webp", name: "Bulk HEIF to WebP", category: "Image", description: "Convert HEIF camera images to WebP for web optimization. Photographers and web devs prepare high-efficiency image libraries from HEIF source files. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIF to WebP — Convert HEIF camera images to WebP for web optimization. Photographers and web devs prepare high-efficiency image libraries from HEIF source files. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heif-to-avif", name: "Bulk HEIF to AVIF", category: "Image", description: "Convert HEIF images to AVIF format for superior compression. Migrate high-efficiency camera photos to the most advanced web image format. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIF to AVIF — Convert HEIF images to AVIF format for superior compression. Migrate high-efficiency camera photos to the most advanced web image format. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heif-to-gif", name: "Bulk HEIF to GIF", category: "Image", description: "Convert HEIF images to GIF format in one batch. Create animations from high-efficiency camera bursts or ensure compatibility with legacy systems. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIF to GIF — Convert HEIF images to GIF format in one batch. Create animations from high-efficiency camera bursts or ensure compatibility with legacy systems. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heif-to-bmp", name: "Bulk HEIF to BMP", category: "Image", description: "Convert HEIF images to uncompressed BMP format. Image analysis tools and legacy editors needing raw pixel access from high-efficiency camera sources. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIF to BMP — Convert HEIF images to uncompressed BMP format. Image analysis tools and legacy editors needing raw pixel access from high-efficiency camera sources. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-heif-to-ico", name: "Bulk HEIF to ICO", category: "Image", description: "Generate Windows icon files from HEIF camera images in batch. Create favicon packages from high-efficiency photos without intermediate format hops. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk HEIF to ICO — Generate Windows icon files from HEIF camera images in batch. Create favicon packages from high-efficiency photos without intermediate format hops. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-gif-to-jpg", name: "Bulk GIF to JPG", category: "Image", description: "Convert GIF frames to JPEG images in bulk. Extract individual frames from animated GIFs as high-quality JPEG photos for printing or web use. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk GIF to JPG — Convert GIF frames to JPEG images in bulk. Extract individual frames from animated GIFs as high-quality JPEG photos for printing or web use. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-gif-to-png", name: "Bulk GIF to PNG", category: "Image", description: "Convert GIF images to lossless PNG format in batch. Upgrade legacy GIF graphics to PNG for better color depth, transparency, and smaller file sizes. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk GIF to PNG — Convert GIF images to lossless PNG format in batch. Upgrade legacy GIF graphics to PNG for better color depth, transparency, and smaller file sizes. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-gif-to-webp", name: "Bulk GIF to WebP", category: "Image", description: "Convert animated GIFs to WebP format for modern websites. Shrink file sizes by 60% while keeping animation and transparency intact. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk GIF to WebP — Convert animated GIFs to WebP format for modern websites. Shrink file sizes by 60% while keeping animation and transparency intact. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-gif-to-avif", name: "Bulk GIF to AVIF", category: "Image", description: "Convert GIF animations to ultra-efficient AVIF format. Save up to 70% bandwidth compared to GIF while supporting true color and animation. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk GIF to AVIF — Convert GIF animations to ultra-efficient AVIF format. Save up to 70% bandwidth compared to GIF while supporting true color and animation. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-gif-to-bmp", name: "Bulk GIF to BMP", category: "Image", description: "Convert GIF frames to uncompressed BMP format. Extract raw bitmap frames from animated GIFs for image processing or forensic analysis. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk GIF to BMP — Convert GIF frames to uncompressed BMP format. Extract raw bitmap frames from animated GIFs for image processing or forensic analysis. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-gif-to-ico", name: "Bulk GIF to ICO", category: "Image", description: "Generate Windows icon files from GIF images in batch. Create animated-style favicons or extract frames as icon resources from your GIF library. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk GIF to ICO — Generate Windows icon files from GIF images in batch. Create animated-style favicons or extract frames as icon resources from your GIF library. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-bmp-to-jpg", name: "Bulk BMP to JPG", category: "Image", description: "Convert uncompressed BMP files to space-saving JPEG format in bulk. Digitize legacy bitmap archives into modern, web-ready JPEG images. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk BMP to JPG — Convert uncompressed BMP files to space-saving JPEG format in bulk. Digitize legacy bitmap archives into modern, web-ready JPEG images. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-bmp-to-png", name: "Bulk BMP to PNG", category: "Image", description: "Batch convert BMP bitmaps to lossless PNG format. Reduce file sizes dramatically while preserving every pixel from your legacy image archives. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk BMP to PNG — Batch convert BMP bitmaps to lossless PNG format. Reduce file sizes dramatically while preserving every pixel from your legacy image archives. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-bmp-to-webp", name: "Bulk BMP to WebP", category: "Image", description: "Convert BMP files to modern WebP format for web optimization. Squash oversized bitmap archives into bandwidth-friendly images with one click. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk BMP to WebP — Convert BMP files to modern WebP format for web optimization. Squash oversized bitmap archives into bandwidth-friendly images with one click. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-bmp-to-avif", name: "Bulk BMP to AVIF", category: "Image", description: "Convert uncompressed BMP images to next-gen AVIF format. Shrink legacy bitmap archives by 90%+ while preserving visual fidelity. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk BMP to AVIF — Convert uncompressed BMP images to next-gen AVIF format. Shrink legacy bitmap archives by 90%+ while preserving visual fidelity. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-bmp-to-gif", name: "Bulk BMP to GIF", category: "Image", description: "Convert BMP bitmaps to GIF format in batch. Create simple animations from bitmap sequences or ensure legacy system compatibility. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk BMP to GIF — Convert BMP bitmaps to GIF format in batch. Create simple animations from bitmap sequences or ensure legacy system compatibility. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-bmp-to-ico", name: "Bulk BMP to ICO", category: "Image", description: "Generate Windows icon files from BMP images in batch. Create favicon packages directly from your bitmap assets without intermediate format conversion. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk BMP to ICO — Generate Windows icon files from BMP images in batch. Create favicon packages directly from your bitmap assets without intermediate format conversion. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-ico-to-jpg", name: "Bulk ICO to JPG", category: "Image", description: "Extract and convert Windows icon files to JPEG format in bulk. Developers and designers repurpose favicon assets as full-size images for social media. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk ICO to JPG — Extract and convert Windows icon files to JPEG format in bulk. Developers and designers repurpose favicon assets as full-size images for social media. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-ico-to-png", name: "Bulk ICO to PNG", category: "Image", description: "Convert Windows icon files to lossless PNG format in batch. Preserve multi-resolution icon data as individual transparent PNGs for web use. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk ICO to PNG — Convert Windows icon files to lossless PNG format in batch. Preserve multi-resolution icon data as individual transparent PNGs for web use. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-ico-to-webp", name: "Bulk ICO to WebP", category: "Image", description: "Convert ICO icon files to WebP format for modern websites. Optimize your favicon library into bandwidth-friendly WebP images. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk ICO to WebP — Convert ICO icon files to WebP format for modern websites. Optimize your favicon library into bandwidth-friendly WebP images. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-ico-to-avif", name: "Bulk ICO to AVIF", category: "Image", description: "Convert Windows icon files to ultra-efficient AVIF format. Shrink icon libraries for the web while supporting transparency and true color. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk ICO to AVIF — Convert Windows icon files to ultra-efficient AVIF format. Shrink icon libraries for the web while supporting transparency and true color. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-ico-to-gif", name: "Bulk ICO to GIF", category: "Image", description: "Convert ICO icon files to GIF format in batch. Extract icon frames as GIF animations or ensure compatibility with legacy display systems. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk ICO to GIF — Convert ICO icon files to GIF format in batch. Extract icon frames as GIF animations or ensure compatibility with legacy display systems. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-ico-to-bmp", name: "Bulk ICO to BMP", category: "Image", description: "Convert Windows icon files to uncompressed BMP format. Extract raw bitmap data from icon resources for image editing or analysis. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk ICO to BMP — Convert Windows icon files to uncompressed BMP format. Extract raw bitmap data from icon resources for image editing or analysis. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-svg-to-jpg", name: "Bulk SVG to JPG", category: "Image", description: "Rasterize SVG vector graphics to high-quality JPEG images in batch. Convert your icon sets and illustrations to photorealistic JPEG format. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk SVG to JPG — Rasterize SVG vector graphics to high-quality JPEG images in batch. Convert your icon sets and illustrations to photorealistic JPEG format. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-svg-to-webp", name: "Bulk SVG to WebP", category: "Image", description: "Rasterize SVG vectors to modern WebP format in bulk. Optimize your icon library and illustrations for the web with superior compression. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk SVG to WebP — Rasterize SVG vectors to modern WebP format in bulk. Optimize your icon library and illustrations for the web with superior compression. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-svg-to-avif", name: "Bulk SVG to AVIF", category: "Image", description: "Rasterize SVG vector graphics to AVIF format in one batch. Convert your scalable illustrations to the most bandwidth-efficient raster format. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk SVG to AVIF — Rasterize SVG vector graphics to AVIF format in one batch. Convert your scalable illustrations to the most bandwidth-efficient raster format. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-svg-to-gif", name: "Bulk SVG to GIF", category: "Image", description: "Rasterize SVG vectors to GIF format in bulk. Create animated icon sequences from SVG source files or ensure legacy platform compatibility. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk SVG to GIF — Rasterize SVG vectors to GIF format in bulk. Create animated icon sequences from SVG source files or ensure legacy platform compatibility. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-svg-to-bmp", name: "Bulk SVG to BMP", category: "Image", description: "Rasterize SVG vectors to uncompressed BMP format. Convert scalable graphics to raw bitmap data for image processing pipelines and legacy tools. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk SVG to BMP — Rasterize SVG vectors to uncompressed BMP format. Convert scalable graphics to raw bitmap data for image processing pipelines and legacy tools. ', parentSlug: "bulk-image-converter" },
  { slug: "bulk-svg-to-ico", name: "Bulk SVG to ICO", category: "Image", description: "Rasterize SVG vector icons to Windows ICO format in batch. Generate favicon packages directly from your scalable vector source files. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk SVG to ICO — Rasterize SVG vector icons to Windows ICO format in batch. Generate favicon packages directly from your scalable vector source files. ', parentSlug: "bulk-image-converter" },
  // Bulk PDF Suite — operation permutations
  { slug: "bulk-pdf-rotate", name: "Bulk PDF Rotate", category: "PDF", description: "Rotate all pages in multiple PDF files at once — 90°, 180°, or 270°. Standardize scanned documents and presentation decks in one batch. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Rotate — Rotate all pages in multiple PDF files at once — 90°, 180°, or 270°. Standardize scanned documents and presentation decks in one batch. ', parentSlug: "bulk-pdf-suite" },
  { slug: "bulk-pdf-protect", name: "Bulk PDF Protect", category: "PDF", description: "Add password protection to multiple PDF files in one batch. Set user and owner passwords to control access and permissions. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Protect — Add password protection to multiple PDF files in one batch. Set user and owner passwords to control access and permissions. ', parentSlug: "bulk-pdf-suite" },
  { slug: "bulk-pdf-unlock", name: "Bulk PDF Unlock", category: "PDF", description: "Remove password protection from multiple PDF files at once. Batch unlock protected documents when you know the password. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Unlock — Remove password protection from multiple PDF files at once. Batch unlock protected documents when you know the password. ', parentSlug: "bulk-pdf-suite" },
  { slug: "bulk-remove-pdf-pages", name: "Bulk Remove PDF Pages", category: "PDF", description: "Delete specific pages from multiple PDF files in one batch. Specify page ranges like 1-3, 5, 7-9 to remove across all files. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk Remove PDF Pages — Delete specific pages from multiple PDF files in one batch. Specify page ranges like 1-3, 5, 7-9 to remove across all files. ', parentSlug: "bulk-pdf-suite" },
  { slug: "bulk-pdf-split", name: "Bulk PDF Split", category: "PDF", description: "Split multi-page PDFs into smaller files — extract the first N pages from each document in batch. Perfect for distributing report sections. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Split — Split multi-page PDFs into smaller files. Extract the first N pages from each document in batch. ', parentSlug: "bulk-pdf-suite" },
  { slug: "bulk-pdf-watermark", name: "Bulk PDF Watermark", category: "PDF", description: "Add text watermarks to every page of multiple PDF files at once. Protect your documents with DRAFT, CONFIDENTIAL, or custom text. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Watermark — Add text watermarks to every page of multiple PDF files at once. Protect your documents with DRAFT, CONFIDENTIAL, or custom text. ', parentSlug: "bulk-pdf-suite" },
  { slug: "bulk-pdf-crop", name: "Bulk PDF Crop", category: "PDF", description: "Crop margins on multiple PDF files in one batch. Trim excess whitespace or standardize page layouts across an entire document set. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Crop — Crop margins on multiple PDF files in one batch. Trim excess whitespace or standardize page layouts. ', parentSlug: "bulk-pdf-suite" },
  { slug: "bulk-pdf-resize", name: "Bulk PDF Resize", category: "PDF", description: "Resize all pages in multiple PDF files to a standard dimension. Scale content to fit A4, Letter, or custom page sizes in batch. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Resize — Resize all pages in multiple PDF files to a standard dimension. Scale content to fit A4, Letter, or custom page sizes. ', parentSlug: "bulk-pdf-suite" },
  { slug: "bulk-pdf-flatten", name: "Bulk PDF Flatten", category: "PDF", description: "Flatten form fields and annotations in multiple PDFs at once. Convert fillable PDF forms into static documents in one batch. Everything runs locally in your browser — nothing is uploaded.", seoDescription: 'Free online Bulk PDF Flatten — Flatten form fields and annotations in multiple PDFs at once. Convert fillable PDF forms into static documents. ', parentSlug: "bulk-pdf-suite" },
];

export const TOOL_REDIRECTS: Record<string, { category: string; slug: string; sourceCategory?: string | string[] }> = {
  "base64-encoder-decoder": { category: "developer", slug: "base64-encode-decode" },
  "yaml-syntax-validator": { category: "developer", slug: "yaml-validator" },
  "jwt-decoder": { category: "developer", slug: "jwt-debugger" },
  "body-fat-estimator": { category: "health", slug: "body-fat-calculator" },
  "due-date-calculator": { category: "health", slug: "pregnancy-due-date-calculator" },
  "csv-data-generator": { category: "utility", slug: "csv-json-row-generator" },
  "data-converter": { category: "converter", slug: "data-format-converter" },
  "json-minifier": { category: "developer", slug: "json-formatter" },
  "csv-sorter": { category: "utility", slug: "csv-row-sorter" },
  "csv-preview-generator": { category: "converter", slug: "csv-html-table-converter" },
  "text-converter": { category: "converter", slug: "text-to-binary" },
  "aes-decrypt": { category: "developer", slug: "aes-encrypt" },
  "morse-code-converter": { category: "converter", slug: "morse-code-translator" },
  "customer-acquisition-cost-calculator": { category: "growth-metrics", slug: "cac-calculator" },
  "ratio-simplifier": { category: "calculator", slug: "ratio-calculator" },
  "proportional-calculator": { category: "calculator", slug: "proportion-calculator" },
  "ideal-weight-calculator": { category: "health", slug: "ideal-weight-calc" },
  "ovulation-calculator": { category: "health", slug: "ovulation-tracker" },
  "mp4-to-gif": { category: "video", slug: "video-to-gif" },
  "webm-to-gif": { category: "video", slug: "video-to-gif" },
  "rpm-calculator": { category: "growth-metrics", slug: "cpm-calculator" },
  "nps-survey-calculator": { category: "growth-metrics", slug: "net-promoter-score-calculator" },
  "random-password-generator": { category: "utility", slug: "password-generator" },
  "random-uuid-generator": { category: "developer", slug: "uuid-generator" },
  "guid-generator": { category: "developer", slug: "uuid-generator" },
  "text-diff-checker": { category: "developer", slug: "diff-checker" },
  "hash-generator": { category: "developer", slug: "md5-hash-generator" },
  "binary-converter": { category: "converter", slug: "number-base-converter" },
  "currency-rate-calculator": { category: "finance", slug: "currency-converter" },
  "exchange-rate-calculator": { category: "finance", slug: "currency-converter" },
  "water-requirement-calculator": { category: "health", slug: "water-intake-calculator" },
  "heart-rate-calculator": { category: "health", slug: "heart-rate-zone-calculator" },
  "pregnancy-calculator": { category: "health", slug: "pregnancy-due-date-calculator" },
  "fraction-simplifier": { category: "calculator", slug: "fraction-calculator" },
  "svg-to-png-converter": { category: "image", slug: "svg-to-png" },
  "kb-image-compressor": { category: "image", slug: "compress-image-to-50kb" },
  "profit-calculator": { category: "finance", slug: "profit-margin-calculator" },
  "css-gradient-generator": { category: "design", slug: "gradient-generator" },
  "days-between-dates-calculator": { category: "calculator", slug: "date-difference-calculator" },
  "days-until-calculator": { category: "calculator", slug: "time-until-calculator" },
  "meta-tag-generator": { category: "seo", slug: "seo-meta-tag-generator" },
  "working-capital-calculator": { category: "finance", slug: "profit-loss-calculator" },
  "macronutrient-calculator": { category: "health", slug: "macro-split-calculator" },
  "distance-calculator": { category: "calculator", slug: "coordinate-calculator" },
  "midpoint-calculator": { category: "calculator", slug: "coordinate-calculator" },
  "rule-of-three-calculator": { category: "calculator", slug: "proportion-calculator" },
  "fluid-typography-calculator": { category: "developer", slug: "fluid-typography-calculator" },
  "semver-calculator": { category: "developer", slug: "semver-calculator", sourceCategory: "calculator" },
  "reverse-text-generator": { category: "text", slug: "text-reverser" },
  "text-styling": { category: "text", slug: "fancy-text-generator" },
  "text-style-generator": { category: "text", slug: "fancy-text-generator" },

  // Category migration: Branding/Finance → Growth & Marketing Metrics (URL slug: /growth-metrics/)
  "conversion-rate-calculator": { category: "growth-metrics", slug: "conversion-rate-calculator" },
  "cpm-calculator": { category: "growth-metrics", slug: "cpm-calculator", sourceCategory: "branding" },
  "roas-calculator": { category: "growth-metrics", slug: "roas-calculator", sourceCategory: "branding" },
  "net-promoter-score-calculator": { category: "growth-metrics", slug: "net-promoter-score-calculator", sourceCategory: "branding" },
  "saas-metrics-dashboard": { category: "growth-metrics", slug: "saas-metrics-dashboard" },
  "ltv-calculator": { category: "growth-metrics", slug: "ltv-calculator" },
  "cac-calculator": { category: "growth-metrics", slug: "cac-calculator" },
  "burn-rate-calculator": { category: "growth-metrics", slug: "burn-rate-calculator", sourceCategory: "finance" },
  "employee-turnover-calculator": { category: "growth-metrics", slug: "employee-turnover-calculator" },
  "saas-pricing-calculator": { category: "growth-metrics", slug: "saas-pricing-calculator", sourceCategory: "finance" },
  "arr-calculator": { category: "growth-metrics", slug: "arr-calculator" },
  "churn-rate-calculator": { category: "growth-metrics", slug: "churn-rate-calculator" },
  "customer-ltv-calculator": { category: "growth-metrics", slug: "customer-ltv-calculator" },
  "mrr-calculator": { category: "growth-metrics", slug: "mrr-calculator" },
  "revenue-growth-calculator": { category: "growth-metrics", slug: "revenue-growth-calculator", sourceCategory: "finance" },
  "runway-calculator": { category: "growth-metrics", slug: "runway-calculator" },
  "ab-test-calculator": { category: "growth-metrics", slug: "ab-test-calculator" },
  "seat-license-calculator": { category: "growth-metrics", slug: "seat-license-calculator" },
  "trial-conversion-calculator": { category: "growth-metrics", slug: "trial-conversion-calculator", sourceCategory: "finance" },
  "acv-calculator": { category: "growth-metrics", slug: "acv-calculator", sourceCategory: "finance" },
  "saas-payback-period": { category: "growth-metrics", slug: "saas-payback-period", sourceCategory: "finance" },
  "saas-quick-ratio": { category: "growth-metrics", slug: "saas-quick-ratio" },
  "saas-rule-of-40": { category: "growth-metrics", slug: "saas-rule-of-40", sourceCategory: "finance" },

  // Stub entries with no module — redirect to nearest equivalent
  "curl-to-code": { category: "developer", slug: "curl-to-code-converter" },
  "video-converter-tool": { category: "converter", slug: "video-converter", sourceCategory: "video" },
  "jwt-encoder-signer": { category: "developer", slug: "jwt-debugger" },
  "memorable-password-generator": { category: "utility", slug: "password-generator" },
  "cpp-formatter": { category: "developer", slug: "code-beautifier" },
  "go-formatter": { category: "developer", slug: "code-beautifier" },
  "kotlin-formatter": { category: "developer", slug: "code-beautifier" },
  "php-beautifier": { category: "developer", slug: "code-beautifier" },
  "ruby-formatter": { category: "developer", slug: "code-beautifier" },
  "rust-formatter": { category: "developer", slug: "code-beautifier" },
  "wifi-qr-generator": { category: "utility", slug: "qr-code-generator" },
  "bulk-link-shortener": { category: "utility", slug: "bulk-url-shortener" },
  "bulk-short-link-generator": { category: "utility", slug: "bulk-url-shortener" },
  // Merged into Random Decision Maker — redirect to unified tool
  "decision-maker": { category: "utility", slug: "random-decision-maker" },
  "yes-no-picker": { category: "utility", slug: "random-decision-maker" },
  // Duplicate — redirect to Design's contrast-ratio-checker
  "contrast-checker": { category: "design", slug: "contrast-ratio-checker" },
  // CSV tools moved from Utility/Developer to Converter
  "tsv-csv-converter": { category: "converter", slug: "tsv-csv-converter", sourceCategory: "utility" },
  "ics-csv-converter": { category: "converter", slug: "ics-csv-converter", sourceCategory: "utility" },
  "vcf-csv-converter": { category: "converter", slug: "vcf-csv-converter", sourceCategory: "utility" },
  "csv-formatter": { category: "converter", slug: "csv-formatter", sourceCategory: "utility" },
  "csv-statistics": { category: "converter", slug: "csv-statistics", sourceCategory: ["utility", "developer"] },
  "csv-data-cleaner": { category: "converter", slug: "csv-data-cleaner", sourceCategory: "utility" },
  // Developer → Converter (category migration)
  "bulk-csv-excel-to-json": { category: "converter", slug: "bulk-csv-excel-to-json", sourceCategory: "developer" },
  "csv-to-sqlite": { category: "converter", slug: "csv-to-sqlite", sourceCategory: "developer" },
  "csv-to-sql": { category: "converter", slug: "csv-to-sql", sourceCategory: "developer" },
  "text-to-binary": { category: "converter", slug: "text-to-binary", sourceCategory: "developer" },
  "binary-to-text": { category: "converter", slug: "binary-to-text", sourceCategory: "developer" },
  "number-base-converter": { category: "converter", slug: "number-base-converter", sourceCategory: "developer" },
  "markdown-slack-converter": { category: "converter", slug: "markdown-slack-converter", sourceCategory: "developer" },
  "image-to-base64": { category: "converter", slug: "image-to-base64", sourceCategory: "developer" },
  "svg-base64-converter": { category: "converter", slug: "svg-base64-converter", sourceCategory: "developer" },
  // Developer → Utility (category migration)
  "csv-merger": { category: "utility", slug: "csv-merger", sourceCategory: "developer" },
  "csv-splitter": { category: "utility", slug: "csv-splitter", sourceCategory: "developer" },
  "csv-transpose": { category: "utility", slug: "csv-transpose", sourceCategory: "developer" },
  "csv-analyzer": { category: "utility", slug: "csv-analyzer", sourceCategory: "developer" },
  // Developer → Design (category migration)
  "avatar-generator": { category: "design", slug: "avatar-generator", sourceCategory: "developer" },
  "logo-placeholder-generator": { category: "design", slug: "logo-placeholder-generator", sourceCategory: "developer" },
  "image-placeholder-generator": { category: "design", slug: "image-placeholder-generator", sourceCategory: "developer" },
  // Utility → Developer (category migration)
  "ip-address-lookup": { category: "developer", slug: "ip-address-lookup", sourceCategory: "utility" },
  "random-port-generator": { category: "developer", slug: "random-port-generator", sourceCategory: "utility" },
  // Utility → Converter (category migration)
  "morse-code-translator": { category: "converter", slug: "morse-code-translator", sourceCategory: "utility" },
  "nato-phonetic-converter": { category: "converter", slug: "nato-phonetic-converter", sourceCategory: "utility" },
  // Text → Converter (category migration)
  "braille-translator": { category: "converter", slug: "braille-translator", sourceCategory: "text" },
  // Color tools moved from Utility to Design
  "color-picker": { category: "design", slug: "color-picker", sourceCategory: "utility" },
  "color-palette-generator": { category: "design", slug: "color-palette-generator", sourceCategory: "utility" },
  "gradient-generator": { category: "design", slug: "gradient-generator", sourceCategory: "utility" },
  "data-type-converter": { category: "converter", slug: "data-type-converter", sourceCategory: "utility" },
  // CSV-adjacent tools moved from Utility CSV Tools → Developer
  "phone-parser": { category: "developer", slug: "phone-parser", sourceCategory: "utility" },
  "mac-vendor-lookup": { category: "developer", slug: "mac-vendor-lookup", sourceCategory: "utility" },
  "large-text-viewer": { category: "developer", slug: "large-text-viewer", sourceCategory: "utility" },
  // Coming-soon stubs — redirect to nearest working tool or category
  "background-remover": { category: "image", slug: "ai-bg-changer" },
  "bg-changer": { category: "image", slug: "ai-bg-changer" },
  "image-converter": { category: "image", slug: "bulk-image-compressor" },
  "video-converter": { category: "converter", slug: "video-converter", sourceCategory: "video" },
  "ai-video-subtitler": { category: "video", slug: "subtitle-generator" },
  // Placeholder marketing page delisted Sep 2026 — route to the live Extension tool
  "browser-extension": { category: "extension", slug: "screen-recorder-extension" },
  // Video-to-audio redirects — from /video/ to /converter/ for proper routing
  "mp4-to-mp3": { category: "converter", slug: "mp4-to-mp3", sourceCategory: "video" },
  "mov-to-mp3": { category: "converter", slug: "mov-to-mp3", sourceCategory: "video" },
  "webm-to-mp3": { category: "converter", slug: "webm-to-mp3", sourceCategory: "video" },
  // Thin wrappers — redirect to parent tool
  "html-minifier": { category: "developer", slug: "js-minifier" },
  "css-minifier": { category: "developer", slug: "js-minifier" },
  // Premium text tool redirects
  "text-repeater-tool": { category: "text", slug: "text-repeater" },
  "repeat-text": { category: "text", slug: "text-repeater" },
  "unicode-text-styler": { category: "text", slug: "fancy-text-generator" },
  "fancy-text-styler": { category: "text", slug: "fancy-text-generator" },
  "superscript-generator": { category: "text", slug: "small-text-generator" },
  "subscript-generator": { category: "text", slug: "small-text-generator" },
  "ascii-big-text": { category: "text", slug: "big-text-generator" },
  "bubble-text-generator": { category: "text", slug: "big-text-generator" },
  "word-count-tool": { category: "text", slug: "writing-tools" },
  "readability-analyzer": { category: "text", slug: "writing-tools" },
  "apa-citation-generator": { category: "text", slug: "citation-generator" },
  "mla-citation-generator": { category: "text", slug: "citation-generator" },

  // Legacy category URLs — tool still lives at its canonical category
  "temperature-converter": { category: "utility", slug: "temperature-converter", sourceCategory: "converter" },
  "color-converter": { category: "design", slug: "color-converter", sourceCategory: "image" },
  "unix-time-converter": { category: "utility", slug: "unix-time-converter", sourceCategory: "developer" },
  "random-word-generator": { category: "utility", slug: "random-word-generator", sourceCategory: "developer" },
  "ascii-art-generator": { category: "utility", slug: "ascii-art-generator", sourceCategory: "developer" },
  "time-duration-calculator": { category: "calculator", slug: "time-duration-calculator", sourceCategory: "developer" },
  "random-time-generator": { category: "utility", slug: "random-time-generator", sourceCategory: "developer" },
  "list-converter": { category: "utility", slug: "list-converter", sourceCategory: "developer" },
  "minutes-to-hours-converter": { category: "utility", slug: "time-converter", sourceCategory: "developer" },
  "text-to-html-converter": { category: "converter", slug: "text-to-html-converter", sourceCategory: "seo" },
  "yaml-json-converter": { category: "converter", slug: "yaml-json-converter", sourceCategory: "developer" },
  "hours-minutes-calculator": { category: "calculator", slug: "hours-minutes-calculator", sourceCategory: "developer" },
  "json-path-query-builder": { category: "developer", slug: "json-path-query-builder", sourceCategory: "utility" },
  "screen-size-converter": { category: "calculator", slug: "screen-size-converter", sourceCategory: "utility" },
  "text-replacer": { category: "text", slug: "text-replacer", sourceCategory: "seo" },
  "trailing-space-remover": { category: "developer", slug: "trailing-space-remover", sourceCategory: "seo" },
  "date-difference-calculator": { category: "calculator", slug: "date-difference-calculator", sourceCategory: "developer" },
  "document-converter": { category: "converter", slug: "document-converter", sourceCategory: "pdf" },
  "xlsx-csv-converter": { category: "converter", slug: "xlsx-csv-converter", sourceCategory: "developer" },
  "line-sorter": { category: "utility", slug: "line-sorter", sourceCategory: "developer" },
  "json-to-code": { category: "converter", slug: "json-to-code", sourceCategory: "developer" },
  "random-string-generator": { category: "utility", slug: "random-string-generator", sourceCategory: "developer" },
  "epub-to-pdf": { category: "converter", slug: "epub-to-pdf", sourceCategory: "pdf" },
  "stylus-to-css-converter": { category: "converter", slug: "stylus-to-css-converter", sourceCategory: "developer" },
  "media-query-generator": { category: "developer", slug: "media-query-generator", sourceCategory: "design" },
  "age-calculator": { category: "calculator", slug: "age-calculator", sourceCategory: "utility" },
  "work-hours-calculator": { category: "calculator", slug: "work-hours-calculator", sourceCategory: "developer" },
  "random-picker-generator": { category: "utility", slug: "random-picker-generator", sourceCategory: "developer" },
  "meeting-time-planner": { category: "calculator", slug: "meeting-time-planner", sourceCategory: "developer" },
  "xml-to-json": { category: "converter", slug: "xml-to-json", sourceCategory: "developer" },
  "text-deduplicator": { category: "text", slug: "text-deduplicator", sourceCategory: "seo" },
  "random-decision-maker": { category: "utility", slug: "random-decision-maker", sourceCategory: "developer" },
  "time-until-calculator": { category: "calculator", slug: "time-until-calculator", sourceCategory: "developer" },
  "nickname-generator": { category: "utility", slug: "nickname-generator", sourceCategory: "developer" },
  "time-zone-converter": { category: "utility", slug: "time-zone-converter", sourceCategory: "developer" },
  "url-shortener": { category: "utility", slug: "url-shortener", sourceCategory: "branding" },
  "sequence-generator": { category: "utility", slug: "sequence-generator", sourceCategory: "developer" },
  "random-team-generator": { category: "utility", slug: "random-team-generator", sourceCategory: "developer" },
  "week-number-calculator": { category: "calculator", slug: "week-number-calculator", sourceCategory: "developer" },
  "daylight-saving-time-checker": { category: "calculator", slug: "daylight-saving-time-checker", sourceCategory: "developer" },
  "toml-converter": { category: "converter", slug: "toml-converter", sourceCategory: "developer" },
  "percentage-calculator": { category: "calculator", slug: "percentage-calculator", sourceCategory: "finance" },
  "date-addition-calculator": { category: "calculator", slug: "date-addition-calculator", sourceCategory: "developer" },
  "roman-numeral-converter": { category: "converter", slug: "roman-numeral-converter", sourceCategory: "utility" },
  "json-to-xml": { category: "converter", slug: "json-to-xml", sourceCategory: "developer" },
  "random-sentence-generator": { category: "utility", slug: "random-sentence-generator", sourceCategory: "developer" },
  "csv-to-markdown": { category: "converter", slug: "csv-to-markdown", sourceCategory: "utility" },
  "tailwind-to-css-converter": { category: "converter", slug: "tailwind-to-css-converter", sourceCategory: "developer" },
  "pdf-workflow-builder": { category: "pdf", slug: "pdf-workflow-builder", sourceCategory: "developer" },
  "text-sorter": { category: "text", slug: "text-sorter", sourceCategory: "seo" },
  "time-converter": { category: "utility", slug: "time-converter", sourceCategory: "converter" },
  "cidr-calculator": { category: "developer", slug: "cidr-calculator", sourceCategory: "utility" },
  "salary-calculator": { category: "finance", slug: "salary-calculator", sourceCategory: ["calculator"] },
  "savings-calculator": { category: "finance", slug: "savings-calculator", sourceCategory: "calculator" },
  "rent-vs-buy-calculator": { category: "finance", slug: "rent-vs-buy-calculator", sourceCategory: "calculator" },
  "percentage-difference-calculator": { category: "calculator", slug: "percentage-difference-calculator", sourceCategory: "utility" },
  "stopwatch": { category: "utility", slug: "stopwatch", sourceCategory: "developer" },
  "simple-interest-calculator": { category: "finance", slug: "simple-interest-calculator", sourceCategory: "calculator" },
  "words-per-page-calculator": { category: "calculator", slug: "words-per-page-calculator", sourceCategory: "finance" },
  "margin-calculator": { category: "finance", slug: "margin-calculator", sourceCategory: "calculator" },
  "greatest-common-factor-calculator": { category: "calculator", slug: "greatest-common-factor-calculator", sourceCategory: "utility" },
  "tabata-timer": { category: "utility", slug: "tabata-timer", sourceCategory: "developer" },
  "tip-calculator": { category: "finance", slug: "tip-calculator", sourceCategory: "utility" },
  "countdown-tool": { category: "utility", slug: "countdown-tool", sourceCategory: "developer" },
  "permutation-calculator": { category: "calculator", slug: "permutation-calculator", sourceCategory: "utility" },
  "eta-calculator": { category: "calculator", slug: "eta-calculator", sourceCategory: "utility" },
  "bmr-calculator": { category: "health", slug: "bmr-calculator", sourceCategory: "calculator" },
  "child-height-predictor": { category: "health", slug: "child-height-predictor", sourceCategory: "calculator" },
  "macro-calculator": { category: "health", slug: "macro-calculator", sourceCategory: "calculator" },
  "prime-number-checker": { category: "calculator", slug: "prime-number-checker", sourceCategory: "utility" },
  "emi-calculator": { category: "finance", slug: "emi-calculator", sourceCategory: "calculator" },
  "car-lease-calculator": { category: "finance", slug: "car-lease-calculator", sourceCategory: "calculator" },
  "hourly-to-salary-calculator": { category: "finance", slug: "hourly-to-salary-calculator", sourceCategory: "calculator" },
  "break-even-calculator": { category: "finance", slug: "break-even-calculator", sourceCategory: "calculator" },
  "sip-calculator": { category: "finance", slug: "sip-calculator", sourceCategory: "calculator" },
  "sales-tax-calculator": { category: "finance", slug: "sales-tax-calculator", sourceCategory: "utility" },
  "vat-calculator": { category: "finance", slug: "vat-calculator", sourceCategory: "calculator" },
  "car-loan-calculator": { category: "finance", slug: "car-loan-calculator", sourceCategory: "calculator" },
  "water-intake-calculator": { category: "health", slug: "water-intake-calculator", sourceCategory: "calculator" },
  "profit-margin-calculator": { category: "finance", slug: "profit-margin-calculator", sourceCategory: "calculator" },
  "steps-to-calories-calculator": { category: "health", slug: "steps-to-calories-calculator", sourceCategory: "calculator" },
  "tds-calculator-india": { category: "finance", slug: "tds-calculator-india", sourceCategory: "calculator" },
  "seconds-to-minutes-converter": { category: "utility", slug: "time-converter", sourceCategory: "developer" },
  "hours-to-minutes-converter": { category: "utility", slug: "time-converter", sourceCategory: "developer" },
};


