import type { ToolMetadata } from './tools-types';

export const entries_chunk_1: ToolMetadata[] = [
  {
    name: 'Unit Converter',
    slug: 'unit-converter',
    description: 'Convert between hundreds of units — length, mass, volume, temperature, currency, and more with a single click.',
    seoDescription: 'Free online Unit Converter — Universal unit conversion tool. ',
    category: 'Utility',
    id:  "224",
    dependencies: 'None'
  },
  {
    name: 'Video Watermark Adder',
    slug: 'video-watermark-adder',
    description: 'Add a logo image or custom text watermark to your videos with position and opacity controls. 100% browser-based.',
    seoDescription: 'Free online Video Watermark Adder — Add logo or text watermark to video. ',
    category: 'Video',
    id:  "223",
    dependencies: 'None',
},
  {
    name: 'GST Invoice Generator',
    slug: 'gst-invoice-generator',
    description: 'Generates compliant PDF invoices with mandatory Indian GST fields — HSN/SAC codes, GSTIN, place of supply, and tax breakdown. Everything runs locally in your browser.',
    seoDescription: 'Free online GST Invoice Generator — Create compliant GST invoices with HSN/SAC codes, GSTIN, place of supply, and tax breakdown. Download as PDF. 100% local and private.',
    category: 'indian-utilities',
    id:  "227",
    dependencies: 'None',
  },
  {
    name: 'ITR Filing Helper',
    slug: 'itr-filing-helper',
    description: 'Step-by-step assistant for India Income Tax Return filing. ITR form selection, 80C/80D deductions, salary and house property income.',
    seoDescription: 'Free online ITR Filing Helper — Guide to Indian income tax return filing. ITR form selection, 80C/80D deductions, salary and house property income. Simplify your tax filing.',
    category: 'indian-utilities',
    id:  "228",
    dependencies: 'None',
    showInCategory: false,
  },
  {
    name: 'Browser Extension',
    slug: 'browser-extension',
    description: 'All-in-one AI sidebar assistant that helps with writing, summarization, translation, and answering questions right in your browser.',
    seoDescription: 'Free online Browser Extension — All-in-one sidebar AI assistant. ',
    category: 'Extension',
    id:  "230",
    dependencies: 'None',
    showInCategory: false,
  },
  {
    name: 'MP3 Compressor',
    slug: 'mp3-compressor',
    description: 'Reduce MP3 file size by adjusting bitrate and audio quality settings. Perfect for saving storage or faster uploads.',
    seoDescription: 'Free online MP3 Compressor — Reduce MP3 size with bitrate control ',
    category: 'Audio',
    id:  "231",
    dependencies: 'FFmpeg WASM'
  },
  {
    name: 'GIF to MP4 Converter',
    slug: 'gif-to-mp4',
    description: 'Convert GIF animations to MP4 videos for drastically smaller file sizes. Content creators use this to shrink animated GIFs by up to 90% for social media, Discord, and web pages — all in your browser, nothing uploaded.',
    seoDescription: 'Free online GIF to MP4 Converter — Convert GIF animations to MP4 videos for drastically smaller file sizes. Shrink animated GIFs by up to 90% for social media, Discord, and web pages. ',
    category: 'Converter',
    id:  "232",
    dependencies: 'FFmpeg WASM'
  },
  {
    name: 'Video Trimmer',
    slug: 'video-trimmer',
    description: 'Trim and cut video clips locally in your browser. Select start and end times, preview, and download the result.',
    seoDescription: 'Free online Video Trimmer — Trim and cut video clips locally ',
    category: 'Video',
    id:  "233",
    dependencies: 'FFmpeg WASM',
},
  {
    name: 'Aadhaar Card Masker',
    slug: 'aadhaar-card-masker',
    description: 'Securely masks the first 8 digits of your 12-digit Aadhaar number on card images, leaving only the last 4 digits visible for safe sharing. Fully local processing.',
    seoDescription: 'Free online Aadhaar Card Masker — Mask first 8 digits of your Aadhaar number on card images. Leave only last 4 digits visible for secure sharing. 100% local, no uploads.',
    category: 'indian-utilities',
    id:  "234",
    dependencies: 'Canvas API',
  },
  {
    name: 'PAN Card Verification',
    slug: 'pan-verification',
    description: 'Verifies PAN card number format and structure locally. Extracts the taxpayer category from the PAN code — Individual, Company, Trust, etc. No data is sent to any server.',
    seoDescription: 'Free online PAN Card Verification — Verify PAN number format and extract taxpayer category (Individual, Company, HUF, Trust, etc.). 100% local validation with no data uploads.',
    category: 'indian-utilities',
    id:  "235",
    dependencies: 'None',
  },
  {
    name: 'IFSC Code Lookup',
    slug: 'ifsc-code-lookup',
    description: 'Looks up bank details from an 11-character IFSC code — bank name, branch, address, city, district, and contact info. Uses the built-in IFSC database for instant results.',
    seoDescription: 'Free online IFSC Code Lookup — Find bank name, branch, address, city, district, and contact details from any 11-character IFSC code. Instant lookup with comprehensive bank database.',
    category: 'indian-utilities',
    id:  "236",
    dependencies: 'IFSC API',
  },
  {
    name: 'Voter ID Form Helper',
    slug: 'voter-id-form-helper',
    description: 'Get document checklists and step-by-step guidance for Indian voter registration forms — Form 6 (new enrollment), Form 7 (correction/objection), and Form 8 (name transfer within constituency).',
    seoDescription: 'Free online Voter ID Form Helper — Guide for Indian voter registration Forms 6, 7, and 8. Document checklists, step-by-step instructions for new enrollment, corrections, and name transfers.',
    category: 'indian-utilities',
    id:  "237",
    dependencies: 'None',
  },
  {
    name: 'India Pincode Finder',
    slug: 'india-pincode-finder',
    description: 'Search Indian pincodes and post office branches by pincode, location name, or area. Find delivery status, office type, and contact details for any post office in India.',
    seoDescription: 'Free online India Pincode Finder — Search 6-digit pincodes and post office branches across India. Find delivery status, office type, district, state, and contact details instantly.',
    category: 'indian-utilities',
    id:  "238",
    dependencies: 'Postal API',
  },
  {
    name: 'Hindi / Regional Font Generator',
    slug: 'hindi-regional-font-generator',
    description: 'Generate stylish Unicode fonts for Hindi, Tamil, Telugu, Bengali, Marathi, Gujarati, and other Indian regional scripts. Copy-paste styled text for social media, WhatsApp, and more.',
    seoDescription: 'Free online Hindi & Regional Font Generator — Generate stylish Unicode fonts for Hindi, Tamil, Telugu, Bengali, Marathi, Gujarati, and more. Copy-paste for social media, WhatsApp, and designs.',
    category: 'indian-utilities',
    id:  "239",
    dependencies: 'None',
  },
  {
    name: 'Indian Age Calculator',
    slug: 'indian-age-calculator',
    description: 'Calculate exact age in years, months, and days from a date of birth in DD/MM/YYYY format. Includes eligibility check for Indian government age requirements.',
    seoDescription: 'Free online Indian Age Calculator — Exact age in years, months, and days from DOB. Includes eligibility checks for Indian age requirements. Instant results, no data upload.',
    category: 'indian-utilities',
    id:  "240",
    dependencies: 'None',
  },
  {
    name: 'CGPA to Percentage Converter',
    slug: 'cgpa-to-percentage-converter',
    description: 'Convert CGPA to percentage using CBSE, Mumbai University (MU), Anna University, and other Indian university conversion formulas. Supports 10-point, 7-point, and 4-point CGPA scales.',
    seoDescription: 'Free online CGPA to Percentage Converter — Convert CGPA to percentage using CBSE (9.5x), Mumbai University (7.1x+11), Anna University, and other India-specific formulas. Supports 10/7/4 point scales.',
    category: 'indian-utilities',
    id:  "241",
    dependencies: 'None',
  },
  {
    name: 'PDF to HTML',
    slug: 'pdf-to-html',
    description: 'Converts PDF files to HTML format — document sharing, printing, and archival with consistent formatting to web pages, email templates, and content rendering. All conversion happens locally in your browser with no file size limits.',
    seoDescription: 'Free online PDF to HTML — Convert PDF pages into a clean, responsive HTML5 document. ',
    category: 'PDF',
    id:  "242",
    dependencies: 'PDF.js'
  },
  {
    name: 'HTML to PDF',
    slug: 'html-to-pdf',
    description: 'Converts HTML files to PDF format — web pages, email templates, and content rendering to document sharing, printing, and archival with consistent formatting. All conversion happens locally in your browser with no file size limits.',
    seoDescription: 'Free online HTML to PDF — Convert HTML source code into a downloadable PDF document. ',
    category: 'PDF',
    id:  "243",
    dependencies: 'jsPDF',
  },
  {
    name: 'Generic PDF Processor',
    slug: 'generic-pdf-processor',
    description: 'Compress, rotate pages, or strip metadata from PDFs in one unified tool. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Generic PDF Processor — Compress, rotate pages, or strip metadata from PDFs in one unified tool. ',
    category: 'PDF',
    id:  "244",
    dependencies: 'pdf-lib'
  },
  {
    name: 'JFIF to PNG Converter',
    slug: 'jfif-to-png',
    showInCategory: false,
    description: 'Converts JFIF (JPEG File Interchange Format) images to standard PNG format without quality loss. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JFIF to PNG Converter — Converts JFIF (JPEG File Interchange Format) images to standard PNG format without quality loss. ',
    category: 'Image',
    id:  "246",
    dependencies: 'Canvas API'
  },
  {
    name: 'Image to JPG Converter',
    slug: 'convert-to-jpg',
    showInCategory: false,
    description: 'Converts any image format — PNG, WebP, BMP, GIF, TIFF — to standard JPG with configurable quality settings. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Image to JPG Converter — Converts any image format — PNG, WebP, BMP, GIF, TIFF — to standard JPG with configurable quality settings. ',
    category: 'Image',
    id:  "248",
    dependencies: 'Canvas API'
  },
  {
    name: 'Rotate Image Online',
    slug: 'rotate-image',
    description: 'Rotates images left or right by 90-degree increments instantly in the browser with no upload required. No signup or account required.',
    seoDescription: 'Free online Rotate Image Online — Rotates images left or right by 90-degree increments instantly in the browser with no upload required. ',
    category: 'Image',
    id:  "249",
    dependencies: 'Canvas API'
  },
  {
    name: 'Blur Face Online',
    slug: 'blur-face',
    description: 'Detects faces in uploaded images using AI-powered computer vision and applies an adjustable blur effect to each detected face. No signup or account required.',
    seoDescription: 'Free online Blur Face Online — Detects faces in uploaded images using AI-powered computer vision and applies an adjustable blur effect to each detected face. ',
    category: 'Image',
    id:  "250",
    dependencies: 'AI API'
  },
  {
    name: 'HTML to Image Converter',
    slug: 'html-to-image',
    description: 'Renders custom HTML and CSS markup into downloadable PNG, JPG, or SVG images directly in the browser. No signup or account required.',
    seoDescription: 'Free online HTML to Image Converter — Renders custom HTML and CSS markup into downloadable PNG, JPG, or SVG images directly in the browser. ',
    category: 'Converter',
    id:  "251",
    dependencies: 'html2canvas'
  },
  {
    name: 'Apple Music Preview Extractor',
    slug: 'apple-music-preview-extractor',
    description: 'Extracts publicly available 30-to-90-second audio preview clips from Apple Music by resolving the store URL. No signup or account required.',
    seoDescription: 'Free online Apple Music Preview Extractor — Extracts publicly available 30-to-90-second audio preview clips from Apple Music by resolving the store URL. ',
    category: 'Audio',
    id:  "252",
    dependencies: 'fetch API'
  },
  {
    name: 'Marriage Biodata Maker',
    slug: 'marriage-biodata-maker',
    description: 'Creates printable matrimonial biodata forms with sections for personal details, family background, education, career, and partner preferences. Download as PDF for sharing on matrimonial platforms.',
    seoDescription: 'Free online Marriage Biodata Maker — Create printable matrimonial biodata forms for Shaadi.com, BharatMatrimony, and other platforms. Personal details, family background, education, career, and partner preferences.',
    category: 'indian-utilities',
    id:  "257",
    dependencies: 'jsPDF',
  },
  {
    name: 'Rental Agreement Generator',
    slug: 'rental-agreement-generator',
    description: 'Generates customizable rental lease and license agreements compliant with Indian property laws. Supports leave-and-license agreements and standard tenancy formats for residential and commercial properties.',
    seoDescription: 'Free online Rental Agreement Generator — Create rental lease and license agreements compliant with Indian property laws. Leave-and-license and tenancy formats for residential/commercial properties. Download as PDF.',
    category: 'indian-utilities',
    id:  "258",
    dependencies: 'jsPDF',
  },
  {
    name: 'Resume ATS Score Checker',
    slug: 'resume-ats-score-checker',
    description: 'Analyzes uploaded resumes against a job description using AI to calculate an ATS compatibility score and provide actionable suggestions. No signup or account required.',
    seoDescription: 'Free online Resume ATS Score Checker — Analyzes uploaded resumes against a job description using AI to calculate an ATS compatibility score and provide actionable suggestions. ',
    category: 'AI',
    id:  "259",
    dependencies: 'AI API',
  },
  {
    name: 'WhatsApp Toolkit',
    slug: 'whatsapp-toolkit',
    description: 'Generates wa.me click-to-chat links, WhatsApp group invite links, QR codes for quick connections, and includes a chat analyzer and status text. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online WhatsApp Toolkit — Generates wa.me click-to-chat links, WhatsApp group invite links, QR codes for quick connections, and includes a chat analyzer and status text. ',
    category: 'Utility',
    id:  "261",
    dependencies: 'QRCode.js',
  },
  {
    name: 'Indian Document Enhancer',
    slug: 'indian-document-enhancer',
    description: 'Enhances scanned images of Indian identification documents — Aadhaar, PAN, Voter ID, Driving License — for upload compliance on government portals. Adjusts contrast, brightness, and sharpness locally.',
    seoDescription: 'Free online Indian Document Enhancer — Enhance scanned images of Aadhaar, PAN, Voter ID, and Driving License for government portal uploads. Improve contrast, brightness, and sharpness. 100% local processing.',
    category: 'indian-utilities',
    id:  "262",
    dependencies: 'Canvas API',
  },
  {
    name: 'Indian Voice Transcriber',
    slug: 'indian-voice-transcriber',
    description: 'Transcribes recorded audio to text with support for 12 Indian languages using browser-based Web Speech API recognition. Works offline with no data uploads for supported languages.',
    seoDescription: 'Free online Indian Voice Transcriber — Transcribe audio to text in 12 Indian languages (Hindi, Tamil, Telugu, Bengali, Marathi, Gujarati, Kannada, Malayalam, Punjabi, Odia, Urdu, English). Browser-based, no uploads.',
    category: 'indian-utilities',
    id:  "264",
    dependencies: 'Web Speech API',
  },
  {
    name: 'Bank Statement Analyser',
    slug: 'bank-statement-analyser',
    description: 'Parses uploaded bank statement PDFs or CSV exports and categorizes transactions into income, expense, and transfer categories with visual spending. No signup or account required.',
    seoDescription: 'Free online Bank Statement Analyser — Parses uploaded bank statement PDFs or CSV exports and categorizes transactions into income, expense, and transfer categories with visual spending. ',
    category: 'Utility',
    id:  "265",
    dependencies: 'PDF.js'
  },
  {
    name: 'Social Media Calendar',
    slug: 'social-media-calendar',
    description: 'Lets users plan and schedule social media posts across multiple platforms in a visual calendar view with draft, scheduled. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Social Media Calendar — Lets users plan and schedule social media posts across multiple platforms in a visual calendar view with draft, scheduled. ',
    category: 'Branding',
    id:  "268",
    dependencies: 'localStorage'
  },
  {
    name: 'Bulk Background Changer',
    slug: 'bulk-bg-changer',
    description: 'Removes or replaces backgrounds on multiple images simultaneously with color-key sampling and batch processing. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Bulk Background Changer — Removes or replaces backgrounds on multiple images simultaneously with color-key sampling and batch processing. ',
    category: 'Image',
    id:  "269",
    dependencies: 'Canvas API',
    isPro: true,
  
    },
  {
    name: 'AI Background Changer',
    slug: 'ai-bg-changer',
    description: 'Removes and replaces image backgrounds using edge-aware detection algorithms that separate foreground subjects without a green screen. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online AI Background Changer — Removes and replaces image backgrounds using edge-aware detection algorithms that separate foreground subjects without a green screen. ',
    category: 'Image',
    id:  "270",
    dependencies: 'Canvas API'
  },
  {
    name: 'Link in Bio Builder',
    slug: 'link-in-bio-builder',
    description: 'Creates customizable link-in-bio landing pages with profile photo, bio, multiple social media links, and custom icon selection. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Link in Bio Builder — Creates customizable link-in-bio landing pages with profile photo, bio, multiple social media links, and custom icon selection. ',
    category: 'Branding',
    id:  "271",
    dependencies: 'None'
  },
  {
    name: 'PDF Page Manager',
    slug: 'pdf-page-manager',
    description: 'Manages PDF pages with crop, organize, extract, rotate, and delete operations in a single unified interface with visual page thumbnails. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online PDF Page Manager — Manages PDF pages with crop, organize, extract, rotate, and delete operations in a single unified interface with visual page thumbnails. ',
    category: 'PDF',
    id:  "274",
    dependencies: 'pdf-lib'
  },
  {
    name: 'Bulk QR Code Generator',
    slug: 'bulk-qr-code-generator',
    description: 'Processes a CSV file containing multiple data entries and generates a corresponding QR code image for each row, delivered as a ZIP archive. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Bulk QR Code Generator — Processes a CSV file containing multiple data entries and generates a corresponding QR code image for each row, delivered as a ZIP archive. ',
    category: 'Utility',
    id:  "275",
    dependencies: 'qrcode.js, JSZip',
    isPro: true,
  
    },
  {
    name: 'PDF AI Summariser',
    slug: 'pdf-ai-summariser',
    description: 'Uploads a PDF document, extracts its full text via OCR and native parsing, then sends the content to an LLM for a condensed summary highlighting key points and insights.',
    seoDescription: 'Free online PDF AI Summariser — Uploads a PDF document, extracts its full text via OCR and native parsing, then sends the content to an LLM for a condensed summary highlighting key points and insights. ',
    category: 'AI',
    id:  "276",
    dependencies: 'AI API, PDF.js',
  },
  {
    id: "278",
    name: "Bulk Image Watermark",
    slug: "bulk-image-watermark",
    category: "Image",
    description: "Apply a text logo, image logo, or timestamp overlay to dozens of images at once with configurable position, opacity, and rotation per batch. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Image Watermark — Apply a text logo, image logo, or timestamp overlay to dozens of images at once with configurable position, opacity, and rotation per batch. ',
    dependencies: "Canvas API, jszip",
  
    },
  {
    id: "279",
    name: "Bulk PDF Data Extractor",
    slug: "bulk-pdf-data-extractor",
    category: "PDF",
    description: "Extract tables, form fields, and key-value pairs from multiple PDFs simultaneously and export the aggregated data to a single CSV or Excel file. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk PDF Data Extractor — Extract tables, form fields, and key-value pairs from multiple PDFs simultaneously and export the aggregated data to a single CSV or Excel file. ',
    dependencies: "pdf-lib, SheetJS",
  
    },
  {
    id: "280",
    name: "Bulk Image to PDF",
    slug: "bulk-image-to-pdf",
    category: "PDF",
    description: "Merge hundreds of JPG, PNG, or WebP images into a single multi-page PDF with configurable page size, orientation, and compression per batch. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Image to PDF — Merge hundreds of JPG, PNG, or WebP images into a single multi-page PDF with configurable page size, orientation, and compression per batch. ',
    dependencies: "jsPDF, Canvas API",
  
    },
  {
    id: "281",
    name: "Bulk Audio Converter",
    slug: "bulk-audio-converter",
    category: "Audio",
    description: "Convert an entire folder of audio files between MP3, WAV, OGG, FLAC, and M4A formats in one batch with consistent quality and bitrate settings. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Audio Converter — Convert an entire folder of audio files between MP3, WAV, OGG, FLAC, and M4A formats in one batch with consistent quality and bitrate settings. ',
    dependencies: "FFmpeg WASM",
  
    },
  {
    id: "282",
    name: "Bulk SVG to PNG",
    slug: "bulk-svg-to-png",
    category: "Image",
    description: "Rasterize hundreds of SVG files to PNG at any resolution, preserving vector sharpness. Ideal for generating icon sprite sheets and asset pipelines. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk SVG to PNG — Rasterize hundreds of SVG files to PNG at any resolution, preserving vector sharpness. Ideal for generating icon sprite sheets and asset pipelines. ',
    dependencies: "Canvas API, jszip",
  
    },
  {
    id: "283",
    name: "Bulk Image Compressor",
    slug: "bulk-image-compressor",
    category: "Image",
    description: "Compress JPG, PNG, and WebP images in bulk with uniform quality settings. E-commerce sellers use it to optimize entire product catalogs before upload. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Image Compressor — Compress JPG, PNG, and WebP images in bulk with uniform quality settings. E-commerce sellers use it to optimize entire product catalogs before upload. ',
    dependencies: "browser-image-compression, jszip",
  
    },
  {
    id: "284",
    name: "Bulk PDF Size Reducer",
    slug: "bulk-pdf-size-reducer",
    category: "PDF",
    description: "Reduce file size of multiple PDFs at once by compressing embedded images, removing metadata, and optimizing object streams across the batch. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk PDF Size Reducer — Reduce file size of multiple PDFs at once by compressing embedded images, removing metadata, and optimizing object streams across the batch. ',
    dependencies: "pdf-lib",
  
    },
  {
    id: "285",
    name: "Bulk Image Resizer",
    slug: "bulk-image-resizer",
    category: "Image",
    description: "Resize hundreds of images to exact pixel dimensions or percentage scale in one pass. Photographers use it to standardize client galleries before delivery. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Image Resizer — Resize hundreds of images to exact pixel dimensions or percentage scale in one pass. Photographers use it to standardize client galleries before delivery. ',
    dependencies: "Canvas API, jszip",
  
    },
  {
    id: "286",
    name: "Bulk Video Compressor",
    slug: "bulk-video-compressor",
    category: "Video",
    description: "Compress multiple video files simultaneously with consistent CRF, resolution, and codec settings. YouTube studios use it to batch-optimize daily uploads. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Video Compressor — Compress multiple video files simultaneously with consistent CRF, resolution, and codec settings. YouTube studios use it to batch-optimize daily uploads. ',
    dependencies: "FFmpeg WASM",
  
    },
  {
    id: "287",
    name: "Bulk PDF Merger",
    slug: "bulk-pdf-merger",
    category: "PDF",
    description: "Join dozens of PDF files into one document in a single operation. Legal teams use it to consolidate contract bundles and discovery exhibits instantly. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk PDF Merger — Join dozens of PDF files into one document in a single operation. Legal teams use it to consolidate contract bundles and discovery exhibits instantly. ',
    dependencies: "pdf-lib",
  
    },
  {
    id: "288",
    name: "Bulk Face Anonymizer",
    slug: "bulk-face-anonymizer",
    category: "Image",
    description: "Detect and blur faces across multiple images automatically using on-device face detection. GDPR compliance teams use it to anonymize datasets before publication. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Face Anonymizer — Detect and blur faces across multiple images automatically using on-device face detection. GDPR compliance teams use it to anonymize datasets before publication. ',
    dependencies: "TensorFlow.js, Canvas API, jszip",
  
    },
  {
    id: "289",
    name: "Bulk PDF Form Extractor",
    slug: "bulk-pdf-form-extractor",
    category: "PDF",
    description: "Extract filled form fields from hundreds of identical PDF forms and aggregate responses into a single CSV. Large-scale survey and application processing teams depend on it. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk PDF Form Extractor — Extract filled form fields from hundreds of identical PDF forms and aggregate responses into a single CSV. Large-scale survey and application processing teams depend on it. ',
    dependencies: "pdf-lib",
  
    },
  {
    id: "290",
    name: "Bulk Video Size Reducer",
    slug: "bulk-video-size-reducer",
    category: "Video",
    description: "Batch-reduce video file sizes to fit email attachment limits (25MB), messaging platform caps, or any user-defined target. Every office worker with video attachments needs this. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Video Size Reducer — Batch-reduce video file sizes to fit email attachment limits (25MB), messaging platform caps, or any user-defined target. Every office worker with video attachments needs this. ',
    dependencies: "FFmpeg WASM",
  
    },
  {
    id: "291",
    name: "Bulk Audio Normalizer",
    slug: "bulk-audio-normalizer",
    category: "Audio",
    description: "Normalize loudness across multiple audio files to broadcast-standard LUFS levels (–16 LUFS for podcasts, –14 LUFS for streaming). Podcast networks use this to unify episode volume. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Audio Normalizer — Normalize loudness across multiple audio files to broadcast-standard LUFS levels (–16 LUFS for podcasts, –14 LUFS for streaming). Podcast networks use this to unify episode volume. ',
    dependencies: "Web Audio API",
  
    },
  {
    id: "292",
    name: "Bulk Video Subtitle Burner",
    slug: "bulk-video-subtitle-burner",
    category: "Video",
    description: "Burn SRT or VTT subtitles directly into multiple video files in one batch. Content republishers use it to prepare videos for platforms that do not support soft subtitles. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Video Subtitle Burner — Burn SRT or VTT subtitles directly into multiple video files in one batch. Content republishers use it to prepare videos for platforms that do not support soft subtitles. ',
    dependencies: "FFmpeg WASM",
  
    },
  {
    id: "293",
    name: "Bulk Invoice & Receipt Parser",
    slug: "bulk-invoice-receipt-parser",
    category: "Finance",
    description: "Drop 100 invoice PDFs or images, auto-detect date, vendor, amount, and tax, then export a clean CSV ready for tax filing. Replaces expensive accounting OCR per-document fees. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Invoice & Receipt Parser — Drop 100 invoice PDFs or images, auto-detect date, vendor, amount, and tax, then export a clean CSV ready for tax filing. Replaces expensive accounting OCR per-document fees. ',
    dependencies: "Tesseract.js, pdf-lib, SheetJS",
  
    },
  {
    id: "294",
    name: "Bulk CSV/Excel to JSON",
    slug: "bulk-csv-excel-to-json",
    category: "Developer",
    description: "Convert messy CSV or Excel sheets from clients into clean JSON in one batch. Handles missing values, nested rows, and generates strict JSON schemas for 50+ files at once. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk CSV/Excel to JSON — Convert messy CSV or Excel sheets from clients into clean JSON in one batch. Handles missing values, nested rows, and generates strict JSON schemas for 50+ files at once. ',
    dependencies: "SheetJS",
  
    },
  {
    id: "295",
    name: "Bulk URL Status Checker",
    slug: "bulk-url-status-checker",
    category: "SEO",
    description: "Check 5,000 URLs for HTTP status codes (200, 301, 404, 500), extract title/meta descriptions, and flag slow pages. SEO agencies use it instead of $50/mo crawling tools. No signup or account required.",
    seoDescription: 'Free online Bulk URL Status Checker — Check 5,000 URLs for HTTP status codes (200, 301, 404, 500), extract title/meta descriptions, and flag slow pages. SEO agencies use it instead of $50/mo crawling tools. ',
    dependencies: "fetch API",
  
    },
  {
    id: "296",
    name: "Bulk Image Format Converter",
    slug: "bulk-image-converter",
    category: "Image",
    description: "Convert images between JPG, PNG, WebP, AVIF, HEIC, HEIF, GIF, BMP, ICO, SVG. Batch convert with quality control. 100% local, zero uploads.",
    seoDescription: 'Free online Bulk Image Converter — Convert JPG, PNG, WebP, AVIF, HEIC, GIF, BMP, ICO, SVG in bulk. Quality control, directory preservation, zero uploads. ',
    dependencies: "Canvas API, jszip, heic2any",
  
    },
  {
    id: "297",
    name: "Bulk EXIF Stripper & Injector",
    slug: "bulk-exif-stripper-injector",
    category: "Image",
    description: "Strip GPS location, camera serial, and timestamps from thousands of photos client-side. Or bulk-inject copyright metadata using a template across an entire image library. No signup or account required.",
    seoDescription: 'Free online Bulk EXIF Stripper & Injector — Strip GPS location, camera serial, and timestamps from thousands of photos client-side. Or bulk-inject copyright metadata using a template across an entire image library. ',
    dependencies: "exifr, piexifjs, jszip",
  
    },
  {
    id: "298",
    name: "Bulk App Icon Generator",
    slug: "bulk-app-icon-generator",
    category: "Image",
    description: "Upload one high-res SVG/PNG and export 30+ correctly sized icons for iOS, Android, PWA, Shopify, and social media OG images in a structured ZIP. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk App Icon Generator — Upload one high-res SVG/PNG and export 30+ correctly sized icons for iOS, Android, PWA, Shopify, and social media OG images in a structured ZIP. ',
    dependencies: "Canvas API, jszip",
  
    },
  {
    id: "299",
    name: "Bulk Markdown to PDF/HTML",
    slug: "bulk-markdown-to-pdf-html",
    category: "Converter",
    description: "Convert 100+ Markdown files into beautifully styled PDFs or static HTML with custom CSS, auto-generated table of contents, and corporate templates. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Markdown to PDF/HTML — Convert 100+ Markdown files into beautifully styled PDFs or static HTML with custom CSS, auto-generated table of contents, and corporate templates. ',
    dependencies: "marked.js, jsPDF, jszip",
  
    },
  {
    id: "300",
    name: "Bulk Font Subsetter",
    slug: "bulk-font-subsetter",
    category: "Developer",
    description: "Convert TTF/OTF fonts to WOFF2 and subset to only used characters (Latin, Cyrillic, etc.). Generates @font-face CSS blocks. Cuts font files from MBs to KBs. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Font Subsetter — Convert TTF/OTF fonts to WOFF2 and subset to only used characters (Latin, Cyrillic, etc.). Generates @font-face CSS blocks. Cuts font files from MBs to KBs. ',
    dependencies: "opentype.js, jszip",
  
    },
  {
    id: "301",
    name: "Bulk Subtitle Time-Shifter",
    slug: "bulk-subtitle-time-shifter",
    category: "Video",
    description: "Apply global time offset (+/- seconds) to a whole season of SRT/VTT files at once. Localization agencies use it to realign and translate subtitle batches. No signup or account required.",
    seoDescription: 'Free online Bulk Subtitle Time-Shifter — Apply global time offset (+/- seconds) to a whole season of SRT/VTT files at once. Localization agencies use it to realign and translate subtitle batches. ',
    dependencies: "Vanilla JS, jszip",
  
    },
  {
    id: "302",
    name: "Bulk Regex Extractor & Replacer",
    slug: "bulk-regex-extractor-replacer",
    category: "Developer",
    description: "Scan thousands of log files or codebase files for regex patterns (IPs, API keys, URLs) and extract or replace them. Visual builder for non-coders with live preview. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Regex Extractor & Replacer — Scan thousands of log files or codebase files for regex patterns (IPs, API keys, URLs) and extract or replace them. Visual builder for non-coders with live preview. ',
    dependencies: "Vanilla JS, jszip",
  
    },
  {
    id: "303",
    name: "Bulk Image to Text (OCR)",
    slug: "bulk-image-to-text-ocr",
    category: "Image",
    description: "Extract text from batches of scanned JPGs, PNGs, or PDF pages and export as a single formatted Word doc. Students and digitizers use it instead of typing 40 pages manually. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: 'Free online Bulk Image to Text (OCR) — Extract text from batches of scanned JPGs, PNGs, or PDF pages and export as a single formatted Word doc. Students and digitizers use it instead of typing 40 pages manually. ',
    dependencies: "Tesseract.js, jszip",
  
    },
  {
    id: "304",
    name: "Bulk E-Book Converter",
    slug: "bulk-ebook-converter",
    category: "Converter",
    description: "Convert your entire digital library between EPUB, MOBI, and PDF in one batch. Note: This is a basic client-side conversion — complex EPUB/MOBI layouts may not render perfectly. For professional results, use a dedicated e-book tool like Calibre.",
    seoDescription: 'Free online Bulk E-Book Converter — Convert your entire digital library between EPUB, MOBI, and PDF in one batch. Basic client-side conversion — complex layouts may not render perfectly. ',
    dependencies: "EPUB.js, jszip",
  
    },
  {
    id: "306",
    name: "Bulk HEIC to JPG",
    slug: "bulk-heic-to-jpg",
    category: "Image",
    description: "Convert hundreds of iPhone HEIC photos to universal JPGs in one batch — fully client-side so your personal vacation photos never leave your machine. Windows users finally view their iPhone library. No signup or account required.",
    seoDescription: 'Free online Bulk HEIC to JPG — Convert hundreds of iPhone HEIC photos to universal JPGs in one batch — fully client-side so your personal vacation photos never leave your machine. Windows users finally view their iPhone library. ',
    dependencies: "libheif WASM, jszip",
  
    },
  {
    id: "307",
    name: "Tax Saving Calculator",
    slug: "tax-saving-calculator",
    category: "indian-utilities",
    description: 'Compares Old vs New tax regime liability with Section 80C, 80D, NPS, HRA, and home loan deductions. Generates a personalized tax-saving report for Indian salaried employees.',
    seoDescription: 'Free online Indian Tax Saving Calculator — Compare Old vs New tax regime liability with 80C, 80D, NPS, HRA, and home loan deductions. Generates personalized tax-saving report for Indian salaried employees.',
    dependencies: "None",
  },
  {
    id: "308",
    name: "GSTIN Lookup",
    slug: "gstin-lookup",
    category: "indian-utilities",
    description: 'Verifies any GSTIN (Goods and Services Tax Identification Number) instantly — returns legal name, trade name, address, registration date, and filing status. Supports bulk CSV export for accounts teams.',
    seoDescription: 'Free online GSTIN Lookup — Verify any GSTIN instantly. Get legal name, trade name, address, registration date, constitution, and filing status. Bulk CSV verification for accounts and vendor onboarding.',
    dependencies: "None",
  },
  {
    id: "309",
    name: "Seller Profit Calculator",
    slug: "seller-profit-calculator",
    category: "indian-utilities",
    description: 'Calculates exact profit after marketplace commissions (Meesho, Amazon, Flipkart), GST, shipping costs, returns, and packaging. Compare platform profitability side-by-side for Indian e-commerce sellers.',
    seoDescription: 'Free online Seller Profit Calculator for India — Calculate exact profit after Meesho, Amazon, Flipkart commissions, GST, shipping, returns, and packaging. Compare platforms side-by-side for Indian e-commerce sellers.',
    dependencies: "None",
  },
  {
    id: "310",
    name: "Complaint Letter Generator",
    slug: "complaint-letter-generator",
    category: "indian-utilities",
    description: 'Generates legally correct formal complaint letters citing Indian consumer law — Consumer Protection Act 2019, RERA, TRAI, or RBI regulations. AI-powered with your API key.',
    seoDescription: 'Free online Complaint Letter Generator India — Create formal complaint letters citing Consumer Protection Act 2019, RERA, TRAI, RBI. Draft legal notices for telecom, banking, real estate, and e-commerce issues.',
    dependencies: "AI API",
  },
  {
    id: "auto-10030",
    name: "Brand Color Palette Generator",
    slug: "brand-color-palette-generator",
    category: "Branding",
    description: "AI-powered brand color palette generator. Describe your brand and get a complete 6-color palette with usage suggestions for designers.",
    seoDescription: "Free online Brand Color Palette Generator — AI-powered brand color palette generator. Describe your brand and receive a complete 6-color palette with hex codes and designer usage notes. ",
    dependencies: "None",
  },
  {
    id: "auto-10031",
    name: "Brand Kit",
    slug: "brand-kit",
    category: "Branding",
    description: "A local-first brand asset manager for colors and fonts. No signup or account required.",
    seoDescription: "Free online Brand Kit — A local-first brand asset manager for colors and fonts. ",
    dependencies: "None",
  },
  {
    id: "auto-10043",
    name: "To-Do List",
    slug: "to-do-list",
    category: "Productivity",
    description: "A persistent task manager with priorities and filters. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: "Free online To-Do List — A persistent task manager with priorities and filters. ",
    dependencies: "None",
  },
  {

    id: "auto-10050",
    name: "Domain Availability Checker",
    slug: "domain-availability-checker",
    category: "Developer",
    description: "Check if a domain name is available across major TLDs. Instantly verify domain availability, lookup registration status, and get suggestions for alternative names.",
    seoDescription: "Free online Domain Availability Checker — Check if a domain name is available across major TLDs. Instantly verify domain availability, lookup registration status, and get suggestions for alternative names. No signup required.",
    dependencies: "DNS API",
},
  {
    id: "auto-10051",
    name: "Pronunciation Tool",
    slug: "pronunciation-tool",
    category: "Text",
    description: 'Hear the correct pronunciation of any word or phrase in multiple English accents using browser-based speech synthesis. Adjustable playback speed with clear audio output.',
    seoDescription: 'Free online Pronunciation Tool — Hear correct pronunciation of words and phrases in multiple English accents using browser speech synthesis. Adjustable speed and clear audio.',
    dependencies: "Web Speech API",
  },
  {
    id: "video-converter-1",
    name: "Video Format Converter",
    slug: "video-converter",
    category: "Video",
    description: 'Convert between MKV, MP4, MOV, WebM, and AVI video formats. Pick any input and output format from the dropdown — your files never leave your device.',
    seoDescription: 'Free online Video Format Converter — Convert between MKV, MP4, MOV, WebM, and AVI video formats. Pick any input and output format. ',
    dependencies: "FFmpeg",

    showInCategory: false,
  },
  {
    id: "audio-converter-1",
    name: "Audio Format Converter",
    slug: "audio-converter",
    category: "Audio",
    description: 'Convert between MP3, WAV, FLAC, OGG, M4A, and AAC audio formats. Pick any input and output format — your files never leave your device.',
    seoDescription: 'Free online Audio Format Converter — Convert between MP3, WAV, FLAC, OGG, M4A, and AAC audio formats. Pick any input and output format. ',
    dependencies: "FFmpeg",
    showInCategory: true,
  },
  {
    id: "image-format-converter-1",
    name: "Image Format Converter",
    slug: "image-format-converter",
    category: "Image",
    description: 'Convert between PNG, JPG, WebP, HEIC, and AVIF image formats. Pick any input and output format — your files never leave your device.',
    seoDescription: 'Free online Image Format Converter — Convert between PNG, JPG, WebP, HEIC, and AVIF image formats. Pick any input and output format. ',
    dependencies: "Sharp / Browser Canvas",
    showInCategory: true,
  },
  {
    id: "data-converter-1",
    name: "Data Converter",
    slug: "data-converter",
    category: "Converter",
    description: 'Convert between JSON, CSV, XML, YAML, and Excel data formats. Pick any input and output format — your files never leave your device.',
    seoDescription: 'Free online Data Converter — Convert between JSON, CSV, XML, YAML, and Excel data formats. Pick any input and output format. ',
    dependencies: "PapaParse / SheetJS / js-yaml",
    showInCategory: true,
  },
  {
    id: "document-converter-1",
    name: "Document Converter",
    slug: "document-converter",
    category: "Converter",
    description: 'Convert between PDF, Word, Excel, PowerPoint, JPG, EPUB, and HEIC document formats. Pick any input and output format — your files never leave your device.',
    seoDescription: 'Free online Document Converter — Convert between PDF, Word, Excel, PowerPoint, JPG, EPUB, and HEIC document formats. Pick any input and output format. ',
    dependencies: "pdf-lib / pdf2docx / SheetJS / PptxGenJS",
    showInCategory: true,
  },
  {
    id: "311",
    name: "PDF to Markdown",
    slug: "pdf-to-markdown",
    category: "PDF",
    description: 'Extracts all text content from PDF files and converts it to clean Markdown format with proper headings, lists, and structure. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online PDF to Markdown — Extracts all text content from PDF files and converts it to clean Markdown format with proper headings, lists, and structure. ',
    dependencies: "pdfjs-dist",
    showInCategory: true,
  },
  {
    id: "312",
    name: "Extract Pages from PDF",
    slug: "extract-pages-from-pdf",
    category: "PDF",
    description: 'Extract specific pages from a PDF document to create a new PDF. Select individual pages or page ranges like 1-3,5,7-9. Keeps original formatting intact.',
    seoDescription: 'Free online Extract Pages from PDF — Extract specific pages from a PDF document to create a new PDF. Select individual pages or page ranges. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "313",
    name: "Scan to PDF",
    slug: "scan-to-pdf",
    category: "PDF",
    description: 'Turn photos and scanned images into a professional PDF document. Upload multiple images, reorder, and combine into a single PDF. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Scan to PDF — Turn photos and scanned images into a professional PDF document. Upload multiple images, reorder, and combine into a single PDF. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "314",
    name: "Repair PDF",
    slug: "repair-pdf",
    category: "PDF",
    description: 'Attempts to repair corrupted or damaged PDF files by rebuilding the internal structure. Recovers readable content from broken PDFs and re-saves them as valid PDF documents.',
    seoDescription: 'Free online Repair PDF — Attempts to repair corrupted or damaged PDF files by rebuilding the internal structure. Recovers readable content from broken PDFs. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "315",
    name: "PDF to PDF/A",
    slug: "pdf-to-pdfa",
    category: "PDF",
    description: 'Converts standard PDF files to PDF/A archival format with proper metadata, embedded fonts, and color profiles. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online PDF to PDF/A — Converts standard PDF files to PDF/A archival format with proper metadata, embedded fonts, and color profiles. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "316",
    name: "Crop PDF",
    slug: "crop-pdf",
    category: "PDF",
    description: 'Crop PDF pages to custom dimensions or preset sizes. Remove unwanted margins, white space, or sections from your PDF documents. Supports all standard and custom crop areas.',
    seoDescription: 'Free online Crop PDF — Crop PDF pages to custom dimensions or preset sizes. Remove unwanted margins, white space, or sections. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "317",
    name: "Redact PDF",
    slug: "redact-pdf",
    category: "PDF",
    description: 'Permanently remove sensitive information from PDF files. Black out text, images, or areas with permanent redaction. Perfect for legal documents, contracts, and personal data protection.',
    seoDescription: 'Free online Redact PDF — Permanently remove sensitive information from PDF files. Black out text, images, or areas with permanent redaction. ',
    dependencies: "pdf-lib, pdfjs-dist",
    showInCategory: true,
  },
  {
    id: "318",
    name: "Translate PDF",
    slug: "translate-pdf",
    category: "PDF",
    description: 'Extract and translate PDF content between 50+ languages. Preserves document structure while converting text to your chosen language. Powered by browser-based and free translation APIs.',
    seoDescription: 'Free online Translate PDF — Extract and translate PDF content between 50+ languages. Preserves document structure while converting text. ',
    dependencies: "pdfjs-dist",
    showInCategory: true,
  },
  {
    id: "319",
    name: "Flatten PDF",
    slug: "flatten-pdf",
    category: "PDF",
    description: 'Flattens PDF files by merging all layers, removing form fields, and converting interactive elements into static content. Perfect for sharing finalized documents and reducing file complexity.',
    seoDescription: 'Free online Flatten PDF — Flattens PDF files by merging all layers, removing form fields, and converting interactive elements into static content. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "320",
    name: "Grayscale PDF",
    slug: "grayscale-pdf",
    category: "PDF",
    description: 'Convert any PDF to grayscale/black and white. Perfect for printing, reducing ink usage, creating archive copies, or giving documents a professional monochrome look.',
    seoDescription: 'Free online Grayscale PDF — Convert any PDF to grayscale/black and white. Perfect for printing and reducing ink usage. ',
    dependencies: "pdfjs-dist, pdf-lib",
    showInCategory: true,
  },
  {
    id: "321",
    name: "Whiteout PDF",
    slug: "whiteout-pdf",
    category: "PDF",
    description: 'Cover sensitive or unwanted content in PDF files with white rectangles. Select entire pages or custom areas to hide text, images, or sections before sharing or printing.',
    seoDescription: 'Free online Whiteout PDF — Cover sensitive content in PDF files with white rectangles. Select entire pages or custom areas to hide text or images. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "322",
    name: "Resize PDF Pages",
    slug: "resize-pdf-pages",
    category: "PDF",
    description: 'Change the page size of your PDF documents. Choose from standard sizes (A4, Letter, Legal, A3) or set custom dimensions. Automatically adds white margins when enlarging.',
    seoDescription: 'Free online Resize PDF Pages — Change page size of your PDF documents. Choose A4, Letter, Legal, A3 or custom dimensions. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "323",
    name: "Add Text to PDF",
    slug: "add-text-to-pdf",
    category: "PDF",
    description: 'Add custom text labels, annotations, and captions directly onto PDF pages. Choose font size, color, and position. Perfect for signing, marking up, or adding notes to documents.',
    seoDescription: 'Free online Add Text to PDF — Add custom text labels, annotations, and captions directly onto PDF pages. Choose font size, color, and position. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "324",
    name: "Add Image to PDF",
    slug: "add-image-to-pdf",
    category: "PDF",
    description: 'Insert images (PNG, JPG) onto any page of your PDF document. Position and resize images anywhere on the page. Perfect for adding signatures, logos, or photos to documents.',
    seoDescription: 'Free online Add Image to PDF — Insert images onto any page of your PDF. Position and resize PNG/JPG images anywhere. Perfect for signatures, logos, or photos. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "325",
    name: "Header and Footer",
    slug: "header-footer-pdf",
    category: "PDF",
    description: 'Add professional headers and footers to every page of your PDF. Supports text, page numbers ({{page}}/{{total}}), dates, and custom alignment. Perfect for reports and official documents.',
    seoDescription: 'Free online PDF Header and Footer — Add professional headers and footers to every page. Supports page numbers, dates, and custom alignment. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "326",
    name: "N-up PDF",
    slug: "nup-pdf",
    category: "PDF",
    description: 'Combine multiple PDF pages onto a single sheet with N-up layout. Choose 2-up, 4-up, 6-up, 9-up, or booklet mode. Perfect for printing multiple slides or pages on one sheet.',
    seoDescription: 'Free online N-up PDF — Combine multiple PDF pages onto a single sheet. Choose 2-up, 4-up, 6-up, 9-up, or booklet layout. ',
    dependencies: "pdfjs-dist, pdf-lib",
    showInCategory: true,
  },
  {
    id: "327",
    name: "PDF Annotator",
    slug: "pdf-annotator",
    category: "PDF",
    description: 'Add visual annotations like highlights, underlines, strikeouts, and shapes to your PDF pages. Perfect for reviewing documents, marking up text, and adding visual emphasis.',
    seoDescription: 'Free online PDF Annotator — Add highlights, underlines, strikeouts, rectangles, circles to PDF pages. Review and markup documents visually. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "328",
    name: "Deskew PDF",
    slug: "deskew-pdf",
    category: "PDF",
    description: 'Automatically detect and straighten crooked scanned PDF pages. Uses advanced image analysis to find the correct rotation angle. Perfect for fixing skewed scanned documents.',
    seoDescription: 'Free online Deskew PDF — Automatically straighten crooked scanned PDF pages. Fix skewed documents with auto-detection or manual rotation. ',
    dependencies: "pdfjs-dist, pdf-lib",
    showInCategory: true,
  },
  {
    id: "329",
    name: "URL to PDF",
    slug: "url-to-pdf",
    category: "PDF",
    description: 'Convert any webpage to PDF in your browser. Save articles, receipts, and web pages as PDF documents. No signup or account required.',
    seoDescription: 'Free online URL to PDF — Convert any webpage to PDF in your browser. Save articles, receipts, and web pages as PDF documents. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "330",
    name: "Markdown to PDF",
    slug: "markdown-to-pdf",
    category: "PDF",
    description: 'Convert Markdown to beautifully formatted PDF. Supports headings, bold, italic, code blocks, and lists. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Markdown to PDF — Convert Markdown to beautifully formatted PDF. Supports headings, bold, italic, code blocks, and lists. ',
    dependencies: "pdf-lib, marked",
    showInCategory: true,
  },
  {
    id: "331",
    name: "Bookmark PDF",
    slug: "bookmark-pdf",
    category: "PDF",
    description: 'Add a Table of Contents to your PDF documents. Organize pages with titled sections, create nested hierarchies, and navigate large documents with ease. Perfect for reports, ebooks, and manuals.',
    seoDescription: 'Free online Bookmark PDF — Add Table of Contents to your PDF documents. Organize pages with titled sections and nested hierarchies. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "332",
    name: "EML to PDF",
    slug: "eml-to-pdf",
    category: "PDF",
    description: 'Converts EML files to PDF format — email backup, archival, and forensic analysis to document sharing, printing, and archival with consistent formatting. All conversion happens locally in your browser with no file size limits.',
    seoDescription: 'Free online EML to PDF — Convert email files (.eml) to PDF documents. Preserves headers and body content in a clean, printable format. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "333",
    name: "RAW Image Converter",
    slug: "raw-image-converter",
    category: "Image",
    description: 'Convert RAW camera images (CR2, NEF, ARW, DNG) to universal formats. Works with most modern camera RAW formats directly in your browser. Perfect for photographers on the go.',
    seoDescription: 'Free online RAW Image Converter — Convert RAW camera images (CR2, NEF, ARW, DNG) to JPG, PNG, or WebP formats. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "334",
    name: "PSD to JPG/PNG",
    slug: "psd-to-jpg-png",
    category: "Image",
    description: 'Convert PSD images to JPG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PSD to JPG/PNG — Convert Adobe Photoshop PSD files to universal image formats. No uploads, works entirely in your browser.',
    dependencies: "ag-psd",
    showInCategory: true,
  },
  {
    id: "335",
    name: "Collage Maker",
    slug: "collage-maker",
    category: "Image",
    description: 'Combine multiple photos into beautiful collages. Choose from grid, strip, or featured layouts. Perfect for creating photo montages, mood boards, and social media posts.',
    seoDescription: 'Free online Collage Maker — Combine multiple photos into beautiful collages. Grid, strip, and featured layouts. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "336",
    name: "Chart Maker",
    slug: "chart-maker",
    category: "Image",
    description: 'Create stunning charts and graphs online for free. Supports bar, line, pie, doughnut, area charts with custom colors, labels, and titles. Perfect for presentations and reports.',
    seoDescription: 'Free online Chart Maker — Create stunning bar, line, pie, doughnut, and area charts with custom colors and labels. ',
    dependencies: "none",
    showInCategory: false,
  },
  {
    id: "337",
    name: "Background Changer",
    slug: "bg-changer",
    category: "Image",
    description: 'Replace image backgrounds with a solid color, gradient, or another image. Perfect for product photos, portraits, and creative projects. Quick and easy, right in your browser.',
    seoDescription: 'Free online Background Changer — Replace image backgrounds with solid color, gradient, or another image. Coming soon.',
    dependencies: "none",
    showInCategory: false,
  },
  {
    id: "338",
    name: "Unblur / Sharpen",
    slug: "unblur-sharpen",
    category: "Image",
    description: 'Fix blurry photos with smart sharpening or add artistic blur effects. Supports sharpen, Gaussian blur, and motion blur with adjustable intensity. ',
    seoDescription: 'Free online Unblur / Sharpen — Fix blurry photos or add artistic blur effects. Supports sharpen, Gaussian blur, and motion blur. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "339",
    name: "GIF Editor",
    slug: "gif-editor",
    category: "Image",
    description: 'Edit animated GIFs — resize, change speed, reverse, optimize colors, and extract frames. Perfect for social media memes, product demos, and animated banners.',
    seoDescription: 'Free online GIF Editor — Resize, change speed, reverse, optimize colors, and extract frames from animated GIFs. ',
    dependencies: "@ffmpeg/ffmpeg, jszip",
    showInCategory: true,
  },
  {
    id: "340",
    name: "Video Speed Changer",
    slug: "video-speed-changer",
    category: "Video",
    description: 'Speed up or slow down any video. Adjust playback speed from 0.1x to 10x with audio pitch preservation. Perfect for creating time-lapses, slow-motion replays, and quick reviews.',
    seoDescription: 'Free online Video Speed Changer — Speed up or slow down videos from 0.1x to 10x with audio pitch preservation. ',
    dependencies: "@ffmpeg/ffmpeg",

    showInCategory: true,
  },
  {
    id: "341",
    name: "Reverse Video",
    slug: "reverse-video",
    category: "Video",
    description: 'Play any video backwards. Reverse video, audio, or both independently. Create fun effects, hidden messages, and creative video edits with a single click.',
    seoDescription: 'Free online Reverse Video — Play any video backwards. Reverse video, audio, or both. ',
    dependencies: "@ffmpeg/ffmpeg",

    showInCategory: true,
  },
  {
    id: "342",
    name: "Mute Video",
    slug: "mute-video",
    category: "Video",
    description: 'Remove audio from a video completely, replace it with a new audio track, or adjust the volume. Perfect for creating silent videos, adding background music, or fixing audio levels.',
    seoDescription: 'Free online Mute Video — Remove, replace, or adjust audio volume in your videos. ',
    dependencies: "@ffmpeg/ffmpeg",

    showInCategory: true,
  },
  {
    id: "343",
    name: "Vocal Remover",
    slug: "vocal-remover",
    category: "Audio",
    description: 'Remove vocals from any song to create karaoke instrumentals. Extract acapella tracks or get both. Perfect for DJs, content creators, and karaoke enthusiasts.',
    seoDescription: 'Free online Vocal Remover — Remove vocals from songs to create karaoke tracks. Extract instrumentals or acapella. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "344",
    name: "Audio Merger",
    slug: "audio-merger",
    category: "Audio",
    description: 'Combine multiple audio files into one continuous track. Supports crossfade between songs and automatic volume normalization. Perfect for making mixtapes, podcasts, and audiobooks.',
    seoDescription: 'Free online Audio Merger — Combine multiple audio files into one track with crossfade and volume normalization. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "345",
    name: "Voice Recorder",
    slug: "voice-recorder",
    category: "Audio",
    description: 'Record audio directly in your browser using your microphone. Features real-time waveform visualization, pause/resume, and multiple export formats. No software installation needed.',
    seoDescription: 'Free online Voice Recorder — Record audio directly in your browser with waveform visualization. No installation needed. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "346",
    name: "Noise Reducer",
    slug: "noise-reducer",
    category: "Audio",
    description: 'Reduce background noise from audio recordings. Choose from mild to extreme reduction or sample a noise profile for precision cleaning. Perfect for podcasts, calls, and field recordings.',
    seoDescription: 'Free online Audio Noise Reducer — Reduce background noise from recordings. Mild to extreme noise reduction. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "347",
    name: "Audio Equalizer",
    slug: "audio-equalizer",
    category: "Audio",
    description: 'Fine-tune your audio with a 10-band graphic equalizer. Boost bass, enhance vocals, or apply professional presets. Includes real-time frequency response visualization.',
    seoDescription: 'Free online Audio Equalizer — Fine-tune audio with 10-band graphic EQ. Boost bass, enhance vocals, apply presets. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "348",
    name: "Audio Compressor",
    slug: "audio-compressor",
    category: "Audio",
    description: 'Balance audio dynamics with professional compression controls. Perfect for podcasts, voice overs, and music production. Features threshold, ratio, attack, release, and makeup gain.',
    seoDescription: 'Free online Audio Compressor — Balance audio dynamics with threshold, ratio, attack, release, and makeup gain controls. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "349",
    name: "Waveform Generator",
    slug: "waveform-generator",
    category: "Audio",
    description: 'Generate beautiful audio waveform visualizations from any audio file. Choose from bar, line, filled, or circular styles. Perfect for podcast artwork, music videos, and social media.',
    seoDescription: 'Free online Audio Waveform Generator — Create beautiful waveform visualizations from audio. Bar, line, filled, or circular styles. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "350",
    name: "Fade In/Out",
    slug: "fade-in-out",
    category: "Audio",
    description: 'Apply smooth volume fades to your audio tracks. Supports fade in, fade out, or both with linear, logarithmic, exponential, and S-curve transitions. Perfect for podcast intros and outros.',
    seoDescription: 'Free online Audio Fade In/Out — Apply smooth volume fades with linear, log, exp, or S-curve transitions. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "351",
    name: "Video Stabilizer",
    slug: "video-stabilizer",
    category: "Video",
    description: 'Fix shaky handheld footage with advanced video stabilization. Two-pass analysis delivers smooth, professional results. Perfect for vloggers, action cameras, and mobile videos.',
    seoDescription: 'Free online Video Stabilizer — Fix shaky footage with advanced stabilization. Two-pass analysis for smooth results. ',
    dependencies: "@ffmpeg/ffmpeg",

    showInCategory: true,
  },
  {
    id: "352",
    name: "Video Screenshot",
    slug: "video-screenshot",
    category: "Video",
    description: 'Capture still frames from any video at precise timestamps. Extract single screenshots or batch capture at regular intervals. Export as JPG, PNG, or WebP. Perfect for thumbnails and previews.',
    seoDescription: 'Free online Video Screenshot — Capture frames from videos at precise timestamps. Single or batch extraction. ',
    dependencies: "@ffmpeg/ffmpeg",

    showInCategory: true,
  },
  {
    id: "353",
    name: "Video Filters",
    slug: "video-filters",
    category: "Video",
    description: 'Apply stunning visual effects to your videos. Choose from color filters, artistic effects, blurs, and lighting adjustments. Combine multiple filters for unique looks.',
    seoDescription: 'Free online Video Filters — Apply color, artistic, blur, and lighting effects to videos. Combine multiple filters. ',
    dependencies: "@ffmpeg/ffmpeg",

    showInCategory: true,
  },
  {
    id: "354",
    name: "Screen Recorder",
    slug: "screen-recorder",
    category: "Video",
    description: 'Record your screen, application window, or browser tab with optional microphone audio. Choose HD, Full HD, or 2K quality. Download as WebM or MP4. No software installation needed.',
    seoDescription: 'Free online Screen Recorder — Record screen, window, or tab with mic audio. HD to 2K quality. Download as WebM or MP4. ',
    dependencies: "@ffmpeg/ffmpeg",

    showInCategory: true,
  },
  {
    id: "355",
    name: "AI Chat PDF",
    slug: "ai-chat-pdf",
    category: "AI",
    description: 'Chat with your PDF documents. Ask questions, get answers, and extract insights from any document. Extract text and use intelligent search to find relevant information instantly.',
    seoDescription: 'Free online AI Chat with PDF — Ask questions and get answers from your PDF documents. Intelligent document search. ',
    dependencies: "pdfjs-dist",
    showInCategory: true,
  },
  {
    id: "356",
    name: "Grammar Checker",
    slug: "grammar-checker",
    category: "AI",
    description: 'Check and correct grammar, spelling, and punctuation in your text. Detects common errors including homophones, misspellings, punctuation issues, and run-on sentences.',
    seoDescription: 'Free online Grammar Checker — Check and correct grammar, spelling, and punctuation. Detects homophones, misspellings, and more. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "357",
    name: "AI Humanizer",
    slug: "ai-humanizer",
    category: "AI",
    description: 'Make AI-generated text sound more natural and human-like. Choose from casual, professional, friendly, natural, or storytelling tones. Reduces robotic patterns and improves readability.',
    seoDescription: 'Free online AI Humanizer — Make AI text sound natural. Casual, professional, friendly, or storytelling tones. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "358",
    name: "AI Detector",
    slug: "ai-detector",
    category: "AI",
    description: 'Detect if text was written by AI. Analyzes burstiness, repetition patterns, sentence variance, and AI trigger phrases. Get a percentage score with detailed breakdown per section.',
    seoDescription: 'Free online AI Detector — Analyze text to detect AI-written content. Burstiness, repetition, and trigger phrase analysis. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "359",
    name: "Article Writer",
    slug: "article-writer",
    category: "AI",
    description: 'Generate well-structured articles on any topic. Choose tone, audience, and length. Includes introduction, body, conclusion, FAQ, and key takeaways sections. Export as text, markdown, or HTML.',
    seoDescription: 'Free online AI Article Writer — Generate structured articles on any topic. Multiple tones, audience types, and export formats. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "360",
    name: "Social Caption Generator",
    slug: "social-caption-generator",
    category: "AI",
    description: 'Generate engaging social media captions for Instagram, Twitter, LinkedIn, Facebook, TikTok, and Pinterest. Multiple moods, hashtag suggestions, and emoji support.',
    seoDescription: 'Free online Social Media Caption Generator — Create engaging captions for Instagram, Twitter, LinkedIn, Facebook, TikTok, Pinterest. ',
    dependencies: "none",
    showInCategory: true,
  },
  {
    id: "361",
    name: "MOBI Converter",
    slug: "mobi-converter",
    category: "Converter",
    description: 'Convert MOBI (Kindle) e-book files to PDF or EPUB, and create MOBI files from PDF. Perfect for Kindle users who need to read books on other devices or share with non-Kindle readers.',
    seoDescription: 'Free online MOBI Converter — Convert MOBI Kindle e-books to PDF or EPUB. Create MOBI files from PDF. ',
    dependencies: "pdf-lib, jszip, pdfjs-dist",
    showInCategory: true,
  },
  {
    id: "362",
    name: "ODT/RTF to PDF",
    slug: "odt-rtf-to-pdf",
    category: "Converter",
    description: 'Convert OpenDocument (ODT) and Rich Text Format (RTF) files to PDF. Preserves basic formatting like bold, italic, headers, and paragraphs. Perfect for LibreOffice and WordPad users.',
    seoDescription: 'Free online ODT/RTF to PDF — Convert OpenDocument and Rich Text Format files to PDF. Preserves formatting. ',
    dependencies: "pdf-lib, jszip",
    showInCategory: true,
  },
  {
    id: "363",
    name: "SVG to PNG",
    slug: "svg-to-png",
    category: "Image",
    description: 'Convert SVG images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to PNG — Convert scalable vector graphics (SVG) into raster PNG images. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "364",
    name: "SVG to JPG",
    slug: "svg-to-jpg",
    category: "Image",
    description: 'Convert SVG images to JPG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to JPG — Convert SVG vector graphics into JPEG images for sharing on platforms that require raster formats. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "365",
    name: "PNG to GIF",
    slug: "png-to-gif",
    category: "Image",
    description: 'Convert PNG images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PNG to GIF — Convert PNG images into GIF format for compatibility with older platforms and software. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "366",
    name: "JPG to GIF",
    slug: "jpg-to-gif",
    category: "Image",
    description: 'Convert JPG images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to GIF — Convert JPEG photos into GIF format for legacy applications and platforms with limited format support. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "367",
    name: "WebP to GIF",
    slug: "webp-to-gif",
    category: "Image",
    description: 'Convert WEBP images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online WebP to GIF — Convert modern WebP images into the widely compatible GIF format. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "368",
    name: "BMP to JPG",
    slug: "bmp-to-jpg",
    category: "Image",
    description: 'Convert BMP images to JPG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to JPG — Convert uncompressed BMP bitmap images into space-efficient JPEG files. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "369",
    name: "BMP to PNG",
    slug: "bmp-to-png",
    category: "Image",
    description: 'Convert BMP images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to PNG — Convert BMP bitmap images into compressed PNG format with optional transparency. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "370",
    name: "TIFF to JPG",
    slug: "tiff-to-jpg",
    category: "Image",
    description: 'Convert TIFF images to JPG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to JPG — Convert TIFF images into universally compatible JPEG format for sharing on the web or via email. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "371",
    name: "TIFF to PNG",
    slug: "tiff-to-png",
    category: "Image",
    description: 'Convert TIFF images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to PNG — Convert TIFF images into lossless PNG format for graphic design workflows. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "372",
    name: "GIF to JPG",
    slug: "gif-to-jpg",
    category: "Image",
    description: 'Convert GIF images to JPG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to JPG — Convert GIF images into JPEG format with millions of colors. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "373",
    name: "GIF to PNG",
    slug: "gif-to-png",
    category: "Image",
    description: 'Convert GIF images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to PNG — Convert GIF images into lossless PNG format with superior color depth and compression. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "374",
    name: "ICO to PNG",
    slug: "ico-to-png",
    category: "Image",
    description: 'Convert ICO images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to PNG — Extract Windows icon (.ico) files and convert them into universal PNG images. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "375",
    name: "JXL to PNG",
    slug: "jxl-to-png",
    category: "Image",
    description: 'Convert JXL images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to PNG — Convert JPEG XL images into universally compatible PNG format. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "376",
    name: "JXL to JPG",
    slug: "jxl-to-jpg",
    category: "Image",
    description: 'Convert JXL images to JPG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to JPEG — Convert JPEG XL images into standard JPEG format for maximum compatibility. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "377",
    name: "WMA to MP3",
    slug: "wma-to-mp3",
    category: "Audio",
    description: 'Convert WMA audio files to MP3 format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WMA to MP3 — Convert Windows Media Audio (WMA) files into universally compatible MP3 format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "378",
    name: "Opus to MP3",
    slug: "opus-to-mp3",
    category: "Audio",
    description: 'Convert OPUS audio files to MP3 format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online Opus to MP3 — Convert Opus audio files into the more widely supported MP3 format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "379",
    name: "AIFF to MP3",
    slug: "aiff-to-mp3",
    category: "Audio",
    description: 'Convert AIFF audio files to MP3 format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AIFF to MP3 — Convert Apple\'s AIFF audio files into space-saving MP3 format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {

    id: "380",
    name: "Website Screenshot",
    slug: "website-screenshot",
    category: "Developer",
    description: 'Capture screenshots of any website directly in your browser. Choose output format, viewport size, and capture delay. No server-side processing.',
    seoDescription: 'Free online Website Screenshot — Capture screenshots of any website in your browser. Multiple formats, viewport sizes, and delay options. ',
    dependencies: "html2canvas",
    showInCategory: true,
},
  {
    id: "381",
    name: "GIF to WebP/WebM",
    slug: "gif-to-webp-webm",
    category: "Converter",
    description: 'Convert animated GIFs to modern WebP or WebM formats with transparency support — ~10x smaller files.',
    seoDescription: 'Free online GIF to WebP/WebM Converter — Convert animated GIFs to modern WebP or WebM formats. ~10x smaller files with transparency support. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "382",
    name: "AVIF to JPG",
    slug: "avif-to-jpg",
    category: "Image",
    description: 'Convert AVIF images to JPG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to JPG — Convert AVIF images back to universally compatible JPEG format. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "383",
    name: "AVIF to PNG",
    slug: "avif-to-png",
    category: "Image",
    description: 'Convert AVIF images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to PNG — Convert AVIF images to lossless PNG format for maximum compatibility. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "384",
    name: "BMP to AVIF",
    slug: "bmp-to-avif",
    category: "Image",
    description: 'Convert BMP images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to AVIF — Convert BMP bitmap images into next-gen AVIF format with superior compression. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "385",
    name: "BMP to GIF",
    slug: "bmp-to-gif",
    category: "Image",
    description: 'Convert BMP images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to GIF — Convert BMP bitmap images into GIF format for compatibility with legacy platforms. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "386",
    name: "BMP to WebP",
    slug: "bmp-to-webp",
    category: "Image",
    description: 'Convert BMP images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to WebP — Convert BMP bitmap images into modern WebP format with dramatically smaller sizes. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "387",
    name: "GIF to AVIF",
    slug: "gif-to-avif",
    category: "Image",
    description: 'Convert GIF images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to AVIF — Convert GIF images into modern AVIF format with better compression and color depth. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "388",
    name: "GIF to WebP",
    slug: "gif-to-webp",
    category: "Image",
    description: 'Converts GIF files to WebP format — simple animations, memes, and images on platforms that support animated GIFs natively to modern websites. All conversion happens locally in your browser with no file size limits.',
    seoDescription: 'Free online GIF to WebP — Convert GIF images into modern WebP format for smaller file sizes with optional animation support. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "389",
    name: "HEIC to AVIF",
    slug: "heic-to-avif",
    category: "Image",
    description: 'Convert HEIC images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online HEIC to AVIF — Convert Apple HEIC/HEIF photos into next-gen AVIF format with superior compression. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "390",
    name: "HEIC to GIF",
    slug: "heic-to-gif",
    category: "Image",
    description: 'Convert HEIC images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online HEIC to GIF — Convert Apple HEIC/HEIF photos into GIF format for compatibility with older platforms. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "391",
    name: "HEIC to WebP",
    slug: "heic-to-webp",
    category: "Image",
    description: 'Convert HEIC images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online HEIC to WebP — Convert Apple HEIC/HEIF photos into modern WebP format for efficient web delivery. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "392",
    name: "ICO to JPG",
    slug: "ico-to-jpg",
    category: "Image",
    description: 'Convert ICO images to JPG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to JPG — Convert Windows icon files into universally compatible JPEG format. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "393",
    name: "ICO to WebP",
    slug: "ico-to-webp",
    category: "Image",
    description: 'Convert ICO images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to WebP — Convert Windows icon files into modern WebP format for web use. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "394",
    name: "JPG to JXL",
    slug: "jpg-to-jxl",
    category: "Image",
    description: 'Convert JPG images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to JXL — Convert JPEG photos into cutting-edge JPEG XL format with superior compression. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "395",
    name: "JXL to GIF",
    slug: "jxl-to-gif",
    category: "Image",
    description: 'Convert JXL images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to GIF — Convert JPEG XL images into GIF format for use on legacy platforms. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "396",
    name: "JXL to WebP",
    slug: "jxl-to-webp",
    category: "Image",
    description: 'Convert JXL images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to WebP — Convert JPEG XL images into modern WebP format for broader compatibility. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "397",
    name: "PNG to JXL",
    slug: "png-to-jxl",
    category: "Image",
    description: 'Convert PNG images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PNG to JXL — Convert PNG images into JPEG XL format for better compression while preserving quality. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "398",
    name: "SVG to AVIF",
    slug: "svg-to-avif",
    category: "Image",
    description: 'Convert SVG images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to AVIF — Convert SVG vector graphics into AVIF format for next-gen web delivery. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "399",
    name: "SVG to GIF",
    slug: "svg-to-gif",
    category: "Image",
    description: 'Convert SVG images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to GIF — Convert SVG vector graphics into GIF format for use in legacy applications. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "400",
    name: "SVG to WebP",
    slug: "svg-to-webp",
    category: "Image",
    description: 'Convert SVG images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to WebP — Convert SVG vector graphics into modern WebP format for efficient web delivery. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "401",
    name: "TIFF to AVIF",
    slug: "tiff-to-avif",
    category: "Image",
    description: 'Convert TIFF images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to AVIF — Convert TIFF images into next-gen AVIF format for best-in-class compression. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "402",
    name: "TIFF to GIF",
    slug: "tiff-to-gif",
    category: "Image",
    description: 'Convert TIFF images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to GIF — Convert TIFF images into GIF format for use in applications with limited format support. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "403",
    name: "TIFF to WebP",
    slug: "tiff-to-webp",
    category: "Image",
    description: 'Convert TIFF images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to WebP — Convert TIFF images into modern WebP format for smaller file sizes and web use. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "404",
    name: "UPI ID Validator & QR Generator",
    slug: "upi-id-validator",
    category: "indian-utilities",
    description: 'Validates UPI ID format rules for all popular handles (@paytm, @okhdfcbank, @ybl, @sbi, @upi, @axl, @icici) and generates UPI payment QR codes with merchant name and amount. All local processing.',
    seoDescription: 'Free online UPI ID Validator and QR Generator — Validate UPI IDs for @paytm, @okhdfcbank, @ybl, @sbi handles. Generate UPI payment QR codes with merchant name, amount, and transaction note. Local processing, no uploads.',
    dependencies: "QRCode.js",
  },
  {
    id: "405",
    name: "Indian Address Parser",
    slug: "indian-address-parser",
    category: "indian-utilities",
    description: 'Parses free-text Indian addresses into structured fields — line 1, line 2, city, district, state, and pincode. Handles multiple Indian address formats with state and city recognition. Local processing only.',
    seoDescription: 'Free online Indian Address Parser — Parse unstructured Indian addresses into fields: line 1, line 2, city, district, state, pincode. Recognizes Indian states, cities, and address patterns. 100 percent local parsing.',
    dependencies: "None",
  },
  {
    id: "406",
    name: "Vehicle Registration Checker",
    slug: "vehicle-registration-checker",
    category: "indian-utilities",
    description: 'Parses Indian vehicle registration numbers to identify state/UT codes, RTO codes, and series. Decodes the format of license plates from all Indian states and union territories.',
    seoDescription: 'Free online Vehicle Registration Number Checker — Parse Indian vehicle registration numbers. Identify state/UT codes, RTO codes, and series for all Indian states and union territories. Instant local parsing.',
    dependencies: "None",
  },
  {
    id: "407",
    name: "Aadhaar Number Validator",
    slug: "aadhaar-number-validator",
    category: "indian-utilities",
    description: 'Validates Aadhaar numbers using Verhoeff checksum verification. Checks format rules, detects fake UIDs, and explains Aadhaar number structure. Fully local validation with no data upload.',
    seoDescription: 'Free online Aadhaar Number Validator — Validate 12-digit Aadhaar numbers with Verhoeff checksum. Check format, detect fake UIDs, and understand Aadhaar structure. 100 percent local validation, no data upload.',
    dependencies: "None",
  },
  {
    id: "408",
    name: "SIP / PPF / EPF Calculator",
    slug: "indian-investment-calculator",
    category: "indian-utilities",
    description: 'Calculate Indian investment returns — SIP with lumpsum and monthly options, PPF with 15-year maturity, and EPF employee provident fund projections. All calculations are local with no data uploads.',
    seoDescription: 'Free online Indian Investment Calculator — SIP, PPF, and EPF return calculator for Indian investors. SIP lumpsum plus monthly, PPF 15-year maturity, EPF projections with current interest rates. 100 percent local.',
    dependencies: "None",
  },
  {
    id: "409",
    name: "Bulk PDF Suite",
    slug: "bulk-pdf-suite",
    category: "PDF",
    description: 'Rotate, protect, unlock, split, watermark, crop, resize, or flatten multiple PDF files in one batch. All processing happens locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Bulk PDF Suite — Rotate, protect, unlock, split, watermark, crop, resize, or flatten multiple PDF files in one batch. ',
    dependencies: "pdf-lib",
  },
];
