import type { ToolMetadata } from './tools-types';

export const entries_chunk_2: ToolMetadata[] = [
  {
    id: "404",
    name: "WebP to AVIF",
    slug: "webp-to-avif",
    category: "Image",
    description: 'Convert WEBP images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online WebP to AVIF — Convert WebP images into AVIF format for even better compression ratios. ',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "405",
    name: "AAC to FLAC",
    slug: "aac-to-flac",
    category: "Audio",
    description: 'Convert AAC audio files to FLAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AAC to FLAC — Convert AAC audio files into lossless FLAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "406",
    name: "AAC to M4A",
    slug: "aac-to-m4a",
    category: "Audio",
    description: 'Convert AAC audio files to M4A format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AAC to M4A — Convert AAC audio files into M4A container format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "407",
    name: "AAC to OGG",
    slug: "aac-to-ogg",
    category: "Audio",
    description: 'Convert AAC audio files to OGG format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AAC to OGG — Convert AAC audio files into OGG Vorbis format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "408",
    name: "AAC to WAV",
    slug: "aac-to-wav",
    category: "Audio",
    description: 'Convert AAC audio files to WAV format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AAC to WAV — Convert AAC audio files into uncompressed WAV format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "409",
    name: "FLAC to AAC",
    slug: "flac-to-aac",
    category: "Audio",
    description: 'Convert FLAC audio files to AAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online FLAC to AAC — Convert lossless FLAC audio into space-efficient AAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "410",
    name: "FLAC to M4A",
    slug: "flac-to-m4a",
    category: "Audio",
    description: 'Convert FLAC audio files to M4A format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online FLAC to M4A — Convert lossless FLAC audio into M4A format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "411",
    name: "FLAC to OGG",
    slug: "flac-to-ogg",
    category: "Audio",
    description: 'Convert FLAC audio files to OGG format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online FLAC to OGG — Convert lossless FLAC audio into OGG Vorbis format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "412",
    name: "FLAC to WAV",
    slug: "flac-to-wav",
    category: "Audio",
    description: 'Convert FLAC audio files to WAV format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online FLAC to WAV — Convert lossless FLAC audio into uncompressed WAV format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "413",
    name: "M4A to AAC",
    slug: "m4a-to-aac",
    category: "Audio",
    description: 'Convert M4A audio files to AAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online M4A to AAC — Convert M4A audio files into raw AAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "414",
    name: "M4A to FLAC",
    slug: "m4a-to-flac",
    category: "Audio",
    description: 'Convert M4A audio files to FLAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online M4A to FLAC — Convert M4A audio files into lossless FLAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "415",
    name: "M4A to OGG",
    slug: "m4a-to-ogg",
    category: "Audio",
    description: 'Convert M4A audio files to OGG format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online M4A to OGG — Convert M4A audio files into OGG Vorbis format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "416",
    name: "M4A to WAV",
    slug: "m4a-to-wav",
    category: "Audio",
    description: 'Convert M4A audio files to WAV format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online M4A to WAV — Convert M4A audio files into uncompressed WAV format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "417",
    name: "MP3 to AAC",
    slug: "mp3-to-aac",
    category: "Audio",
    description: 'Convert MP3 audio files to AAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online MP3 to AAC — Convert MP3 audio files into AAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "418",
    name: "MP3 to AIFF",
    slug: "mp3-to-aiff",
    category: "Audio",
    description: 'Convert MP3 audio files to AIFF format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online MP3 to AIFF — Convert MP3 audio files into uncompressed AIFF format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "419",
    name: "MP3 to FLAC",
    slug: "mp3-to-flac",
    category: "Audio",
    description: 'Convert MP3 audio files to FLAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online MP3 to FLAC — Convert MP3 audio files into lossless FLAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "420",
    name: "MP3 to M4A",
    slug: "mp3-to-m4a",
    category: "Audio",
    description: 'Convert MP3 audio files to M4A format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online MP3 to M4A — Convert MP3 audio files into M4A format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "421",
    name: "MP3 to OGG",
    slug: "mp3-to-ogg",
    category: "Audio",
    description: 'Convert MP3 audio files to OGG format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online MP3 to OGG — Convert MP3 audio files into OGG Vorbis format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "422",
    name: "MP3 to Opus",
    slug: "mp3-to-opus",
    category: "Audio",
    description: 'Convert MP3 audio files to OPUS format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online MP3 to Opus — Convert MP3 audio files into Opus format for superior compression. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "423",
    name: "MP3 to WMA",
    slug: "mp3-to-wma",
    category: "Audio",
    description: 'Convert MP3 audio files to WMA format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online MP3 to WMA — Convert MP3 audio files into Windows Media Audio format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "424",
    name: "OGG to AAC",
    slug: "ogg-to-aac",
    category: "Audio",
    description: 'Convert OGG audio files to AAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online OGG to AAC — Convert OGG Vorbis audio files into AAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "425",
    name: "OGG to FLAC",
    slug: "ogg-to-flac",
    category: "Audio",
    description: 'Convert OGG audio files to FLAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online OGG to FLAC — Convert OGG Vorbis audio files into lossless FLAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "426",
    name: "OGG to M4A",
    slug: "ogg-to-m4a",
    category: "Audio",
    description: 'Convert OGG audio files to M4A format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online OGG to M4A — Convert OGG Vorbis audio files into M4A format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "427",
    name: "OGG to WAV",
    slug: "ogg-to-wav",
    category: "Audio",
    description: 'Convert OGG audio files to WAV format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online OGG to WAV — Convert OGG Vorbis audio files into uncompressed WAV format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "428",
    name: "WAV to AAC",
    slug: "wav-to-aac",
    category: "Audio",
    description: 'Convert WAV audio files to AAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WAV to AAC — Convert WAV audio files into space-efficient AAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "429",
    name: "WAV to AIFF",
    slug: "wav-to-aiff",
    category: "Audio",
    description: 'Convert WAV audio files to AIFF format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WAV to AIFF — Convert WAV audio files into AIFF format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "430",
    name: "WAV to FLAC",
    slug: "wav-to-flac",
    category: "Audio",
    description: 'Convert WAV audio files to FLAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WAV to FLAC — Convert uncompressed WAV files into lossless FLAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "431",
    name: "WAV to M4A",
    slug: "wav-to-m4a",
    category: "Audio",
    description: 'Convert WAV audio files to M4A format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WAV to M4A — Convert WAV audio files into M4A format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "432",
    name: "WAV to OGG",
    slug: "wav-to-ogg",
    category: "Audio",
    description: 'Convert WAV audio files to OGG format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WAV to OGG — Convert WAV audio files into OGG Vorbis format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "433",
    name: "WAV to Opus",
    slug: "wav-to-opus",
    category: "Audio",
    description: 'Convert WAV audio files to OPUS format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WAV to Opus — Convert WAV audio files into Opus format for best compression. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "434",
    name: "WAV to WMA",
    slug: "wav-to-wma",
    category: "Audio",
    description: 'Convert WAV audio files to WMA format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WAV to WMA — Convert WAV audio files into Windows Media Audio format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "435",
    name: "GIF Compressor",
    slug: "gif-compressor",
    category: "Image",
    description: 'Compress animated GIFs by reducing colors from 256 to as few as 16, removing duplicate frames, and applying lossy optimization. Reduce file size by up to 80% while keeping animation intact. Essential for web performance, email signatures, and social media where large GIFs cause slow loading.',
    seoDescription: 'Free online GIF Compressor — reduce animated GIF file size by up to 80% with color reduction, frame dedup, and lossy optimization. Essential for faster website loading and email attachments. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "436",
    name: "GIF Resizer",
    slug: "gif-resizer",
    category: "Image",
    description: 'Resize animated GIFs to exact dimensions while preserving animation. Choose from presets or custom width with aspect ratio lock.',
    seoDescription: 'Free online GIF Resizer — Resize animated GIFs to exact dimensions while preserving animation. Presets or custom size. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "437",
    name: "GIF to APNG",
    slug: "gif-to-apng",
    category: "Image",
    description: 'Convert GIF images to APNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to APNG Converter — Convert animated GIFs to APNG format with 24-bit color and alpha transparency. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "440",
    name: "APNG to GIF",
    slug: "apng-to-gif",
    category: "Image",
    description: 'Convert APNG images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online APNG to GIF — Convert animated PNG files into universally compatible GIF format. ',
    dependencies: "@ffmpeg/ffmpeg",
    showInCategory: true,
  },
  {
    id: "441",
    name: "Image to ICO",
    slug: "image-to-ico",
    category: "Image",
    description: 'Convert IMAGE images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online Image to ICO — Convert any image to Windows ICO format for favicons and app icons. Multi-size support. ',
    dependencies: "Canvas API",
    showInCategory: true,
  },
  {
    id: "442",
    name: "Color Converter",
    slug: "color-converter",
    category: "Design",
    description: 'Convert colors between Hex, RGB, HSL, HSV, and CMYK formats. Real-time preview, color picker, and copy-to-clipboard.',
    seoDescription: 'Free online Color Converter — Convert colors between Hex, RGB, HSL, HSV, and CMYK. Real-time preview with color picker. ',
    dependencies: "none",
      },
  {

    id: "443",
    name: "QR Code Reader",
    slug: "qr-code-reader",
    category: "Developer",
    description: 'Decode QR codes from uploaded images. Scan any QR code image and extract the embedded text or URL.',
    seoDescription: 'Free online QR Code Reader — Decode QR codes from images. Scan and extract text/URL from any QR code. ',
    dependencies: "jsQR",
    showInCategory: true,
},
  {
    id: "444",
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum-generator",
    category: "Text",
    description: 'Generate placeholder text in multiple styles — Standard Lorem Ipsum, Cicero (original Latin), Legal, Startup, Coffee, and Pirate themes. Customizable paragraph and word counts for design mockups.',
    seoDescription: 'Free online Lorem Ipsum Generator — Generate placeholder text in Standard, Cicero, Legal, Startup, Coffee, and Pirate themes. Customizable paragraphs and word count for design mockups and layouts.',
    dependencies: "none",
    showInCategory: true,
  },
  {

    id: "445",
    name: "WHOIS Lookup",
    slug: "whois-lookup",
    category: "Developer",
    description: 'Look up domain registration information using public RDAP APIs. Check registrar, expiration date, name servers, and more.',
    seoDescription: 'Free online WHOIS Lookup — Check domain registration info: registrar, expiration, name servers. Uses public RDAP APIs. ',
    dependencies: "none",
    showInCategory: true,
},
  {

    id: "446",
    name: "SSL Checker",
    slug: "ssl-checker",
    category: "Developer",
    description: 'Check SSL/TLS certificate details for any domain. View issuer, validity period, days remaining, and SANs.',
    seoDescription: 'Free online SSL Checker — Check SSL certificate details for any domain. Issuer, validity, days remaining, SANs. ',
    dependencies: "none",
    showInCategory: true,
},
  {
    id: "447",
    name: "PDF to TIFF",
    slug: "pdf-to-tiff",
    category: "PDF",
    description: 'Convert PDF images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PDF to TIFF — Convert PDF pages to high-quality TIFF images. Multi-page output, DPI control, LZW compression. ',
    dependencies: "pdfjs-dist",
    showInCategory: true,
  },
  {
    id: "448",
    name: "TIFF to PDF",
    slug: "tiff-to-pdf",
    category: "PDF",
    description: 'Convert TIFF images to PDF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to PDF — Convert TIFF images to PDF documents. Multi-page support, page size options, margins. ',
    dependencies: "pdf-lib, utif",
    showInCategory: true,
  },
  {
    id: "449",
    name: "Font Converter",
    slug: "font-converter",
    category: "Design",
    description: 'Convert fonts between TTF, OTF, WOFF, and WOFF2 formats. Preview fonts with custom text before downloading. Perfect for web developers and designers.',
    seoDescription: 'Free online Font Converter — Convert between TTF, OTF, WOFF, and WOFF2 formats. Preview with custom text. ',
    dependencies: "opentype.js",
    showInCategory: true,
  },
  {
    id: "450",
    name: "Font Subsetter",
    slug: "font-subsetter",
    category: "Design",
    description: 'Reduce font file size by removing unused glyphs. Keep only the characters you need. Perfect for web fonts and performance optimization.',
    seoDescription: 'Free online Font Subsetter — Reduce font file size by removing unused glyphs. Keep only needed characters. ',
    dependencies: "opentype.js",
    showInCategory: true,
  },
  {
    id: "451",
    name: "CBZ to PDF",
    slug: "cbz-to-pdf",
    category: "Converter",
    description: 'Convert comic book archives to PDF. Page ranges, double-page spreads, multiple sizes. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CBZ to PDF — Convert comic book archives to PDF. Page ranges, double-page spreads, multiple sizes. ',
    dependencies: "jszip, pdf-lib",
    showInCategory: true,
  },
  {
    id: "453",
    name: "YAML ↔ JSON Converter",
    slug: "yaml-json-converter",
    category: "Converter",
    description: 'Bidirectional YAML to JSON and JSON to YAML conversion with auto-format detection and real-time preview. Perfect for configuration files, API payloads, and data migration.',
    seoDescription: 'Free online YAML ↔ JSON Converter — Bidirectional YAML to JSON and JSON to YAML conversion with auto-format detection and real-time preview. ',
    dependencies: "js-yaml",
  },
  {
    id: "454",
    name: "XLSX ↔ CSV Converter",
    slug: "xlsx-csv-converter",
    category: "Converter",
    description: 'Bidirectional converter between Excel spreadsheets (XLSX) and CSV files. Select sheets, choose delimiters, and preview data before converting.',
    seoDescription: 'Free online XLSX ↔ CSV Converter — Bidirectional conversion between Excel and CSV. Sheet selector, delimiter options, data preview. ',
    dependencies: "xlsx",
  },
  {

    id: "455",
    name: "VCF ↔ CSV Converter",
    slug: "vcf-csv-converter",
    category: "Converter",
    description: 'Bidirectional converter between vCard (VCF) and CSV formats. Perfect for importing/exporting address books between any platform or service.',
    seoDescription: 'Free online VCF ↔ CSV Converter — Bidirectional conversion between vCard and CSV. Field mapping, multi-value support. ',
    dependencies: "vcard-parser",
    showInCategory: false,
},
  {

    id: "456",
    name: "ICS ↔ CSV Converter",
    slug: "ics-csv-converter",
    category: "Converter",
    description: 'Bidirectional converter between iCalendar (ICS) and CSV formats. Migrate events between Google Calendar, Outlook, Apple Calendar, and spreadsheets.',
    seoDescription: 'Free online ICS ↔ CSV Converter — Bidirectional conversion between iCalendar and CSV. Multiple date formats, field mapping. ',
    dependencies: "ical",
    showInCategory: false,
},
  {
    id: "457",
    name: "WAV to MP3",
    slug: "wav-to-mp3",
    category: "Audio",
    description: 'Convert WAV audio files to MP3 format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WAV to MP3 — Convert uncompressed WAV audio files into widely compatible MP3 format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "458",
    name: "FLAC to MP3",
    slug: "flac-to-mp3",
    category: "Audio",
    description: 'Convert FLAC audio files to MP3 format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online FLAC to MP3 — Convert lossless FLAC audio files into widely compatible MP3 format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "459",
    name: "FLAC to WMA",
    slug: "flac-to-wma",
    category: "Audio",
    description: 'Convert FLAC audio files to WMA format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online FLAC to WMA — Convert lossless FLAC audio files into Windows Media Audio format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "460",
    name: "FLAC to Opus",
    slug: "flac-to-opus",
    category: "Audio",
    description: 'Convert FLAC audio files to OPUS format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online FLAC to Opus — Convert lossless FLAC audio files into Opus format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "461",
    name: "FLAC to AIFF",
    slug: "flac-to-aiff",
    category: "Audio",
    description: 'Convert FLAC audio files to AIFF format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online FLAC to AIFF — Convert lossless FLAC audio files into AIFF format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "462",
    name: "OGG to MP3",
    slug: "ogg-to-mp3",
    category: "Audio",
    description: 'Convert OGG audio files to MP3 format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online OGG to MP3 — Convert OGG Vorbis audio files into widely compatible MP3 format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "463",
    name: "OGG to WMA",
    slug: "ogg-to-wma",
    category: "Audio",
    description: 'Convert OGG audio files to WMA format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online OGG to WMA — Convert OGG Vorbis audio files into Windows Media Audio format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "464",
    name: "OGG to Opus",
    slug: "ogg-to-opus",
    category: "Audio",
    description: 'Convert OGG audio files to OPUS format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online OGG to Opus — Convert OGG Vorbis audio files into Opus format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "465",
    name: "OGG to AIFF",
    slug: "ogg-to-aiff",
    category: "Audio",
    description: 'Convert OGG audio files to AIFF format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online OGG to AIFF — Convert OGG Vorbis audio files into AIFF format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "466",
    name: "M4A to MP3",
    slug: "m4a-to-mp3",
    category: "Audio",
    description: 'Convert M4A audio files to MP3 format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online M4A to MP3 — Convert M4A audio files into widely compatible MP3 format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "467",
    name: "M4A to WMA",
    slug: "m4a-to-wma",
    category: "Audio",
    description: 'Convert M4A audio files to WMA format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online M4A to WMA — Convert M4A audio files into Windows Media Audio format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "468",
    name: "M4A to Opus",
    slug: "m4a-to-opus",
    category: "Audio",
    description: 'Convert M4A audio files to OPUS format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online M4A to Opus — Convert M4A audio files into Opus format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "469",
    name: "M4A to AIFF",
    slug: "m4a-to-aiff",
    category: "Audio",
    description: 'Convert M4A audio files to AIFF format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online M4A to AIFF — Convert M4A audio files into AIFF format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "470",
    name: "AAC to MP3",
    slug: "aac-to-mp3",
    category: "Audio",
    description: 'Convert AAC audio files to MP3 format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AAC to MP3 — Convert AAC audio files into widely compatible MP3 format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "471",
    name: "AAC to WMA",
    slug: "aac-to-wma",
    category: "Audio",
    description: 'Convert AAC audio files to WMA format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AAC to WMA — Convert AAC audio files into Windows Media Audio format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "472",
    name: "AAC to Opus",
    slug: "aac-to-opus",
    category: "Audio",
    description: 'Convert AAC audio files to OPUS format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AAC to Opus — Convert AAC audio files into Opus format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "473",
    name: "AAC to AIFF",
    slug: "aac-to-aiff",
    category: "Audio",
    description: 'Convert AAC audio files to AIFF format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AAC to AIFF — Convert AAC audio files into AIFF format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "474",
    name: "WMA to WAV",
    slug: "wma-to-wav",
    category: "Audio",
    description: 'Convert WMA audio files to WAV format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WMA to WAV — Convert Windows Media Audio (WMA) audio files into uncompressed WAV format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "475",
    name: "WMA to FLAC",
    slug: "wma-to-flac",
    category: "Audio",
    description: 'Convert WMA audio files to FLAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WMA to FLAC — Convert Windows Media Audio (WMA) audio files into lossless FLAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "476",
    name: "WMA to OGG",
    slug: "wma-to-ogg",
    category: "Audio",
    description: 'Convert WMA audio files to OGG format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WMA to OGG — Convert Windows Media Audio (WMA) audio files into OGG Vorbis format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "477",
    name: "WMA to M4A",
    slug: "wma-to-m4a",
    category: "Audio",
    description: 'Convert WMA audio files to M4A format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WMA to M4A — Convert Windows Media Audio (WMA) audio files into M4A format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "478",
    name: "WMA to AAC",
    slug: "wma-to-aac",
    category: "Audio",
    description: 'Convert WMA audio files to AAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WMA to AAC — Convert Windows Media Audio (WMA) audio files into AAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "479",
    name: "WMA to Opus",
    slug: "wma-to-opus",
    category: "Audio",
    description: 'Convert WMA audio files to OPUS format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WMA to Opus — Convert Windows Media Audio (WMA) audio files into Opus format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "480",
    name: "WMA to AIFF",
    slug: "wma-to-aiff",
    category: "Audio",
    description: 'Convert WMA audio files to AIFF format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online WMA to AIFF — Convert Windows Media Audio (WMA) audio files into AIFF format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "481",
    name: "Opus to WAV",
    slug: "opus-to-wav",
    category: "Audio",
    description: 'Convert OPUS audio files to WAV format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online Opus to WAV — Convert Opus audio files into uncompressed WAV format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "482",
    name: "Opus to FLAC",
    slug: "opus-to-flac",
    category: "Audio",
    description: 'Convert OPUS audio files to FLAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online Opus to FLAC — Convert Opus audio files into lossless FLAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "483",
    name: "Opus to OGG",
    slug: "opus-to-ogg",
    category: "Audio",
    description: 'Convert OPUS audio files to OGG format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online Opus to OGG — Convert Opus audio files into OGG Vorbis format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "484",
    name: "Opus to M4A",
    slug: "opus-to-m4a",
    category: "Audio",
    description: 'Convert OPUS audio files to M4A format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online Opus to M4A — Convert Opus audio files into M4A format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "485",
    name: "Opus to AAC",
    slug: "opus-to-aac",
    category: "Audio",
    description: 'Convert OPUS audio files to AAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online Opus to AAC — Convert Opus audio files into AAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "486",
    name: "Opus to WMA",
    slug: "opus-to-wma",
    category: "Audio",
    description: 'Convert OPUS audio files to WMA format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online Opus to WMA — Convert Opus audio files into Windows Media Audio format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "487",
    name: "Opus to AIFF",
    slug: "opus-to-aiff",
    category: "Audio",
    description: 'Convert OPUS audio files to AIFF format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online Opus to AIFF — Convert Opus audio files into AIFF format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "488",
    name: "AIFF to WAV",
    slug: "aiff-to-wav",
    category: "Audio",
    description: 'Convert AIFF audio files to WAV format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AIFF to WAV — Convert AIFF audio files into uncompressed WAV format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "489",
    name: "AIFF to FLAC",
    slug: "aiff-to-flac",
    category: "Audio",
    description: 'Convert AIFF audio files to FLAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AIFF to FLAC — Convert AIFF audio files into lossless FLAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "490",
    name: "AIFF to OGG",
    slug: "aiff-to-ogg",
    category: "Audio",
    description: 'Convert AIFF audio files to OGG format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AIFF to OGG — Convert AIFF audio files into OGG Vorbis format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "491",
    name: "AIFF to M4A",
    slug: "aiff-to-m4a",
    category: "Audio",
    description: 'Convert AIFF audio files to M4A format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AIFF to M4A — Convert AIFF audio files into M4A format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "492",
    name: "AIFF to AAC",
    slug: "aiff-to-aac",
    category: "Audio",
    description: 'Convert AIFF audio files to AAC format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AIFF to AAC — Convert AIFF audio files into AAC format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "493",
    name: "AIFF to WMA",
    slug: "aiff-to-wma",
    category: "Audio",
    description: 'Convert AIFF audio files to WMA format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AIFF to WMA — Convert AIFF audio files into Windows Media Audio format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {
    id: "494",
    name: "AIFF to Opus",
    slug: "aiff-to-opus",
    category: "Audio",
    description: 'Convert AIFF audio files to OPUS format directly in your browser. High-quality conversion with no file size limits. Private and free.',
    seoDescription: 'Free online AIFF to Opus — Convert AIFF audio files into Opus format. ',
    dependencies: "FFmpeg.wasm",
    showInCategory: false,
  },
  {

    id: "495-uniq",
    name: "Hex ↔ ASCII Converter",
    slug: "hex-ascii-converter",
    category: "Developer",
    description: 'Convert between hexadecimal bytes and ASCII text. Supports custom delimiters and real-time bidirectional conversion. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Hex to ASCII Converter — Convert between hexadecimal bytes and ASCII text. Supports custom delimiters and real-time bidirectional conversion. ',
    dependencies: "None",
},
  {

    id: "496",
    name: "URL Encoder / Decoder",
    slug: "url-encoder-decoder",
    category: "Developer",
    description: 'Encode or decode URLs with percent-encoding. Swaps input/output for quick bidirectional conversion. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online URL Encoder Decoder — Encode or decode URLs with percent-encoding. Swaps input/output for quick bidirectional conversion. ',
    dependencies: "None",
},
  {

    id: "497",
    name: "HTML Entity Encoder / Decoder",
    slug: "html-entity-encoder",
    category: "Developer",
    description: 'Encode special HTML characters into entities (&amp; &lt; &gt;) or decode them back to readable text.',
    seoDescription: 'Free online HTML Entity Encoder Decoder — Encode special HTML characters into entities or decode them back to readable text. ',
    dependencies: "None",
    showInCategory: false,
},
  {

    id: "498",
    name: "Backslash Escape / Unescape",
    slug: "backslash-escape",
    category: "Developer",
    description: 'Escape or unescape special characters with backslashes. Handles newlines, tabs, quotes, and more. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Backslash Escape Unescape — Escape or unescape special characters with backslashes. Handles newlines, tabs, quotes, and more. ',
    dependencies: "None",
    showInCategory: false,
},
  {

    id: "499",
    name: "Random String Generator",
    slug: "random-string-generator",
    category: "Utility",
    description: 'Generate cryptographically secure random strings with customizable length, count, and character sets (uppercase, lowercase, digits, symbols).',
    seoDescription: 'Free online Random String Generator — Generate cryptographically secure random strings with customizable length, count, and character sets. ',
    dependencies: "None",
},
  {

    id: "500",
    name: "Number Base Converter",
    slug: "number-base-converter",
    category: "Converter",
    description: 'Convert numbers between binary (2), octal (8), decimal (10), and hexadecimal (16) bases with instant swap.',
    seoDescription: 'Free online Number Base Converter — Convert numbers between binary, octal, decimal, and hexadecimal bases with instant swap. ',
    dependencies: "None",
},
  {

    id: "501",
    name: "Line Sorter & Deduplicator",
    slug: "line-sorter",
    category: "Utility",
    description: 'Sort lines alphabetically (A→Z, Z→A), reverse order, shuffle randomly, or remove duplicate lines.',
    seoDescription: 'Free online Line Sorter and Deduplicator — Sort lines A→Z or Z→A, reverse, shuffle, or remove duplicates. ',
    dependencies: "None",
},
  {

    id: "502",
    name: "URL Parser",
    slug: "url-parser",
    category: "Developer",
    description: 'Parse any URL into its components — protocol, hostname, path, query parameters, hash, and more with copy-to-clipboard.',
    seoDescription: 'Free online URL Parser — Parse any URL into its components — protocol, hostname, path, query parameters, hash, and more. ',
    dependencies: "None",
},
  {

    id: "503",
    name: "String Inspector",
    slug: "string-inspector",
    category: "Developer",
    description: 'Inspect any string — view character count, byte length, word count, line count, Unicode code points, and non-ASCII character breakdown.',
    seoDescription: 'Free online String Inspector — Inspect any string with character count, byte length, word count, line count, Unicode code points, and non-ASCII breakdown. ',
    dependencies: "None",
},
  {
    id: "504",
    name: "Unix Time Converter",
    slug: "unix-time-converter",
    category: "Utility",
    description: 'Convert Unix timestamps to human-readable dates and back. Shows UTC, ISO 8601, locale, date, and time formats.',
    seoDescription: 'Free online Unix Time Converter — Convert Unix timestamps to human-readable dates and back. Shows UTC, ISO 8601, locale, date, and time. ',
    dependencies: "None",
        },
  {

    id: "505",
    name: "Code Beautifier & Minifier",
    slug: "code-beautifier",
    category: "Developer",
    description: 'Beautify or minify HTML, CSS, JavaScript, XML, ERB, LESS, and SCSS with a single click.',
    seoDescription: 'Free online Code Beautifier and Minifier — Beautify or minify HTML, CSS, JavaScript, XML, ERB, LESS, and SCSS. ',
    dependencies: "None",
},
  {

    id: "506",
    name: "HTML to JSX Converter",
    slug: "html-to-jsx",
    category: "Developer",
    description: 'Converts HTML files to JSX format — web pages, email templates, and content rendering to React component definitions and UI rendering. All conversion happens locally in your browser with no file size limits.',
    seoDescription: 'Free online HTML to JSX Converter — Convert HTML markup to JSX for React components. Handles class→className, for→htmlFor, event handlers, and more. ',
    dependencies: "None",
},
  {

    id: "507",
    name: "PHP Tools",
    slug: "php-tools",
    category: "Developer",
    description: 'Convert between JSON and PHP arrays, and serialize/unserialize PHP data. All four operations in one tool with instant swap.',
    seoDescription: 'Free online PHP Tools — Convert between JSON and PHP arrays, serialize and unserialize PHP data. All operations in one tool. ',
    dependencies: "None",
},
  {

    id: "508",
    name: "SVG to CSS Converter",
    slug: "svg-to-css",
    category: "Developer",
    description: 'Convert SVG images to CSS format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to CSS Converter — Convert SVG markup to CSS background-image data URIs. Preview the result. ',
    dependencies: "None",
},
  {
    id: "510",
    name: "JSON to Code Generator",
    slug: "json-to-code",
    category: "Converter",
    description: 'Generate type definitions from JSON for TypeScript, Java, C#, Python, Go, Rust, and Kotlin. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JSON to Code Generator — Generate type definitions from JSON for TypeScript, Java, C#, Python, Go, Rust, and Kotlin. ',
    dependencies: "None",
    showInCategory: false,
  },
  {

    id: "511",
    name: "JWT Debugger",
    slug: "jwt-debugger",
    category: "Developer",
    description: 'Decode and inspect JWT tokens — view header, payload, expiration, issuer, subject, and other standard claims.',
    seoDescription: 'Free online JWT Debugger — Decode and inspect JWT tokens. View header, payload, expiration, issuer, subject, and standard claims. ',
    dependencies: "None",
},
  {

    id: "512",
    name: "HTML Preview",
    slug: "html-preview",
    category: "Developer",
    description: 'Write HTML and see a live preview rendered in a sandboxed iframe. Perfect for prototyping and testing. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online HTML Preview — Write HTML and see a live preview rendered in a sandboxed iframe. Perfect for prototyping and testing. ',
    dependencies: "None",
},
  {

    id: "513",
    name: "Cron Expression Parser",
    slug: "cron-parser",
    category: "Developer",
    description: 'Parse cron expressions into human-readable descriptions. Includes common presets for quick reference.',
    seoDescription: 'Free online Cron Expression Parser — Parse cron expressions into human-readable descriptions with common presets. ',
    dependencies: "None",
},
  {

    id: "514",
    name: "Crypto & Hash Toolkit",
    slug: "crypto-kit",
    category: "Developer",
    description: 'Compute SHA-1, SHA-224, SHA-256, SHA-384, SHA-512, SHA-3, and RIPEMD-160 hashes, generate HMACs, and encrypt/decrypt text with AES. All client-side, no server uploads.',
    seoDescription: 'Free online Crypto & Hash Toolkit — Compute SHA-1, SHA-224, SHA-256, SHA-384, SHA-512, SHA-3, and RIPEMD-160 hashes, generate HMACs, and encrypt/decrypt text with AES. ',
    dependencies: "None",
    showInCategory: false,
},
  {
    id: "515",
    name: "TOML Converter",
    slug: "toml-converter",
    category: "Converter",
    description: 'Convert between JSON, YAML, and TOML formats. Four-direction conversion: JSON↔TOML and YAML↔TOML.',
    seoDescription: 'Free online TOML Converter — Convert between JSON, YAML, and TOML formats. Four-direction conversion: JSON to TOML, TOML to JSON, YAML to TOML, and TOML to YAML. ',
    dependencies: "None",
    showInCategory: false,
  },
  {

    id: "517",
    name: "Web Inspector & HTTP Tools",
    slug: "web-inspector",
    category: "Developer",
    description: 'Browser device info, user-agent parser, HTTP status codes reference, MIME types lookup, Basic Auth header generator, Open Graph meta tags generator, and keycode inspector.',
    seoDescription: 'Free online Web Inspector & HTTP Tools — Browser device info, user-agent parser, HTTP status codes, MIME types, Basic Auth generator, OG meta tags, and keycode inspector. ',
    dependencies: "None",
},
  {

    id: "518",
    name: "Text Converter & Obfuscator",
    slug: "text-converter",
    category: "Developer",
    description: 'NATO phonetic alphabet converter, ASCII binary converter, Unicode code point viewer, Roman numeral converter, and string obfuscator with leet speak, ROT13, Base64, and shuffle.',
    seoDescription: 'Free online Text Converter & Obfuscator — NATO alphabet, ASCII binary, Unicode viewer, Roman numerals, and string obfuscation with leet, ROT13, Base64, and shuffle. ',
    dependencies: "None",
    showInCategory: false,
},
  {
    id: "mt-1",
    name: "ETA Calculator",
    slug: "eta-calculator",
    category: "Calculator",
    description: 'Estimate travel time from distance and speed — with optional arrival time.',
    seoDescription: 'Free online ETA Calculator — Estimate travel time from distance and speed with optional arrival time. ',
    dependencies: "None",
  },
  {

    id: "du-5",
    name: "YAML Re-indenter",
    slug: "yaml-reindenter",
    category: "Developer",
    description: 'Clean up messy YAML — fix indentation, align colons, and normalize list formatting. Paste any YAML and get consistently formatted output.',
    seoDescription: 'Free online YAML Re-indenter — Clean up messy YAML with proper indentation, aligned colons, and normalized list formatting. ',
    dependencies: "Vanilla JS",
},
  {

    id: "ou-1",
    name: "WiFi QR Generator",
    slug: "wifi-qr-generator",
    category: "Utility",
    description: 'Generate QR codes for WiFi network credentials — scan to connect.',
    seoDescription: 'Free online WiFi QR Generator — Generate QR codes for WiFi network credentials to share with others. ',
    dependencies: "None",
    showInCategory: false,
},
  {

    id: "ou-2",
    name: "Phone Number Parser",
    slug: "phone-parser",
    category: "Developer",
    description: 'Parse and validate international phone numbers with country detection.',
    seoDescription: 'Free online Phone Number Parser — Parse and validate international phone numbers with country detection and formatting. ',
    dependencies: "None",
},
  {

    id: "ou-4",
    name: "Slugify",
    slug: "slugify-tool",
    category: "Utility",
    description: 'Convert text to URL-friendly slugs with configurable separators. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Slugify — Convert text to URL-friendly slugs with configurable separators. ',
    dependencies: "None",
},
  {

    id: "mg-1",
    name: "ULID Generator",
    slug: "ulid-generator",
    category: "Utility",
    description: 'Generate time-ordered ULID identifiers with Crockford base32 encoding. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online ULID Generator — Generate time-ordered ULID identifiers with Crockford base32 encoding. ',
    dependencies: "None",
},
  {

    id: "mg-2",
    name: "Numeronym Generator",
    slug: "numeronym-generator",
    category: "Utility",
    description: 'Convert words to numeronyms (a11y-style) and acronyms. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Numeronym Generator — Convert words to numeronyms (a11y-style) and acronyms. ',
    dependencies: "None",
},
  {

    id: "mg-3",
    name: "MAC Vendor Lookup",
    slug: "mac-vendor-lookup",
    category: "Developer",
    description: 'Look up device manufacturer from MAC address OUI prefix.',
    seoDescription: 'Free online MAC Vendor Lookup — Look up device manufacturer from MAC address OUI prefix with extensive vendor database. ',
    dependencies: "None",
},
  {

    id: "523",
    name: "List Converter",
    slug: "list-converter",
    category: "Utility",
    description: 'Convert lists between delimiters: comma, newline, pipe, tab, semicolon, and space. Auto-detects input format and supports trim, sort, and deduplicate.',
    seoDescription: 'Free online List Converter — Convert lists between comma, newline, pipe, tab, semicolon, and space delimiters with auto-detect. ',
    dependencies: "None",
},
  {

    id: "524",
    name: "RSA Key Pair Generator",
    slug: "rsa-key-generator",
    category: "Developer",
    description: 'Generate RSA key pairs (2048/4096-bit) using the Web Crypto API. Export public and private keys as PEM strings. All client-side, no server uploads.',
    seoDescription: 'Free online RSA Key Pair Generator — Generate 2048 or 4096-bit RSA key pairs and export as PEM. Uses Web Crypto API, ',
    dependencies: "None",
},
  {

    id: "ct-1",
    name: "Emoji Picker",
    slug: "emoji-picker",
    category: "Utility",
    description: 'Browse 400+ emojis organized by category with search and copy.',
    seoDescription: 'Free online Emoji Picker — Browse 400+ emojis organized by category with search and copy to clipboard. ',
    dependencies: "None",
},
  {

    id: "ct-2",
    name: "ASCII Art Generator",
    slug: "ascii-art-generator",
    category: "Utility",
    description: 'Convert text to ASCII art with multiple font styles.',
    seoDescription: 'Free online ASCII Art Generator — Convert text to ASCII art with block, bubble, fancy, and digital styles. ',
    dependencies: "None",
},
  {

    id: "ct-2b",
    name: "ASCII Font Generator",
    slug: "ascii-font-generator",
    category: "Utility",
    description: 'Generate large ASCII text banners with multiple font styles — perfect for terminal headers and text art.',
    seoDescription: 'Free online ASCII Font Generator — Generate large ASCII text banners with multiple font styles for terminal headers and text art. ',
    dependencies: "None",
},
  {

    id: "526",
    name: "Benchmark Builder",
    slug: "benchmark-builder",
    category: "Utility",
    description: 'Measure browser CPU performance with synthetic benchmarks: integer math, floating point, array sorting, string ops, and mixed workloads.',
    seoDescription: 'Free online Browser Benchmark — Measure CPU performance with integer, float, array, string, and mixed workloads. All client-side. ',
    dependencies: "None",
},
  {
    id: "527",
    name: "PDF to PNG",
    slug: "pdf-to-png",
    category: "PDF",
    description: 'Convert PDF images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PDF to PNG — Convert PDF pages to PNG, WebP, or BMP images. Extract slides and graphics with customizable DPI and color modes. ',
    dependencies: "pdfjs-dist, jszip",
    showInCategory: true,
  },
  {
    id: "528",
    name: "Create PDF",
    slug: "create-pdf",
    category: "PDF",
    description: 'Generate PDF documents from plain text, CSV tables, JSON data, or XML content. Includes customizable title, font size, and table formatting for the CSV mode.',
    seoDescription: 'Free online Create PDF — Generate PDF documents from plain text, CSV tables, JSON data, or XML. Fully customizable with titles and table formatting. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "529",
    name: "PDF Info & Analysis",
    slug: "pdf-info",
    category: "PDF",
    description: 'View document metadata, page dimensions, extract all text content, and export structured data as JSON from any PDF. Essential for document auditing and compliance.',
    seoDescription: 'Free online PDF Info & Analysis — View metadata, page dimensions, extract text, or export JSON from PDF. Document auditing and compliance tool. ',
    dependencies: "pdf-lib, pdfjs-dist",
    showInCategory: true,
  },
  {
    id: "530",
    name: "PDF Cleanup",
    slug: "pdf-cleanup",
    category: "PDF",
    description: 'Remove annotations, strip hidden metadata, delete blank pages, reverse page order, or sanitize your PDF documents. Combine multiple cleanup operations in one pass.',
    seoDescription: 'Free online PDF Cleanup — Remove annotations, strip metadata, delete blank pages, reverse page order, or sanitize PDFs. Combine operations in one pass. ',
    dependencies: "pdf-lib, pdfjs-dist",
    showInCategory: true,
  },
  {
    id: "531b",
    name: "PDF Background Color",
    slug: "pdf-background-color",
    category: "PDF",
    description: 'Add a subtle color tint to all pages in a PDF document. Upload your PDF and pick a background color.',
    seoDescription: 'Free online PDF Background Color \u2014 Add a subtle color tint to all pages in a PDF document. ',
    dependencies: "pdf-lib",
  },
  {
    id: "531c",
    name: "PDF Add Blank Page",
    slug: "pdf-add-blank-page",
    category: "PDF",
    description: 'Insert blank pages at any position in a PDF document. Choose page size, count, and position.',
    seoDescription: 'Free online PDF Add Blank Page \u2014 Insert blank pages at any position in a PDF document. ',
    dependencies: "pdf-lib",
  },
  {
    id: "950",
    name: "PDF Bates Numbering",
    slug: "pdf-bates-numbering",
    category: "PDF",
    description: 'Add sequential Bates numbers to every page of your PDF. Customize prefix, starting number, and position.',
    seoDescription: 'Free online PDF Bates Numbering — Add sequential Bates numbers to every page. Customize prefix, start number, and position. ',
    dependencies: "pdf-lib",
  },
  {
    id: "951",
    name: "PDF Stamp",
    slug: "pdf-stamp",
    category: "PDF",
    description: 'Add a diagonal watermark stamp (DRAFT, CONFIDENTIAL, etc.) to every page of your PDF.',
    seoDescription: 'Free online PDF Stamp — Add diagonal watermark stamps like DRAFT or CONFIDENTIAL to every page. ',
    dependencies: "pdf-lib",
  },
  {
    id: "952",
    name: "PDF Timestamp",
    slug: "pdf-timestamp",
    category: "PDF",
    description: 'Add a generation timestamp to the bottom-right corner of every page in your PDF.',
    seoDescription: 'Free online PDF Timestamp — Add a generation timestamp to every page of your PDF. ',
    dependencies: "pdf-lib",
  },
  {
    id: "953",
    name: "PDF Table of Contents",
    slug: "pdf-table-of-contents",
    category: "PDF",
    description: 'Insert a table of contents page at the beginning of your PDF document.',
    seoDescription: 'Free online PDF Table of Contents — Insert a table of contents page at the beginning of your PDF. ',
    dependencies: "pdf-lib",
  },
  {
    id: "532",
    name: "Advanced PDF Tools",
    slug: "pdf-advanced",
    category: "PDF",
    description: 'Overlay one PDF on another, alternate-merge two documents, combine pages into sheets, apply booklet layout, invert colors, or extract pages as ZIP images.',
    seoDescription: 'Free online Advanced PDF Tools — Overlay, alternate-merge, booklet layout, combine pages, invert colors, or extract PDF pages as ZIP images. ',
    dependencies: "pdf-lib, pdfjs-dist, jszip",
    showInCategory: true,
  },
  {
    id: "533",
    name: "PDF Attachments",
    slug: "pdf-attachments",
    category: "PDF",
    description: 'View, add, and extract embedded files inside PDF documents. Supports any file type as attachments — images, spreadsheets, archives, and more.',
    seoDescription: 'Free online PDF Attachments — View, add, and extract embedded files from PDF documents. Supports any file type. ',
    dependencies: "pdf-lib",
    showInCategory: true,
  },
  {
    id: "534a",
    name: "Study Time Calculator",
    slug: "study-time-calculator",
    category: "Calculator",
    description: 'Calculate total study hours over a period and see monthly projections.',
    seoDescription: 'Free online Study Time Calculator \u2014 Calculate total study hours and monthly projections. ',
    dependencies: "None",
  },
  {
    id: "534b",
    name: "Test Score Calculator",
    slug: "test-score-calculator",
    category: "Calculator",
    description: 'Convert correct/total answers to percentage and letter grade.',
    seoDescription: 'Free online Test Score Calculator \u2014 Convert correct answers to percentage and letter grade. ',
    dependencies: "None",
  },
  {
    id: "534c",
    name: "Words Per Page Calculator",
    slug: "words-per-page-calculator",
    category: "Calculator",
    description: 'Estimate how many pages your word count will take at different font sizes.',
    seoDescription: 'Free online Words Per Page Calculator \u2014 Estimate page count from word count and font size. ',
    dependencies: "None",
  },
  {
    id: "534d",
    name: "Profit & Loss Calculator",
    slug: "profit-loss-calculator",
    category: "Finance",
    description: 'Calculate gross profit, net income, and margin from revenue, COGS, and operating expenses.',
    seoDescription: 'Free online Working Capital Calculator \u2014 Calculate gross profit, net income, and margin. ',
    dependencies: "None",

  },
  {

    id: "534e",
    name: "Ring Size Converter",
    slug: "ring-size-converter",
    category: "Utility",
    description: 'Convert inner diameter in millimeters to US ring sizes.',
    seoDescription: 'Free online Ring Size Converter \u2014 Convert inner diameter in mm to US ring sizes. ',
    dependencies: "None",
},
  {
    id: "534f",
    name: "Screen Size Calculator",
    slug: "screen-size-converter",
    category: "Calculator",
    description: 'Calculate width, height, and area from diagonal screen size and aspect ratio.',
    seoDescription: 'Free online Screen Size Calculator \u2014 Calculate width, height, and area from diagonal and aspect ratio. ',
    dependencies: "None",
  },
  {

    id: "534g",
    name: "Shoe Size Converter",
    slug: "shoe-size-converter",
    category: "Utility",
    description: 'Convert between US, UK, European, and Asian shoe size systems instantly. Includes men\'s, women\'s, and children\'s size charts.',
    seoDescription: 'Free online Shoe Size Converter \u2014 Convert between US and UK shoe sizes. ',
    dependencies: "None",
},
  {

    id: "534h",
    name: "ZIP File Extractor",
    slug: "zip-file-extractor",
    category: "Utility",
    description: 'View the contents and file sizes inside a ZIP archive without extracting.',
    seoDescription: 'Free online ZIP File Extractor \u2014 View ZIP archive contents and file sizes. ',
    dependencies: "fflate",
},
  {

    id: "537a",
    name: "OAuth Client Setup",
    slug: "oauth-client-setup",
    category: "Developer",
    description: 'Generate OAuth authorization URLs for Google, GitHub, Facebook, Microsoft, and LinkedIn with custom client ID, redirect URI, and scope.',
    seoDescription: 'Free online OAuth Client Setup \u2014 Generate authorization URLs for Google, GitHub, Facebook, Microsoft, and LinkedIn. ',
    dependencies: "None",
},
  {

    id: "537b",
    name: "PKCE Verifier",
    slug: "pkce-verifier",
    category: "Developer",
    description: 'Generate PKCE code_verifier and code_challenge (S256) pairs, or verify that a verifier matches a challenge.',
    seoDescription: 'Free online PKCE Verifier \u2014 Generate and verify PKCE code_verifier / code_challenge pairs for secure OAuth flows. ',
    dependencies: "None",
},
  {

    id: "537c",
    name: "OAuth Scope Builder",
    slug: "oauth-scope-builder",
    category: "Developer",
    description: 'Build OAuth scope strings from comma-separated values with URL encoding and breakdown.',
    seoDescription: 'Free online OAuth Scope Builder \u2014 Build and preview OAuth scope strings with URL encoding. ',
    dependencies: "None",
},
  {

    id: "537d",
    name: "OAuth State Validator",
    slug: "oauth-state-validator",
    category: "Developer",
    description: 'Validate OAuth state parameters for format, length, and age.',
    seoDescription: 'Free online OAuth State Validator \u2014 Validate state parameters for format, length, and age. ',
    dependencies: "None",
},
  {

    id: "537e",
    name: "PBKDF2 Hash Generator",
    slug: "pbkdf2-hash-generator",
    category: "Developer",
    description: 'Generate PBKDF2 hashes with 10,000 iterations of SHA-256 for password storage simulation.',
    seoDescription: 'Free online PBKDF2 Hash Generator \u2014 Generate PBKDF2 hashes with 10,000 SHA-256 iterations. ',
    dependencies: "None",
},
  {

    id: "537f",
    name: "Cookie Parser & Analyzer",
    slug: "cookie-parser",
    category: "Developer",
    description: 'Parse Set-Cookie headers into structured JSON, or analyze cookie security flags (Secure, HttpOnly, SameSite, expiry).',
    seoDescription: 'Free online Cookie Parser & Analyzer \u2014 Parse Set-Cookie headers and check security flags. ',
    dependencies: "None",
},
  {

    id: "539b",
    name: "HTML Linter",
    slug: "html-linter",
    category: "Developer",
    description: 'Lint HTML for missing DOCTYPE, unclosed tags, and unexpected closing tags. Paste your HTML and get instant feedback.',
    seoDescription: 'Free online HTML Linter \u2014 Lint HTML for missing DOCTYPE, unclosed tags, and unexpected closing tags. ',
    dependencies: "None",
},
  {

    id: "539c",
    name: "XML Minifier / Validator",
    slug: "xml-minifier-validator",
    category: "Developer",
    description: 'Minify XML by removing whitespace, or validate XML syntax. Paste your XML and choose an operation.',
    seoDescription: 'Free online XML Minifier / Validator \u2014 Minify XML by removing whitespace, or validate XML syntax. ',
    dependencies: "None",
},
  {
    id: "948",
    name: "Border CSS Generator",
    slug: "border-css-generator",
    category: "Design",
    description: 'Visual border CSS generator with width, style, color, and radius controls with live preview.',
    seoDescription: 'Free online Border CSS Generator — Generate border CSS with width, style, color, and radius controls with live preview. ',
    dependencies: "None",
    showInCategory: false,
  },
  {
    id: "949",
    name: "Typography Preview",
    slug: "typography-preview",
    category: "Design",
    description: 'Typography CSS generator with font-size, line-height, letter-spacing, and font-weight controls with live preview.',
    seoDescription: 'Free online Typography Preview — Generate typography CSS with font-size, line-height, letter-spacing, and font-weight controls with live preview. ',
    dependencies: "None",
  },
  {

    id: "543a",
    name: "Base32 Encoder / Decoder",
    slug: "base32-encoder",
    category: "Developer",
    description: 'Encode text to Base32 or decode Base32 strings back to text.',
    seoDescription: 'Free online Base32 Encoder / Decoder \u2014 Encode and decode Base32 strings. ',
    dependencies: "None",
},
  {

    id: "543b",
    name: "Base64 to JSON Decoder",
    slug: "base64-json-decoder",
    category: "Developer",
    description: 'Decode Base64 and pretty-print JSON. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Base64 to JSON Decoder \u2014 Decode Base64 and pretty-print JSON. ',
    dependencies: "None",
},
  {

    id: "543c",
    name: "Hex to Text Converter",
    slug: "hex-text-converter",
    category: "Developer",
    description: 'Convert between hex strings and text. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Hex to Text Converter \u2014 Convert between hex strings and text. ',
    dependencies: "None",
},
  {

    id: "543d",
    name: "SVG to Base64 Converter",
    slug: "svg-base64-converter",
    category: "Converter",
    description: 'Convert SVG images to BASE64 format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to Base64 Converter \u2014 Convert SVG to data URIs. ',
    dependencies: "None",
},
  {

    id: "543e",
    name: "Character Encoding Converter",
    slug: "character-encoding-converter",
    category: "Developer",
    description: 'Analyze each character to see its Unicode code point and ASCII/non-ASCII status.',
    seoDescription: 'Free online Character Encoding Converter \u2014 Analyze Unicode code points and ASCII status. ',
    dependencies: "None",
},
  {

    id: "543f",
    name: "Unicode Converter",
    slug: "unicode-converter",
    category: "Developer",
    description: 'Convert text to Unicode code points with JavaScript escape sequences and HTML entities.',
    seoDescription: 'Free online Unicode Converter \u2014 Get code points, JS escapes, and HTML entities. ',
    dependencies: "None",
},
  {

    id: "543g",
    name: "Markdown to Slack Converter",
    slug: "markdown-slack-converter",
    category: "Converter",
    description: 'Convert Markdown to Slack mrkdwn. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Markdown to Slack Converter \u2014 Convert Markdown to Slack mrkdwn. ',
    dependencies: "None",
},
  {

    id: "543h",
    name: "PX to REM Converter",
    slug: "px-rem-converter",
    category: "Developer",
    description: 'Convert between PX and REM with custom base size. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online PX to REM Converter \u2014 Convert between PX and REM with custom base size. ',
    dependencies: "None",
},
  {

    id: "543i",
    name: "SVG Optimizer",
    slug: "svg-optimizer",
    category: "Developer",
    description: 'Minify SVG by removing whitespace, comments, and redundant attributes.',
    seoDescription: 'Free online SVG Optimizer \u2014 Minify SVG by removing whitespace and comments. ',
    dependencies: "None",
},
  {

    id: "543k",
    name: "Power Converter",
    slug: "power-converter",
    category: "Utility",
    description: 'Convert between kW, hp, bhp, W, MW, and BTU/hr.',
    seoDescription: 'Free online Power Converter \u2014 Convert between kW, hp, W, MW, and BTU/hr. ',
    dependencies: "None",
},
  {

    id: "543l",
    name: "Pressure Converter",
    slug: "pressure-converter",
    category: "Utility",
    description: 'Convert between kPa, psi, bar, atm, Torr, and mbar. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Pressure Converter \u2014 Convert between kPa, psi, bar, atm, Torr, and mbar. ',
    dependencies: "None",
},
  {
    id: "548a",
    name: "Color Shades & Tints",
    slug: "color-shades-tints",
    category: "Design",
    description: 'Generate color shades and tints from a base color by varying lightness in HSL space.',
    seoDescription: 'Free online Color Shades & Tints \u2014 Generate color shades and tints from a base color. ',
    dependencies: "None",
  },
  {
    id: "548b",
    name: "Contrast Ratio Checker",
    slug: "contrast-ratio-checker",
    category: "Design",
    description: 'Check foreground/background color contrast against WCAG AA and AAA accessibility standards.',
    seoDescription: 'Free online Contrast Ratio Checker \u2014 Check color contrast against WCAG AA and AAA standards. ',
    dependencies: "None",
  },
  {

    id: "548c",
    name: "Media Query Generator",
    slug: "media-query-generator",
    category: "Developer",
    description: 'Generate CSS media queries with min/max width and optional device type conditions.',
    seoDescription: 'Free online Media Query Generator \u2014 Generate CSS media queries with width and device conditions. ',
    dependencies: "None",
},
  {

    id: "548d",
    name: "Markdown Table Generator",
    slug: "markdown-table-generator",
    category: "Developer",
    description: 'Generate Markdown table templates with configurable rows and columns.',
    seoDescription: 'Free online Markdown Table Generator \u2014 Generate Markdown table templates with custom dimensions. ',
    dependencies: "None",
},
{
    id: "500",
    name: "Gemini Watermark Remover",
    slug: "gemini-watermark-remover",
    category: "Image",
    description: "Remove the visible sparkle watermark from Gemini AI-generated images using reverse alpha blending. Supports single image and batch processing with ZIP download. 100% client-side — nothing is uploaded.",
    seoDescription: "Free online Gemini Watermark Remover — Remove visible AI sparkle watermarks from Gemini-generated images using mathematically precise reverse alpha blending. ",
    dependencies: "Canvas API, jszip",
    showInCategory: true,
},
{
    id: "501",
    name: "Bulk AVIF Optimizer",
    slug: "bulk-avif-optimizer",
    category: "Image",
    description: "Convert and compress images to AVIF format in bulk with quality presets and max-width controls. AVIF provides 50% smaller files than JPEG with better quality. 100% client-side.",
    seoDescription: "Free online Bulk AVIF Optimizer — Convert and compress images to AVIF format in batch with quality presets. ",
    dependencies: "Canvas API, jszip",
    showInCategory: true,
},
];
