import type { ToolMetadata } from './tools-types';

export const entries_chunk_4: ToolMetadata[] = [
  {

    id: "779",
    name: "Serial Number Generator",
    slug: "serial-number-generator",
    category: "Developer",
    description: 'Generate serial numbers with configurable format patterns using X (hex), 9 (digit), and A (alphanumeric) placeholders. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Serial Number Generator — Generate serial numbers with configurable format patterns using X (hex), 9 (digit), and A (alphanumeric) placeholders. ',
    dependencies: "None",
},
  {

    id: "780",
    name: "Nickname Generator",
    slug: "nickname-generator",
    category: "Utility",
    description: 'Generate random nicknames by combining adjectives and creative name parts. Perfect for gaming, social media, and creative projects. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Nickname Generator — Generate random nicknames by combining adjectives and creative name parts. Perfect for gaming, social media, and creative projects. ',
    dependencies: "None",
},
  {

    id: "781",
    name: "Avatar Generator",
    slug: "avatar-generator",
    category: "Developer",
    description: 'Generate avatar initials SVG from any name with customizable background color, text color, and size. Perfect for profile placeholders. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Avatar Generator — Generate avatar initials SVG from any name with customizable background color, text color, and size. Perfect for profile placeholders. ',
    dependencies: "None",
},
  {

    id: "782",
    name: "Timer",
    slug: "timer",
    category: "Utility",
    description: 'Configurable countdown timer with hours, minutes, and seconds input. Features start, pause, and reset controls with visual progress bar. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Timer — Configurable countdown timer with hours, minutes, and seconds input. Features start, pause, and reset controls with visual progress bar. ',
    dependencies: "None",
},
  {

    id: "783",
    name: "Stopwatch",
    slug: "stopwatch",
    category: "Utility",
    description: 'Precision stopwatch with start, stop, lap recording, and reset functionality. Lap times are displayed in a table for easy comparison. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Stopwatch — Precision stopwatch with start, stop, lap recording, and reset functionality. Lap times are displayed in a table for easy comparison. ',
    dependencies: "None",
},
  {

    id: "784",
    name: "Countdown Timer",
    slug: "countdown-tool",
    category: "Utility",
    description: 'Countdown to a specific date and time with live days, hours, minutes, and seconds display. Perfect for event countdowns and deadlines. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Countdown Timer — Countdown to a specific date and time with live days, hours, minutes, and seconds display. Perfect for event countdowns and deadlines. ',
    dependencies: "None",
},
  {

    id: "786",
    name: "Interval Timer",
    slug: "interval-timer",
    category: "Utility",
    description: 'Repeating interval timer for workouts and training. Configure sets, work period, and rest period with automatic cycling. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Interval Timer — Repeating interval timer for workouts and training. Configure sets, work period, and rest period with automatic cycling. ',
    dependencies: "None",
},
  {

    id: "787",
    name: "Tabata Timer",
    slug: "tabata-timer",
    category: "Utility",
    description: 'Tabata interval timer with 20 seconds work and 10 seconds rest per round. Features a 3-second preparation countdown and configurable rounds. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Tabata Timer — Tabata interval timer with 20 seconds work and 10 seconds rest per round. Features a 3-second preparation countdown and configurable rounds. ',
    dependencies: "None",
},
  {

    id: "788",
    name: "World Clock",
    slug: "world-clock",
    category: "Utility",
    description: 'Display multiple timezone clocks simultaneously. Add and remove cities from a curated list of major world timezones. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online World Clock — Display multiple timezone clocks simultaneously. Add and remove cities from a curated list of major world timezones. ',
    dependencies: "None",
},
  {
    id: "790",
    name: "Time Duration Calculator",
    slug: "time-duration-calculator",
    category: "Calculator",
    description: 'Calculate the exact duration between two times. Handles overnight time spans and displays results in hours, minutes, and seconds. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Time Duration Calculator — Calculate the exact duration between two times. Handles overnight time spans and displays results in hours, minutes, and seconds. ',
    dependencies: "None",
  },
  {
    id: "791",
    name: "Time Addition Calculator",
    slug: "time-addition-calculator",
    category: "Calculator",
    description: 'Add or subtract hours and minutes from a starting time. Perfect for scheduling, project planning, and time tracking. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Time Addition Calculator — Add or subtract hours and minutes from a starting time. Perfect for scheduling, project planning, and time tracking. ',
    dependencies: "None",
  },
  {
    id: "792",
    name: "Time Until Calculator",
    slug: "time-until-calculator",
    category: "Calculator",
    description: 'Calculate the exact days, hours, and minutes remaining until a specified future date and time. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Time Until Calculator — Calculate the exact days, hours, and minutes remaining until a specified future date and time. ',
    dependencies: "None",
  },
  {
    id: "793",
    name: "Meeting Time Planner",
    slug: "meeting-time-planner",
    category: "Calculator",
    description: 'Plan meeting times across multiple timezones. Select date and time, then see the equivalent time in all selected cities simultaneously. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Meeting Time Planner — Plan meeting times across multiple timezones. Select date and time, then see the equivalent time in all selected cities simultaneously. ',
    dependencies: "None",
  },
  {
    id: "796",
    name: "Word Frequency Counter",
    slug: "word-frequency-counter",
    category: "SEO",
    description: 'Analyze word frequency in any text. Shows top N words with count and percentage. Essential for keyword analysis and content optimization. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Word Frequency Counter — Analyze word frequency in any text. Shows top N words with count and percentage. Essential for keyword analysis and content optimization. ',
    dependencies: "None",
  },
  {
    id: "798",
    name: "Keyword Planner Tool",
    slug: "keyword-planner-tool",
    category: "SEO",
    description: 'Extract potential SEO keywords from text with stop word filtering and frequency analysis. Shows word count, percentage, and density. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Keyword Planner Tool — Extract potential SEO keywords from text with stop word filtering and frequency analysis. Shows word count, percentage, and density. ',
    dependencies: "None",
  },
  {
    id: "799",
    name: "SEO Meta Tag Generator",
    slug: "seo-meta-tag-generator",
    category: "SEO",
    description: 'Generate complete HTML meta tags including title, description, keywords, Open Graph, Twitter Cards, and canonical URL from a simple form. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SEO Meta Tag Generator — Generate complete HTML meta tags including title, description, keywords, Open Graph, Twitter Cards, and canonical URL from a simple form. ',
    dependencies: "None",
  },
  {
    id: "800",
    name: "SEO Preview Generator",
    slug: "seo-preview-generator",
    category: "SEO",
    description: 'Preview how your page will appear in Google search results. Enter title, URL, and description to see the live search snippet preview. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SEO Preview Generator — Preview how your page will appear in Google search results. Enter title, URL, and description to see the live search snippet preview. ',
    dependencies: "None",
  },
  {
    id: "801",
    name: "SEO Headline Analyzer",
    slug: "seo-headline-analyzer",
    category: "SEO",
    description: 'Analyze headlines for word count, character count, sentiment, power words, and overall SEO score. Optimize your titles for better engagement. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SEO Headline Analyzer — Analyze headlines for word count, character count, sentiment, power words, and overall SEO score. Optimize your titles for better engagement. ',
    dependencies: "None",
  },
  {
    id: "802",
    name: "SEO Schema Generator",
    slug: "seo-schema-generator",
    category: "SEO",
    description: 'Generate JSON-LD structured data markup for Article, Product, FAQ, LocalBusiness, Recipe, and Event schema types. No signup or account required.',
    seoDescription: 'Free online SEO Schema Generator — Generate JSON-LD structured data markup for Article, Product, FAQ, LocalBusiness, Recipe, and Event schema types. ',
    dependencies: "None",
  },
  {
    id: "803",
    name: "SEO Slug Generator",
    slug: "seo-slug-generator",
    category: "SEO",
    description: 'Generate SEO-friendly URL slugs from any text. Automatically removes special characters and converts spaces to hyphens. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SEO Slug Generator — Generate SEO-friendly URL slugs from any text. Automatically removes special characters and converts spaces to hyphens. ',
    dependencies: "None",
  },
  {
    id: "805",
    name: "Text Replacer",
    slug: "text-replacer",
    category: "Text",
    description: 'Find and replace text in any string instantly. Supports case-sensitive and case-insensitive matching, whole-word replacement, and regex patterns for advanced text manipulation.',
    seoDescription: 'Free online Text Replacer — Find and replace text instantly with case-sensitive or case-insensitive matching, whole-word replacement, and regex support. Fast bulk replacement for editing and data cleanup.',
    dependencies: "None",
  },
  {
    id: "806",
    name: "Text Sorter",
    slug: "text-sorter",
    category: "Text",
    description: 'Sort text lines alphabetically (A-Z, Z-A), by length (shortest-first or longest-first), randomize order, or remove duplicates. Essential for organizing lists, cleaning data, and preparing content.',
    seoDescription: 'Free online Text Sorter — Sort text lines A-Z or Z-A, by length, randomize order, or remove duplicates. Essential for organizing lists, cleaning data, and preparing content. Instant local processing.',
    dependencies: "None",
  },
  {
    id: "807",
    name: "Text Deduplicator",
    slug: "text-deduplicator",
    category: "Text",
    description: 'Remove duplicate lines from text instantly while preserving the order of first occurrences. Perfect for cleaning up lists, CSV data, log files, and removing redundant entries from any line-based data.',
    seoDescription: 'Free online Text Deduplicator — Remove duplicate lines from text instantly while preserving first occurrence order. Clean up lists, CSV data, logs, and redundant entries. 100% local processing.',
    dependencies: "None",
  },
  {
    id: "809",
    name: "Text to HTML Converter",
    slug: "text-to-html-converter",
    category: "Converter",
    description: 'Convert plain text to HTML paragraphs with proper paragraph and line break tags. Handles double line breaks as paragraph separators. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Text to HTML Converter — Convert plain text to HTML paragraphs with proper paragraph and line break tags. Handles double line breaks as paragraph separators. ',
    dependencies: "None",
    showInCategory: false,
  },
  {
    id: "810",
    name: "HTML to Text Converter",
    slug: "html-to-text-converter",
    category: "Converter",
    description: 'Strip all HTML tags from content and decode HTML entities. Convert any HTML document back to clean plain text. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online HTML to Text Converter — Strip all HTML tags from content and decode HTML entities. Convert any HTML document back to clean plain text. ',
    dependencies: "None",
  },
  {
    id: "811",
    name: "Markdown Previewer",
    slug: "markdown-previewer",
    category: "Text",
    description: 'Preview Markdown text as rendered HTML in real time. Supports headings, bold, italic, blockquotes, code blocks, inline code, links, images, lists, tables, and strikethrough. All processing is local.',
    seoDescription: 'Free online Markdown Previewer — Preview Markdown as rendered HTML in real time. Supports headings, bold, italic, code blocks, tables, blockquotes, and links. 100% local processing with instant preview.',
    dependencies: "None",
  },
  {

    id: "813",
    name: "Color Picker",
    slug: "color-picker",
    category: "Design",
    description: 'Pick colors from a visual spectrum or enter hex values. Copy to clipboard — perfect for design palettes, CSS variables, and UI mockups. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Color Picker \u2014 Pick colors from a visual spectrum or enter hex values. Copy to clipboard \u2014 perfect for design palettes, CSS variables, and UI mockups. ',
    dependencies: "None",
},
  {

    id: "814",
    name: "Color Palette Generator",
    slug: "color-palette-generator",
    category: "Design",
    description: 'Generate harmonious color palettes from a base color. Includes complementary, analogous, and triadic color schemes for designers. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Color Palette Generator \u2014 Generate harmonious color palettes from a base color. Includes complementary, analogous, and triadic color schemes for designers. ',
    dependencies: "None",
},
  {

    id: "815",
    name: "Gradient Generator",
    slug: "gradient-generator",
    category: "Design",
    description: 'Create beautiful CSS gradients with a visual preview. Choose between linear and radial gradients for your web designs. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Gradient Generator \u2014 Create beautiful CSS gradients with a visual preview. Choose between linear and radial gradients for your web designs. ',
    dependencies: "None",
},
  {

    id: "816",
    name: "Contrast Checker",
    slug: "contrast-checker",
    category: "Utility",
    description: 'Check the contrast ratio between two colors against WCAG AA and AAA standards. Essential for accessible web design. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Contrast Checker \u2014 Check the contrast ratio between two colors against WCAG AA and AAA standards. Essential for accessible web design. ',
    dependencies: "None",
    showInCategory: false,
},
  {

    id: "817",
    name: "Counter Tool",
    slug: "counter-tool",
    category: "Utility",
    description: 'Simple increment/decrement counter with a reset option. Track anything from reps to inventory counts. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Counter Tool \u2014 Simple increment/decrement counter with a reset option. Track anything from reps to inventory counts. ',
    dependencies: "None",
},
  {

    id: "818",
    name: "List Randomizer",
    slug: "list-randomizer",
    category: "Utility",
    description: 'Randomly shuffle any list of items. Enter each item on a new line and see them randomized instantly. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online List Randomizer \u2014 Randomly shuffle any list of items. Enter each item on a new line and see them randomized instantly. ',
    dependencies: "None",
},
  {

    id: "819",
    name: "List Sorter",
    slug: "list-sorter",
    category: "Utility",
    description: 'Sort lists alphabetically (A-Z or Z-A) or by length. Great for organizing data and cleaning up unordered lists. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online List Sorter \u2014 Sort lists alphabetically (A-Z or Z-A) or by length. Great for organizing data and cleaning up unordered lists. ',
    dependencies: "None",
},
  {

    id: "820",
    name: "Decision Maker",
    slug: "decision-maker",
    category: "Utility",
    description: "Can't decide? Enter your options and let the tool randomly pick one for you. Perfect for everyday choices. Everything runs locally in your browser — nothing is uploaded.",
    seoDescription: "Free online Decision Maker \u2014 Can't decide? Enter your options and let the tool randomly pick one for you. Perfect for everyday choices. ",
    dependencies: "None",
    showInCategory: false,
},
  {

    id: "821",
    name: "Yes / No Picker",
    slug: "yes-no-picker",
    category: "Utility",
    description: 'Quick yes/no picker for binary decisions. Randomly picks yes or no with animated reveal. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Yes / No Picker \u2014 Quick yes/no picker for binary decisions. Randomly picks yes or no with animated reveal. ',
    dependencies: "None",
    showInCategory: false,
},
  {

    id: "823",
    name: "Number Guessing Game",
    slug: "number-guessing-game",
    category: "Utility",
    description: 'Guess the random number between 1 and 100. Get hints if your guess is too high or too low. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Number Guessing Game \u2014 Guess the random number between 1 and 100. Get hints if your guess is too high or too low. ',
    dependencies: "None",
},
  {

    id: "824",
    name: "Rock Paper Scissors",
    slug: "rock-paper-scissors",
    category: "Utility",
    description: 'Play rock paper scissors against the computer. Keep track of wins, losses, and ties. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Rock Paper Scissors \u2014 Play rock paper scissors against the computer. Keep track of wins, losses, and ties. ',
    dependencies: "None",
},
  {

    id: "825",
    name: "Hangman Game",
    slug: "hangman-game",
    category: "Utility",
    description: 'Classic hangman word guessing game. Choose letters to reveal the hidden word before the hangman is complete. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Hangman Game \u2014 Classic hangman word guessing game. Choose letters to reveal the hidden word before the hangman is complete. ',
    dependencies: "None",
},
  {
    id: "828",
    name: "Roman Numeral Converter",
    slug: "roman-numeral-converter",
    category: "Converter",
    description: 'Convert between Roman numerals and decimal numbers. Supports standard numeral rules up to 3999. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Roman Numeral Converter \u2014 Convert between Roman numerals and decimal numbers. Supports standard numeral rules up to 3999. ',
    dependencies: "None",
  },
  {

    id: "829",
    name: "Number to Words Converter",
    slug: "number-to-words-converter",
    category: "Utility",
    description: 'Convert any number to its English word representation. Supports large numbers up to billions. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Number to Words Converter \u2014 Convert any number to its English word representation. Supports large numbers up to billions. ',
    dependencies: "None",
},
  {
    id: "831",
    name: "Percentage Difference Calculator",
    slug: "percentage-difference-calculator",
    category: "Calculator",
    description: 'Calculate the percentage difference between any two numbers. Useful for comparing data sets, prices, and measurements. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Percentage Difference Calculator \u2014 Calculate the percentage difference between any two numbers. Useful for comparing data sets, prices, and measurements. ',
    dependencies: "None",
  },
  {
    id: "832",
    name: "Tip Calculator",
    slug: "tip-calculator",
    category: "Finance",
    description: 'Calculate the tip amount and total bill per person. Customize tip percentage and split among any number of people. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Tip Calculator \u2014 Calculate the tip amount and total bill per person. Customize tip percentage and split among any number of people. ',
    dependencies: "None",

  },
  {
    id: "833",
    name: "Sales Tax Calculator",
    slug: "sales-tax-calculator",
    category: "Finance",
    description: 'Calculate total price including sales tax. Enter the pre-tax amount and tax rate to see the exact tax amount and final total. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Sales Tax Calculator \u2014 Calculate total price including sales tax. Enter the pre-tax amount and tax rate to see the exact tax amount and final total. ',
    dependencies: "None",

  },
  {
    id: "834",
    name: "Markup Calculator",
    slug: "markup-calculator",
    category: "Finance",
    description: 'Calculate markup percentage, selling price, and gross profit from cost. Essential for retail pricing and margin analysis. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Markup Calculator \u2014 Calculate markup percentage, selling price, and gross profit from cost. Essential for retail pricing and margin analysis. ',
    dependencies: "None",

  },
  {
    id: "836",
    name: "CAGR Calculator",
    slug: "cagr-calculator",
    category: "Finance",
    description: 'Calculate the Compound Annual Growth Rate (CAGR) for investments. Shows year-by-year growth breakdown. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CAGR Calculator \u2014 Calculate the Compound Annual Growth Rate (CAGR) for investments. Shows year-by-year growth breakdown. ',
    dependencies: "None",

  },
  {
    id: "840",
    name: "Fraction to Decimal Calculator",
    slug: "fraction-to-decimal-calculator",
    category: "Calculator",
    description: 'Convert fractions to decimal numbers. Shows the step-by-step division process. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Fraction to Decimal Calculator \u2014 Convert fractions to decimal numbers. Shows the step-by-step division process. ',
    dependencies: "None",
  },
  {
    id: "841",
    name: "Decimal to Fraction Calculator",
    slug: "decimal-to-fraction-calculator",
    category: "Calculator",
    description: 'Convert decimal numbers to fractions. Handles terminating and repeating decimals with precision. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Decimal to Fraction Calculator \u2014 Convert decimal numbers to fractions. Handles terminating and repeating decimals with precision. ',
    dependencies: "None",
  },
  {
    id: "845",
    name: "Combination Calculator",
    slug: "combination-calculator",
    category: "Calculator",
    description: 'Calculate the number of ways to choose k items from n items (nCr). Includes the formula and step-by-step result. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Combination Calculator \u2014 Calculate the number of ways to choose k items from n items (nCr). Includes the formula and step-by-step result. ',
    dependencies: "None",
  },
  {
    id: "846",
    name: "Permutation Calculator",
    slug: "permutation-calculator",
    category: "Calculator",
    description: 'Calculate the number of ways to arrange k items from n items (nPr). Shows the step-by-step permutation calculation. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Permutation Calculator \u2014 Calculate the number of ways to arrange k items from n items (nPr). Shows the step-by-step permutation calculation. ',
    dependencies: "None",
  },
  {
    id: "847",
    name: "Factorial Calculator",
    slug: "factorial-calculator",
    category: "Calculator",
    description: 'Calculate the factorial of any number (n!). Handles large numbers and shows the full multiplication sequence. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Factorial Calculator \u2014 Calculate the factorial of any number (n!). Handles large numbers and shows the full multiplication sequence. ',
    dependencies: "None",
  },
  {
    id: "848",
    name: "Prime Number Checker",
    slug: "prime-number-checker",
    category: "Calculator",
    description: 'Check if any number is prime. Also shows all factors and whether the number is odd or even. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Prime Number Checker \u2014 Check if any number is prime. Also shows all factors and whether the number is odd or even. ',
    dependencies: "None",
  },
  {
    id: "849",
    name: "Prime Factorization Calculator",
    slug: "prime-factorization-calculator",
    category: "Calculator",
    description: 'Find the prime factors of any number. Shows the complete factorization tree and exponential form. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Prime Factorization Calculator \u2014 Find the prime factors of any number. Shows the complete factorization tree and exponential form. ',
    dependencies: "None",
  },
  {
    id: "850",
    name: "Greatest Common Factor Calculator",
    slug: "greatest-common-factor-calculator",
    category: "Calculator",
    description: 'Calculate the GCF/GCD of two or more numbers. Shows the prime factorization method step by step. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Greatest Common Factor Calculator \u2014 Calculate the GCF/GCD of two or more numbers. Shows the prime factorization method step by step. ',
    dependencies: "None",
  },
  {
    id: "851",
    name: "Least Common Multiple Calculator",
    slug: "least-common-multiple-calculator",
    category: "Calculator",
    description: 'Calculate the LCM of two or more numbers. Shows the prime factorization approach for clarity. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Least Common Multiple Calculator \u2014 Calculate the LCM of two or more numbers. Shows the prime factorization approach for clarity. ',
    dependencies: "None",
  },
  {
    id: "852",
    name: "Modulo Calculator",
    slug: "modulo-calculator",
    category: "Calculator",
    description: 'Calculate the remainder of division (a mod b). Shows quotient, remainder, and the full division expression. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Modulo Calculator \u2014 Calculate the remainder of division (a mod b). Shows quotient, remainder, and the full division expression. ',
    dependencies: "None",
  },
  {
    id: "853",
    name: "Logarithm Calculator",
    slug: "logarithm-calculator",
    category: "Calculator",
    description: 'Calculate logarithms with any base. Supports log base 10, natural log (ln), and custom bases. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Logarithm Calculator \u2014 Calculate logarithms with any base. Supports log base 10, natural log (ln), and custom bases. ',
    dependencies: "None",
  },
  {
    id: "854",
    name: "Trigonometry Calculator",
    slug: "trigonometry-calculator",
    category: "Calculator",
    description: 'Calculate sine, cosine, tangent, and their inverses. Enter an angle in degrees or radians and see all six trig functions. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Trigonometry Calculator \u2014 Calculate sine, cosine, tangent, and their inverses. Enter an angle in degrees or radians and see all six trig functions. ',
    dependencies: "None",
  },
  {
    id: "855",
    name: "Degree / Radian Converter",
    slug: "degree-radian-converter",
    category: "Calculator",
    description: 'Convert between degrees and radians. Shows the formula and step-by-step conversion process. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Degree / Radian Converter \u2014 Convert between degrees and radians. Shows the formula and step-by-step conversion process. ',
    dependencies: "None",
  },
  {
    id: "856",
    name: "Scientific Notation Converter",
    slug: "scientific-notation-converter",
    category: "Calculator",
    description: 'Convert numbers between standard form and scientific notation (E-notation). Handles very large and very small numbers. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Scientific Notation Converter \u2014 Convert numbers between standard form and scientific notation (E-notation). Handles very large and very small numbers. ',
    dependencies: "None",
  },
  {
    id: "857",
    name: "Significant Figures Calculator",
    slug: "significant-figures-calculator",
    category: "Calculator",
    description: 'Round numbers to a specified number of significant figures. Essential for scientific and engineering calculations. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Significant Figures Calculator \u2014 Round numbers to a specified number of significant figures. Essential for scientific and engineering calculations. ',
    dependencies: "None",
  },
  {
    id: "858",
    name: "Rounding Calculator",
    slug: "rounding-calculator",
    category: "Calculator",
    description: 'Round numbers to the nearest whole, tenth, hundredth, thousandth, or decimal places. Shows intermediate rounding steps. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Rounding Calculator \u2014 Round numbers to the nearest whole, tenth, hundredth, thousandth, or decimal places. Shows intermediate rounding steps. ',
    dependencies: "None",
  },
  {
    id: "859",
    name: "Math Equation Solver",
    slug: "math-equation-solver",
    category: "Calculator",
    description: 'Solve linear and quadratic equations. Enter an equation with one variable (x) and see the step-by-step solution. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Math Equation Solver \u2014 Solve linear and quadratic equations. Enter an equation with one variable (x) and see the step-by-step solution. ',
    dependencies: "None",
  },
  {
    id: "860",
    name: "Algebra Calculator",
    slug: "algebra-calculator",
    category: "Calculator",
    description: 'Solve algebraic expressions, evaluate formulas, and simplify expressions. Perfect for homework and quick calculations. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Algebra Calculator \u2014 Solve algebraic expressions, evaluate formulas, and simplify expressions. Perfect for homework and quick calculations. ',
    dependencies: "None",
  },
  {
    id: "861",
    name: "Geometry Calculator",
    slug: "geometry-calculator",
    category: "Calculator",
    description: 'Calculate area, perimeter, and volume for shapes including circle, square, triangle, rectangle, sphere, cylinder, cone, and cube. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Geometry Calculator \u2014 Calculate area, perimeter, and volume for shapes including circle, square, triangle, rectangle, sphere, cylinder, cone, and cube. ',
    dependencies: "None",
  },
  {
    id: "862",
    name: "Coordinate Calculator",
    slug: "coordinate-calculator",
    category: "Calculator",
    description: 'Calculate the distance and midpoint between two points on a 2D coordinate plane. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Coordinate Calculator \u2014 Calculate the distance and midpoint between two points on a 2D coordinate plane. ',
    dependencies: "None",
  },
  {
    id: "863",
    name: "Slope Calculator",
    slug: "slope-calculator",
    category: "Calculator",
    description: 'Calculate the slope, equation, and intercept of a line from two points. Shows the full line equation in y = mx + b form. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Slope Calculator \u2014 Calculate the slope, equation, and intercept of a line from two points. Shows the full line equation in y = mx + b form. ',
    dependencies: "None",
  },
  {
    id: "866",
    name: "Speed Converter",
    slug: "speed-converter",
    category: "Utility",
    description: 'Convert speed between km/h, mph, knots, m/s, and ft/s. Instant conversion for travel and scientific use. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Speed Converter \u2014 Convert speed between km/h, mph, knots, m/s, and ft/s. Instant conversion for travel and scientific use. ',
    dependencies: "None",
  },

  {

    id: "867",
    name: "Length Converter",
    slug: "length-converter",
    category: "Utility",
    description: 'Convert length and distance between km, miles, meters, yards, feet, and inches. Simple and intuitive. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Length Converter \u2014 Convert length and distance between km, miles, meters, yards, feet, and inches. Simple and intuitive. ',
    dependencies: "None",
},
  {

    id: "868",
    name: "Weight Converter",
    slug: "weight-converter",
    category: "Utility",
    description: 'Convert weight between kg, g, lb, oz, and stone. Supports both metric and imperial systems. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Weight Converter \u2014 Convert weight between kg, g, lb, oz, and stone. Supports both metric and imperial systems. ',
    dependencies: "None",
},
  {

    id: "869",
    name: "Volume Converter",
    slug: "volume-converter",
    category: "Utility",
    description: 'Convert volume between liters, mL, gallons, quarts, fl oz, and cups. Handy for cooking, science, and travel. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Volume Converter \u2014 Convert volume between liters, mL, gallons, quarts, fl oz, and cups. Handy for cooking, science, and travel. ',
    dependencies: "None",
},
  {

    id: "870",
    name: "Area Converter",
    slug: "area-converter",
    category: "Utility",
    description: 'Convert area between square meters, square feet, acres, hectares, and square kilometers. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Area Converter \u2014 Convert area between square meters, square feet, acres, hectares, and square kilometers. ',
    dependencies: "None",
},
  {

    id: "871",
    name: "Data Size Converter",
    slug: "data-size-converter",
    category: "Utility",
    description: 'Convert data sizes between bytes, KB, MB, GB, TB, and PB. Understand disk space and file sizes in different units. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Data Size Converter \u2014 Convert data sizes between bytes, KB, MB, GB, TB, and PB. Understand disk space and file sizes in different units. ',
    dependencies: "None",
},
  {
    id: "873",
    name: "Body Fat Estimator",
    slug: "body-fat-calculator",
    category: "Health",
    description: 'Estimate body fat percentage using BMI-based formula adjusted for age and gender. Shows fitness range and category. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Body Fat Estimator \u2014 Estimate body fat percentage using BMI-based formula adjusted for age and gender. Shows fitness range and category. ',
    dependencies: "None",
  },
  {
    id: "874",
    name: "Daily Calorie Needs",
    slug: "calorie-intake-calculator",
    category: "Health",
    description: 'Calculate your daily calorie needs using BMR and activity level. Shows maintenance, cutting, and bulking calorie targets for fitness planning. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Daily Calorie Needs \u2014 Calculate your daily calorie needs using BMR and activity level. Shows maintenance, cutting, and bulking calorie targets for fitness planning. ',
    dependencies: "None",
  },
  {
    id: "875",
    name: "30/40/30 Macro Split",
    slug: "macro-split-calculator",
    category: "Health",
    description: 'Calculate recommended daily protein, carbs, and fat grams based on calorie intake. Follows standard 30/40/30 macro split. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Daily Macronutrients \u2014 Calculate recommended daily protein, carbs, and fat grams based on calorie intake. Follows standard 30/40/30 macro split. ',
    dependencies: "None",
  },
  {
    id: "877",
    name: "Sleep Requirements",
    slug: "sleep-requirement-calculator",
    category: "Health",
    description: 'Get recommended sleep hours based on your age. Follows CDC and National Sleep Foundation guidelines from newborn to senior. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Sleep Requirements \u2014 Get recommended sleep hours based on your age. Follows CDC and National Sleep Foundation guidelines from newborn to senior. ',
    dependencies: "None",
  },
  {
    id: "879",
    name: "Ideal Body Weight",
    slug: "ideal-weight-calc",
    category: "Health",
    description: 'Calculate your ideal body weight using Devine and Robinson formulas. Provides a healthy weight range for your height and gender. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Ideal Body Weight \u2014 Calculate your ideal body weight using Devine and Robinson formulas. Provides a healthy weight range for your height and gender. ',
    dependencies: "None",
  },
  {
    id: "881",
    name: "Steps to Distance",
    slug: "steps-calculator",
    category: "Health",
    description: 'Convert steps walked to distance in km and miles. Also estimates calories burned based on height and step count. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Steps to Distance \u2014 Convert steps walked to distance in km and miles. Also estimates calories burned based on height and step count. ',
    dependencies: "None",
  },
  {
    id: "882",
    name: "Calories Burned Calculator",
    slug: "calories-burned-calculator",
    category: "Health",
    description: 'Estimate calories burned during exercise. Supports running, walking, cycling, swimming, yoga, lifting, and jump rope activities. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Calories Burned Calculator \u2014 Estimate calories burned during exercise. Supports running, walking, cycling, swimming, yoga, lifting, and jump rope activities. ',
    dependencies: "None",
  },
  {
    id: "883",
    name: "Blood Alcohol Estimator",
    slug: "blood-alcohol-calculator",
    category: "Health",
    description: 'Estimate your blood alcohol concentration (BAC) based on drinks consumed, weight, gender, and time elapsed. For educational purposes only. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Blood Alcohol Estimator \u2014 Estimate your blood alcohol concentration (BAC) based on drinks consumed, weight, gender, and time elapsed. For educational purposes only. ',
    dependencies: "None",
  },
  {
    id: "885",
    name: "Ovulation Tracker",
    slug: "ovulation-tracker",
    category: "Health",
    description: 'Track your fertile window and estimated ovulation date based on your last menstrual period. Helps with family planning. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Ovulation Tracker \u2014 Track your fertile window and estimated ovulation date based on your last menstrual period. Helps with family planning. ',
    dependencies: "None",
  },
  {
    id: "887",
    name: "Date Difference Calculator",
    slug: "date-difference-calculator",
    category: "Calculator",
    description: 'Calculate the exact difference between two dates in days, hours, minutes, and seconds. Perfect for project timelines and countdowns. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Date Difference Calculator \u2014 Calculate the exact difference between two dates in days, hours, minutes, and seconds. Perfect for project timelines and countdowns. ',
    dependencies: "None",
  },
  {
    id: "888",
    name: "Date Addition Calculator",
    slug: "date-addition-calculator",
    category: "Calculator",
    description: 'Add or subtract days from any date. Get the resulting date instantly — useful for deadlines, scheduling, and planning. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Date Addition Calculator \u2014 Add or subtract days from any date. Get the resulting date instantly \u2014 useful for deadlines, scheduling, and planning. ',
    dependencies: "None",
  },
  {
    id: "889",
    name: "Week Number Calculator",
    slug: "week-number-calculator",
    category: "Calculator",
    description: 'Find the ISO week number for any date. Also shows the day of the week and the current week of the year. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Week Number Calculator \u2014 Find the ISO week number for any date. Also shows the day of the week and the current week of the year. ',
    dependencies: "None",
  },
  {
    id: "890",
    name: "Time Since Calculator",
    slug: "time-since-calculator",
    category: "Calculator",
    description: 'Calculate the time elapsed between any date and now. Shows results in years, months, weeks, days, hours, minutes, and seconds. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Time Since Calculator \u2014 Calculate the time elapsed between any date and now. Shows results in years, months, weeks, days, hours, minutes, and seconds. ',
    dependencies: "None",
  },
  {

    id: "891",
    name: "Time Zone Converter",
    slug: "time-zone-converter",
    category: "Utility",
    description: 'Convert time between different time zones. Enter a time and your source/target time zones and see the converted result. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Time Zone Converter \u2014 Convert time between different time zones. Enter a time and your source/target time zones and see the converted result. ',
    dependencies: "None",
},
  {
    id: "892",
    name: "DST Checker (US)",
    slug: "daylight-saving-time-checker",
    category: "Calculator",
    description: 'Check when daylight saving time starts and ends in the US for any year. Shows the exact dates and DST period length. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online DST Checker (US) \u2014 Check when daylight saving time starts and ends in the US for any year. Shows the exact dates and DST period length. ',
    dependencies: "None",
  },
  {
    id: "893",
    name: "Work Hours Calculator",
    slug: "work-hours-calculator",
    category: "Calculator",
    description: 'Calculate total work hours between start and end times with a configurable break. Essential for timesheets and payroll. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Work Hours Calculator \u2014 Calculate total work hours between start and end times with a configurable break. Essential for timesheets and payroll. ',
    dependencies: "None",
  },
  {
    id: "894",
    name: "Hours & Minutes Calculator",
    slug: "hours-minutes-calculator",
    category: "Calculator",
    description: 'Add, subtract, and calculate duration between hours and minutes. Perfect for time tracking and scheduling. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Hours & Minutes Calculator \u2014 Add, subtract, and calculate duration between hours and minutes. Perfect for time tracking and scheduling. ',
    dependencies: "None",
  },

  {

    id: "895",
    name: "Minutes to Hours Converter",
    slug: "minutes-to-hours-converter",
    category: "Utility",
    description: 'Convert minutes to hours and minutes format. Also shows the decimal hours equivalent for payroll and billing. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Minutes to Hours Converter \u2014 Convert minutes to hours and minutes format. Also shows the decimal hours equivalent for payroll and billing. ',
    dependencies: "None",
},
  {

    id: "897",
    name: "Seconds to Minutes Converter",
    slug: "seconds-to-minutes-converter",
    category: "Utility",
    description: 'Convert seconds to hours, minutes, and seconds format. Handles large values for video durations, countdowns, and scientific use. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Seconds to Minutes Converter \u2014 Convert seconds to hours, minutes, and seconds format. Handles large values for video durations, countdowns, and scientific use. ',
    dependencies: "None",
},
  {

    id: "898",
    name: "Password Entropy Calculator",
    slug: "password-entropy-calculator",
    category: "Developer",
    description: 'Calculate password entropy in bits to measure password strength against brute-force attacks. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Password Entropy Calculator \u2014 Calculate password entropy in bits to measure password strength against brute-force attacks. ',
    dependencies: "None",
},
  {

    id: "899",
    name: "Two-Factor Auth Generator",
    slug: "two-factor-auth-generator",
    category: "Developer",
    description: 'Generate TOTP URIs for two-factor authentication setup with authenticator apps. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Two-Factor Auth Generator \u2014 Generate TOTP URIs for two-factor authentication setup with authenticator apps. ',
    dependencies: "None",
},
  {

    id: "900",
    name: "Brute Force Time Estimator",
    slug: "brute-force-time-estimator",
    category: "Developer",
    description: 'Estimate the time required to brute-force a password given its length, character set, and hash rate. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Brute Force Time Estimator \u2014 Estimate the time required to brute-force a password given its length, character set, and hash rate. ',
    dependencies: "None",
},
  {

    id: "902",
    name: "Hash Verifier",
    slug: "hash-verifier",
    category: "Developer",
    description: 'Verify that a hash matches a given input to check data integrity. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Hash Verifier \u2014 Verify that a hash matches a given input to check data integrity. ',
    dependencies: "None",
},
  {

    id: "903",
    name: "Hash Password Generator",
    slug: "hash-password-generator",
    category: "Developer",
    description: 'Generate password hashes using PBKDF2-SHA256 with 600,000 iterations for secure password storage. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Hash Password Generator \u2014 Generate password hashes using PBKDF2-SHA256 with 600,000 iterations for secure password storage. ',
    dependencies: "None",
},
  {

    id: "904",
    name: "Content Hash Generator",
    slug: "hash-file-generator",
    category: "Developer",
    description: 'Compute SHA-1, SHA-256, SHA-384, or SHA-512 hashes of text content using the Web Crypto API. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Content Hash Generator \u2014 Compute SHA-1, SHA-256, SHA-384, or SHA-512 hashes of text content using the Web Crypto API. ',
    dependencies: "None",
},
  {

    id: "905",
    name: "HMAC Generator",
    slug: "hmac-generator",
    category: "Developer",
    description: 'Generate HMAC signatures using a secret key and hash algorithm for API authentication. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online HMAC Generator \u2014 Generate HMAC signatures using a secret key and hash algorithm for API authentication. ',
    dependencies: "None",
},
  {

    id: "906",
    name: "SSL/TLS Checker",
    slug: "ssl-tls-checker",
    category: "Developer",
    description: 'Analyze SSL/TLS certificate details including issuer, expiry, and supported protocols. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SSL/TLS Checker \u2014 Analyze SSL/TLS certificate details including issuer, expiry, and supported protocols. ',
    dependencies: "None",
},
  {

    id: "907",
    name: "HTTP Security Checker",
    slug: "http-security-checker",
    category: "Developer",
    description: 'Scan HTTP response headers for security best practices like HSTS, X-Frame-Options, and CSP.',
    seoDescription: 'Free online HTTP Security Checker \u2014 Scan HTTP response headers for security best practices. ',
    dependencies: "None",
},
  {

    id: "909",
    name: "JWT Inspector",
    slug: "jwt-inspector",
    category: "Developer",
    description: 'Deep-inspect JWT tokens with expiry validation, algorithm analysis, and claim details. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JWT Inspector \u2014 Deep-inspect JWT tokens with expiry validation, algorithm analysis, and claim details. ',
    dependencies: "None",
},
  {

    id: "910",
    name: "Content Security Policy Generator",
    slug: "content-security-policy-generator",
    category: "Developer",
    description: 'Build a Content Security Policy header by selecting directives and allowed sources. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Content Security Policy Generator \u2014 Build a Content Security Policy header by selecting directives and allowed sources. ',
    dependencies: "None",
},
  {

    id: "911",
    name: "Subnet Calculator",
    slug: "subnet-calculator",
    category: "Developer",
    description: 'Calculate subnet masks, network addresses, broadcast addresses, and usable host ranges. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Subnet Calculator \u2014 Calculate subnet masks, network addresses, broadcast addresses, and usable host ranges. ',
    dependencies: "None",
},
  {

    id: "912",
    name: "Subnet Visualizer",
    slug: "subnet-visualizer",
    category: "Developer",
    description: 'Visualize IP subnet divisions with a hierarchical tree view for network planning. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Subnet Visualizer \u2014 Visualize IP subnet divisions with a hierarchical tree view for network planning. ',
    dependencies: "None",
},
  {

    id: "912b",
    name: "IPv4 Address Converter",
    slug: "ip-address-converter",
    category: "Developer",
    description: 'Convert IPv4 addresses between dotted decimal, decimal, binary, and hexadecimal formats. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online IPv4 Address Converter \u2014 Convert IPv4 addresses between dotted decimal, decimal, binary, and hexadecimal formats. ',
    dependencies: "None",
},
  {

    id: "912c",
    name: "IP Range Expander",
    slug: "ip-range-expander",
    category: "Developer",
    description: 'Expand an IP address range into a list of individual addresses. Useful for network planning and firewall rules. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online IP Range Expander \u2014 Expand an IP address range into a list of individual addresses. Useful for network planning and firewall rules. ',
    dependencies: "None",
},
  {

    id: "912d",
    name: "IPv6 ULA Generator",
    slug: "ipv6-ula-generator",
    category: "Developer",
    description: 'Generate random IPv6 Unique Local Addresses (ULA) for internal network use. No signup or account required.',
    seoDescription: 'Free online IPv6 ULA Generator \u2014 Generate random IPv6 Unique Local Addresses (ULA) for internal network use. ',
    dependencies: "None",
},
  {

    id: "913",
    name: "DNS Lookup Generator",
    slug: "dns-lookup-generator",
    category: "Developer",
    description: 'Perform DNS lookups for A, AAAA, CNAME, MX, TXT, and NS records. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online DNS Lookup Generator \u2014 Perform DNS lookups for A, AAAA, CNAME, MX, TXT, and NS records. ',
    dependencies: "None",
},
  {

    id: "914",
    name: "CORS Inspector",
    slug: "cors-inspector",
    category: "Developer",
    description: 'Analyze CORS headers to identify cross-origin request configuration issues. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CORS Inspector \u2014 Analyze CORS headers to identify cross-origin request configuration issues. ',
    dependencies: "None",
},
  {

    id: "915",
    name: "CORS Header Generator",
    slug: "cors-header-generator",
    category: "Developer",
    description: 'Generate CORS headers for your API by configuring allowed origins, methods, and headers.',
    seoDescription: 'Free online CORS Header Generator \u2014 Generate CORS headers by configuring allowed origins, methods, and headers. ',
    dependencies: "None",
},
  {

    id: "916",
    name: "Env File Generator",
    slug: "env-file-generator",
    category: "Developer",
    description: 'Generate .env file templates with configurable variable names and default values. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Env File Generator \u2014 Generate .env file templates with configurable variable names and default values. ',
    dependencies: "None",
},
  {

    id: "917",
    name: "Env File Parser",
    slug: "env-file-parser",
    category: "Developer",
    description: 'Parse and validate .env files to detect missing variables, syntax errors, and duplicates. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Env File Parser \u2014 Parse and validate .env files to detect missing variables, syntax errors, and duplicates. ',
    dependencies: "None",
},
  {

    id: "918",
    name: "CVE Lookup",
    slug: "cve-lookup",
    category: "Developer",
    description: 'Look up Common Vulnerabilities and Exposures (CVE) by ID or keyword search. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CVE Lookup \u2014 Look up Common Vulnerabilities and Exposures (CVE) by ID or keyword search. ',
    dependencies: "None",
},
  {

    id: "919",
    name: "SQL Injection Detector",
    slug: "sql-injection-detector",
    category: "Developer",
    description: 'Analyze SQL queries for common injection patterns and parameterization issues. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SQL Injection Detector \u2014 Analyze SQL queries for common injection patterns and parameterization issues. ',
    dependencies: "None",
},
  {

    id: "920",
    name: "XSS Protection Checker",
    slug: "xss-protection-checker",
    category: "Developer",
    description: 'Scan HTML/JavaScript code for reflected, stored, and DOM-based XSS vulnerabilities.',
    seoDescription: 'Free online XSS Protection Checker \u2014 Scan HTML/JavaScript for reflected, stored, and DOM-based XSS vulnerabilities. ',
    dependencies: "None",
},
  {

    id: "921",
    name: "CSRF Token Generator",
    slug: "csrf-token-generator",
    category: "Developer",
    description: 'Generate cryptographically secure CSRF tokens with configurable length and encoding. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSRF Token Generator \u2014 Generate cryptographically secure CSRF tokens with configurable length and encoding. ',
    dependencies: "None",
},
  {

    id: "922",
    name: "OAuth2 Debugger",
    slug: "oauth2-debugger",
    category: "Developer",
    description: 'Debug and decode OAuth2 tokens, authorization codes, and refresh token flows. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online OAuth2 Debugger \u2014 Debug and decode OAuth2 tokens, authorization codes, and refresh token flows. ',
    dependencies: "None",
},
  {

    id: "923",
    name: "SAML Decoder",
    slug: "saml-decoder",
    category: "Developer",
    description: 'Decode and inspect SAML assertions and responses for SSO troubleshooting. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SAML Decoder \u2014 Decode and inspect SAML assertions and responses for SSO troubleshooting. ',
    dependencies: "None",
},
  {

    id: "924",
    name: "CSP Policy Validator",
    slug: "csp-policy-validator",
    category: "Developer",
    description: 'Validate Content Security Policy headers against W3C spec and common pitfalls. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSP Policy Validator \u2014 Validate Content Security Policy headers against W3C spec and common pitfalls. ',
    dependencies: "None",
},
  {

    id: "925",
    name: "TLS Cipher Checker",
    slug: "tls-cipher-checker",
    category: "Developer",
    description: 'Check which TLS ciphers and protocol versions are supported by a server.',
    seoDescription: 'Free online TLS Cipher Checker \u2014 Check which TLS ciphers and protocol versions are supported. ',
    dependencies: "None",
},
  {

    id: "926",
    name: "IP Reputation Checker",
    slug: "ip-reputation-checker",
    category: "Developer",
    description: 'Check an IP address against known threat intelligence and blacklist databases. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online IP Reputation Checker \u2014 Check an IP address against known threat intelligence and blacklist databases. ',
    dependencies: "None",
},
  {

    id: "927",
    name: "URL Sanitizer",
    slug: "url-sanitizer",
    category: "Developer",
    description: 'Sanitize URLs by removing tracking parameters and normalizing the URL structure. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online URL Sanitizer \u2014 Sanitize URLs by removing tracking parameters and normalizing the URL structure. ',
    dependencies: "None",
},
  {

    id: "928",
    name: "SSL Certificate Decoder",
    slug: "ssl-certificate-decoder",
    category: "Developer",
    description: 'Decode and view SSL certificate details including subject, issuer, and validity period. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SSL Certificate Decoder \u2014 Decode and view SSL certificate details including subject, issuer, and validity period. ',
    dependencies: "None",
},
  {

    id: "929",
    name: "Subdomain Finder",
    slug: "subdomain-finder",
    category: "Developer",
    description: 'Discover subdomains for a given domain using common wordlists and patterns. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Subdomain Finder \u2014 Discover subdomains for a given domain using common wordlists and patterns. ',
    dependencies: "None",
},
  {

    id: "930",
    name: "Email Validator",
    slug: "email-format-validator",
    category: "Developer",
    description: 'Validate email addresses for correct format, disposable domains, and MX record existence. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Email Validator \u2014 Validate email addresses for correct format, disposable domains, and MX record existence. ',
    dependencies: "None",
},
  {

    id: "931",
    name: "Validator",
    slug: "syntax-validator",
    category: "Developer",
    description: 'Validate code syntax across multiple languages including JSON, XML, and JavaScript. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Syntax Validator \u2014 Validate code syntax across multiple languages including JSON, XML, and JavaScript. ',
    dependencies: "None",
},
  {

    id: "932",
    name: "YAML Syntax Validator",
    slug: "yaml-syntax-validator",
    category: "Developer",
    description: 'Validate YAML syntax, check for indentation errors, and preview the parsed structure. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online YAML Validator \u2014 Validate YAML syntax, check for indentation errors, and preview the parsed structure. ',
    dependencies: "None",
},
  {
    id: "933",
    name: "Annual Contract Value Calculator",
    slug: "acv-calculator",
    category: "Growth & Marketing",
    description: 'Calculate Annual Contract Value (ACV) by dividing total contract value by the contract term in years.',
    seoDescription: 'Free online Annual Contract Value (ACV) Calculator \u2014 Calculate ACV by dividing total contract value by the contract term in years. ',
    dependencies: "None",

  },
  {
    id: "934",
    name: "ASCII Table Generator",
    slug: "ascii-table-generator",
    category: "Text",
    description: 'Generate clean ASCII art tables from CSV, TSV, or pipe-delimited data. Configurable header alignment, border styles, column padding, and export options for documentation, code comments, and terminal output.',
    seoDescription: 'Free online ASCII Table Generator — Generate clean ASCII art tables from CSV, TSV, or delimited data. Customizable borders, alignment, and padding for code comments, docs, and terminal output.',
    dependencies: "None",
  },
  {

    id: "935",
    name: "Git Commit Linter",
    slug: "git-commit-linter",
    category: "Developer",
    description: 'Validate git commit messages against the Conventional Commits specification. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Git Commit Linter \u2014 Validate git commit messages against the Conventional Commits specification. ',
    dependencies: "None",
},
  {

    id: "936",
    name: ".gitignore Generator",
    slug: "gitignore-generator",
    category: "Developer",
    description: 'Generate .gitignore files by selecting languages, frameworks, and tools from a checklist.',
    seoDescription: 'Free online .gitignore Generator \u2014 Generate .gitignore files by selecting languages, frameworks, and tools. ',
    dependencies: "None",
},
  {

    id: "937",
    name: "Hours to Minutes Converter",
    slug: "hours-to-minutes-converter",
    category: "Utility",
    description: 'Convert hours and minutes to total minutes for time tracking and scheduling. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Hours to Minutes Converter \u2014 Convert hours and minutes to total minutes for time tracking and scheduling. ',
    dependencies: "None",
},
  {
    id: "939",
    name: "SaaS Payback Period",
    slug: "saas-payback-period",
    category: "Growth & Marketing",
    description: 'Calculate SaaS customer payback period by dividing CAC by monthly revenue per customer.',
    seoDescription: 'Free online SaaS Payback Period Calculator \u2014 Calculate payback period by dividing CAC by monthly revenue per customer. ',
    dependencies: "None",

  },
  {
    id: "940",
    name: "SaaS Quick Ratio",
    slug: "saas-quick-ratio",
    category: "Growth & Marketing",
    description: 'Calculate SaaS Quick Ratio from new, expansion, reactivation, churned, and contraction MRR.',
    seoDescription: 'Free online SaaS Quick Ratio Calculator \u2014 Calculate Quick Ratio from new, expansion, reactivation, churned, and contraction MRR. ',
    dependencies: "None",

  },
  {
    id: "941",
    name: "SaaS Rule of 40",
    slug: "saas-rule-of-40",
    category: "Growth & Marketing",
    description: 'Calculate the Rule of 40 score by combining revenue growth rate and profit margin. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SaaS Rule of 40 Calculator \u2014 Calculate the Rule of 40 score by combining revenue growth rate and profit margin. ',
    dependencies: "None",

  },
  {

    id: "942",
    name: "Swift Formatter",
    slug: "swift-formatter",
    category: "Developer",
    description: 'Formats Swift source code with proper indentation, spacing, and bracing style for readable iOS and macOS development.',
    seoDescription: 'Free online Swift Formatter \u2014 Format Swift source code with proper indentation and spacing for readability. ',
    dependencies: "None",
},
  {
    id: "943",
    name: "Temperature Converter",
    slug: "temperature-converter",
    category: "Converter",
    description: 'Convert temperatures between Celsius, Fahrenheit, and Kelvin scales instantly. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Temperature Converter \u2014 Convert temperatures between Celsius, Fahrenheit, and Kelvin scales instantly. ',
    dependencies: "None",
  },
  {
    id: "945",
    name: "PDF to TXT",
    slug: "pdf-to-txt",
    category: "PDF",
    description: 'Extract plain text from PDF files with estimated output size. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online PDF to TXT Extractor \u2014 Extract plain text from PDF files with estimated output size. ',
    dependencies: "None",
  },
  {

    id: "946",
    name: "CSV to SQLite Web Terminal",
    slug: "csv-to-sqlite",
    category: "Developer",
    description: 'Import CSV data directly into a SQLite database. Run SQL queries, filter rows, and export results.',
    seoDescription: 'Free online CSV to SQLite Converter \u2014 Import CSV data into a SQLite database, run SQL queries, and export results directly in your browser.',
    dependencies: "sql.js",
},
  {
    id: "947",
    name: "Vector Pen Canvas",
    slug: "vector-pen-canvas",
    category: "Design",
    description: 'A freeform vector drawing tool with freehand pen, shapes (rectangle, ellipse, line), multi-page canvas, color picker, and SVG/PNG export. Draw diagrams and illustrations entirely in your browser.',
    seoDescription: 'Free online Vector Pen Canvas \u2014 Draw vector graphics with freehand pen, shapes, and multi-page canvas. Export as SVG or PNG.',
    dependencies: "fabric.js",
  },
  {

    id: "956",
    name: "AES Encrypt",
    slug: "aes-encrypt",
    category: "Developer",
    description: 'Encrypt text using AES symmetric encryption with a passphrase. Generate ciphertext that can be safely transmitted or stored. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online AES Encrypt — Encrypt text using AES symmetric encryption with a passphrase. Generate ciphertext that can be safely transmitted or stored. ',
    dependencies: "CryptoJS",
},
  {

    id: "957",
    name: "AES Decrypt",
    slug: "aes-decrypt",
    category: "Developer",
    description: 'Decrypt AES-encrypted ciphertext back to plain text using the original passphrase. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online AES Decrypt — Decrypt AES-encrypted ciphertext back to plain text using the original passphrase. ',
    dependencies: "CryptoJS",
    showInCategory: false,
},
  {

    id: "958",
    name: "HTTP Header Analyzer",
    slug: "http-header-analyzer",
    category: "Developer",
    description: 'Analyze HTTP request and response headers — detect security headers, review formatting, and inspect value structure. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online HTTP Header Analyzer — Analyze HTTP request and response headers — detect security headers, review formatting, and inspect value structure. ',
    dependencies: "None",
},
  {

    id: "959",
    name: "HTTP Headers Generator",
    slug: "http-headers-generator",
    category: "Developer",
    description: 'Generate common HTTP headers for JSON, REST, and GraphQL APIs with correct Content-Type and authorization patterns. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online HTTP Headers Generator — Generate common HTTP headers for JSON, REST, and GraphQL APIs with correct Content-Type and authorization patterns. ',
    dependencies: "None",
},
  {

    id: "960",
    name: "HTTP Cache Header Generator",
    slug: "http-cache-header-generator",
    category: "Developer",
    description: 'Generate Cache-Control directives with configurable max-age, scope, must-revalidate, and no-transform options. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online HTTP Cache Header Generator — Generate Cache-Control directives with configurable max-age, scope, must-revalidate, and no-transform options. ',
    dependencies: "None",
},
  {

    id: "961",
    name: "HTTP Status Code Checker",
    slug: "http-status-code-checker",
    category: "Developer",
    description: 'Look up HTTP status codes by number — view description, label, and response class (informational, success, redirect, client error, server error).',
    seoDescription: 'Free online HTTP Status Code Checker — Look up HTTP status codes by number — view description, label, and response class. ',
    dependencies: "None",
},
  {

    id: "962",
    name: "ESLint Config Generator",
    slug: "eslint-config-generator",
    category: "Developer",
    description: 'Generate ESLint configuration presets for React, Node.js, TypeScript, and Next.js projects with recommended rules. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online ESLint Config Generator — Generate ESLint configuration presets for React, Node.js, TypeScript, and Next.js projects with recommended rules. ',
    dependencies: "None",
},
  {

    id: "963",
    name: "HTTP Retry Policy Builder",
    slug: "http-retry-policy-builder",
    category: "Developer",
    description: 'Build HTTP retry policies with exponential backoff, fixed delay, or circuit breaker strategies for resilient API clients. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online HTTP Retry Policy Builder — Build HTTP retry policies with exponential backoff, fixed delay, or circuit breaker strategies for resilient API clients. ',
    dependencies: "None",
},
  {
    id: "964",
    name: "Triangle Area Calculator",
    slug: "triangle-area-calculator",
    category: "Calculator",
    description: 'Calculate the area of a triangle given base and height using the formula 0.5 × base × height. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Triangle Area Calculator — Calculate the area of a triangle given base and height using the formula 0.5 × base × height. ',
    dependencies: "None",
  },
  {
    id: "965",
    name: "Gas Mileage Calculator",
    slug: "gas-mileage-calculator",
    category: "Calculator",
    description: 'Calculate fuel economy in MPG (miles per gallon) from distance driven and fuel consumed. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Gas Mileage Calculator — Calculate fuel economy in MPG (miles per gallon) from distance driven and fuel consumed. ',
    dependencies: "None",
  },
  {
    id: "966",
    name: "Calorie Tracker",
    slug: "calorie-tracker",
    category: "Health",
    description: 'Log your daily food intake with a built-in common foods database. Track total calories consumed throughout the day. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Calorie Tracker — Log your daily food intake with a built-in common foods database. Track total calories consumed throughout the day. ',
    dependencies: "None",
  },
  {
    id: "967",
    name: "Waist-to-Hip Ratio Calculator",
    slug: "waist-to-hip-ratio-calculator",
    category: "Health",
    description: 'Calculate your waist-to-hip ratio and assess health risk based on your measurements and gender. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Waist-to-Hip Ratio Calculator — Calculate your waist-to-hip ratio and assess health risk based on your measurements and gender. ',
    dependencies: "None",
  },
  {

    id: "969",
    name: "TSV ↔ CSV Converter",
    slug: "tsv-csv-converter",
    category: "Converter",
    description: 'Bidirectional converter between tab-separated values (TSV) and comma-separated values (CSV) with proper quoting. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online TSV ↔ CSV Converter — Bidirectional converter between tab-separated values (TSV) and comma-separated values (CSV) with proper quoting. ',
    dependencies: "None",
},
  {
    id: "970",
    name: "JSON → Toon Converter",
    slug: "json-toon-converter",
    category: "Converter",
    description: 'Convert JSON objects into a human-readable Toon format using → arrows instead of colons. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JSON → Toon Converter — Convert JSON objects into a human-readable Toon format using → arrows instead of colons. ',
    dependencies: "None",
  },
  {

    id: "971",
    name: "CSV Data Cleaner",
    slug: "csv-data-cleaner",
    category: "Converter",
    description: 'Clean CSV data by trimming whitespace, removing empty rows, deduplicating, and applying column-aware transforms (email lowercasing, phone digit-stripping, note normalizing). Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSV Data Cleaner — Clean CSV data by trimming whitespace, removing empty rows, deduplicating, and applying column-aware transforms (email lowercasing, phone digit-stripping, note normalizing). ',
    dependencies: "None",
},
  {

    id: "972",
    name: "CSV Statistics",
    slug: "csv-statistics",
    category: "Converter",
    description: 'Compute per-column statistics for CSV data including count, sum, average, min, max for numeric columns. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSV Statistics — Compute per-column statistics for CSV data including count, sum, average, min, max for numeric columns. ',
    dependencies: "None",
},
  {
    id: "973",
    name: "CSV ↔ HTML Table Converter",
    slug: "csv-html-table-converter",
    category: "Converter",
    description: 'Bidirectional converter between CSV data and HTML table markup with live preview. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSV ↔ HTML Table Converter — Bidirectional converter between CSV data and HTML table markup with live preview. ',
    dependencies: "None",
  },
  {

    id: "974",
    name: "YAML Validator",
    slug: "yaml-validator",
    category: "Developer",
    description: 'Validate YAML formatting, detect indentation issues, convert YAML to JSON, and minify YAML comments. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online YAML Validator — Validate YAML formatting, detect indentation issues, convert YAML to JSON, and minify YAML comments. ',
    dependencies: "None",
},
  {
    id: "975",
    name: "Duplicate Word Remover",
    slug: "duplicate-word-remover",
    category: "Text",
    description: 'Remove duplicate words from text while preserving the first occurrence and original word order. Leaves line structure intact — only targets repeated words, not lines.',
    seoDescription: 'Free online Duplicate Word Remover — Remove repeated words from text while preserving first occurrence and original order. Keeps line structure intact. Instant local processing.',
    dependencies: "None",
  },
  {
    id: "976",
    name: "Text Cleaner",
    slug: "text-cleaner",
    category: "Text",
    description: 'Normalize whitespace, trim trailing spaces, remove excess newlines, strip empty lines, and clean up messy text with one click. Handles mixed line endings and irregular spacing.',
    seoDescription: 'Free online Text Cleaner — Normalize whitespace, trim trailing spaces, remove excess newlines, strip empty lines, and fix messy text with one click. Handles mixed line endings.',
    dependencies: "None",
  },
  {
    id: "977",
    name: "Text Splitter",
    slug: "text-splitter",
    category: "Text",
    description: 'Split text by any delimiter (comma, space, tab, newline, or custom) and view numbered parts. Essential for parsing CSV data, extracting fields, and breaking structured text into components.',
    seoDescription: 'Free online Text Splitter — Split text by any delimiter (comma, space, tab, newline, or custom) and view numbered parts. Parse CSV data, extract fields, and break structured text into components.',
    dependencies: "None",
  },
  {

    id: "978",
    name: "Trailing Space Remover",
    slug: "trailing-space-remover",
    category: "Developer",
    description: 'Remove trailing whitespace from every line in your text. Essential for code cleanup and formatting.',
    seoDescription: 'Free online Trailing Space Remover — Remove trailing whitespace from every line. Essential for code cleanup and formatting. ',
    dependencies: "None",
},
  {
    id: "979",
    name: "Canonical URL Checker",
    slug: "canonical-url-checker",
    category: "SEO",
    description: 'Validate canonical URLs — check protocol, domain, path, query parameters, fragments, trailing slash, and www prefix for SEO best practices.',
    seoDescription: 'Free online Canonical URL Checker — Validate canonical URLs for SEO. Checks protocol, domain, path, query params, fragments, trailing slash, and www prefix. ',
    dependencies: "None",
  },
  {
    id: "980",
    name: "Breadcrumb Schema Generator",
    slug: "breadcrumb-schema-generator",
    category: "SEO",
    description: 'Generate JSON-LD BreadcrumbList structured data from a list of page names and URLs. Add breadcrumb schema to your website for better SEO.',
    seoDescription: 'Free online Breadcrumb Schema Generator — Generate JSON-LD BreadcrumbList structured data from page names and URLs for better SEO. ',
    dependencies: "None",
  },
  {
    id: "981",
    name: "UTM Builder",
    slug: "utm-builder",
    category: "SEO",
    description: 'Build campaign tracking URLs with utm_source, utm_medium, utm_campaign, utm_term, and utm_content parameters. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online UTM Builder — Build campaign tracking URLs with utm_source, utm_medium, utm_campaign, utm_term, and utm_content parameters. ',
    dependencies: "None",
  },
  {

    id: "982",
    name: "Port Number Lookup",
    slug: "port-number-lookup",
    category: "Developer",
    description: 'Look up service names for TCP/UDP port numbers — well-known (0-1023), registered (1024-49151), and dynamic/private (49152-65535) ranges. Includes 25+ common services.',
    seoDescription: 'Free online Port Number Lookup — Look up service names for TCP/UDP port numbers with 25+ common services. Well-known, registered, and dynamic ranges. ',
    dependencies: "None",
},
  {

    id: "983",
    name: "User-Agent Parser",
    slug: "user-agent-parser",
    category: "Developer",
    description: 'Parse browser, operating system, and version from any User-Agent string. Detects Chrome, Firefox, Safari, Edge, and the client OS from request headers.',
    seoDescription: 'Free online User-Agent Parser — Parse browser, operating system, and version from any User-Agent string. Detects Chrome, Firefox, Safari, and Edge. ',
    dependencies: "None",
},
  {

    id: "984",
    name: "Query String Parser",
    slug: "query-string-parser",
    category: "Developer",
    description: 'Parse and inspect URL query parameters as structured key-value pairs. Decodes URL-encoded values and displays them in a readable JSON format.',
    seoDescription: 'Free online Query String Parser — Parse and inspect URL query parameters as structured key-value pairs. Decodes URL-encoded values. ',
    dependencies: "None",
},
  {

    id: "985",
    name: "SSE Event Formatter",
    slug: "sse-event-formatter",
    category: "Developer",
    description: 'Parse and visualize Server-Sent Events (SSE) streams into structured data. Formats event fields including data, event, id, and retry directives.',
    seoDescription: 'Free online SSE Event Formatter — Parse and visualize Server-Sent Events (SSE) streams into structured data. Formats event, data, id, and retry fields. ',
    dependencies: "None",
},
];
