import type { ToolMetadata } from './tools-types';

export const entries_chunk_3: ToolMetadata[] = [
  {
    id: "548e",
    name: "Nginx Config Generator",
    slug: "nginx-config-generator",
    category: "Developer",
    description: 'Generate Nginx server block configurations from directive lists.',
    seoDescription: 'Free online Nginx Config Generator \u2014 Generate Nginx server blocks from directive lists. ',
    dependencies: "None",
  },
  {
    id: "548f",
    name: "IP Allowlist Generator",
    slug: "ip-allowlist-generator",
    category: "Developer",
    description: 'Generate Nginx allow/deny rules from a list of CIDR ranges.',
    seoDescription: 'Free online IP Allowlist Generator \u2014 Generate Nginx allow/deny rules from CIDR ranges. ',
    dependencies: "None",
  },
  {
    id: "549a",
    name: "INI to JSON Converter",
    slug: "ini-json-converter",
    category: "Developer",
    description: 'Convert INI configs to JSON. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online INI to JSON Converter \u2014 Convert INI configs to JSON. ',
    dependencies: "None",
        },
  {
    id: "549b",
    name: "MessagePack Inspector",
    slug: "msgpack-inspector",
    category: "Developer",
    description: 'Simulate MessagePack encoding by inspecting JSON as UTF-8 bytes and hex.',
    seoDescription: 'Free online MessagePack Inspector \u2014 Simulate MessagePack encoding from JSON. ',
    dependencies: "None",
  },
  {
    id: "549c",
    name: "CBOR Inspector",
    slug: "cbor-inspector",
    category: "Developer",
    description: 'Simulate CBOR encoding by inspecting JSON as UTF-8 bytes with major type analysis.',
    seoDescription: 'Free online CBOR Inspector \u2014 Simulate CBOR encoding from JSON. ',
    dependencies: "None",
  },
  {
    id: "549d",
    name: "Data Anonymizer",
    slug: "data-anonymizer",
    category: "Developer",
    description: 'Anonymize emails, phone numbers, and IP addresses in text by replacing them with placeholders.',
    seoDescription: 'Free online Data Anonymizer \u2014 Anonymize emails, phones, and IPs in text. ',
    dependencies: "None",
  },
  {
    id: "549e",
    name: "Code to cURL Converter",
    slug: "code-to-curl-converter",
    category: "Developer",
    description: 'Convert fetch/axios code to cURL. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Code to cURL Converter \u2014 Convert fetch/axios code to cURL. ',
    dependencies: "None",
        },
  {
    id: "549f",
    name: "cURL to Code Converter",
    slug: "curl-to-code-converter",
    category: "Developer",
    description: 'Convert cURL commands to fetch(). Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online cURL to Code Converter \u2014 Convert cURL commands to fetch(). ',
    dependencies: "None",
  },
  {
    id: "549g",
    name: "JSON-RPC Builder",
    slug: "jsonrpc-builder",
    category: "Developer",
    description: 'Build JSON-RPC 2.0 request objects with method, params, and auto-generated ID.',
    seoDescription: 'Free online JSON-RPC Builder \u2014 Build JSON-RPC 2.0 request objects. ',
    dependencies: "None",
  },
  {
    id: "549h",
    name: "HAR File Analyzer",
    slug: "har-analyzer",
    category: "Developer",
    description: 'Analyze HAR files to see entry count, total size, total time, and URLs.',
    seoDescription: 'Free online HAR File Analyzer \u2014 Analyze HAR files for size, time, and URLs. ',
    dependencies: "None",
  },
  {
    id: "549i",
    name: "Log File Analyzer",
    slug: "log-analyzer",
    category: "Developer",
    description: 'Count log lines by level (ERROR, INFO, WARN, DEBUG, etc.).',
    seoDescription: 'Free online Log File Analyzer \u2014 Count log lines by level. ',
    dependencies: "None",
  },
  {
    id: "549j",
    name: "package.json Validator",
    slug: "package-json-validator",
    category: "Developer",
    description: 'Validate package.json for required fields, semver format, and dependency presence.',
    seoDescription: 'Free online package.json Validator \u2014 Validate name, version, scripts, and dependencies. ',
    dependencies: "None",
  },
  {
    id: "549k",
    name: "MIME Type Finder",
    slug: "mime-finder",
    category: "Developer",
    description: 'Look up MIME types for common file extensions.',
    seoDescription: 'Free online MIME Type Finder \u2014 Look up MIME types for file extensions. ',
    dependencies: "None",
  },
  {
    id: "551a",
    name: "CIDR Calculator",
    slug: "cidr-calculator",
    category: "Developer",
    description: 'Calculate CIDR subnet ranges — network address, broadcast, first/last host, total hosts, and netmask.',
    seoDescription: 'Free online CIDR Calculator \u2014 Calculate subnet ranges, broadcast addresses, and host counts from CIDR notation. ',
    dependencies: "None",
  },
  {
    id: "551b",
    name: "AWS IAM Policy Analyzer",
    slug: "aws-iam-policy-analyzer",
    category: "Utility",
    description: 'Paste an AWS IAM policy JSON to check for wildcard resources, overly broad actions, and full admin access.',
    seoDescription: 'Free online AWS IAM Policy Analyzer \u2014 Check IAM policies for wildcard resources, overly broad actions, and admin access. ',
    dependencies: "None",
  },
  {
    id: "553a",
    name: "SCSS to CSS Converter",
    slug: "scss-to-css-converter",
    category: "Developer",
    description: 'Convert SCSS variables and nesting to plain CSS. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online SCSS to CSS Converter \u2014 Convert SCSS variables and nesting to plain CSS. ',
    dependencies: "None",
        },
  {
    id: "553b",
    name: "Stylus to CSS Converter",
    slug: "stylus-to-css-converter",
    category: "Developer",
    description: 'Convert Stylus syntax to plain CSS. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Stylus to CSS Converter \u2014 Convert Stylus syntax to plain CSS. ',
    dependencies: "None",
        },
  {
    id: "553c",
    name: "Tailwind to CSS Converter",
    slug: "tailwind-to-css-converter",
    category: "Developer",
    description: 'Convert Tailwind utility classes to plain CSS. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Tailwind to CSS Converter \u2014 Convert Tailwind utility classes to plain CSS. ',
    dependencies: "None",
        },
  {
    id: "553d",
    name: "Proto Schema Converter",
    slug: "proto-schema-converter",
    category: "Developer",
    description: 'Convert Protobuf message definitions to TypeScript interfaces and JSON samples.',
    seoDescription: 'Free online Proto Schema Converter \u2014 Convert Protobuf to TypeScript and JSON. ',
    dependencies: "None",
  },
  {
    id: "553e",
    name: "Protobuf Decoder",
    slug: "protobuf-decoder",
    category: "Developer",
    description: 'Decode raw protobuf hex bytes to readable text.',
    seoDescription: 'Free online Protobuf Decoder \u2014 Decode raw protobuf hex bytes to text. ',
    dependencies: "None",
  },
  {
    id: "553f",
    name: "tsconfig Analyzer",
    slug: "tsconfig-analyzer",
    category: "Developer",
    description: 'Parse and describe each option in a tsconfig.json file.',
    seoDescription: 'Free online tsconfig Analyzer \u2014 Parse and describe tsconfig.json options. ',
    dependencies: "None",
  },
  {
    id: "553g",
    name: "TypeScript Formatter",
    slug: "typescript-formatter",
    category: "Developer",
    description: 'Auto-format TypeScript code with consistent indentation and line breaks.',
    seoDescription: 'Free online TypeScript Formatter \u2014 Auto-format TypeScript with consistent indentation. ',
    dependencies: "None",
  },
  {
    id: "553h",
    name: "String Template Tester",
    slug: "string-template-tester",
    category: "Developer",
    description: 'Test string templates with {{variable}} placeholders against JSON variables.',
    seoDescription: 'Free online String Template Tester \u2014 Test {{variable}} templates with JSON data. ',
    dependencies: "None",
  },
  {
    id: "553i",
    name: "Test Data Generator",
    slug: "test-data-generator",
    category: "Developer",
    description: 'Generate test data objects from a schema defining field names and types.',
    seoDescription: 'Free online Test Data Generator \u2014 Generate test data from field name/type schemas. ',
    dependencies: "None",
  },
  {
    id: "601",
    name: "Mortgage Calculator",
    slug: "mortgage-calculator",
    category: "Finance",
    description: 'Calculate monthly mortgage payments with amortization schedule. Enter loan amount, interest rate, and term to see total interest paid. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Mortgage Calculator — Calculate monthly mortgage payments with amortization schedule. Enter loan amount, interest rate, and term to see total interest paid. ',
    dependencies: "None",
  },
  {
    id: "602",
    name: "ARR Calculator",
    slug: "arr-calculator",
    category: "Finance",
    description: 'Calculate Annual Recurring Revenue from subscription revenue, expansion revenue, and churn. Essential for SaaS businesses tracking growth. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online ARR Calculator — Calculate Annual Recurring Revenue from subscription revenue, expansion revenue, and churn. Essential for SaaS businesses tracking growth. ',
    dependencies: "None",
  },
  {
    id: "603",
    name: "Compound Interest Calculator",
    slug: "compound-interest-calculator",
    category: "Finance",
    description: 'Calculate compound interest with regular contributions. See how your money grows over time with different compounding frequencies. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Compound Interest Calculator — Calculate compound interest with regular contributions. See how your money grows over time with different compounding frequencies. ',
    dependencies: "None",
  },
  {
    id: "605",
    name: "Car Loan Calculator",
    slug: "car-loan-calculator",
    category: "Finance",
    description: 'Calculate monthly car loan payments, total interest, and total cost. Enter loan amount, rate, and term for a complete auto financing picture. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Car Loan Calculator — Calculate monthly car loan payments, total interest, and total cost. Enter loan amount, rate, and term for a complete auto financing picture. ',
    dependencies: "None",
  },
  {
    id: "606",
    name: "Car Lease Calculator",
    slug: "car-lease-calculator",
    category: "Finance",
    description: 'Calculate monthly lease payments using capitalized cost, residual value, term, and money factor. Compare lease vs buy for your next vehicle. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Car Lease Calculator — Calculate monthly lease payments using capitalized cost, residual value, term, and money factor. Compare lease vs buy for your next vehicle. ',
    dependencies: "None",
  },
  {
    id: "607",
    name: "Churn Rate Calculator",
    slug: "churn-rate-calculator",
    category: "Finance",
    description: 'Calculate customer churn rate by dividing customers lost by total customers. Monitor retention health for your subscription business. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Churn Rate Calculator — Calculate customer churn rate by dividing customers lost by total customers. Monitor retention health for your subscription business. ',
    dependencies: "None",
  },
  {
    id: "609",
    name: "Debt Payoff Calculator",
    slug: "debt-payoff-calculator",
    category: "Finance",
    description: 'Calculate how long it will take to pay off debt with monthly payments. See total interest paid and create a payoff plan. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Debt Payoff Calculator — Calculate how long it will take to pay off debt with monthly payments. See total interest paid and create a payoff plan. ',
    dependencies: "None",
  },
  {
    id: "610",
    name: "Discount Calculator",
    slug: "discount-calculator",
    category: "Finance",
    description: 'Calculate savings and final price after a percentage discount. Perfect for shopping, sales, and budget planning. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Discount Calculator — Calculate savings and final price after a percentage discount. Perfect for shopping, sales, and budget planning. ',
    dependencies: "None",
  },
  {
    id: "611",
    name: "Hourly to Salary Calculator",
    slug: "hourly-to-salary-calculator",
    category: "Finance",
    description: 'Convert hourly wage to annual salary. Enter hourly rate and hours per week to see your projected yearly income. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Hourly to Salary Calculator — Convert hourly wage to annual salary. Enter hourly rate and hours per week to see your projected yearly income. ',
    dependencies: "None",
  },
  {
    id: "612",
    name: "Inflation Calculator",
    slug: "inflation-calculator",
    category: "Finance",
    description: 'Calculate the future value of money adjusted for inflation. See how purchasing power changes over time with different inflation rates. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Inflation Calculator — Calculate the future value of money adjusted for inflation. See how purchasing power changes over time with different inflation rates. ',
    dependencies: "None",
  },
  {
    id: "613",
    name: "Customer LTV Calculator",
    slug: "customer-ltv-calculator",
    category: "Finance",
    description: 'Calculate Customer Lifetime Value using ARPU and churn rate. Understand how much revenue each customer generates over their relationship. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Customer LTV Calculator — Calculate Customer Lifetime Value using ARPU and churn rate. Understand how much revenue each customer generates over their relationship. ',
    dependencies: "None",
  },
  {
    id: "614",
    name: "MRR Calculator",
    slug: "mrr-calculator",
    category: "Finance",
    description: 'Calculate Monthly Recurring Revenue by multiplying customers by average revenue per customer. Track your SaaS revenue growth. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online MRR Calculator — Calculate Monthly Recurring Revenue by multiplying customers by average revenue per customer. Track your SaaS revenue growth. ',
    dependencies: "None",
  },
  {
    id: "615",
    name: "Net Worth Calculator",
    slug: "net-worth-calculator",
    category: "Finance",
    description: 'Calculate your net worth by subtracting total liabilities from total assets. Get a snapshot of your financial health. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Net Worth Calculator — Calculate your net worth by subtracting total liabilities from total assets. Get a snapshot of your financial health. ',
    dependencies: "None",
  },
  {
    id: "617",
    name: "Rent vs Buy Calculator",
    slug: "rent-vs-buy-calculator",
    category: "Finance",
    description: 'Compare the total cost of renting versus buying a home over time. Factor in mortgage payments, rent, and equity growth. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Rent vs Buy Calculator — Compare the total cost of renting versus buying a home over time. Factor in mortgage payments, rent, and equity growth. ',
    dependencies: "None",
  },
  {
    id: "618",
    name: "Retirement Calculator",
    slug: "retirement-calculator",
    category: "Finance",
    description: 'Project your retirement savings based on current age, savings, monthly contributions, and expected returns. Plan for a comfortable retirement. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Retirement Calculator — Project your retirement savings based on current age, savings, monthly contributions, and expected returns. Plan for a comfortable retirement. ',
    dependencies: "None",
  },
  {
    id: "619",
    name: "Revenue Growth Calculator",
    slug: "revenue-growth-calculator",
    category: "Finance",
    description: 'Calculate revenue growth rate by comparing current period revenue to previous period. Track your business growth over time. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Revenue Growth Calculator — Calculate revenue growth rate by comparing current period revenue to previous period. Track your business growth over time. ',
    dependencies: "None",
  },
  {
    id: "620",
    name: "Runway Calculator",
    slug: "runway-calculator",
    category: "Finance",
    description: 'Calculate how many months your cash balance will last given your monthly burn rate. Essential for startup financial planning. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Runway Calculator — Calculate how many months your cash balance will last given your monthly burn rate. Essential for startup financial planning. ',
    dependencies: "None",
  },
  {
    id: "621",
    name: "A/B Test Calculator",
    slug: "ab-test-calculator",
    category: "Finance",
    description: 'Calculate A/B test significance between two variants. Compare conversion rates with visitor and conversion data for each variant. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online A/B Test Calculator — Calculate A/B test significance between two variants. Compare conversion rates with visitor and conversion data for each variant. ',
    dependencies: "None",
  },
  {
    id: "622",
    name: "Business Days Calculator",
    slug: "business-days-calculator",
    category: "Calculator",
    description: 'Count the number of business days between two dates, excluding weekends. Plan projects and track working days accurately. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Business Days Calculator — Count the number of business days between two dates, excluding weekends. Plan projects and track working days accurately. ',
    dependencies: "None",
  },
  {
    id: "625",
    name: "Day of Week Calculator",
    slug: "day-of-week-calculator",
    category: "Calculator",
    description: 'Find out what day of the week any date falls on. Look up birthdays, holidays, historical events, and future dates. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Day of Week Calculator — Find out what day of the week any date falls on. Look up birthdays, holidays, historical events, and future dates. ',
    dependencies: "None",
  },
  {
    id: "626",
    name: "Day of Year Calculator",
    slug: "day-of-year-calculator",
    category: "Calculator",
    description: 'Calculate the day number of the year for any date. Find out which day of 365 (or 366) a specific date represents. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Day of Year Calculator — Calculate the day number of the year for any date. Find out which day of 365 (or 366) a specific date represents. ',
    dependencies: "None",
  },
  {
    id: "627",
    name: "Exponent Calculator",
    slug: "exponent-calculator",
    category: "Calculator",
    description: 'Calculate base raised to an exponent power. Compute large exponential values quickly with this simple math tool. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Exponent Calculator — Calculate base raised to an exponent power. Compute large exponential values quickly with this simple math tool. ',
    dependencies: "None",
  },
  {
    id: "628",
    name: "Final Grade Calculator",
    slug: "final-grade-calculator",
    category: "Calculator",
    description: 'Calculate your final grade using weighted assignment scores. Enter grades and their weights to compute your overall percentage. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Final Grade Calculator — Calculate your final grade using weighted assignment scores. Enter grades and their weights to compute your overall percentage. ',
    dependencies: "None",
  },
  {
    id: "629",
    name: "GPA Calculator",
    slug: "gpa-calculator",
    category: "Calculator",
    description: 'Calculate your Grade Point Average from letter grades and credit hours. Supports standard 4.0 grading scale. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online GPA Calculator — Calculate your Grade Point Average from letter grades and credit hours. Supports standard 4.0 grading scale. ',
    dependencies: "None",
  },
  {
    id: "630",
    name: "Grade Calculator",
    slug: "grade-calculator",
    category: "Calculator",
    description: 'Convert percentage scores to letter grades. Enter your percentage to see the corresponding letter grade on standard scale. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Grade Calculator — Convert percentage scores to letter grades. Enter your percentage to see the corresponding letter grade on standard scale. ',
    dependencies: "None",
  },
  {
    id: "631",
    name: "College GPA Calculator",
    slug: "college-gpa-calculator",
    category: "Calculator",
    description: 'Calculate semester and cumulative GPA. Enter current grades, credits, and previous GPA to track your academic performance. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online College GPA Calculator — Calculate semester and cumulative GPA. Enter current grades, credits, and previous GPA to track your academic performance. ',
    dependencies: "None",
  },
  {
    id: "632",
    name: "Leap Year Calculator",
    slug: "leap-year-calculator",
    category: "Calculator",
    description: 'Check if any year is a leap year. Enter a year to find out if it has 366 days with February 29. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Leap Year Calculator — Check if any year is a leap year. Enter a year to find out if it has 366 days with February 29. ',
    dependencies: "None",
  },
  {
    id: "633",
    name: "Probability Calculator",
    slug: "probability-calculator",
    category: "Calculator",
    description: 'Calculate probability of an event occurring. Enter favorable outcomes and total outcomes to get probability percentage and odds. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Probability Calculator — Calculate probability of an event occurring. Enter favorable outcomes and total outcomes to get probability percentage and odds. ',
    dependencies: "None",
  },
  {
    id: "634",
    name: "Proportion Calculator",
    slug: "proportion-calculator",
    category: "Calculator",
    description: 'Solve proportions with three known values. Find the missing value in a:b = c:d ratio equations. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Proportion Calculator — Solve proportions with three known values. Find the missing value in a:b = c:d ratio equations. ',
    dependencies: "None",
  },
  {
    id: "635",
    name: "Ratio Calculator",
    slug: "ratio-calculator",
    category: "Calculator",
    description: 'Simplify ratios to their lowest terms. Enter two numbers to find the simplest whole-number ratio between them. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Ratio Calculator — Simplify ratios to their lowest terms. Enter two numbers to find the simplest whole-number ratio between them. ',
    dependencies: "None",
  },
  {
    id: "636",
    name: "Aspect Ratio Calculator",
    slug: "aspect-ratio-calculator",
    category: "Calculator",
    description: 'Calculate the aspect ratio from width and height dimensions. Find the simplified W:H ratio for images, videos, and screens. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Aspect Ratio Calculator — Calculate the aspect ratio from width and height dimensions. Find the simplified W:H ratio for images, videos, and screens. ',
    dependencies: "None",
  },
  {
    id: "637",
    name: "Circle Calculator",
    slug: "circle-calculator",
    category: "Calculator",
    description: 'Calculate circle area and circumference from radius. Quick geometry calculations for circles of any size. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Circle Calculator — Calculate circle area and circumference from radius. Quick geometry calculations for circles of any size. ',
    dependencies: "None",
  },
  {
    id: "638",
    name: "DPI Calculator",
    slug: "dpi-calculator",
    category: "Calculator",
    description: 'Calculate dots per inch from pixel dimensions and physical size. Determine display and print resolution quality. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online DPI Calculator — Calculate dots per inch from pixel dimensions and physical size. Determine display and print resolution quality. ',
    dependencies: "None",
  },
  {
    id: "639",
    name: "Fraction Calculator",
    slug: "fraction-calculator",
    category: "Calculator",
    description: 'Add, subtract, multiply, and divide fractions. Get simplified results for all common fraction arithmetic operations. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Fraction Calculator — Add, subtract, multiply, and divide fractions. Get simplified results for all common fraction arithmetic operations. ',
    dependencies: "None",
  },
  {
    id: "640",
    name: "Mean Median Mode Calculator",
    slug: "mean-median-mode-calculator",
    category: "Calculator",
    description: 'Calculate mean, median, and mode from a list of numbers. Statistical analysis for any dataset with instant results. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Mean Median Mode Calculator — Calculate mean, median, and mode from a list of numbers. Statistical analysis for any dataset with instant results. ',
    dependencies: "None",
  },
  {
    id: "641",
    name: "PPI Calculator",
    slug: "ppi-calculator",
    category: "Calculator",
    description: 'Calculate pixels per inch from diagonal resolution and screen size. Determine screen sharpness and pixel density. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online PPI Calculator — Calculate pixels per inch from diagonal resolution and screen size. Determine screen sharpness and pixel density. ',
    dependencies: "None",
  },
  {
    id: "642",
    name: "Pythagorean Theorem Calculator",
    slug: "pythagorean-theorem-calculator",
    category: "Calculator",
    description: 'Calculate the hypotenuse of a right triangle using the Pythagorean theorem. Enter sides a and b to find side c. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Pythagorean Theorem Calculator — Calculate the hypotenuse of a right triangle using the Pythagorean theorem. Enter sides a and b to find side c. ',
    dependencies: "None",
  },
  {
    id: "643",
    name: "Quadratic Equation Solver",
    slug: "quadratic-equation-solver",
    category: "Calculator",
    description: 'Solve quadratic equations of the form ax² + bx + c = 0. Get real and complex roots with step-by-step solutions. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Quadratic Equation Solver — Solve quadratic equations of the form ax² + bx + c = 0. Get real and complex roots with step-by-step solutions. ',
    dependencies: "None",
  },
  {
    id: "644",
    name: "Rectangle Area Calculator",
    slug: "rectangle-area-calculator",
    category: "Calculator",
    description: 'Calculate the area and perimeter of a rectangle from length and width. Simple geometry for construction, design, and planning. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Rectangle Area Calculator — Calculate the area and perimeter of a rectangle from length and width. Simple geometry for construction, design, and planning. ',
    dependencies: "None",
  },
  {
    id: "645",
    name: "Square Root Calculator",
    slug: "square-root-calculator",
    category: "Calculator",
    description: 'Calculate the square root of any number. Get precise square root values for mathematical and scientific calculations. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Square Root Calculator — Calculate the square root of any number. Get precise square root values for mathematical and scientific calculations. ',
    dependencies: "None",
  },
  {
    id: "646",
    name: "Scientific Calculator",
    slug: "scientific-calculator",
    category: "Calculator",
    description: 'Evaluate mathematical expressions with sin, cos, tan, log, and sqrt functions. A versatile scientific calculator in your browser. No signup or account required.',
    seoDescription: 'Free online Scientific Calculator — Evaluate mathematical expressions with sin, cos, tan, log, and sqrt functions. A versatile scientific calculator in your browser. ',
    dependencies: "None",
  },
  {
    id: "647",
    name: "Fluid Typography Calculator",
    slug: "fluid-typography-calculator",
    category: "Calculator",
    description: 'Generate CSS clamp() values for fluid responsive typography. Calculate viewport-based font sizes that scale smoothly. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Fluid Typography Calculator — Generate CSS clamp() values for fluid responsive typography. Calculate viewport-based font sizes that scale smoothly. ',
    dependencies: "None",
  },
  {
    id: "648",
    name: "BMI Calculator for Kids",
    slug: "bmi-calculator-for-kids",
    category: "Health",
    description: 'Calculate BMI for children with age and gender considerations. Track childhood growth and weight status. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online BMI Calculator for Kids — Calculate BMI for children with age and gender considerations. Track childhood growth and weight status. ',
    dependencies: "None",
  },
  {
    id: "649",
    name: "Body Fat Percentage Calculator",
    slug: "body-fat-percentage-calculator",
    category: "Health",
    description: 'Calculate body fat percentage using the US Navy circumference method. Enter waist, neck, height, and hip measurements. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Body Fat Percentage Calculator — Calculate body fat percentage using the US Navy circumference method. Enter waist, neck, height, and hip measurements. ',
    dependencies: "None",
  },
  {
    id: "650",
    name: "Body Surface Area Calculator",
    slug: "body-surface-area-calculator",
    category: "Health",
    description: 'Calculate Body Surface Area using the Mosteller formula. Enter height and weight for medical and fitness BSA measurements. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Body Surface Area Calculator — Calculate Body Surface Area using the Mosteller formula. Enter height and weight for medical and fitness BSA measurements. ',
    dependencies: "None",
  },
  {
    id: "651",
    name: "Baby Formula Calculator",
    slug: "baby-formula-calculator",
    category: "Health",
    description: 'Calculate daily baby formula amount based on weight and age. Get recommended ounces and milliliters per feeding. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Baby Formula Calculator — Calculate daily baby formula amount based on weight and age. Get recommended ounces and milliliters per feeding. ',
    dependencies: "None",
  },
  {
    id: "652",
    name: "Baby Growth Percentile Calculator",
    slug: "baby-growth-percentile-calculator",
    category: "Health",
    description: 'Estimate baby growth percentiles from weight, height, and age. Monitor your childs growth compared to population averages. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Baby Growth Percentile Calculator — Estimate baby growth percentiles from weight, height, and age. Monitor your childs growth compared to population averages. ',
    dependencies: "None",
  },
  {
    id: "653",
    name: "Baby Sleep Schedule Calculator",
    slug: "baby-sleep-schedule-calculator",
    category: "Health",
    description: 'Get recommended sleep schedules for babies by age. Learn total sleep hours, nap count, and nighttime sleep duration. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Baby Sleep Schedule Calculator — Get recommended sleep schedules for babies by age. Learn total sleep hours, nap count, and nighttime sleep duration. ',
    dependencies: "None",
  },
  {
    id: "654",
    name: "Breastfeeding Calorie Calculator",
    slug: "breastfeeding-calorie-calculator",
    category: "Health",
    description: 'Calculate calories burned through breastfeeding. Enter babys age and feedings per day to estimate daily energy expenditure. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Breastfeeding Calorie Calculator — Calculate calories burned through breastfeeding. Enter babys age and feedings per day to estimate daily energy expenditure. ',
    dependencies: "None",
  },
  {
    id: "656",
    name: "Child Height Predictor",
    slug: "child-height-predictor",
    category: "Health",
    description: 'Predict a childs adult height based on parents heights using the mid-parental method. Estimate future height for boys and girls. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Child Height Predictor — Predict a childs adult height based on parents heights using the mid-parental method. Estimate future height for boys and girls. ',
    dependencies: "None",
  },
  {
    id: "657",
    name: "Cycling Calorie Calculator",
    slug: "cycling-calorie-calculator",
    category: "Health",
    description: 'Calculate calories burned during cycling based on weight, duration, and speed. Track your cycling workout calorie expenditure. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Cycling Calorie Calculator — Calculate calories burned during cycling based on weight, duration, and speed. Track your cycling workout calorie expenditure. ',
    dependencies: "None",
  },
  {
    id: "657b",
    name: "TDEE Calculator",
    slug: "calorie-calculator",
    category: "Health",
    description: 'Calculate your Total Daily Energy Expenditure (TDEE) from BMR and activity level. Find how many calories you burn per day.',
    seoDescription: 'Free online TDEE Calculator \u2014 Calculate your Total Daily Energy Expenditure from BMR and activity level. Find how many calories you burn per day. ',
    dependencies: "None",
  },
  {
    id: "658",
    name: "Heart Rate Zone Calculator",
    slug: "heart-rate-zone-calculator",
    category: "Health",
    description: 'Calculate heart rate training zones by age. Find your target heart rate ranges for different exercise intensity levels. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Heart Rate Zone Calculator — Calculate heart rate training zones by age. Find your target heart rate ranges for different exercise intensity levels. ',
    dependencies: "None",
  },
  {
    id: "660",
    name: "Keto Calculator",
    slug: "keto-calculator",
    category: "Health",
    description: 'Calculate keto diet macros including protein, fat, and carbs. Get your personalized macronutrient targets for the ketogenic diet. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Keto Calculator — Calculate keto diet macros including protein, fat, and carbs. Get your personalized macronutrient targets for the ketogenic diet. ',
    dependencies: "None",
  },
  {
    id: "661",
    name: "Lean Body Mass Calculator",
    slug: "lean-body-mass-calculator",
    category: "Health",
    description: 'Calculate lean body mass from total weight and body fat percentage. Understand your muscle mass versus fat mass. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Lean Body Mass Calculator — Calculate lean body mass from total weight and body fat percentage. Understand your muscle mass versus fat mass. ',
    dependencies: "None",
  },
  {
    id: "662",
    name: "Macro Calculator",
    slug: "macro-calculator",
    category: "Health",
    description: 'Calculate daily macronutrient targets based on your goals. Get personalized protein, fat, and carb recommendations for weight loss or muscle gain. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Macro Calculator — Calculate daily macronutrient targets based on your goals. Get personalized protein, fat, and carb recommendations for weight loss or muscle gain. ',
    dependencies: "None",
  },
  {
    id: "664",
    name: "Pregnancy Due Date Calculator",
    slug: "pregnancy-due-date-calculator",
    category: "Health",
    description: 'Calculate your estimated due date from the first day of your last period. Get trimester dates and important pregnancy milestones. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Pregnancy Due Date Calculator — Calculate your estimated due date from the first day of your last period. Get trimester dates and important pregnancy milestones. ',
    dependencies: "None",
  },
  {
    id: "665",
    name: "Protein Calculator",
    slug: "protein-calculator",
    category: "Health",
    description: 'Calculate daily protein requirements based on weight and activity level. Get tailored protein recommendations for your fitness goals. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Protein Calculator — Calculate daily protein requirements based on weight and activity level. Get tailored protein recommendations for your fitness goals. ',
    dependencies: "None",
  },
  {
    id: "666",
    name: "Running Pace Calculator",
    slug: "running-pace-calculator",
    category: "Health",
    description: 'Calculate running pace from distance and time. Enter your run details to find pace per kilometer and speed in km/h. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Running Pace Calculator — Calculate running pace from distance and time. Enter your run details to find pace per kilometer and speed in km/h. ',
    dependencies: "None",
  },
  {
    id: "667",
    name: "Sleep Calculator",
    slug: "sleep-calculator",
    category: "Health",
    description: 'Calculate optimal bedtime based on wake time and sleep cycles. Find the best time to go to bed for refreshed mornings. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Sleep Calculator — Calculate optimal bedtime based on wake time and sleep cycles. Find the best time to go to bed for refreshed mornings. ',
    dependencies: "None",
  },
  {
    id: "668",
    name: "Steps to Calories Calculator",
    slug: "steps-to-calories-calculator",
    category: "Health",
    description: 'Convert steps to calories burned. Enter your step count and weight to estimate calories and distance walked. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Steps to Calories Calculator — Convert steps to calories burned. Enter your step count and weight to estimate calories and distance walked. ',
    dependencies: "None",
  },
  {
    id: "669",
    name: "Water Intake Calculator",
    slug: "water-intake-calculator",
    category: "Health",
    description: 'Calculate daily water intake recommendations based on weight and exercise. Stay hydrated with personalized water goals. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Water Intake Calculator — Calculate daily water intake recommendations based on weight and exercise. Stay hydrated with personalized water goals. ',
    dependencies: "None",
  },
  {
    id: "670",
    name: "Simple Interest Calculator",
    slug: "simple-interest-calculator",
    category: "Finance",
    description: 'Calculate simple interest using principal, rate, and time. Find total interest earned and final amount for basic interest calculations. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Simple Interest Calculator — Calculate simple interest using principal, rate, and time. Find total interest earned and final amount for basic interest calculations. ',
    dependencies: "None",
  },
  {
    id: "671",
    name: "Savings Calculator",
    slug: "savings-calculator",
    category: "Finance",
    description: 'Calculate the future value of monthly savings with compound interest. Plan your savings goals and see your money grow over time. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Savings Calculator — Calculate the future value of monthly savings with compound interest. Plan your savings goals and see your money grow over time. ',
    dependencies: "None",
  },
  {
    id: "672",
    name: "Seat License Calculator",
    slug: "seat-license-calculator",
    category: "Finance",
    description: 'Calculate total cost of software licenses by seats, price per seat, and duration. Budget and plan your SaaS subscription costs. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Seat License Calculator — Calculate total cost of software licenses by seats, price per seat, and duration. Budget and plan your SaaS subscription costs. ',
    dependencies: "None",
  },
  {
    id: "673",
    name: "Semver Calculator",
    slug: "semver-calculator",
    category: "Calculator",
    description: 'Compare semantic version numbers. Check if one version is greater than, less than, or equal to another using semver rules. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Semver Calculator — Compare semantic version numbers. Check if one version is greater than, less than, or equal to another using semver rules. ',
    dependencies: "None",
  },
  {
    id: "674",
    name: "Standard Deviation Calculator",
    slug: "standard-deviation-calculator",
    category: "Calculator",
    description: 'Calculate standard deviation, variance, and mean from a list of numbers. Statistical analysis for data science and mathematics. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Standard Deviation Calculator — Calculate standard deviation, variance, and mean from a list of numbers. Statistical analysis for data science and mathematics. ',
    dependencies: "None",
  },
  {
    id: "675",
    name: "Tax Calculator",
    slug: "tax-calculator",
    category: "Finance",
    description: 'Estimate your income tax with progressive tax brackets. Enter income and deductions to calculate estimated tax liability and effective rate. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Tax Calculator — Estimate your income tax with progressive tax brackets. Enter income and deductions to calculate estimated tax liability and effective rate. ',
    dependencies: "None",
  },
  {
    id: "676",
    name: "TDS Calculator India",
    slug: "tds-calculator-india",
    category: "Finance",
    description: 'Calculate TDS for Indian salaried employees under the new tax regime. Estimate monthly TDS deduction and net take-home salary. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online TDS Calculator India — Calculate TDS for Indian salaried employees under the new tax regime. Estimate monthly TDS deduction and net take-home salary. ',
    dependencies: "None",
  },
  {
    id: "677",
    name: "Trial Conversion Calculator",
    slug: "trial-conversion-calculator",
    category: "Finance",
    description: 'Calculate trial-to-paid conversion rate. Enter total trials and paid conversions to understand your freemium or trial funnel performance. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Trial Conversion Calculator — Calculate trial-to-paid conversion rate. Enter total trials and paid conversions to understand your freemium or trial funnel performance. ',
    dependencies: "None",
  },
  {
    id: "678",
    name: "API Request Builder",
    slug: "api-request-builder",
    category: "Developer",
    description: 'Build HTTP requests with custom method, URL, headers, and body. Generate equivalent curl commands. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online API Request Builder — Build HTTP requests with custom method, URL, headers, and body. Generate equivalent curl commands. ',
    dependencies: "None",
  },
  {
    id: "679",
    name: "API Tester",
    slug: "api-tester",
    category: "Developer",
    description: 'Test any HTTP endpoint by sending GET, POST, PUT, or DELETE requests directly from your browser. View response status, headers, and body.',
    seoDescription: 'Free online API Tester — Test any HTTP endpoint by sending GET, POST, PUT, or DELETE requests directly from your browser. ',
    dependencies: "None",
  },
  {
    id: "680",
    name: "API Response Formatter",
    slug: "api-response-formatter",
    category: "Developer",
    description: 'Prettifies JSON and API response data with configurable indentation, sorting, and syntax validation — fixes malformed JSON and makes nested structures readable.',
    seoDescription: 'Free online API Response Formatter — Format and beautify JSON and XML API responses with proper indentation and syntax highlighting. ',
    dependencies: "None",
  },
  {
    id: "681",
    name: "API Error Decoder",
    slug: "api-error-decoder",
    category: "Developer",
    description: 'Decode HTTP status codes with full category, description, and common causes for each code from 1xx to 5xx.',
    seoDescription: 'Free online API Error Decoder — Decode HTTP status codes with full category, description, and common causes for each code. ',
    dependencies: "None",
  },
  {
    id: "682",
    name: "API Payload Analyzer",
    slug: "api-payload-analyzer",
    category: "Developer",
    description: 'Analyze JSON payload size, structure, nesting depth, and key count for optimizing API request and response bodies.',
    seoDescription: 'Free online API Payload Analyzer — Analyze JSON payload size, structure, nesting depth, and key count. ',
    dependencies: "None",
  },
  {
    id: "683",
    name: "API Mock Data Generator",
    slug: "api-mock-data-generator",
    category: "Developer",
    description: 'Generate realistic mock JSON data from a schema description. Ideal for rapid API prototyping and frontend development without a backend.',
    seoDescription: 'Free online API Mock Data Generator — Generate realistic mock JSON data from a schema description. Ideal for rapid API prototyping. ',
    dependencies: "None",
  },
  {
    id: "684",
    name: "API Mock Server Config",
    slug: "api-mock-server-config",
    category: "Developer",
    description: 'Generate JSON Server configuration files from endpoint definitions. Set up a fully functional mock API server in seconds.',
    seoDescription: 'Free online API Mock Server Config — Generate JSON Server configuration files from endpoint definitions. Set up a mock API server. ',
    dependencies: "None",
  },
  {
    id: "685",
    name: "Mock API Response Generator",
    slug: "mock-api-response-generator",
    category: "Developer",
    description: 'Generate sample API responses from a schema definition. Create realistic mock data for frontend testing and development.',
    seoDescription: 'Free online Mock API Response Generator — Generate sample API responses from a schema definition. Create realistic mock data for frontend testing. ',
    dependencies: "None",
  },
  {
    id: "686",
    name: "API Latency Budget",
    slug: "api-latency-budget",
    category: "Developer",
    description: 'Calculate API latency budgets from SLA requirements. Distribute response time across application, database, and external service layers.',
    seoDescription: 'Free online API Latency Budget — Calculate API latency budgets from SLA requirements. Distribute response time across layers. ',
    dependencies: "None",
  },
  {
    id: "687",
    name: "API Pagination Calculator",
    slug: "api-pagination-calculator",
    category: "Developer",
    description: 'Calculate pagination parameters including page count, offset values, and next/previous page navigation for any API.',
    seoDescription: 'Free online API Pagination Calculator — Calculate pagination parameters including page count, offset values, and navigation. ',
    dependencies: "None",
  },
  {
    id: "688",
    name: "API Key Generator",
    slug: "api-key-generator",
    category: "Developer",
    description: 'Generate secure API keys with configurable length, character set, and optional prefix. Use with any authentication scheme.',
    seoDescription: 'Free online API Key Generator — Generate secure API keys with configurable length, character set, and optional prefix. ',
    dependencies: "None",
  },
  {
    id: "689",
    name: "API Key Hasher",
    slug: "api-key-hasher",
    category: "Developer",
    description: 'Hash API keys using SHA-256 for secure storage. Never store raw API keys — hash them before persisting to your database.',
    seoDescription: 'Free online API Key Hasher — Hash API keys using SHA-256 for secure storage. Never store raw API keys in your database. ',
    dependencies: "None",
  },
  {
    id: "690",
    name: "API Key Validator",
    slug: "api-key-validator",
    category: "Developer",
    description: 'Validate API key format including length checks, character set validation, prefix verification, and entropy analysis.',
    seoDescription: 'Free online API Key Validator — Validate API key format including length checks, character set validation, and entropy analysis. ',
    dependencies: "None",
  },
  {
    id: "691",
    name: "API Cost Estimator",
    slug: "api-cost-estimator",
    category: "Developer",
    description: 'Estimate API costs based on monthly requests, price per million calls, and number of users. Plan your API budget with confidence.',
    seoDescription: 'Free online API Cost Estimator — Estimate API costs based on monthly requests, price per million calls, and users. Plan your budget. ',
    dependencies: "None",
  },
  {
    id: "692",
    name: "API Gateway Rate Calculator",
    slug: "api-gateway-rate-calculator",
    category: "Developer",
    description: 'Calculate rate limits, burst capacities, and throttling thresholds for API gateway configurations. Plan your traffic management strategy.',
    seoDescription: 'Free online API Gateway Rate Calculator — Calculate rate limits, burst capacities, and throttling thresholds for API gateway config. ',
    dependencies: "None",
  },
  {
    id: "693",
    name: "API Rate Limiter Calculator",
    slug: "api-rate-limiter-calculator",
    category: "Developer",
    description: 'Calculate rate limit windows, burst allowances, and retry intervals. Design effective rate limiting for your API endpoints.',
    seoDescription: 'Free online API Rate Limiter Calculator — Calculate rate limit windows, burst allowances, and retry intervals. Design effective rate limiting. ',
    dependencies: "None",
  },
  {
    id: "694",
    name: "API Changelog Generator",
    slug: "api-changelog-generator",
    category: "Developer",
    description: 'Generate structured changelogs from API version diffs. Categorize changes as Added, Changed, Deprecated, Removed, Fixed, or Security.',
    seoDescription: 'Free online API Changelog Generator — Generate structured changelogs from API version diffs. Categorize every change type. ',
    dependencies: "None",
  },
  {
    id: "695",
    name: "API Documentation Generator",
    slug: "api-documentation-generator",
    category: "Developer",
    description: 'Generate clean API documentation from endpoint descriptions. Includes parameters, response examples, and curl command samples.',
    seoDescription: 'Free online API Documentation Generator — Generate clean API docs from endpoint descriptions with parameters and response examples. ',
    dependencies: "None",
  },
  {
    id: "696",
    name: "REST Endpoint Documenter",
    slug: "rest-endpoint-documenter",
    category: "Developer",
    description: 'Document REST API endpoints with method, path, and description. Generates formatted documentation with sample request and response bodies.',
    seoDescription: 'Free online REST Endpoint Documenter — Document REST API endpoints with method, path, and description. Generate formatted docs. ',
    dependencies: "None",
  },
  {
    id: "697",
    name: "GraphQL Cost Estimator",
    slug: "graphql-cost-estimator",
    category: "Developer",
    description: 'Estimate GraphQL query complexity based on field count and nesting depth. Identify expensive queries before they hit your server.',
    seoDescription: 'Free online GraphQL Cost Estimator — Estimate GraphQL query complexity based on field count and nesting depth. ',
    dependencies: "None",
  },
  {
    id: "698",
    name: "GraphQL Query Formatter",
    slug: "graphql-query-formatter",
    category: "Developer",
    description: 'Format and prettify GraphQL queries with proper indentation. Makes complex nested queries readable and maintainable.',
    seoDescription: 'Free online GraphQL Query Formatter — Format and prettify GraphQL queries with proper indentation. ',
    dependencies: "None",
  },
  {
    id: "699",
    name: "GraphQL Schema to JSON Schema",
    slug: "graphql-schema-to-json-schema",
    category: "Developer",
    description: 'Convert GraphQL schema definitions to JSON Schema format. Bridge the gap between GraphQL and REST tooling ecosystems.',
    seoDescription: 'Free online GraphQL Schema to JSON Schema — Convert GraphQL schema definitions to JSON Schema format. ',
    dependencies: "None",
  },
  {
    id: "700",
    name: "GraphQL Schema Validator",
    slug: "graphql-schema-validator",
    category: "Developer",
    description: 'Validate GraphQL schema syntax and structure. Detect missing root types, unknown type references, and common schema issues.',
    seoDescription: 'Free online GraphQL Schema Validator — Validate GraphQL schema syntax and structure. Detect missing root types and issues. ',
    dependencies: "None",
  },
  {
    id: "701",
    name: "GraphQL Subscription Builder",
    slug: "graphql-subscription-builder",
    category: "Developer",
    description: 'Build GraphQL subscription queries with custom event names and payload fields. Generate ready-to-use subscription strings.',
    seoDescription: 'Free online GraphQL Subscription Builder — Build GraphQL subscription queries with custom event names and payload fields. ',
    dependencies: "None",
  },
  {
    id: "702",
    name: "GraphQL Tester",
    slug: "graphql-tester",
    category: "Developer",
    description: 'Test GraphQL queries with variables. Format queries and variables, and preview formatted responses for development and debugging.',
    seoDescription: 'Free online GraphQL Tester — Test GraphQL queries with variables. Format and preview responses for development. ',
    dependencies: "None",
  },
  {
    id: "703",
    name: "GraphQL Variables Formatter",
    slug: "graphql-variables-formatter",
    category: "Developer",
    description: 'Format and beautify GraphQL variables JSON with proper indentation. Ensure your variables are correctly structured before sending queries.',
    seoDescription: 'Free online GraphQL Variables Formatter — Format and beautify GraphQL variables JSON with proper indentation. ',
    dependencies: "None",
  },
  {
    id: "704",
    name: "gRPC Status Code Lookup",
    slug: "grpc-status-code-lookup",
    category: "Developer",
    description: 'Lookup gRPC status codes from 0 (OK) to 16 (Unauthenticated) with descriptions and common causes for each error.',
    seoDescription: 'Free online gRPC Status Code Lookup — Lookup gRPC status codes with descriptions and common causes for each error. ',
    dependencies: "None",
  },
  {
    id: "705",
    name: "SOAP API Tester",
    slug: "soap-api-tester",
    category: "Developer",
    description: 'Build and test SOAP API envelopes with WSDL URL, method name, and XML parameters. Generate complete SOAP request envelopes.',
    seoDescription: 'Free online SOAP API Tester — Build and test SOAP API envelopes with WSDL URL, method, and XML parameters. ',
    dependencies: "None",
  },
  {
    id: "706",
    name: "OpenAPI Mock Generator",
    slug: "openapi-mock-generator",
    category: "Developer",
    description: 'Generate mock API responses from OpenAPI spec fragments. Create realistic sample data for API development and testing.',
    seoDescription: 'Free online OpenAPI Mock Generator — Generate mock API responses from OpenAPI spec fragments. Create realistic sample data. ',
    dependencies: "None",
  },
  {
    id: "707",
    name: "OpenAPI to Postman",
    slug: "openapi-to-postman",
    category: "Developer",
    description: 'Convert OpenAPI specs to Postman collection JSON format. Import directly into Postman. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online OpenAPI to Postman — Convert OpenAPI specs to Postman collection JSON format. Import directly into Postman. ',
    dependencies: "None",
  },
  {
    id: "708",
    name: "OpenAPI Validator",
    slug: "openapi-validator",
    category: "Developer",
    description: 'Validate OpenAPI/Swagger spec syntax. Check for required fields, missing paths, and structural issues in your API specification.',
    seoDescription: 'Free online OpenAPI Validator — Validate OpenAPI/Swagger spec syntax. Check required fields, missing paths, and structural issues. ',
    dependencies: "None",
  },
  {
    id: "709",
    name: "Postman Collection Generator",
    slug: "postman-collection-generator",
    category: "Developer",
    description: 'Generate Postman collection JSON from endpoint descriptions. Create ready-to-import collections with method and path for each endpoint.',
    seoDescription: 'Free online Postman Collection Generator — Generate Postman collection JSON from endpoint descriptions. Ready-to-import. ',
    dependencies: "None",
  },
  {
    id: "710",
    name: "Postman to OpenAPI Converter",
    slug: "postman-to-openapi-converter",
    category: "Developer",
    description: 'Convert Postman collections to OpenAPI 3.0 specs. Migrate your API documentation. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Postman to OpenAPI Converter — Convert Postman collections to OpenAPI 3.0 specs. Migrate your API documentation. ',
    dependencies: "None",
  },
  {
    id: "711",
    name: "Swagger/OpenAPI Generator",
    slug: "swagger-openapi-generator",
    category: "Developer",
    description: 'Generate Swagger UI / OpenAPI specs from a simple description. Enter title, version, and endpoints to produce a complete spec JSON.',
    seoDescription: 'Free online Swagger/OpenAPI Generator — Generate Swagger UI / OpenAPI specs from a simple description. ',
    dependencies: "None",
  },
  {
    id: "712",
    name: "Webhook Payload Generator",
    slug: "webhook-payload-generator",
    category: "Developer",
    description: 'Generate realistic webhook payload examples with customizable event names and data fields. Test your webhook handlers with realistic data.',
    seoDescription: 'Free online Webhook Payload Generator — Generate realistic webhook payload examples with customizable events and fields. ',
    dependencies: "None",
  },
  {
    id: "713",
    name: "Webhook Retry Config",
    slug: "webhook-retry-config",
    category: "Developer",
    description: 'Configure and compare webhook retry strategies — Fixed, Linear, Exponential, and Exponential + Jitter. Calculate total delays and visualize retry patterns.',
    seoDescription: 'Free online Webhook Retry Config — Configure and compare webhook retry strategies including exponential backoff with jitter. ',
    dependencies: "None",
  },
  {
    id: "714",
    name: "Webhook Signature Verifier",
    slug: "webhook-signature-verifier",
    category: "Developer",
    description: 'Verify webhook HMAC-SHA256 signatures. Validate that incoming webhooks are genuinely from your provider and haven\'t been tampered with.',
    seoDescription: 'Free online Webhook Signature Verifier — Verify webhook HMAC-SHA256 signatures. Validate webhook authenticity. ',
    dependencies: "None",
  },
  {
    id: "715",
    name: "Webhook Tester",
    slug: "webhook-tester",
    category: "Developer",
    description: 'Test webhook endpoints by sending simulated POST requests with custom JSON payloads. Verify your webhook handlers are working correctly.',
    seoDescription: 'Free online Webhook Tester — Test webhook endpoints by sending simulated POST requests with custom JSON payloads. ',
    dependencies: "None",
  },
  {
    id: "716",
    name: "Webhook Validator",
    slug: "webhook-validator",
    category: "Developer",
    description: 'Validate webhook payload structure including required fields (id, event, data, created). Ensure your webhooks meet the standard format.',
    seoDescription: 'Free online Webhook Validator — Validate webhook payload structure including required fields. Ensure standard format compliance. ',
    dependencies: "None",
  },
  {
    id: "954",
    name: "API Diff Checker",
    slug: "api-diff-checker",
    category: "Developer",
    description: 'Compare two OpenAPI specs side-by-side to detect breaking changes, new endpoints, removed fields, and modified schemas between versions.',
    seoDescription: 'Free online API Diff Checker — Compare two OpenAPI specs side-by-side to detect breaking changes, new endpoints, and modified schemas. ',
    dependencies: "None",
  },
  {
    id: "955",
    name: "OpenAPI Documentation Generator",
    slug: "api-docs-generator",
    category: "Developer",
    description: 'Generate Markdown API documentation from OpenAPI specs. Create clean, readable docs with endpoints, parameters, and response examples.',
    seoDescription: 'Free online OpenAPI Documentation Generator — Generate Markdown API docs from OpenAPI specs with endpoints, parameters, and response examples. ',
    dependencies: "None",
  },
  {
    id: "717",
    name: "Conventional Commit Generator",
    slug: "conventional-commit-generator",
    category: "Developer",
    description: 'Generate conventional commit messages with type, scope, description, breaking changes, and body. Follow the Conventional Commits specification.',
    seoDescription: 'Free online Conventional Commit Generator — Generate conventional commit messages with type, scope, description, and breaking changes. ',
    dependencies: "None",
  },
  {
    id: "718",
    name: "Code Formatter",
    slug: "code-formatter",
    category: "Developer",
    description: 'Auto-formats source code across 15+ languages — JavaScript, Python, HTML, CSS, SQL, YAML — with language-aware indentation and syntax rules.',
    seoDescription: 'Free online Code Formatter — Format and beautify source code in JavaScript, TypeScript, Python, HTML, CSS, SQL, YAML, XML, and Markdown. ',
    dependencies: "None",
  },
  {
    id: "720",
    name: "HTML Formatter",
    slug: "html-formatter",
    category: "Developer",
    description: 'Indents and structures HTML markup with proper nesting, attribute alignment, and readable indentation for templates and email designs.',
    seoDescription: 'Free online HTML Formatter — Format and beautify HTML markup with proper indentation and structure. ',
    dependencies: "None",
  },
  {
    id: "721",
    name: "CSS Formatter",
    slug: "css-formatter",
    category: "Developer",
    description: 'Organizes CSS stylesheets with consistent indentation, property grouping, and selector formatting for maintainable styles.',
    seoDescription: 'Free online CSS Formatter — Format and beautify CSS stylesheets with proper indentation and organization. ',
    dependencies: "None",
  },
  {
    id: "722",
    name: "JavaScript Formatter",
    slug: "javascript-formatter",
    category: "Developer",
    description: 'Formats JavaScript code with proper indentation, consistent spacing, and syntax structure — supports modern ES6+ features and async patterns.',
    seoDescription: 'Free online JavaScript Formatter — Format and beautify JavaScript code with proper indentation and syntax structure. ',
    dependencies: "None",
  },
  {
    id: "724",
    name: "JSX Formatter",
    slug: "jsx-formatter",
    category: "Developer",
    description: 'Formats JSX/React component code with proper indentation, prop alignment, and JSX expression structure for readable component definitions.',
    seoDescription: 'Free online JSX Formatter — Format and beautify JSX/React code with proper indentation and component structure. ',
    dependencies: "None",
  },
  {
    id: "725",
    name: "TSX Formatter",
    slug: "tsx-formatter",
    category: "Developer",
    description: 'Formats TSX/React TypeScript components with type-aware indentation, prop type alignment, and clean JSX structure.',
    seoDescription: 'Free online TSX Formatter — Format and beautify TSX/React TypeScript code with proper indentation. ',
    dependencies: "None",
  },
  {
    id: "726",
    name: "SCSS Formatter",
    slug: "scss-formatter",
    category: "Developer",
    description: 'Organizes SCSS/Sass stylesheets with proper nesting indentation, variable alignment, and mixin formatting for maintainable styles.',
    seoDescription: 'Free online SCSS Formatter — Format and beautify SCSS/Sass stylesheets with proper nesting and indentation. ',
    dependencies: "None",
  },
  {
    id: "727",
    name: "Python Formatter",
    slug: "python-formatter",
    category: "Developer",
    description: 'Formats Python code with PEP 8 compliant indentation, consistent spacing, and readable structure for scripts and modules.',
    seoDescription: 'Free online Python Formatter — Format and beautify Python code with proper indentation and structure. ',
    dependencies: "None",
  },
  {
    id: "729",
    name: "YAML Formatter",
    slug: "yaml-formatter",
    category: "Developer",
    description: 'Structures YAML configuration files with consistent indentation, proper key alignment, and readable hierarchy for Docker and CI/CD configs.',
    seoDescription: 'Free online YAML Formatter — Format and beautify YAML configuration files with consistent indentation. ',
    dependencies: "None",
  },
  {
    id: "730",
    name: "XML Formatter",
    slug: "xml-formatter",
    category: "Developer",
    description: 'Pretty-prints XML documents with proper tree indentation, validates structure, and reorganizes attributes for maximum readability.',
    seoDescription: 'Free online XML Formatter — Format and beautify XML documents with proper tree indentation. ',
    dependencies: "None",
  },
  {
    id: "731",
    name: "Markdown Formatter",
    slug: "markdown-formatter",
    category: "Developer",
    description: 'Normalizes Markdown formatting with consistent heading spacing, list indentation, and code block structure for readable documentation.',
    seoDescription: 'Free online Markdown Formatter — Format and beautify Markdown documents with consistent heading and list spacing. ',
    dependencies: "None",
  },
  {
    id: "732",
    name: "CSS Generator",
    slug: "css-generator",
    category: "Developer",
    description: 'Generate CSS code interactively for box shadows, gradients, border radius, transforms, filters, and more. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSS Generator — Generate CSS code interactively for box shadows, gradients, border radius, transforms, filters, and more. ',
    dependencies: "None",
  },
  {
    id: "733",
    name: "Box Shadow Generator",
    slug: "box-shadow-generator",
    category: "Developer",
    description: 'Generate CSS box-shadow values with an interactive preview. Configure offset, blur, spread, color, and inset. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Box Shadow Generator — Generate CSS box-shadow values with an interactive preview. Configure offset, blur, spread, color, and inset. ',
    dependencies: "None",
  },
  {
    id: "735",
    name: "Border Radius Generator",
    slug: "border-radius-generator",
    category: "Developer",
    description: 'Generate CSS border-radius values visually. Control each corner independently with live preview. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Border Radius Generator — Generate CSS border-radius values visually. Control each corner independently with live preview. ',
    dependencies: "None",
  },
  {
    id: "736",
    name: "Flexbox CSS Generator",
    slug: "flexbox-css-generator",
    category: "Developer",
    description: 'Generate Flexbox CSS code interactively. Configure direction, wrap, justify, align, and gap with live preview. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Flexbox CSS Generator — Generate Flexbox CSS code interactively. Configure direction, wrap, justify, align, and gap with live preview. ',
    dependencies: "None",
  },
  {
    id: "737",
    name: "CSS Grid Generator",
    slug: "css-grid-generator",
    category: "Developer",
    description: 'Generate CSS Grid layout code interactively. Configure columns, rows, and gap with live preview. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSS Grid Generator — Generate CSS Grid layout code interactively. Configure columns, rows, and gap with live preview. ',
    dependencies: "None",
  },
  {
    id: "738",
    name: "Text Shadow Generator",
    slug: "text-shadow-generator",
    category: "Developer",
    description: 'Generate CSS text-shadow values with interactive preview. Configure offset, blur, color, and opacity. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Text Shadow Generator — Generate CSS text-shadow values with interactive preview. Configure offset, blur, color, and opacity. ',
    dependencies: "None",
  },
  {
    id: "739",
    name: "CSS Transform Generator",
    slug: "css-transform-generator",
    category: "Developer",
    description: 'Generate CSS transform values interactively. Configure rotate, scale, skew, and translate with live preview. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSS Transform Generator — Generate CSS transform values interactively. Configure rotate, scale, skew, and translate with live preview. ',
    dependencies: "None",
  },
  {
    id: "740",
    name: "CSS Animation Generator",
    slug: "css-animation-generator",
    category: "Developer",
    description: 'Generate CSS keyframe animations interactively. Choose from fade-in, slide-in, and pulse animations. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSS Animation Generator — Generate CSS keyframe animations interactively. Choose from fade-in, slide-in, and pulse animations. ',
    dependencies: "None",
  },
  {
    id: "741",
    name: "CSS Filter Generator",
    slug: "css-filter-generator",
    category: "Developer",
    description: 'Generate CSS filter values interactively. Configure blur, brightness, contrast, saturation, hue, sepia, and grayscale. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSS Filter Generator — Generate CSS filter values interactively. Configure blur, brightness, contrast, saturation, hue, sepia, and grayscale. ',
    dependencies: "None",
    showInCategory: false,
  },
  {
    id: "745",
    name: "Image Converter",
    slug: "image-converter",
    category: "Image",
    description: 'Convert images between PNG, JPG, WebP, GIF, BMP, SVG, ICO, AVIF, and TIFF formats with format auto-detection.',
    seoDescription: 'Free online Image Converter — Convert images between PNG, JPG, WebP, GIF, BMP, SVG, ICO, AVIF, and TIFF. Coming soon.',
    dependencies: "None",
    showInCategory: false,
  },
  {
    id: "747",
    name: "Video Converter",
    slug: "video-converter-tool",
    category: "Video",
    description: 'Convert video files between MP4, AVI, MKV, MOV, WMV, FLV, WebM, 3GP, MPEG, and VOB formats with format auto-detection.',
    seoDescription: 'Free online Video Converter — Convert video files between MP4, AVI, MKV, MOV, WMV, FLV, WebM, 3GP, MPEG, and VOB. Coming soon.',
    dependencies: "None",
  },
  {
    id: "750",
    name: "Encoder / Decoder",
    slug: "encoder-decoder",
    category: "Developer",
    description: 'Encode or decode text using Base64, Base64URL, URL encoding, HTML entities, Hex, Binary, ROT13, UTF-8, and Unicode escape schemes.',
    seoDescription: 'Free online Encoder / Decoder — Encode or decode text with Base64, Base64URL, URL, HTML, Hex, Binary, ROT13, UTF-8, and Unicode escape. ',
    dependencies: "None",
  },
  {
    id: "du-6",
    name: "CSV Analyzer",
    slug: "csv-analyzer",
    category: "Utility",
    description: 'Analyze CSV structure — column types, counts, unique values, and empty cells.',
    seoDescription: 'Free online CSV Analyzer — Analyze CSV structure including column types, counts, unique values, and empty cells. ',
    dependencies: "None",
  },
  {
    id: "du-7",
    name: "JSON Path Query Builder",
    slug: "json-path-query-builder",
    category: "Utility",
    description: 'Query JSON data using dot-notation path expressions with wildcard support. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JSON Path Query Builder — Query JSON data using dot-notation path expressions with wildcard support. ',
    dependencies: "None",
  },
  {
    id: "du-8",
    name: "JSON Tree Viewer",
    slug: "json-tree-viewer",
    category: "Utility",
    description: 'Visualize JSON structure as an indented tree — see nested objects and arrays at a glance.',
    seoDescription: 'Free online JSON Tree Viewer — Visualize JSON structure as an indented tree with nested objects and arrays. ',
    dependencies: "None",
  },
  {
    id: "du-9",
    name: "JSON Diff Checker",
    slug: "json-diff-checker",
    category: "Developer",
    description: 'Compare two JSON objects side-by-side with color-coded key-level differences. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JSON Diff Checker — Compare two JSON objects side-by-side with color-coded key-level differences. ',
    dependencies: "None",
  },
  {
    id: "763",
    name: "Random Color Generator",
    slug: "random-color-generator",
    category: "Developer",
    description: 'Generate random colors in Hex, RGB, or HSL format with visual preview swatches. Perfect for design palettes and testing. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Color Generator — Generate random colors in Hex, RGB, or HSL format with visual preview swatches. Perfect for design palettes and testing. ',
    dependencies: "None",
  },
  {
    id: "764",
    name: "Random Team Generator",
    slug: "random-team-generator",
    category: "Developer",
    description: 'Split a list of names into random teams with configurable number of teams. Perfect for classroom activities, sports, and group projects. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Team Generator — Split a list of names into random teams with configurable number of teams. Perfect for classroom activities, sports, and group projects. ',
    dependencies: "None",
  },
  {
    id: "765",
    name: "Random Picker Generator",
    slug: "random-picker-generator",
    category: "Developer",
    description: 'Randomly pick one or more items from a list with optional repeat control. Perfect for giveaways, raffles, and random selection. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Picker Generator — Randomly pick one or more items from a list with optional repeat control. Perfect for giveaways, raffles, and random selection. ',
    dependencies: "None",
  },
  {
    id: "766",
    name: "Random Decision Maker",
    slug: "random-decision-maker",
    category: "Developer",
    description: 'Make decisions with a fun animated spinner that cycles through Yes, No, Maybe, and other responses. Perfect for quick decisions. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Decision Maker — Make decisions with a fun animated spinner that cycles through Yes, No, Maybe, and other responses. Perfect for quick decisions. ',
    dependencies: "None",
  },
  {
    id: "767",
    name: "Random Username Generator",
    slug: "random-username-generator",
    category: "Developer",
    description: 'Generate creative usernames from configurable patterns including adjective+noun, noun+number, and word-word combinations. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Username Generator — Generate creative usernames from configurable patterns including adjective+noun, noun+number, and word-word combinations. ',
    dependencies: "None",
  },
  {
    id: "769",
    name: "Random Token Generator",
    slug: "random-token-generator",
    category: "Developer",
    description: 'Generate cryptographically secure random tokens in hex, base64, or alphanumeric format. Perfect for API keys, session tokens, and secrets. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Token Generator — Generate cryptographically secure random tokens in hex, base64, or alphanumeric format. Perfect for API keys, session tokens, and secrets. ',
    dependencies: "None",
  },
  {
    id: "771",
    name: "Dummy Text Generator",
    slug: "dummy-text-generator",
    category: "Developer",
    description: 'Generate dummy placeholder text at a specified character length for design mockups, UI prototypes, and content layout testing. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Dummy Text Generator — Generate dummy placeholder text at a specified character length for design mockups, UI prototypes, and content layout testing. ',
    dependencies: "None",
  },
  {
    id: "772",
    name: "Fake Data Generator",
    slug: "fake-data-generator",
    category: "Developer",
    description: 'Generate fake personal data including names, emails, phone numbers, and addresses. Perfect for testing forms, databases, and application development. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Fake Data Generator — Generate fake personal data including names, emails, phone numbers, and addresses. Perfect for testing forms, databases, and application development. ',
    dependencies: "None",
  },
  {
    id: "773",
    name: "Fake Identity Generator",
    slug: "fake-identity-generator",
    category: "Developer",
    description: 'Generate complete fake identities with name, email, phone, address, date of birth, and occupation. Includes a photo placeholder. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Fake Identity Generator — Generate complete fake identities with name, email, phone, address, date of birth, and occupation. Includes a photo placeholder. ',
    dependencies: "None",
  },
  {
    id: "774",
    name: "Fake Credit Card Generator",
    slug: "fake-credit-card-generator",
    category: "Developer",
    description: 'Generate fake credit card numbers with valid formats including Visa, Mastercard, Amex, and Discover. All numbers pass Luhn algorithm validation. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Fake Credit Card Generator — Generate fake credit card numbers with valid formats including Visa, Mastercard, Amex, and Discover. All numbers pass Luhn algorithm validation. ',
    dependencies: "None",
  },
  {
    id: "775",
    name: "Sequence Generator",
    slug: "sequence-generator",
    category: "Developer",
    description: 'Generate number sequences in arithmetic, geometric, or custom progression. Configure start value, difference/ratio, and count. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Sequence Generator — Generate number sequences in arithmetic, geometric, or custom progression. Configure start value, difference/ratio, and count. ',
    dependencies: "None",
  },
  {
    id: "778",
    name: "Coupon Code Generator",
    slug: "coupon-code-generator",
    category: "Developer",
    description: 'Generate random coupon/discount codes with customizable pattern using X as placeholder for random characters. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Coupon Code Generator — Generate random coupon/discount codes with customizable pattern using X as placeholder for random characters. ',
    dependencies: "None",
  },
];
