import type { ToolMetadata } from './tools-types';

export const entries_chunk_5: ToolMetadata[] = [
  {

    id: "986",
    name: "Rate Limit Header Parser",
    slug: "rate-limit-header-parser",
    category: "Developer",
    description: 'Parse X-RateLimit headers and compute usage percentage, reset times, and retry intervals. Supports standard X-RateLimit-Limit, X-RateLimit-Remaining, and X-RateLimit-Reset formats.',
    seoDescription: 'Free online Rate Limit Header Parser — Parse X-RateLimit headers and compute usage percentage, reset times, and retry intervals. ',
    dependencies: "None",
},
  {

    id: "987",
    name: "Pricing Tier Builder",
    slug: "pricing-tier-builder",
    category: "Developer",
    description: 'Build pricing tier descriptions from JSON input. Supports free/pro tiers with configurable pricing (monthly/annual), user limits, and feature lists.',
    seoDescription: 'Free online Pricing Tier Builder — Build pricing tier descriptions from JSON. Supports free/pro tiers, pricing, user limits, and feature lists. ',
    dependencies: "None",
},
  {

    id: "988",
    name: "SSH Key Generator",
    slug: "ssh-key-generator",
    category: "Developer",
    description: 'Generate RSA, ECDSA, and Ed25519 SSH key pairs with proper OpenSSH format output. RSA uses RSASSA-PKCS1-v1_5 (2048-bit). ECDSA supports P-256 and P-384. Ed25519 uses a pure-JS implementation (no server). Public keys paste directly into ~/.ssh/authorized_keys.',
    seoDescription: 'Free online SSH Key Generator — Generate RSA (2048-bit), ECDSA (P-256/P-384), and Ed25519 SSH key pairs. OpenSSH format public keys for authorized_keys. ',
    dependencies: "None",
},
  {

    id: "989",
    name: "Secret Scanner",
    slug: "secret-scanner",
    category: "Developer",
    description: 'Scan text and code for leaked secrets and credentials. Detects Stripe keys, GitHub tokens, Slack tokens, Google API keys, AWS keys, OpenAI keys, JWT tokens, private keys, and config passwords.',
    seoDescription: 'Free online Secret Scanner — Scan text and code for leaked API keys, tokens, and credentials. Detects Stripe, GitHub, Slack, AWS, Google, OpenAI, and more. ',
    dependencies: "None",
},
  {

    id: "990",
    name: "security.txt Generator",
    slug: "security-txt-generator",
    category: "Developer",
    description: 'Generate a security.txt file for your website following RFC 9116 standard. Specify contact email, security policy URL, encryption key, and expiry date for vulnerability disclosure.',
    seoDescription: 'Free online security.txt Generator — Generate RFC 9116 security.txt files with contact, policy, encryption, and expiry fields for vulnerability disclosure. ',
    dependencies: "None",
},
  {

    id: "991",
    name: "robots.txt Validator",
    slug: "robots-txt-validator",
    category: "Developer",
    description: 'Validate robots.txt syntax — checks User-agent, Allow, Disallow, Sitemap, Crawl-delay directives. Identifies unknown directives, missing colons, and missing User-agent declarations.',
    seoDescription: 'Free online robots.txt Validator — Validate robots.txt directives: User-agent, Allow, Disallow, Sitemap. Detects syntax errors and missing declarations. ',
    dependencies: "None",
},
  {

    id: "992",
    name: "DNS Record Validator",
    slug: "dns-record-validator",
    category: "Developer",
    description: 'Validate DNS record syntax for A, AAAA, CNAME, MX, TXT, NS, SOA, SRV, CAA, and PTR records. Checks IP format for A/AAAA records and domain validity for MX records.',
    seoDescription: 'Free online DNS Record Validator — Validate DNS records: A, AAAA, CNAME, MX, TXT, NS, SOA, SRV, CAA, PTR. Checks IP format and domain validity. ',
    dependencies: "None",
},
  {

    id: "993",
    name: "Docker Compose Validator",
    slug: "docker-compose-validator",
    category: "Developer",
    description: 'Validate docker-compose.yml files — checks YAML syntax, correct indentation, tab usage, and the presence of the services section. Identifies mixed indentation and formatting issues.',
    seoDescription: 'Free online Docker Compose Validator — Validate docker-compose.yml YAML syntax, indentation, services section, and formatting. ',
    dependencies: "None",
},
  {

    id: "994",
    name: "Dockerfile Linter",
    slug: "dockerfile-linter",
    category: "Developer",
    description: 'Lint Dockerfiles against 20+ valid instructions (FROM, RUN, CMD, COPY, ENTRYPOINT, HEALTHCHECK, SHELL). Detects unknown instructions and missing FROM declaration.',
    seoDescription: 'Free online Dockerfile Linter — Lint Dockerfiles with 20+ valid instructions. Checks FROM, RUN, CMD, COPY, ENTRYPOINT, HEALTHCHECK. ',
    dependencies: "None",
},
  {

    id: "995",
    name: "htaccess Validator",
    slug: "htaccess-validator",
    category: "Developer",
    description: 'Validate .htaccess files against 30+ known Apache directives. Checks RewriteEngine, RewriteRule, ErrorDocument, Redirect, Header, Options, and block directives. Flags unknown directives.',
    seoDescription: 'Free online htaccess Validator — Validate .htaccess files with 30+ Apache directives. Checks RewriteRule, ErrorDocument, Header, Options. ',
    dependencies: "None",
},
  {

    id: "996",
    name: "Kubernetes YAML Validator",
    slug: "kubernetes-yaml-validator",
    category: "Developer",
    description: 'Validate Kubernetes YAML manifests — checks for required fields (apiVersion, kind, metadata), correct YAML structure, indentation, and tab usage.',
    seoDescription: 'Free online Kubernetes YAML Validator — Validate K8s manifests for apiVersion, kind, metadata, and YAML structure correctness. ',
    dependencies: "None",
},
  {

    id: "997",
    name: "GitHub Actions Validator",
    slug: "github-actions-validator",
    category: "Developer",
    description: 'Validate GitHub Actions workflow YAML — checks for workflow name, on trigger, jobs section, and correct YAML structure. Identifies formatting issues and missing fields.',
    seoDescription: 'Free online GitHub Actions Validator — Validate workflow YAML for name, on trigger, jobs section, and YAML structure. ',
    dependencies: "None",
},
  {

    id: "998",
    name: "GeoJSON Validator",
    slug: "geojson-validator",
    category: "Developer",
    description: 'Validate GeoJSON objects against the GeoJSON specification. Checks feature, geometry, point coordinates, FeatureCollection structure, and bounding box format.',
    seoDescription: 'Free online GeoJSON Validator — Validate GeoJSON for feature, geometry, point coordinates, FeatureCollection, and bbox correctness. ',
    dependencies: "None",
},
  {

    id: "999",
    name: "RSS Feed Validator",
    slug: "rss-feed-validator",
    category: "Developer",
    description: 'Validate RSS 2.0 and Atom feed XML — checks root element, channel/feed, title, link, description, items/entries, and XML declaration.',
    seoDescription: 'Free online RSS Feed Validator — Validate RSS 2.0 and Atom feeds for root element, channel, title, link, description, items, and XML declaration. ',
    dependencies: "None",
},
  {

    id: "1000",
    name: "Sitemap Validator",
    slug: "sitemap-validator",
    category: "Developer",
    description: 'Validate XML sitemaps — checks urlset/sitemapindex root, loc entries, XML declaration, and URL count. Supports standard sitemap protocol formatting.',
    seoDescription: 'Free online Sitemap Validator — Validate XML sitemaps for urlset, loc entries, XML declaration, and sitemap protocol compliance. ',
    dependencies: "None",
},
  {

    id: "1001",
    name: "XPath Validator",
    slug: "xpath-validator",
    category: "Developer",
    description: 'Test XPath expressions against XML or HTML documents. Evaluates queries and displays matching results in real time. Checks XML parsing errors before evaluation.',
    seoDescription: 'Free online XPath Validator — Test XPath expressions against XML/HTML. Evaluate queries and see matching results instantly. ',
    dependencies: "None",
},
  {

    id: "1002",
    name: "Cron Expression Validator",
    slug: "cron-expression-validator",
    category: "Developer",
    description: 'Validate cron expressions with field-level range checking. Supports 5-field format with step values, ranges, lists, and wildcards. Detects out-of-bounds values and provides readable descriptions.',
    seoDescription: 'Free online Cron Expression Validator — Validate cron expressions with field-level range checking, step values, lists, and wildcards. ',
    dependencies: "None",
},
  {

    id: "gt-1",
    name: "Random Date Generator",
    slug: "random-date-generator",
    category: "Utility",
    description: 'Generate random dates within a configurable range with optional format selection including ISO, US, EU, and full-date styles. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Date Generator — Generate random dates within a configurable range with optional format selection including ISO, US, EU, and full-date styles. ',
    dependencies: "Vanilla JS",
},
  {

    id: "gt-2",
    name: "Random Time Generator",
    slug: "random-time-generator",
    category: "Utility",
    description: 'Generate random times in 12-hour or 24-hour format with optional seconds and configurable time range. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Time Generator — Generate random times in 12-hour or 24-hour format with optional seconds and configurable time range. ',
    dependencies: "Vanilla JS",
},
  {

    id: "gt-3",
    name: "Random IP Generator",
    slug: "random-ip-generator",
    category: "Developer",
    description: 'Generate random IPv4 and IPv6 addresses for network testing, development, and security research. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random IP Generator — Generate random IPv4 and IPv6 addresses for network testing, development, and security research. ',
    dependencies: "Vanilla JS",
},
  {

    id: "gt-4",
    name: "Random User-Agent Generator",
    slug: "random-user-agent-generator",
    category: "Developer",
    description: 'Generate random browser user-agent strings from a curated list covering Chrome, Firefox, Safari, Edge, and mobile browsers. No signup or account required.',
    seoDescription: 'Free online Random User-Agent Generator — Generate random browser user-agent strings from a curated list covering Chrome, Firefox, Safari, Edge, and mobile browsers. ',
    dependencies: "Vanilla JS",
},
  {

    id: "gt-5",
    name: "Random Sentence Generator",
    slug: "random-sentence-generator",
    category: "Utility",
    description: 'Generate random sentences from a curated word list, useful for placeholder text and content generation. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Sentence Generator — Generate random sentences from a curated word list, useful for placeholder text and content generation. ',
    dependencies: "Vanilla JS",
},
  {

    id: "gt-6",
    name: "Random Word Generator",
    slug: "random-word-generator",
    category: "Utility",
    description: 'Generate random words from a curated vocabulary list for brainstorming, naming, and word games. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Random Word Generator — Generate random words from a curated vocabulary list for brainstorming, naming, and word games. ',
    dependencies: "Vanilla JS",
},
  {

    id: "gt-7",
    name: "PIN Generator",
    slug: "pin-generator",
    category: "Developer",
    description: 'Generate numeric PINs of configurable length from 4 to 10 digits for security codes, verification codes, and access tokens. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online PIN Generator — Generate numeric PINs of configurable length from 4 to 10 digits for security codes, verification codes, and access tokens. ',
    dependencies: "Crypto API",
},
  {

    id: "gt-8",
    name: "License Key Generator",
    slug: "license-key-generator",
    category: "Developer",
    description: 'Generate license keys in custom formats with configurable character sets, segment separators, and prefix/suffix options. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online License Key Generator — Generate license keys in custom formats with configurable character sets, segment separators, and prefix/suffix options. ',
    dependencies: "Vanilla JS",
},
  {

    id: "gt-9",
    name: "Image Placeholder Generator",
    slug: "image-placeholder-generator",
    category: "Developer",
    description: 'Generate SVG image placeholders as base64 data URIs with configurable dimensions and random background colors for prototyping. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Image Placeholder Generator — Generate SVG image placeholders as base64 data URIs with configurable dimensions and random background colors for prototyping. ',
    dependencies: "Canvas API",
},
  {

    id: "gt-10",
    name: "Logo Placeholder Generator",
    slug: "logo-placeholder-generator",
    category: "Developer",
    description: 'Generate brand logo placeholders as SVG with random brand names, initials, colors, and configurable size for design mockups. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Logo Placeholder Generator — Generate brand logo placeholders as SVG with random brand names, initials, colors, and configurable size for design mockups. ',
    dependencies: "Canvas API",
},
  {

    id: "gt-11",
    name: "Open Graph Generator",
    slug: "open-graph-generator",
    category: "Developer",
    description: 'Generate Open Graph (og:) and Twitter Card meta tags for social sharing, with fields for title, description, URL, and image. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Open Graph Generator — Generate Open Graph (og:) and Twitter Card meta tags for social sharing, with fields for title, description, URL, and image. ',
    dependencies: "Vanilla JS",
},
  {

    id: "gt-12",
    name: "OAuth PKCE Generator",
    slug: "oauth-pkce-generator",
    category: "Developer",
    description: 'Generate RFC 7636 OAuth PKCE code_verifier + code_challenge (S256 method) pairs. Verifier uses 48 bytes → 64-char base64url, challenge uses SHA-256. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online OAuth PKCE Generator — Generate RFC 7636 OAuth PKCE code_verifier + code_challenge (S256 method) pairs. Verifier uses 48 bytes → 64-char base64url, challenge uses SHA-256. ',
    dependencies: "Crypto API (Web Crypto)",
},
  {

    id: "ce-1",
    name: "Cooking Measurement Converter",
    slug: "cooking-measurement-converter",
    category: "Utility",
    description: 'Convert cooking measurements between teaspoons, tablespoons, fluid ounces, cups, pints, quarts, gallons, milliliters, and liters. Includes tsp and tbsp not found in the volume converter.',
    seoDescription: 'Free online Cooking Measurement Converter — Convert between teaspoons, tablespoons, fluid ounces, cups, pints, quarts, gallons, milliliters, and liters. Includes tsp and tbsp. ',
    dependencies: "Vanilla JS",
},
  {

    id: "ce-2",
    name: "Fuel Consumption Converter",
    slug: "fuel-consumption-converter",
    category: "Utility",
    description: 'Convert fuel economy between L/100km, MPG (US), MPG (UK), and km/L. Essential for comparing vehicle efficiency across metric and imperial systems.',
    seoDescription: 'Free online Fuel Consumption Converter — Convert fuel economy between L/100km, MPG (US), MPG (UK), and km/L. ',
    dependencies: "Vanilla JS",
},
  {

    id: "ce-3",
    name: "Paper Size Converter",
    slug: "paper-size-converter",
    category: "Utility",
    description: 'Compare and convert between A0, A1, A4, Letter, and Legal paper sizes. Understand how many sheets of one size fit into another.',
    seoDescription: 'Free online Paper Size Converter — Compare and convert between A0, A1, A4, Letter, and Legal paper sizes. ',
    dependencies: "Vanilla JS",
},
  {

    id: "ce-4",
    name: "Clothing Size Converter",
    slug: "clothing-size-converter",
    category: "Utility",
    description: 'Convert clothing sizes between US/Canada, UK, EU, Japan, and France sizing systems. Supports women\'s apparel size conversions with international standards.',
    seoDescription: 'Free online Clothing Size Converter — Convert clothing sizes between US/Canada, UK, EU, Japan, and France sizing systems. ',
    dependencies: "Vanilla JS",
},
  {

    id: "ce-5",
    name: "Large Text File Viewer",
    slug: "large-text-viewer",
    category: "Utility",
    description: 'View and search large text files (logs, CSVs, JSON) up to 100K characters in the browser with text search and match counting. No file upload needed — all client-side.',
    seoDescription: 'Free online Large Text File Viewer — View and search large text files up to 100K characters with text search. All client-side, no uploads. ',
    dependencies: "FileReader API",
},
  {

    id: "ce-6",
    name: "Avro Schema Generator",
    slug: "avro-schema-generator",
    category: "Developer",
    description: 'Generate Apache Avro schemas from a JSON field definition. Configure namespace, record name, and field types — outputs valid Avro schema JSON.',
    seoDescription: 'Free online Avro Schema Generator — Generate Apache Avro schemas from JSON field definitions. Configure namespace, record name, and field types. ',
    dependencies: "Vanilla JS",
},
  {

    id: "ce-7",
    name: "Avro to JSON Sample Generator",
    slug: "avro-to-json-sample",
    category: "Developer",
    description: 'Generate sample JSON data from an Avro schema. Auto-generates values based on field types. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Avro to JSON Sample Generator — Generate sample JSON data from an Avro schema. Auto-generates values based on field types. ',
    dependencies: "Vanilla JS",
},
  {

    id: "ce-8",
    name: "iCal Event Generator",
    slug: "ical-event-generator",
    category: "Utility",
    description: 'Generate .ics calendar files for any event. Set summary, dates, times, description, and location — download or copy ready-to-import iCal (RFC 5545) format.',
    seoDescription: 'Free online iCal Event Generator — Generate .ics calendar files for any event with summary, dates, times, description, and location. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-1",
    name: "Column Extractor",
    slug: "column-extractor",
    category: "Utility",
    description: 'Extract specific columns from CSV data by header name. Select the columns you need and get a clean CSV with only your chosen fields.',
    seoDescription: 'Free online CSV Column Extractor — Extract specific columns from CSV data by header name, output only the fields you need. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-2",
    name: "Column Renamer",
    slug: "column-renamer",
    category: "Utility",
    description: 'Rename CSV column headers in bulk using old:new mapping. Quickly relabel columns for data standardization and reporting.',
    seoDescription: 'Free online CSV Column Renamer — Rename CSV column headers in bulk using old:new mapping. Relabel columns for data standardization. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-3",
    name: "Data Type Converter",
    slug: "data-type-converter",
    category: "Utility",
    description: 'Convert CSV column data types between number, string, integer, and float. Ensure consistent typing across your dataset.',
    seoDescription: 'Free online CSV Data Type Converter — Convert CSV column data to number, string, integer, or float. Consistent typing across your dataset. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-4",
    name: "CSV Deduplicator",
    slug: "deduplicator",
    category: "Utility",
    description: 'Remove duplicate rows from CSV data based on a specific column. Keep only unique values for cleaner datasets.',
    seoDescription: 'Free online CSV Deduplicator — Remove duplicate rows from CSV data based on a specific column. Keep only unique values. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-5",
    name: "CSV Format Validator",
    slug: "format-validator",
    category: "Utility",
    description: 'Validate CSV formatting — detect inconsistent column counts, quoting errors, and malformed rows. Get detailed issue reports.',
    seoDescription: 'Free online CSV Format Validator — Validate CSV formatting, detect inconsistent columns, quoting errors, and malformed rows. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-6",
    name: "CSV Merger",
    slug: "csv-merger",
    category: "Developer",
    description: 'Merge two CSV files on a common column. Join datasets horizontally by matching key values, like a SQL JOIN for your spreadsheets.',
    seoDescription: 'Free online CSV Merger — Merge two CSV files on a common column. Join datasets horizontally by matching key values. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-7",
    name: "Null Value Handler",
    slug: "null-value-handler",
    category: "Utility",
    description: 'Replace empty, null, or NA values in CSV data with a custom fill value. Clean your datasets for analysis and migration.',
    seoDescription: 'Free online Null Value Handler — Replace empty/null/NA values in CSV data with a custom fill value. Clean datasets for analysis. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-8",
    name: "CSV Pivot Generator",
    slug: "pivot-generator",
    category: "Utility",
    description: 'Generate pivot tables from CSV data by specifying group and value columns. Transform long-format data into summary tables. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSV Pivot Generator — Generate pivot tables from CSV data by specifying group and value columns. Transform long-format data into summary tables. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-9",
    name: "CSV Row Filter",
    slug: "row-filter",
    category: "Utility",
    description: 'Filter CSV rows by column value matching. Includes exact match, contains, and not-equal operators for flexible data selection.',
    seoDescription: 'Free online CSV Row Filter — Filter CSV rows by column value with exact match, contains, and not-equal operators. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-10",
    name: "CSV Row Sorter",
    slug: "csv-row-sorter",
    category: "Utility",
    description: 'Sort CSV rows by any column in ascending or descending order. Quickly organize your data for analysis and reporting.',
    seoDescription: 'Free online CSV Row Sorter — Sort CSV rows by any column in ascending or descending order. Organize data for analysis. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-11",
    name: "CSV Splitter",
    slug: "csv-splitter",
    category: "Developer",
    description: 'Split a large CSV file into multiple smaller files by page count. Divide datasets into manageable chunks for processing.',
    seoDescription: 'Free online CSV Splitter — Split large CSV files into multiple smaller files by page count. Divide datasets into manageable chunks. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-12",
    name: "CSV Transpose",
    slug: "csv-transpose",
    category: "Developer",
    description: 'Transpose CSV data — swap rows and columns. Convert horizontal data to vertical and vice versa for reformatting.',
    seoDescription: 'Free online CSV Transpose — Swap rows and columns in CSV data. Convert horizontal to vertical and vice versa. ',
    dependencies: "Vanilla JS",
},
  {
    id: "dt-13",
    name: "CSV to Markdown Table",
    slug: "csv-to-markdown",
    category: "Converter",
    description: 'Convert CSV data into GitHub-flavored Markdown tables for docs and README files. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSV to Markdown Table — Convert CSV data into GitHub-flavored Markdown tables for docs and README files. ',
    dependencies: "Vanilla JS",
  },
  {

    id: "dt-14",
    name: "CSV to NDJSON",
    slug: "csv-to-ndjson",
    category: "Utility",
    description: 'Convert CSV to Newline Delimited JSON. Each row becomes a separate JSON object. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSV to NDJSON — Convert CSV to Newline Delimited JSON. Each row becomes a separate JSON object. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-15",
    name: "CSV to SQL INSERT",
    slug: "csv-to-sql",
    category: "Developer",
    description: 'Converts CSV files to SQL format — spreadsheets, database exports, and data imports to relational database operations, data analysis, and reporting. All conversion happens locally in your browser with no file size limits.',
    seoDescription: 'Free online CSV to SQL INSERT — Generate SQL INSERT statements from CSV data with custom table names. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-16",
    name: "JSON Escape/Unescape",
    slug: "json-escape-unescape",
    category: "Developer",
    description: 'Escape or unescape JSON strings — convert special characters to their JSON-safe escaped equivalents and back.',
    seoDescription: 'Free online JSON Escape/Unescape — Escape or unescape JSON strings. Convert special characters to safe equivalents and back. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-17",
    name: "JSON Flattener",
    slug: "json-flattener",
    category: "Developer",
    description: 'Flatten nested JSON objects into dot-notation key-value pairs. Unwrap complex hierarchies for tabular processing.',
    seoDescription: 'Free online JSON Flattener — Flatten nested JSON into dot-notation key-value pairs. Unwrap complex hierarchies for tabular processing. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-18",
    name: "JSON-LD Generator",
    slug: "json-ld-generator",
    category: "Developer",
    description: 'Wrap JSON data in valid JSON-LD (Linked Data) structure with @context and @type. Generate schema.org-compatible structured data.',
    seoDescription: 'Free online JSON-LD Generator — Wrap JSON data in valid JSON-LD with @context and @type. Schema.org-compatible structured data. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-19",
    name: "Merge Patch Generator",
    slug: "merge-patch-generator",
    category: "Developer",
    description: 'Generate JSON Merge Patch (RFC 7396) documents by comparing original and modified JSON objects. Show exactly what changed.',
    seoDescription: 'Free online Merge Patch Generator — Generate JSON Merge Patch (RFC 7396) documents by comparing original and modified JSON. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-20",
    name: "JSON Schema Generator",
    slug: "json-schema-generator",
    category: "Developer",
    description: 'Generate a JSON Schema (draft-07) from sample JSON data. Auto-detect types, required fields, and nested structures.',
    seoDescription: 'Free online JSON Schema Generator — Generate JSON Schema (draft-07) from sample JSON. Auto-detect types and nested structures. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-21",
    name: "JSON Size Analyzer",
    slug: "json-size-analyzer",
    category: "Developer",
    description: 'Analyze JSON payload size, character count, key count, and nesting depth. Understand the size profile of your data.',
    seoDescription: 'Free online JSON Size Analyzer — Analyze JSON payload size, character count, key count, and nesting depth. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-22",
    name: "JSON to Zod Schema",
    slug: "json-to-zod",
    category: "Developer",
    description: 'Generate Zod validation schemas from sample JSON data. TypeScript runtime validation. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JSON to Zod Schema — Generate Zod validation schemas from sample JSON data. TypeScript runtime validation. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-23",
    name: "JWK Generator",
    slug: "jwk-generator",
    category: "Developer",
    description: 'Generate JSON Web Keys (JWK) with RSA key sizes of 2048 or 4096 bits. Export public and private keys in JWK format.',
    seoDescription: 'Free online JWK Generator — Generate JSON Web Keys (JWK) with 2048 or 4096 bit RSA. Export public/private key pairs. ',
    dependencies: "Web Crypto API",
},
  {

    id: "dt-24",
    name: "JSONL Formatter",
    slug: "jsonl-formatter",
    category: "Developer",
    description: 'Format JSON Lines (JSONL) data — pretty-print each line as formatted JSON for readability and debugging.',
    seoDescription: 'Free online JSONL Formatter — Format JSON Lines data, pretty-print each line as formatted JSON for readability. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-25",
    name: "NDJSON to JSON Array",
    slug: "ndjson-to-json",
    category: "Developer",
    description: 'Convert Newline Delimited JSON into a standard JSON array format. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online NDJSON to JSON Array — Convert Newline Delimited JSON into a standard JSON array format. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-26",
    name: "JSON to URL Parameters",
    slug: "json-to-url-params",
    category: "Developer",
    description: 'Convert JSON objects into URL query string parameters for API calls and web requests. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JSON to URL Parameters — Convert JSON objects into URL query string parameters for API calls and web requests. ',
    dependencies: "Vanilla JS",
},
  {

    id: "dt-27",
    name: "CSV Row / JSON Generator",
    slug: "csv-json-row-generator",
    category: "Utility",
    description: 'Generate realistic dummy data as CSV rows or JSON objects. Configure count (1-50) for test data, demos, and prototyping.',
    seoDescription: 'Free online CSV Row / JSON Generator — Generate realistic dummy data as CSV rows or JSON objects for test data and prototyping. ',
    dependencies: "Vanilla JS",
},
  {

    id: "css-1",
    name: "Glassmorphism CSS Generator",
    slug: "glassmorphism-generator",
    category: "Developer",
    description: 'Generate glassmorphism CSS with adjustable blur, opacity, and border radius. Copy ready-to-use CSS for frosted-glass UI effects. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Glassmorphism CSS Generator — Generate glassmorphism CSS with adjustable blur, opacity, and border radius. Copy ready-to-use CSS for frosted-glass UI effects. ',
    dependencies: "None",
    showInCategory: false,
},
  {

    id: "css-2",
    name: "Neumorphism CSS Generator",
    slug: "neumorphism-generator",
    category: "Developer",
    description: 'Generate neumorphism CSS with configurable size, blur, and color. Create soft UI shadow effects with live preview.',
    seoDescription: 'Free online Neumorphism CSS Generator — Generate neumorphism CSS with configurable size, blur, and color. Create soft UI shadow effects. ',
    dependencies: "None",
    showInCategory: false,
},
  {

    id: "css-3",
    name: "CSS Specificity Calculator",
    slug: "css-specificity-calculator",
    category: "Developer",
    description: 'Calculate CSS selector specificity as (IDs, classes, tags) and total weight. Understand which selector wins in a specificity conflict.',
    seoDescription: 'Free online CSS Specificity Calculator — Calculate CSS selector specificity as (IDs, classes, tags) and total weight. Understand which selector wins. ',
    dependencies: "None",
},
  {
    id: "css-4",
    name: "CSS to SCSS Converter",
    slug: "css-to-scss-converter",
    category: "Converter",
    description: 'Convert plain CSS to SCSS syntax with nesting and parent selector references. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSS to SCSS Converter — Convert plain CSS to SCSS syntax with nesting and parent selector references. ',
    dependencies: "None",
  },
  {
    id: "css-5",
    name: "Less to CSS Converter",
    slug: "less-to-css-converter",
    category: "Converter",
    description: 'Convert Less variables and syntax to plain CSS. Comment out Less variables and output standard CSS. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Less to CSS Converter — Convert Less variables and syntax to plain CSS. Comment out Less variables and output standard CSS. ',
    dependencies: "None",
  },
  {

    id: "css-6",
    name: "CSS Validator",
    slug: "css-validator",
    category: "Developer",
    description: 'Validate CSS for missing semicolons, unclosed braces, and syntax issues. Get line-by-line error reports.',
    seoDescription: 'Free online CSS Validator — Validate CSS for missing semicolons, unclosed braces, and syntax issues. Line-by-line error reports. ',
    dependencies: "None",
},
  {

    id: "code-1",
    name: "Code Obfuscator",
    slug: "code-obfuscator",
    category: "Developer",
    description: 'Obfuscate or deobfuscate code using Base64 encoding with reversed output. Quick one-way code protection for sharing.',
    seoDescription: 'Free online Code Obfuscator — Obfuscate or deobfuscate code using Base64 encoding with reversed output. Quick code protection for sharing. ',
    dependencies: "None",
},
  {

    id: "code-2",
    name: "Code to cURL Parser",
    slug: "code-to-curl-parser",
    category: "Developer",
    description: 'Parse cURL commands to extract method, URL, headers, and body. Debug HTTP requests from cURL strings. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Code to cURL Parser — Parse cURL commands to extract method, URL, headers, and body. Debug HTTP requests from cURL strings. ',
    dependencies: "None",
},
  {

    id: "code-3",
    name: "JavaScript Syntax Checker",
    slug: "js-syntax-checker",
    category: "Developer",
    description: 'Check JavaScript code for syntax errors using the Function constructor. Validate code before execution. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online JavaScript Syntax Checker — Check JavaScript code for syntax errors using the Function constructor. Validate code before execution. ',
    dependencies: "None",
},
  {

    id: "code-4",
    name: "Pug to HTML Converter",
    slug: "pug-to-html-converter",
    category: "Developer",
    description: 'Convert Pug/Jade template syntax to HTML. Parse indentation-based Pug into standard HTML tags. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Pug to HTML Converter — Convert Pug/Jade template syntax to HTML. Parse indentation-based Pug into standard HTML tags. ',
    dependencies: "None",
},
  {
    id: "text-tools-hub",
    name: "Text Converter",
    slug: "text-tools",
    category: "Converter",
    description: 'Convert between case styles, CSS preprocessors (SCSS/Less/Stylus), HTML/JSX, number bases, serialization formats (YAML/INI/TOML/JSON), and time zones. One tool for all text transformations.',
    seoDescription: 'Free online Text Converter — Convert between case styles, CSS preprocessors, HTML/JSX, number bases, serialization formats, and time zones. ',
    dependencies: "None",
    showInCategory: false,
  },
  {

    id: "json-formatter-tool-hub",
    name: "JSON Output Tools",
    slug: "json-formatter-tool",
    category: "Developer",
    description: 'Format, validate, and convert JSON to Zod schemas, URL query parameters, flat key-value pairs, JSON-LD, or analyze size and structure.',
    seoDescription: 'Free online JSON Output Tools — Format JSON, generate Zod schemas, convert to URL params, flatten, create JSON-LD, and analyze size. ',
    dependencies: "None",
    showInCategory: true,
},
  {

    id: "csv-formatter-hub",
    name: "CSV Output Tools",
    slug: "csv-formatter",
    category: "Utility",
    description: 'Convert CSV data to Markdown tables, NDJSON, SQL INSERT statements, HTML tables, or analyze statistics and find data quality issues.',
    seoDescription: 'Free online CSV Output Tools — Convert CSV to Markdown, NDJSON, SQL, HTML tables, or analyze statistics and data quality. ',
    dependencies: "None",
    showInCategory: true,
},
  {
    id: "import-to-csv-hub",
    name: "Import to CSV",
    slug: "import-to-csv",
    category: "Converter",
    description: 'Convert TSV, Excel XLSX, vCard VCF, iCalendar ICS, and Parquet files to CSV. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online Import to CSV Converter — Convert TSV, Excel XLSX, vCard VCF, iCalendar ICS, and Parquet files to CSV. ',
    dependencies: "None",
    showInCategory: true,
  },

  {

    id: "cb-1",
    name: "Color Blindness Simulator",
    slug: "color-blindness-simulator",
    category: "Design",
    description: 'Simulate how your designs and images appear to users with protanopia, deuteranopia, tritanopia, and achromatopsia color vision deficiencies.',
    seoDescription: 'Free online Color Blindness Simulator — Simulate how designs and images appear with protanopia, deuteranopia, tritanopia, and achromatopsia color vision deficiencies. ',
    dependencies: "Canvas API",
  },
  {

    id: "cf-cpp",
    name: "C++ Formatter",
    slug: "cpp-formatter",
    category: "Developer",
    description: 'Format and beautify C++ source code with configurable indentation, brace style, and spacing. Supports modern C++11 through C++23 syntax.',
    seoDescription: 'Free online C++ Formatter — Format and beautify C++ source code with configurable indentation, brace style, and spacing. Supports modern C++ standards. ',
    dependencies: "None",
},
  {

    id: "cf-go",
    name: "Go Formatter",
    slug: "go-formatter",
    category: "Developer",
    description: 'Format and beautify Go source code with proper indentation, alignment, and standard gofmt-style conventions. Clean up any Go file instantly.',
    seoDescription: 'Free online Go Formatter — Format and beautify Go source code with proper indentation and gofmt-style conventions. ',
    dependencies: "None",
},
  {

    id: "cf-kt",
    name: "Kotlin Formatter",
    slug: "kotlin-formatter",
    category: "Developer",
    description: 'Format and beautify Kotlin source code with correct indentation, spacing, and brace placement. Supports Kotlin DSL, coroutines, and modern syntax.',
    seoDescription: 'Free online Kotlin Formatter — Format and beautify Kotlin source code with correct indentation, spacing, and brace placement. ',
    dependencies: "None",
},
  {

    id: "cf-php",
    name: "PHP Beautifier",
    slug: "php-beautifier",
    category: "Developer",
    description: 'Beautify and format PHP source code with proper indentation, brace style, and spacing. Handles PHP, HTML embedded PHP, and mixed syntax files.',
    seoDescription: 'Free online PHP Beautifier — Beautify and format PHP source code with proper indentation, brace style, and spacing. Handles embedded PHP in HTML. ',
    dependencies: "None",
},
  {

    id: "cf-rb",
    name: "Ruby Formatter",
    slug: "ruby-formatter",
    category: "Developer",
    description: 'Format and beautify Ruby source code with proper indentation, spacing, and block alignment. Supports modern Ruby syntax and Rails conventions.',
    seoDescription: 'Free online Ruby Formatter — Format and beautify Ruby source code with proper indentation, spacing, and block alignment. ',
    dependencies: "None",
},
  {

    id: "cf-rs",
    name: "Rust Formatter",
    slug: "rust-formatter",
    category: "Developer",
    description: 'Format and beautify Rust source code with proper indentation, spacing, and brace placement. Handles Rust macros, traits, generics, and module structure.',
    seoDescription: 'Free online Rust Formatter — Format and beautify Rust source code with proper indentation, spacing, and brace placement. ',
    dependencies: "None",
},
  {

    id: "jwt-e-1",
    name: "JWT Encoder & Signer",
    slug: "jwt-encoder-signer",
    category: "Developer",
    description: 'Create and sign JSON Web Tokens with custom header and payload. Supports HS256, HS384, HS512 signing algorithms for API authentication testing.',
    seoDescription: 'Free online JWT Encoder & Signer — Create and sign JSON Web Tokens with custom header and payload. Supports HS256, HS384, and HS512 algorithms. ',
    dependencies: "None",
},
  {

    id: "mp-1",
    name: "Memorable Password Generator",
    slug: "memorable-password-generator",
    category: "Developer",
    description: 'Generate easy-to-remember passphrases using random word combinations with separators, numbers, and capitalization. More secure than dictionary words, easier to remember than random strings.',
    seoDescription: 'Free online Memorable Password Generator — Generate easy-to-remember passphrases using random word combinations with separators, numbers, and capitalization. ',
    dependencies: "None",
},
  {
    id: "ytt-1",
    name: "YAML → Toon Converter",
    slug: "yaml-to-toon",
    category: "Converter",
    description: 'Convert YAML data into a human-readable Toon format using → arrows. Perfect for quick visualization of hierarchical YAML structures.',
    seoDescription: 'Free online YAML → Toon Converter — Convert YAML data into a human-readable Toon format using arrows for quick visualization of hierarchical structures. ',
    dependencies: "None",
  },
  {
    id: "ttj-1",
    name: "Toon → JSON Converter",
    slug: "toon-to-json",
    category: "Converter",
    description: 'Convert Toon format (→ arrows) back into JSON. Reverse of the JSON → Toon converter for round-trip data transformation.',
    seoDescription: 'Free online Toon → JSON Converter — Convert Toon format back into JSON for round-trip data transformation. ',
    dependencies: "None",
  },
  {
    id: "tty-1",
    name: "Toon → YAML Converter",
    slug: "toon-to-yaml",
    category: "Converter",
    description: 'Convert Toon format (→ arrows) back into YAML. Complete the round-trip from any source format.',
    seoDescription: 'Free online Toon → YAML Converter — Convert Toon format back into YAML for complete round-trip data transformation. ',
    dependencies: "None",
  },
  {
    id: "1003",
    name: "MKV to WEBM",
    slug: "mkv-to-webm",
    category: "Video",
    description: 'Convert MKV video files to WEBM format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online MKV to WEBM — Convert MKV video files into WEBM format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1004",
    name: "MKV to AVI",
    slug: "mkv-to-avi",
    category: "Video",
    description: 'Convert MKV video files to AVI format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online MKV to AVI — Convert MKV video files into AVI format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1005",
    name: "MP4 to WEBM",
    slug: "mp4-to-webm",
    category: "Video",
    description: 'Convert MP4 video files to WEBM format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online MP4 to WEBM — Convert MP4 video files into WEBM format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1006",
    name: "MP4 to AVI",
    slug: "mp4-to-avi",
    category: "Video",
    description: 'Convert MP4 video files to AVI format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online MP4 to AVI — Convert MP4 video files into AVI format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1007",
    name: "MOV to WEBM",
    slug: "mov-to-webm",
    category: "Video",
    description: 'Convert MOV video files to WEBM format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online MOV to WEBM — Convert MOV video files into WEBM format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1008",
    name: "MOV to AVI",
    slug: "mov-to-avi",
    category: "Video",
    description: 'Convert MOV video files to AVI format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online MOV to AVI — Convert MOV video files into AVI format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1009",
    name: "WEBM to MKV",
    slug: "webm-to-mkv",
    category: "Video",
    description: 'Convert WEBM video files to MKV format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online WEBM to MKV — Convert WEBM video files into MKV format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1010",
    name: "WEBM to MOV",
    slug: "webm-to-mov",
    category: "Video",
    description: 'Convert WEBM video files to MOV format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online WEBM to MOV — Convert WEBM video files into MOV format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1011",
    name: "WEBM to AVI",
    slug: "webm-to-avi",
    category: "Video",
    description: 'Convert WEBM video files to AVI format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online WEBM to AVI — Convert WEBM video files into AVI format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1012",
    name: "AVI to MKV",
    slug: "avi-to-mkv",
    category: "Video",
    description: 'Convert AVI video files to MKV format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online AVI to MKV — Convert AVI video files into MKV format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1013",
    name: "AVI to MOV",
    slug: "avi-to-mov",
    category: "Video",
    description: 'Convert AVI video files to MOV format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online AVI to MOV — Convert AVI video files into MOV format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1014",
    name: "AVI to WEBM",
    slug: "avi-to-webm",
    category: "Video",
    description: 'Convert AVI video files to WEBM format directly in your browser. 100% free, private — your files never leave your device.',
    seoDescription: 'Free online AVI to WEBM — Convert AVI video files into WEBM format. Fast browser-based video conversion.',
    dependencies: "FFmpeg",

    showInCategory: false
  },
  {
    id: "1015",
    name: "JPG to PNG",
    slug: "jpg-to-png",
    category: "Image",
    description: 'Convert JPG images to PNG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to PNG — Convert JPG images into PNG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1016",
    name: "PNG to WEBP",
    slug: "png-to-webp",
    category: "Image",
    description: 'Convert PNG images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PNG to WEBP — Convert PNG images into WEBP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1017",
    name: "JPG to WEBP",
    slug: "jpg-to-webp",
    category: "Image",
    description: 'Convert JPG images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to WEBP — Convert JPG images into WEBP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1018",
    name: "WEBP to PNG",
    slug: "webp-to-png",
    category: "Image",
    description: 'Converts WebP files to PNG format — modern websites to graphics with sharp edges, text overlays, screenshots, and images requiring transparent backgrounds. All conversion happens locally in your browser with no file size limits.',
    seoDescription: 'Free online WEBP to PNG — Convert WEBP images into PNG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1019",
    name: "HEIC to PNG",
    slug: "heic-to-png",
    category: "Image",
    description: 'Converts HEIC files to PNG format — Apple device photos to graphics with sharp edges, text overlays, screenshots, and images requiring transparent backgrounds. All conversion happens locally in your browser with no file size limits.',
    seoDescription: 'Free online HEIC to PNG — Convert HEIC images into PNG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1020",
    name: "PNG to AVIF",
    slug: "png-to-avif",
    category: "Image",
    description: 'Convert PNG images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PNG to AVIF — Convert PNG images into AVIF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1021",
    name: "JPG to AVIF",
    slug: "jpg-to-avif",
    category: "Image",
    description: 'Convert JPG images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to AVIF — Convert JPG images into AVIF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1022",
    name: "PNG to HEIC",
    slug: "png-to-heic",
    category: "Image",
    description: 'Convert PNG images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PNG to HEIC — Convert PNG images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1023",
    name: "PNG to BMP",
    slug: "png-to-bmp",
    category: "Image",
    description: 'Convert PNG images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PNG to BMP — Convert PNG images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1024",
    name: "PNG to TIFF",
    slug: "png-to-tiff",
    category: "Image",
    description: 'Convert PNG images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PNG to TIFF — Convert PNG images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1025",
    name: "PNG to ICO",
    slug: "png-to-ico",
    category: "Image",
    description: 'Convert PNG images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online PNG to ICO — Convert PNG images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1026",
    name: "JPG to HEIC",
    slug: "jpg-to-heic",
    category: "Image",
    description: 'Convert JPG images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to HEIC — Convert JPG images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1027",
    name: "JPG to SVG",
    slug: "jpg-to-svg",
    category: "Image",
    description: 'Convert JPG images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to SVG — Convert JPG images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1028",
    name: "JPG to BMP",
    slug: "jpg-to-bmp",
    category: "Image",
    description: 'Convert JPG images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to BMP — Convert JPG images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1029",
    name: "JPG to TIFF",
    slug: "jpg-to-tiff",
    category: "Image",
    description: 'Convert JPG images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to TIFF — Convert JPG images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1030",
    name: "JPG to ICO",
    slug: "jpg-to-ico",
    category: "Image",
    description: 'Convert JPG images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JPG to ICO — Convert JPG images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1031",
    name: "WEBP to HEIC",
    slug: "webp-to-heic",
    category: "Image",
    description: 'Convert WEBP images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online WEBP to HEIC — Convert WEBP images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1032",
    name: "WEBP to SVG",
    slug: "webp-to-svg",
    category: "Image",
    description: 'Convert WEBP images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online WEBP to SVG — Convert WEBP images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1033",
    name: "WEBP to BMP",
    slug: "webp-to-bmp",
    category: "Image",
    description: 'Convert WEBP images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online WEBP to BMP — Convert WEBP images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1034",
    name: "WEBP to TIFF",
    slug: "webp-to-tiff",
    category: "Image",
    description: 'Convert WEBP images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online WEBP to TIFF — Convert WEBP images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1035",
    name: "WEBP to ICO",
    slug: "webp-to-ico",
    category: "Image",
    description: 'Convert WEBP images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online WEBP to ICO — Convert WEBP images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1036",
    name: "WEBP to JXL",
    slug: "webp-to-jxl",
    category: "Image",
    description: 'Convert WEBP images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online WEBP to JXL — Convert WEBP images into JXL format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1037",
    name: "HEIC to SVG",
    slug: "heic-to-svg",
    category: "Image",
    description: 'Convert HEIC images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online HEIC to SVG — Convert HEIC images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1038",
    name: "HEIC to BMP",
    slug: "heic-to-bmp",
    category: "Image",
    description: 'Convert HEIC images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online HEIC to BMP — Convert HEIC images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1039",
    name: "HEIC to TIFF",
    slug: "heic-to-tiff",
    category: "Image",
    description: 'Convert HEIC images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online HEIC to TIFF — Convert HEIC images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1040",
    name: "HEIC to ICO",
    slug: "heic-to-ico",
    category: "Image",
    description: 'Convert HEIC images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online HEIC to ICO — Convert HEIC images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1041",
    name: "HEIC to JXL",
    slug: "heic-to-jxl",
    category: "Image",
    description: 'Convert HEIC images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online HEIC to JXL — Convert HEIC images into JXL format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1042",
    name: "AVIF to WEBP",
    slug: "avif-to-webp",
    category: "Image",
    description: 'Convert AVIF images to WEBP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to WEBP — Convert AVIF images into WEBP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1043",
    name: "AVIF to HEIC",
    slug: "avif-to-heic",
    category: "Image",
    description: 'Convert AVIF images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to HEIC — Convert AVIF images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1044",
    name: "AVIF to SVG",
    slug: "avif-to-svg",
    category: "Image",
    description: 'Convert AVIF images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to SVG — Convert AVIF images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1045",
    name: "AVIF to BMP",
    slug: "avif-to-bmp",
    category: "Image",
    description: 'Convert AVIF images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to BMP — Convert AVIF images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1046",
    name: "AVIF to TIFF",
    slug: "avif-to-tiff",
    category: "Image",
    description: 'Convert AVIF images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to TIFF — Convert AVIF images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1047",
    name: "AVIF to GIF",
    slug: "avif-to-gif",
    category: "Image",
    description: 'Convert AVIF images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to GIF — Convert AVIF images into GIF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1048",
    name: "AVIF to ICO",
    slug: "avif-to-ico",
    category: "Image",
    description: 'Convert AVIF images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to ICO — Convert AVIF images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1049",
    name: "AVIF to JXL",
    slug: "avif-to-jxl",
    category: "Image",
    description: 'Convert AVIF images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online AVIF to JXL — Convert AVIF images into JXL format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1050",
    name: "SVG to HEIC",
    slug: "svg-to-heic",
    category: "Image",
    description: 'Convert SVG images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to HEIC — Convert SVG images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1051",
    name: "SVG to BMP",
    slug: "svg-to-bmp",
    category: "Image",
    description: 'Convert SVG images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to BMP — Convert SVG images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1052",
    name: "SVG to TIFF",
    slug: "svg-to-tiff",
    category: "Image",
    description: 'Convert SVG images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to TIFF — Convert SVG images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1053",
    name: "SVG to ICO",
    slug: "svg-to-ico",
    category: "Image",
    description: 'Convert SVG images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to ICO — Convert SVG images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1054",
    name: "SVG to JXL",
    slug: "svg-to-jxl",
    category: "Image",
    description: 'Convert SVG images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online SVG to JXL — Convert SVG images into JXL format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1055",
    name: "BMP to HEIC",
    slug: "bmp-to-heic",
    category: "Image",
    description: 'Convert BMP images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to HEIC — Convert BMP images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1056",
    name: "BMP to SVG",
    slug: "bmp-to-svg",
    category: "Image",
    description: 'Convert BMP images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to SVG — Convert BMP images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1057",
    name: "BMP to TIFF",
    slug: "bmp-to-tiff",
    category: "Image",
    description: 'Convert BMP images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to TIFF — Convert BMP images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1058",
    name: "BMP to ICO",
    slug: "bmp-to-ico",
    category: "Image",
    description: 'Convert BMP images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to ICO — Convert BMP images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1059",
    name: "BMP to JXL",
    slug: "bmp-to-jxl",
    category: "Image",
    description: 'Convert BMP images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online BMP to JXL — Convert BMP images into JXL format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1060",
    name: "TIFF to HEIC",
    slug: "tiff-to-heic",
    category: "Image",
    description: 'Convert TIFF images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to HEIC — Convert TIFF images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1061",
    name: "TIFF to SVG",
    slug: "tiff-to-svg",
    category: "Image",
    description: 'Convert TIFF images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to SVG — Convert TIFF images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1062",
    name: "TIFF to BMP",
    slug: "tiff-to-bmp",
    category: "Image",
    description: 'Convert TIFF images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to BMP — Convert TIFF images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1063",
    name: "TIFF to ICO",
    slug: "tiff-to-ico",
    category: "Image",
    description: 'Convert TIFF images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to ICO — Convert TIFF images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1064",
    name: "TIFF to JXL",
    slug: "tiff-to-jxl",
    category: "Image",
    description: 'Convert TIFF images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online TIFF to JXL — Convert TIFF images into JXL format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1065",
    name: "GIF to HEIC",
    slug: "gif-to-heic",
    category: "Image",
    description: 'Convert GIF images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to HEIC — Convert GIF images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1066",
    name: "GIF to SVG",
    slug: "gif-to-svg",
    category: "Image",
    description: 'Convert GIF images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to SVG — Convert GIF images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1067",
    name: "GIF to BMP",
    slug: "gif-to-bmp",
    category: "Image",
    description: 'Convert GIF images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to BMP — Convert GIF images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1068",
    name: "GIF to TIFF",
    slug: "gif-to-tiff",
    category: "Image",
    description: 'Convert GIF images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to TIFF — Convert GIF images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1069",
    name: "GIF to ICO",
    slug: "gif-to-ico",
    category: "Image",
    description: 'Convert GIF images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to ICO — Convert GIF images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1070",
    name: "GIF to JXL",
    slug: "gif-to-jxl",
    category: "Image",
    description: 'Convert GIF images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online GIF to JXL — Convert GIF images into JXL format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1071",
    name: "ICO to HEIC",
    slug: "ico-to-heic",
    category: "Image",
    description: 'Convert ICO images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to HEIC — Convert ICO images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1072",
    name: "ICO to AVIF",
    slug: "ico-to-avif",
    category: "Image",
    description: 'Convert ICO images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to AVIF — Convert ICO images into AVIF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1073",
    name: "ICO to SVG",
    slug: "ico-to-svg",
    category: "Image",
    description: 'Convert ICO images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to SVG — Convert ICO images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1074",
    name: "ICO to BMP",
    slug: "ico-to-bmp",
    category: "Image",
    description: 'Convert ICO images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to BMP — Convert ICO images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1075",
    name: "ICO to TIFF",
    slug: "ico-to-tiff",
    category: "Image",
    description: 'Convert ICO images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to TIFF — Convert ICO images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1076",
    name: "ICO to GIF",
    slug: "ico-to-gif",
    category: "Image",
    description: 'Convert ICO images to GIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to GIF — Convert ICO images into GIF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1077",
    name: "ICO to JXL",
    slug: "ico-to-jxl",
    category: "Image",
    description: 'Convert ICO images to JXL format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online ICO to JXL — Convert ICO images into JXL format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1078",
    name: "JXL to HEIC",
    slug: "jxl-to-heic",
    category: "Image",
    description: 'Convert JXL images to HEIC format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to HEIC — Convert JXL images into HEIC format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1079",
    name: "JXL to AVIF",
    slug: "jxl-to-avif",
    category: "Image",
    description: 'Convert JXL images to AVIF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to AVIF — Convert JXL images into AVIF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1080",
    name: "JXL to SVG",
    slug: "jxl-to-svg",
    category: "Image",
    description: 'Convert JXL images to SVG format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to SVG — Convert JXL images into SVG format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1081",
    name: "JXL to BMP",
    slug: "jxl-to-bmp",
    category: "Image",
    description: 'Convert JXL images to BMP format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to BMP — Convert JXL images into BMP format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1082",
    name: "JXL to TIFF",
    slug: "jxl-to-tiff",
    category: "Image",
    description: 'Convert JXL images to TIFF format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to TIFF — Convert JXL images into TIFF format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1083",
    name: "JXL to ICO",
    slug: "jxl-to-ico",
    category: "Image",
    description: 'Convert JXL images to ICO format in your browser. Lossless, private, and completely free — no uploads needed.',
    seoDescription: 'Free online JXL to ICO — Convert JXL images into ICO format. Perfect for image conversion needs.',
    dependencies: "Canvas API",
    showInCategory: false,
  },
  {
    id: "1085",
    name: "Subtitle Generator",
    slug: "subtitle-generator",
    category: "Video",
    description: 'Generate SRT/VTT subtitles for videos from transcript text. Auto-sync timestamps with configurable duration and gap.',
    seoDescription: 'Free online Subtitle Generator — Generate SRT and VTT subtitle files from transcript text. Auto-sync with configurable timestamps.',
    dependencies: "None",

  },
  {

    id: "1086",
    name: "Validator Kit",
    slug: "validator-kit",
    category: "Developer",
    description: 'Validate email addresses, URLs, phone numbers, credit cards, IP addresses, JSON, and more. Batch validation supported.',
    seoDescription: 'Free online Validator Kit — Validate email, URL, phone, credit card, IP, JSON, and more. Batch validation with detailed error messages.',
    dependencies: "None",
},
  {
    id: "1087",
    name: "JSON to YAML Converter",
    slug: "json-to-yaml-converter",
    category: "Converter",
    description: 'Convert JSON objects to YAML format with proper key-value formatting and nested structure support. Everything runs locally in your browser.',
    seoDescription: 'Free online JSON to YAML Converter — Convert JSON objects to YAML format with proper key-value formatting. ',
    dependencies: "None",
  },
  {
    id: "1088",
    name: "JSON to INI Converter",
    slug: "json-to-ini-converter",
    category: "Converter",
    description: 'Convert JSON objects to INI config file format with section headers and key-value pairs. Perfect for configuration file generation.',
    seoDescription: 'Free online JSON to INI Converter — Convert JSON to INI config format with section headers and key-value pairs. ',
    dependencies: "None",
  },
  {
    id: "1089",
    name: "JSON to TOML Converter",
    slug: "json-to-toml-converter",
    category: "Converter",
    description: 'Convert JSON objects to TOML configuration format with proper typing and section support. Everything runs locally in your browser.',
    seoDescription: 'Free online JSON to TOML Converter — Convert JSON to TOML configuration format with proper typing. ',
    dependencies: "None",
  },
  {
    id: "1090",
    name: "CSS to Less Converter",
    slug: "css-to-less-converter",
    category: "Converter",
    description: 'Convert CSS to Less syntax by transforming CSS variables to Less variables (@). Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSS to Less Converter — Convert CSS variables to Less syntax with proper transformation. ',
    dependencies: "None",
  },
  {
    id: "1091",
    name: "CSS to Stylus Converter",
    slug: "css-to-stylus-converter",
    category: "Converter",
    description: 'Convert CSS braces and semicolons to Stylus indentation-based syntax. Everything runs locally in your browser — nothing is uploaded.',
    seoDescription: 'Free online CSS to Stylus Converter — Convert CSS to Stylus indentation syntax. ',
    dependencies: "None",
  },
  {

    id: "1092",
    name: "Bulk URL Shortener",
    slug: "bulk-url-shortener",
    category: "Utility",
    description: 'Shorten hundreds of URLs in one batch. Paste a list or upload a CSV — get shortened links with copy-all and CSV export. Uses cloud-based processing.',
    seoDescription: 'Free online Bulk URL Shortener — Shorten hundreds of URLs at once. Paste a list or upload a CSV, get shortened links with copy-all and CSV export. ',
    dependencies: "Node.js / Redis",
},
  {
    id: "1093",
    name: "Text Repeater",
    slug: "text-repeater",
    category: "Text",
    description: 'Repeat any text a specified number of times with customizable separators (newline, space, comma, custom) and optional line numbering. Perfect for templates, practice drills, and repetitive patterns.',
    seoDescription: 'Free online Text Repeater — Repeat text any number of times with customizable separators and optional numbering. Perfect for templates, practice drills, generating test data, and repetitive content.',
    dependencies: "None",
  },
  {
    id: "1095",
    name: "Small Text Generator",
    slug: "small-text-generator",
    category: "Text",
    description: 'Convert text to superscript, subscript, tiny text, or small caps Unicode variants. Perfect for footnotes, chemical formulas, mathematical expressions, and decorative text in social media.',
    seoDescription: 'Free online Small Text Generator — Convert text to superscript, subscript, tiny text, or small caps Unicode. Perfect for footnotes, chemical formulas (H2O), math expressions, and social media.',
    dependencies: "None",
  },
  {
    id: "1096",
    name: "Big Text Generator",
    slug: "big-text-generator",
    category: "Text",
    description: 'Convert regular text into large ASCII block art, circled bubble letters, or mathematical bold Unicode. Make your text stand out with big, bold styles for social media headers, signs, and emphasis.',
    seoDescription: 'Free online Big Text Generator — Convert text into large ASCII block art, circled bubble letters, and math bold Unicode. Make words stand out for social media, signs, and creative projects.',
    dependencies: "None",
  },
  {
    id: "1097",
    name: "Writing Tools",
    slug: "writing-tools",
    category: "Text",
    description: 'Comprehensive writing analysis dashboard — real-time word count, character count, sentences, paragraphs, syllables, reading time, speaking time, Flesch-Kincaid readability score, and vocabulary richness metrics.',
    seoDescription: 'Free online Writing Tools — Comprehensive writing analysis with real-time word count, readability scores, syllable count, reading/speaking time, and vocabulary richness metrics. Essential for writers, students, and editors.',
    dependencies: "None",
  },
  {
    id: "1098",
    name: "Citation Generator",
    slug: "citation-generator",
    category: "Text",
    description: 'Generate citations in APA, MLA, Chicago, Harvard, IEEE, AMA, and Vancouver formats. Supports books, websites, journal articles, videos, and more with all fields auto-formatted.',
    seoDescription: 'Free online Citation Generator — Generate citations in APA, MLA, Chicago, Harvard, IEEE, AMA, and Vancouver formats. Supports books, websites, journal articles, and videos with auto-formatted fields.',
    dependencies: "None",
  },
  {
    id: "1099",
    name: "Text Reverser",
    slug: "text-reverser",
    category: "Text",
    description: 'Reverse text by characters, words, or lines; flip upside down using Unicode rot180; mirror horizontally; or rotate 180 degrees. Six transformation modes for creating puzzles, secret messages, and unique social media content.',
    seoDescription: 'Free online Text Reverser — Reverse text by characters, words, or lines. Flip upside down, mirror horizontally, or rotate 180 degrees. Create puzzles, secret messages, and unique social content.',
    dependencies: "None",
  },
  {
    id: "1100",
    name: "Upside Down Text Generator",
    slug: "upside-down-text",
    category: "Text",
    description: 'Flip text upside down using Unicode rot180 (rotated 180 degrees) characters. Two modes: full flip reverses order and flips characters, mirror flips characters in place. Great for social media and fun.',
    seoDescription: 'Free online Upside Down Text Generator — Flip text upside down using Unicode rot180 characters. Full flip (reverse plus rotate) or mirror mode (rotate in place). Perfect for social media and creative content.',
    dependencies: "None",
  },
  {
    id: "1101",
    name: "Glitch Text Generator",
    slug: "glitch-text",
    category: "Text",
    description: 'Create corrupted glitch text effects with Zalgo diacritics, random character corruption, or scramble transformations. Adjustable intensity, position, and seed for reproducible results.',
    seoDescription: 'Free online Glitch Text Generator — Create corrupted glitch text with Zalgo diacritics, random corruption, and scramble effects. Adjustable intensity and seed for reproducible glitch styles.',
    dependencies: "None",
  },
  {
    id: "1102",
    name: "Invisible Character Generator",
    slug: "invisible-character",
    category: "Text",
    description: 'Generate and inspect invisible Unicode characters — zero-width space (ZWSP), zero-width non-joiner (ZWNJ), zero-width joiner (ZWJ), left-to-right/right-to-left marks, and word joiner. Copy raw bytes or visualizable forms.',
    seoDescription: 'Free online Invisible Character Generator — Generate zero-width spaces (ZWSP), ZWNJ, ZWJ, LTR/RTL marks, and word joiners. Copy raw Unicode characters or inspect hex and bytes.',
    dependencies: "None",
  },
  {

    id: "1099",
    name: "NATO Phonetic Converter",
    slug: "nato-phonetic-converter",
    category: "Utility",
    description: 'Bidirectional NATO phonetic alphabet converter. Convert text to NATO words (Alpha, Bravo, Charlie) and back. Perfect for radio communication, spelling clarification, and aviation.',
    seoDescription: 'Free online NATO Phonetic Converter — Convert text to NATO phonetic alphabet (Alpha, Bravo, Charlie) and back. Perfect for radio communication and spelling clarification. ',
    dependencies: "None",
},
  {

    id: "1100",
    name: "Unicode Code Point Viewer",
    slug: "unicode-viewer",
    category: "Utility",
    description: 'View Unicode code points, HTML entities, and percent-encoding for any text. Character-by-character breakdown with U+XXXX codes and HTML entity references.',
    seoDescription: 'Free online Unicode Code Point Viewer — View Unicode code points (U+XXXX), HTML entities, and percent-encoding for any text with character-by-character breakdown. ',
    dependencies: "None",
},
];
