"use client";

import { useEffect } from "react";

/**
 * Registers the Workbox service worker (out/sw.js), freshly generated by
 * scripts/gen-sw.js at the end of every production build. Sole
 * registration path. No-op on browsers without service workers and
 * during development.
 */
export function ServiceWorkerRegister() {
  useEffect(() => {
    if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
    if (process.env.NODE_ENV !== "production") return;
    navigator.serviceWorker.register("/sw.js").catch(() => {
      /* offline support unavailable — app works fine without it */
    });
  }, []);
  return null;
}
