"use client";

import { useEffect } from "react";

/**
 * Registers the prebuilt Workbox service worker (public/sw.js).
 * The worker file is committed rather than generated by next-pwa
 * (which isn't wired in next.config.ts), so registration is the only
 * missing piece for offline/caching support. No-op on browsers
 * without service workers and during development.
 */
export function ServiceWorkerRegister() {
  useEffect(() => {
    if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
    if (process.env.NODE_ENV !== "production") return;
    navigator.serviceWorker.register("/sw.js").catch(() => {
      /* offline support unavailable — app works fine without it */
    });
  }, []);
  return null;
}
