/**
 * generate-site-data.ts — precompute site-wide static data that pages otherwise
 * derive from the full toolsRegistry at bundle time (root-layout chunk bloat).
 *
 * Outputs src/registry/site-data.generated.ts:
 *   - TOOL_COUNT            (was toolsRegistry.length in layout.tsx)
 *   - SITE_STATS            (share-link counters, was getCachedToolCounts() in Header)
 *   - MEGAMENU_COLUMNS      (was buildMegamenuColumns() in Header)
 *
 * Run: npm run gen:site-data   (wired into `npm run build`)
 * Guard: src/__tests__/site-data.test.ts asserts parity with the live registry.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { toolsRegistry } from "../src/registry/tools";
import { getCachedToolCounts } from "../src/registry/tools-helpers";
import { buildMegamenuColumns } from "../src/registry/megamenu-defs";

const __dirname = dirname(fileURLToPath(import.meta.url));

const counts = getCachedToolCounts();
const columns = buildMegamenuColumns(toolsRegistry);

const out = `// Auto-generated by \`npm run gen:site-data\` — DO NOT EDIT BY HAND.
// Regenerate whenever the registry or megamenu definition changes:
//   npm run gen:site-data   (wired into \`npm run build\`)
// Parity guard: src/__tests__/site-data.test.ts

export interface MegamenuTool {
  name: string;
  href: string;
}

export interface MegamenuColumn {
  title: string;
  icon: string;
  tools: MegamenuTool[];
  allCount: number;
  allHref: string;
  isIndia: boolean;
}

export const TOOL_COUNT = ${toolsRegistry.length};

export const SITE_STATS = {
  totalImplemented: ${counts.totalImplemented},
  freeTierTotal: ${counts.freeTierTotal},
  localTools: ${counts.localTools},
  cloudTools: ${counts.cloudTools},
  hybridTools: ${counts.hybridTools},
} as const;

export const MEGAMENU_COLUMNS: MegamenuColumn[] = ${JSON.stringify(columns, null, 2)};
`;

const outPath = join(__dirname, "../src/registry/site-data.generated.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out);
console.log(`Generated ${outPath} — ${columns.length} columns, TOOL_COUNT=${toolsRegistry.length}`);
