#!/usr/bin/env node
/**
 * Generates src/lib/downloadProducingSlugs.ts from static analysis:
 * 1. Finds all module files that import downloadOrShare
 * 2. Excludes files that import but never call it (dead imports)
 * 3. Maps file paths to their DynamicModuleWrapper slugs
 * 4. Writes a Set constant used by ToolLayout for download badge visibility
 *
 * Run: npx tsx scripts/generate-download-slugs.ts
 * Wired into: npm run build (via gen:download-slugs)
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dirname, '..');
const WRAPPER_PATH = join(ROOT, 'src/components/tools/modules/DynamicModuleWrapper.tsx');
const MODULES_DIR = join(ROOT, 'src/components/tools/modules');
const OUTPUT_PATH = join(ROOT, 'src/lib/downloadProducingSlugs.ts');

// Files that import downloadOrShare but never call it (verified by audit 2026-09-04)
const DEAD_IMPORTS = new Set([
  'pdf/UrlToPdf',
  'converter/DocumentConverter',
  'privacy/PrivacyCleaner',
  'ai/AiHumanizer',
]);

function findDownloadFiles(): string[] {
  // Use a simple recursive glob since we can't assume ripgrep is available
  const { readdirSync, readFileSync: read } = require('fs');
  const { join: j } = require('path');

  function walk(dir: string): string[] {
    const entries = readdirSync(dir, { withFileTypes: true });
    const files: string[] = [];
    for (const entry of entries) {
      const full = j(dir, entry.name);
      if (entry.isDirectory()) {
        files.push(...walk(full));
      } else if (/\.(tsx?|mts?)$/.test(entry.name)) {
        const content = read(full, 'utf8');
        if (content.includes('downloadOrShare') || content.includes('BulkToolShell') || content.includes('JSZip') || content.includes('URL.createObjectURL')) {
          files.push(full);
        }
      }
    }
    return files;
  }

  return walk(MODULES_DIR);
}

function mapSlugs(filePaths: string[]): string[] {
  const wrapper = readFileSync(WRAPPER_PATH, 'utf8');
  const lines = wrapper.split('\n');
  const slugs = new Set<string>();

  for (const filePath of filePaths) {
    // Extract relative path from modules/ (e.g. "ai/AiArticleWriter")
    const relPath = filePath
      .replace(MODULES_DIR + '/', '')
      .replace(/\.tsx?$/, '');

    // Skip dead imports
    if (DEAD_IMPORTS.has(relPath)) continue;

    // Find DynamicModuleWrapper lines referencing this exact module path
    for (const line of lines) {
      if (line.includes(relPath)) {
        const slugMatch = line.match(/'([\w-]+)'/);
        if (slugMatch) {
          slugs.add(slugMatch[1]);
        }
      }
    }
  }

  return [...slugs].sort();
}

function generateFile(slugs: string[]): string {
  const lines = [
    '// AUTO-GENERATED by scripts/generate-download-slugs.ts — do not edit manually.',
    '// Regenerate: npx tsx scripts/generate-download-slugs.ts',
    '// Source: grep for downloadOrShare calls in modules/ × DynamicModuleWrapper slug mappings.',
    '',
    'export const DOWNLOAD_PRODUCING_SLUGS = new Set([',
  ];

  for (let i = 0; i < slugs.length; i += 8) {
    const chunk = slugs
      .slice(i, i + 8)
      .map((s) => `  '${s}'`)
      .join(', ');
    lines.push(chunk + ',');
  }

  lines.push(']);');
  lines.push('');
  return lines.join('\n');
}

// --- Main ---
const files = findDownloadFiles();
console.log(`Found ${files.length} files importing downloadOrShare`);

const slugs = mapSlugs(files);
console.log(`Mapped to ${slugs.length} DynamicModuleWrapper slugs`);

const content = generateFile(slugs);
writeFileSync(OUTPUT_PATH, content);
console.log(`Written to ${OUTPUT_PATH}`);
