/**
 * generate-legal-dates.ts — stamp each legal page with its real last-change
 * date from git history, so "Last updated" can never go stale or lie.
 *
 * Outputs src/lib/legal-dates.generated.ts: { route: ISO date }.
 * Run: npx tsx scripts/generate-legal-dates.ts (wired into `npm run build`
 * via gen:parallel). Falls back to file mtime when git is unavailable.
 * Guard: src/__tests__/legal-dates.test.ts.
 */
import { writeFileSync, statSync } from "node:fs";
import { execSync } from "node:child_process";

const PAGES: Record<string, string> = {
  "/privacy-policy/": "src/app/privacy-policy/page.tsx",
  "/terms/": "src/app/terms/page.tsx",
  "/cookies/": "src/app/cookies/page.tsx",
  "/disclaimer/": "src/app/disclaimer/page.tsx",
};

function lastChange(file: string): string {
  try {
    const iso = execSync(`git log -1 --format=%cs -- "${file}"`, {
      encoding: "utf8",
    }).trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(iso)) return iso;
  } catch {
    /* fall through to mtime */
  }
  try {
    const mtime = statSync(file).mtime;
    const iso = `${mtime.getFullYear()}-${String(mtime.getMonth() + 1).padStart(2, "0")}-${String(mtime.getDate()).padStart(2, "0")}`;
    if (/^\d{4}-\d{2}-\d{2}$/.test(iso)) return iso;
  } catch {
    /* fall through */
  }
  return new Date().toISOString().slice(0, 10);
}

const entries = Object.entries(PAGES)
  .map(([route, file]) => `  ${JSON.stringify(route)}: ${JSON.stringify(lastChange(file))},`)
  .join("\n");

writeFileSync(
  "src/lib/legal-dates.generated.ts",
  `// Auto-generated by \`npx tsx scripts/generate-legal-dates.ts\` — DO NOT EDIT BY HAND.
// Regenerated on every build (gen:parallel). Source of truth: git history
// of each legal page. Guard: src/__tests__/legal-dates.test.ts.

export const LEGAL_DATES: Record<string, string> = {
${entries}
};

export function legalDate(route: string): string {
  return LEGAL_DATES[route] ?? new Date().toISOString().slice(0, 10);
}

export function formatLegalDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y!, m! - 1, d)).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}
`
);
console.log("legal dates written for", Object.keys(PAGES).length, "pages");
